extern int CCTKi_BindingsCreateADMMacrosParameters(void);
extern int CCTKi_BindingsCreateAEILocalInterpParameters(void);
extern int CCTKi_BindingsCreateBoundaryParameters(void);
extern int CCTKi_BindingsCreateCactusParameters(void);
extern int CCTKi_BindingsCreateCarpetParameters(void);
extern int CCTKi_BindingsCreateCarpetEvolutionMaskParameters(void);
extern int CCTKi_BindingsCreateCarpetIOASCIIParameters(void);
extern int CCTKi_BindingsCreateCarpetIOBasicParameters(void);
extern int CCTKi_BindingsCreateCarpetIOHDF5Parameters(void);
extern int CCTKi_BindingsCreateCarpetIntegrateTestParameters(void);
extern int CCTKi_BindingsCreateCarpetInterpParameters(void);
extern int CCTKi_BindingsCreateCarpetLibParameters(void);
extern int CCTKi_BindingsCreateCarpetReduceParameters(void);
extern int CCTKi_BindingsCreateCarpetRegridParameters(void);
extern int CCTKi_BindingsCreateCarpetRegrid2Parameters(void);
extern int CCTKi_BindingsCreateCarpetSlabParameters(void);
extern int CCTKi_BindingsCreateCarpetTrackerParameters(void);
extern int CCTKi_BindingsCreateCartGrid3DParameters(void);
extern int CCTKi_BindingsCreateCartoon2DParameters(void);
extern int CCTKi_BindingsCreateCoordBaseParameters(void);
extern int CCTKi_BindingsCreateDissipationParameters(void);
extern int CCTKi_BindingsCreateGSLParameters(void);
extern int CCTKi_BindingsCreateHDF5Parameters(void);
extern int CCTKi_BindingsCreateIDScalarWaveMoLParameters(void);
extern int CCTKi_BindingsCreateIDWaveMoLParameters(void);
extern int CCTKi_BindingsCreateIOASCIIParameters(void);
extern int CCTKi_BindingsCreateIOBasicParameters(void);
extern int CCTKi_BindingsCreateIOUtilParameters(void);
extern int CCTKi_BindingsCreateInitBaseParameters(void);
extern int CCTKi_BindingsCreateLocalInterpParameters(void);
extern int CCTKi_BindingsCreateLocalReduceParameters(void);
extern int CCTKi_BindingsCreateLoopControlParameters(void);
extern int CCTKi_BindingsCreateMoLParameters(void);
extern int CCTKi_BindingsCreateNaNCheckerParameters(void);
extern int CCTKi_BindingsCreateOS_collapseParameters(void);
extern int CCTKi_BindingsCreateOS_toyParameters(void);
extern int CCTKi_BindingsCreateSpaceMaskParameters(void);
extern int CCTKi_BindingsCreateSphericalSurfaceParameters(void);
extern int CCTKi_BindingsCreateStaticConformalParameters(void);
extern int CCTKi_BindingsCreateSymBaseParameters(void);
extern int CCTKi_BindingsCreateTimeParameters(void);
extern int CCTKi_BindingsCreateTwoPuncturesParameters(void);
extern int CCTKi_BindingsCreateTwoPuncturesAEIParameters(void);
extern int CCTKi_BindingsCreateWaveMoLParameters(void);
extern int CCTKi_BindingsCreateWaveToyMoLParameters(void);
extern int CCTKi_BindingsCreateahfinderdirectParameters(void);
extern int CCTKi_BindingsCreateang_freq_ofBfieldParameters(void);
extern int CCTKi_BindingsCreatebbh_cookpfeiffer_rotParameters(void);
extern int CCTKi_BindingsCreatebbhloreneParameters(void);
extern int CCTKi_BindingsCreatebhnsParameters(void);
extern int CCTKi_BindingsCreatebssnParameters(void);
extern int CCTKi_BindingsCreatecylindrical2dParameters(void);
extern int CCTKi_BindingsCreatediagnostics_mhdParameters(void);
extern int CCTKi_BindingsCreatediagnostics_vacuumParameters(void);
extern int CCTKi_BindingsCreatedisk_powerlawParameters(void);
extern int CCTKi_BindingsCreateem_extractionParameters(void);
extern int CCTKi_BindingsCreateexcisionParameters(void);
extern int CCTKi_BindingsCreatefisheyeParameters(void);
extern int CCTKi_BindingsCreategw_extractionParameters(void);
extern int CCTKi_BindingsCreatejobsuicideParameters(void);
extern int CCTKi_BindingsCreatelapseParameters(void);
extern int CCTKi_BindingsCreatelinearized_waveParameters(void);
extern int CCTKi_BindingsCreatemag_bondiParameters(void);
extern int CCTKi_BindingsCreatemagnetarParameters(void);
extern int CCTKi_BindingsCreatemhd_evolveParameters(void);
extern int CCTKi_BindingsCreatemovingboxParameters(void);
extern int CCTKi_BindingsCreatemovingbox_for_boosted_bhParameters(void);
extern int CCTKi_BindingsCreatenonlinear_alfven_waveParameters(void);
extern int CCTKi_BindingsCreatescalarwaveMoLParameters(void);
extern int CCTKi_BindingsCreateshiftParameters(void);
extern int CCTKi_BindingsCreateshock_mhdParameters(void);
extern int CCTKi_BindingsCreatezlibParameters(void);

extern int CCTKi_BindingsADMMacrosParameterExtensions(void);
extern int CCTKi_BindingsAEILocalInterpParameterExtensions(void);
extern int CCTKi_BindingsBoundaryParameterExtensions(void);
extern int CCTKi_BindingsCactusParameterExtensions(void);
extern int CCTKi_BindingsCarpetParameterExtensions(void);
extern int CCTKi_BindingsCarpetEvolutionMaskParameterExtensions(void);
extern int CCTKi_BindingsCarpetIOASCIIParameterExtensions(void);
extern int CCTKi_BindingsCarpetIOBasicParameterExtensions(void);
extern int CCTKi_BindingsCarpetIOHDF5ParameterExtensions(void);
extern int CCTKi_BindingsCarpetIntegrateTestParameterExtensions(void);
extern int CCTKi_BindingsCarpetInterpParameterExtensions(void);
extern int CCTKi_BindingsCarpetLibParameterExtensions(void);
extern int CCTKi_BindingsCarpetReduceParameterExtensions(void);
extern int CCTKi_BindingsCarpetRegridParameterExtensions(void);
extern int CCTKi_BindingsCarpetRegrid2ParameterExtensions(void);
extern int CCTKi_BindingsCarpetSlabParameterExtensions(void);
extern int CCTKi_BindingsCarpetTrackerParameterExtensions(void);
extern int CCTKi_BindingsCartGrid3DParameterExtensions(void);
extern int CCTKi_BindingsCartoon2DParameterExtensions(void);
extern int CCTKi_BindingsCoordBaseParameterExtensions(void);
extern int CCTKi_BindingsDissipationParameterExtensions(void);
extern int CCTKi_BindingsGSLParameterExtensions(void);
extern int CCTKi_BindingsHDF5ParameterExtensions(void);
extern int CCTKi_BindingsIDScalarWaveMoLParameterExtensions(void);
extern int CCTKi_BindingsIDWaveMoLParameterExtensions(void);
extern int CCTKi_BindingsIOASCIIParameterExtensions(void);
extern int CCTKi_BindingsIOBasicParameterExtensions(void);
extern int CCTKi_BindingsIOUtilParameterExtensions(void);
extern int CCTKi_BindingsInitBaseParameterExtensions(void);
extern int CCTKi_BindingsLocalInterpParameterExtensions(void);
extern int CCTKi_BindingsLocalReduceParameterExtensions(void);
extern int CCTKi_BindingsLoopControlParameterExtensions(void);
extern int CCTKi_BindingsMoLParameterExtensions(void);
extern int CCTKi_BindingsNaNCheckerParameterExtensions(void);
extern int CCTKi_BindingsOS_collapseParameterExtensions(void);
extern int CCTKi_BindingsOS_toyParameterExtensions(void);
extern int CCTKi_BindingsSpaceMaskParameterExtensions(void);
extern int CCTKi_BindingsSphericalSurfaceParameterExtensions(void);
extern int CCTKi_BindingsStaticConformalParameterExtensions(void);
extern int CCTKi_BindingsSymBaseParameterExtensions(void);
extern int CCTKi_BindingsTimeParameterExtensions(void);
extern int CCTKi_BindingsTwoPuncturesParameterExtensions(void);
extern int CCTKi_BindingsTwoPuncturesAEIParameterExtensions(void);
extern int CCTKi_BindingsWaveMoLParameterExtensions(void);
extern int CCTKi_BindingsWaveToyMoLParameterExtensions(void);
extern int CCTKi_BindingsahfinderdirectParameterExtensions(void);
extern int CCTKi_Bindingsang_freq_ofBfieldParameterExtensions(void);
extern int CCTKi_Bindingsbbh_cookpfeiffer_rotParameterExtensions(void);
extern int CCTKi_BindingsbbhloreneParameterExtensions(void);
extern int CCTKi_BindingsbhnsParameterExtensions(void);
extern int CCTKi_BindingsbssnParameterExtensions(void);
extern int CCTKi_Bindingscylindrical2dParameterExtensions(void);
extern int CCTKi_Bindingsdiagnostics_mhdParameterExtensions(void);
extern int CCTKi_Bindingsdiagnostics_vacuumParameterExtensions(void);
extern int CCTKi_Bindingsdisk_powerlawParameterExtensions(void);
extern int CCTKi_Bindingsem_extractionParameterExtensions(void);
extern int CCTKi_BindingsexcisionParameterExtensions(void);
extern int CCTKi_BindingsfisheyeParameterExtensions(void);
extern int CCTKi_Bindingsgw_extractionParameterExtensions(void);
extern int CCTKi_BindingsjobsuicideParameterExtensions(void);
extern int CCTKi_BindingslapseParameterExtensions(void);
extern int CCTKi_Bindingslinearized_waveParameterExtensions(void);
extern int CCTKi_Bindingsmag_bondiParameterExtensions(void);
extern int CCTKi_BindingsmagnetarParameterExtensions(void);
extern int CCTKi_Bindingsmhd_evolveParameterExtensions(void);
extern int CCTKi_BindingsmovingboxParameterExtensions(void);
extern int CCTKi_Bindingsmovingbox_for_boosted_bhParameterExtensions(void);
extern int CCTKi_Bindingsnonlinear_alfven_waveParameterExtensions(void);
extern int CCTKi_BindingsscalarwaveMoLParameterExtensions(void);
extern int CCTKi_BindingsshiftParameterExtensions(void);
extern int CCTKi_Bindingsshock_mhdParameterExtensions(void);
extern int CCTKi_BindingszlibParameterExtensions(void);


int CCTKi_BindingsParametersInitialise(void);
int CCTKi_BindingsParametersInitialise(void)
{
  CCTKi_BindingsCreateADMMacrosParameters();
  CCTKi_BindingsCreateAEILocalInterpParameters();
  CCTKi_BindingsCreateBoundaryParameters();
  CCTKi_BindingsCreateCactusParameters();
  CCTKi_BindingsCreateCarpetParameters();
  CCTKi_BindingsCreateCarpetEvolutionMaskParameters();
  CCTKi_BindingsCreateCarpetIOASCIIParameters();
  CCTKi_BindingsCreateCarpetIOBasicParameters();
  CCTKi_BindingsCreateCarpetIOHDF5Parameters();
  CCTKi_BindingsCreateCarpetIntegrateTestParameters();
  CCTKi_BindingsCreateCarpetInterpParameters();
  CCTKi_BindingsCreateCarpetLibParameters();
  CCTKi_BindingsCreateCarpetReduceParameters();
  CCTKi_BindingsCreateCarpetRegridParameters();
  CCTKi_BindingsCreateCarpetRegrid2Parameters();
  CCTKi_BindingsCreateCarpetSlabParameters();
  CCTKi_BindingsCreateCarpetTrackerParameters();
  CCTKi_BindingsCreateCartGrid3DParameters();
  CCTKi_BindingsCreateCartoon2DParameters();
  CCTKi_BindingsCreateCoordBaseParameters();
  CCTKi_BindingsCreateDissipationParameters();
  CCTKi_BindingsCreateGSLParameters();
  CCTKi_BindingsCreateHDF5Parameters();
  CCTKi_BindingsCreateIDScalarWaveMoLParameters();
  CCTKi_BindingsCreateIDWaveMoLParameters();
  CCTKi_BindingsCreateIOASCIIParameters();
  CCTKi_BindingsCreateIOBasicParameters();
  CCTKi_BindingsCreateIOUtilParameters();
  CCTKi_BindingsCreateInitBaseParameters();
  CCTKi_BindingsCreateLocalInterpParameters();
  CCTKi_BindingsCreateLocalReduceParameters();
  CCTKi_BindingsCreateLoopControlParameters();
  CCTKi_BindingsCreateMoLParameters();
  CCTKi_BindingsCreateNaNCheckerParameters();
  CCTKi_BindingsCreateOS_collapseParameters();
  CCTKi_BindingsCreateOS_toyParameters();
  CCTKi_BindingsCreateSpaceMaskParameters();
  CCTKi_BindingsCreateSphericalSurfaceParameters();
  CCTKi_BindingsCreateStaticConformalParameters();
  CCTKi_BindingsCreateSymBaseParameters();
  CCTKi_BindingsCreateTimeParameters();
  CCTKi_BindingsCreateTwoPuncturesParameters();
  CCTKi_BindingsCreateTwoPuncturesAEIParameters();
  CCTKi_BindingsCreateWaveMoLParameters();
  CCTKi_BindingsCreateWaveToyMoLParameters();
  CCTKi_BindingsCreateahfinderdirectParameters();
  CCTKi_BindingsCreateang_freq_ofBfieldParameters();
  CCTKi_BindingsCreatebbh_cookpfeiffer_rotParameters();
  CCTKi_BindingsCreatebbhloreneParameters();
  CCTKi_BindingsCreatebhnsParameters();
  CCTKi_BindingsCreatebssnParameters();
  CCTKi_BindingsCreatecylindrical2dParameters();
  CCTKi_BindingsCreatediagnostics_mhdParameters();
  CCTKi_BindingsCreatediagnostics_vacuumParameters();
  CCTKi_BindingsCreatedisk_powerlawParameters();
  CCTKi_BindingsCreateem_extractionParameters();
  CCTKi_BindingsCreateexcisionParameters();
  CCTKi_BindingsCreatefisheyeParameters();
  CCTKi_BindingsCreategw_extractionParameters();
  CCTKi_BindingsCreatejobsuicideParameters();
  CCTKi_BindingsCreatelapseParameters();
  CCTKi_BindingsCreatelinearized_waveParameters();
  CCTKi_BindingsCreatemag_bondiParameters();
  CCTKi_BindingsCreatemagnetarParameters();
  CCTKi_BindingsCreatemhd_evolveParameters();
  CCTKi_BindingsCreatemovingboxParameters();
  CCTKi_BindingsCreatemovingbox_for_boosted_bhParameters();
  CCTKi_BindingsCreatenonlinear_alfven_waveParameters();
  CCTKi_BindingsCreatescalarwaveMoLParameters();
  CCTKi_BindingsCreateshiftParameters();
  CCTKi_BindingsCreateshock_mhdParameters();
  CCTKi_BindingsCreatezlibParameters();

  CCTKi_BindingsADMMacrosParameterExtensions();
  CCTKi_BindingsAEILocalInterpParameterExtensions();
  CCTKi_BindingsBoundaryParameterExtensions();
  CCTKi_BindingsCactusParameterExtensions();
  CCTKi_BindingsCarpetParameterExtensions();
  CCTKi_BindingsCarpetEvolutionMaskParameterExtensions();
  CCTKi_BindingsCarpetIOASCIIParameterExtensions();
  CCTKi_BindingsCarpetIOBasicParameterExtensions();
  CCTKi_BindingsCarpetIOHDF5ParameterExtensions();
  CCTKi_BindingsCarpetIntegrateTestParameterExtensions();
  CCTKi_BindingsCarpetInterpParameterExtensions();
  CCTKi_BindingsCarpetLibParameterExtensions();
  CCTKi_BindingsCarpetReduceParameterExtensions();
  CCTKi_BindingsCarpetRegridParameterExtensions();
  CCTKi_BindingsCarpetRegrid2ParameterExtensions();
  CCTKi_BindingsCarpetSlabParameterExtensions();
  CCTKi_BindingsCarpetTrackerParameterExtensions();
  CCTKi_BindingsCartGrid3DParameterExtensions();
  CCTKi_BindingsCartoon2DParameterExtensions();
  CCTKi_BindingsCoordBaseParameterExtensions();
  CCTKi_BindingsDissipationParameterExtensions();
  CCTKi_BindingsGSLParameterExtensions();
  CCTKi_BindingsHDF5ParameterExtensions();
  CCTKi_BindingsIDScalarWaveMoLParameterExtensions();
  CCTKi_BindingsIDWaveMoLParameterExtensions();
  CCTKi_BindingsIOASCIIParameterExtensions();
  CCTKi_BindingsIOBasicParameterExtensions();
  CCTKi_BindingsIOUtilParameterExtensions();
  CCTKi_BindingsInitBaseParameterExtensions();
  CCTKi_BindingsLocalInterpParameterExtensions();
  CCTKi_BindingsLocalReduceParameterExtensions();
  CCTKi_BindingsLoopControlParameterExtensions();
  CCTKi_BindingsMoLParameterExtensions();
  CCTKi_BindingsNaNCheckerParameterExtensions();
  CCTKi_BindingsOS_collapseParameterExtensions();
  CCTKi_BindingsOS_toyParameterExtensions();
  CCTKi_BindingsSpaceMaskParameterExtensions();
  CCTKi_BindingsSphericalSurfaceParameterExtensions();
  CCTKi_BindingsStaticConformalParameterExtensions();
  CCTKi_BindingsSymBaseParameterExtensions();
  CCTKi_BindingsTimeParameterExtensions();
  CCTKi_BindingsTwoPuncturesParameterExtensions();
  CCTKi_BindingsTwoPuncturesAEIParameterExtensions();
  CCTKi_BindingsWaveMoLParameterExtensions();
  CCTKi_BindingsWaveToyMoLParameterExtensions();
  CCTKi_BindingsahfinderdirectParameterExtensions();
  CCTKi_Bindingsang_freq_ofBfieldParameterExtensions();
  CCTKi_Bindingsbbh_cookpfeiffer_rotParameterExtensions();
  CCTKi_BindingsbbhloreneParameterExtensions();
  CCTKi_BindingsbhnsParameterExtensions();
  CCTKi_BindingsbssnParameterExtensions();
  CCTKi_Bindingscylindrical2dParameterExtensions();
  CCTKi_Bindingsdiagnostics_mhdParameterExtensions();
  CCTKi_Bindingsdiagnostics_vacuumParameterExtensions();
  CCTKi_Bindingsdisk_powerlawParameterExtensions();
  CCTKi_Bindingsem_extractionParameterExtensions();
  CCTKi_BindingsexcisionParameterExtensions();
  CCTKi_BindingsfisheyeParameterExtensions();
  CCTKi_Bindingsgw_extractionParameterExtensions();
  CCTKi_BindingsjobsuicideParameterExtensions();
  CCTKi_BindingslapseParameterExtensions();
  CCTKi_Bindingslinearized_waveParameterExtensions();
  CCTKi_Bindingsmag_bondiParameterExtensions();
  CCTKi_BindingsmagnetarParameterExtensions();
  CCTKi_Bindingsmhd_evolveParameterExtensions();
  CCTKi_BindingsmovingboxParameterExtensions();
  CCTKi_Bindingsmovingbox_for_boosted_bhParameterExtensions();
  CCTKi_Bindingsnonlinear_alfven_waveParameterExtensions();
  CCTKi_BindingsscalarwaveMoLParameterExtensions();
  CCTKi_BindingsshiftParameterExtensions();
  CCTKi_Bindingsshock_mhdParameterExtensions();
  CCTKi_BindingszlibParameterExtensions();

  return 0;
}

