/*@@
   @file    CarpetEvolutionMask_Parameters.c
   @author  Automatically generated by CreateParameterBindings.pl
   @desc
            Creates/extends parameters for this thorn
   @enddesc
 @@*/


#include <stdio.h>
#include <stdlib.h>
#include <stdarg.h>

#include "cctk_Config.h"
#include "cctk_Constants.h"
#include "ParameterBindings.h"
#include "CParameterStructNames.h"

/* structure containing all private parameters of thorn CarpetEvolutionMask */
struct
{
  const char * enforce_vars;
  CCTK_INT enforce_mask;
  CCTK_INT verbose;
  CCTK_INT writeNaNs;
} PRIVATE_CARPETEVOLUTIONMASK_STRUCT;


/* structure containing all restricted parameters of thorn CarpetEvolutionMask */
struct
{
  int dummy_parameter;
} RESTRICTED_CARPETEVOLUTIONMASK_STRUCT;


int CCTKi_BindingsCreateCarpetEvolutionMaskParameters(void);
int CCTKi_BindingsCreateCarpetEvolutionMaskParameters(void)
{
  CCTKi_ParameterCreate("enforce_mask",
                        "CarpetEvolutionMask",
                        "BOOLEAN",
                        "PRIVATE",
                        CCTK_STEERABLE_NEVER,
                        "Set RHS to zero where mask value is 0?",
                        "no",
                        &(PRIVATE_CARPETEVOLUTIONMASK_STRUCT.enforce_mask),
                        0,
                        NULL,
                        0);

  CCTKi_ParameterCreate("enforce_vars",
                        "CarpetEvolutionMask",
                        "STRING",
                        "PRIVATE",
                        CCTK_STEERABLE_NEVER,
                        "Enforce mask in MoL automatically on the following variables",
                        "",
                        &(PRIVATE_CARPETEVOLUTIONMASK_STRUCT.enforce_vars),
                        0,
                        NULL,
                        1,
                        "", "a list of variables or groups");

  CCTKi_ParameterCreate("verbose",
                        "CarpetEvolutionMask",
                        "BOOLEAN",
                        "PRIVATE",
                        CCTK_STEERABLE_NEVER,
                        "Do verbose debugging output",
                        "no",
                        &(PRIVATE_CARPETEVOLUTIONMASK_STRUCT.verbose),
                        0,
                        NULL,
                        0);

  CCTKi_ParameterCreate("writeNaNs",
                        "CarpetEvolutionMask",
                        "BOOLEAN",
                        "PRIVATE",
                        CCTK_STEERABLE_NEVER,
                        "Write NaNs into masked regions",
                        "no",
                        &(PRIVATE_CARPETEVOLUTIONMASK_STRUCT.writeNaNs),
                        0,
                        NULL,
                        0);

  return 0;
}

int CCTKi_BindingsCarpetEvolutionMaskParameterExtensions(void);
int CCTKi_BindingsCarpetEvolutionMaskParameterExtensions(void)
{
  return 0;
}

