/*@@
   @file    diagnostics_vacuum_Parameters.c
   @author  Automatically generated by CreateParameterBindings.pl
   @desc
            Creates/extends parameters for this thorn
   @enddesc
 @@*/


#include <stdio.h>
#include <stdlib.h>
#include <stdarg.h>

#include "cctk_Config.h"
#include "cctk_Constants.h"
#include "ParameterBindings.h"
#include "CParameterStructNames.h"
#include "ParameterCRestrictedGRID.h"
#include "ParameterCRestrictedLAPSE.h"
#include "ParameterCRestrictedSHIFT.h"

/* structure containing all private parameters of thorn diagnostics_vacuum */
struct
{
  int dummy_parameter;
} PRIVATE_DIAGNOSTICS_VACUUM_STRUCT;


/* structure containing all restricted parameters of thorn diagnostics_vacuum */
struct
{
  CCTK_REAL BH_Vol_Excise_Radius;
  CCTK_REAL dcostheta;
  CCTK_REAL ddrbddr;
  CCTK_REAL dphi;
  CCTK_REAL drbdr;
  CCTK_REAL inner_volInt_radius;
  CCTK_REAL rbr;
  CCTK_REAL rsurf2;
  CCTK_REAL surf_radius;
  CCTK_INT Compute_VolIntegrands_Every;
  CCTK_INT N_phi;
  CCTK_INT N_theta;
  CCTK_INT WhichIntegral;
  CCTK_INT arithsurf;
  CCTK_INT enable_Jz_constraint;
  CCTK_INT enable_M_constraint;
  CCTK_INT enable_P_constraint;
  CCTK_INT nsurf;
  CCTK_INT ntot;
  CCTK_INT num_BHs;
  CCTK_INT numphi;
  CCTK_INT numtheta;
  CCTK_INT scaledsurf;
  CCTK_INT sym_factor;
} RESTRICTED_DIAGNOSTICS_VACUUM_STRUCT;


int CCTKi_BindingsCreatediagnostics_vacuumParameters(void);
int CCTKi_BindingsCreatediagnostics_vacuumParameters(void)
{
  CCTKi_ParameterCreate("BH_Vol_Excise_Radius",
                        "diagnostics_vacuum",
                        "REAL",
                        "RESTRICTED",
                        CCTK_STEERABLE_ALWAYS,
                        "Sets size of BH excision volumes",
                        "1.1",
                        &(RESTRICTED_DIAGNOSTICS_VACUUM_STRUCT.BH_Vol_Excise_Radius),
                        0,
                        NULL,
                        1,
                        ":", "No restriction");

  CCTKi_ParameterCreate("Compute_VolIntegrands_Every",
                        "diagnostics_vacuum",
                        "INT",
                        "RESTRICTED",
                        CCTK_STEERABLE_NEVER,
                        "Compute volume integrals every x timesteps.  You set x here.",
                        "1",
                        &(RESTRICTED_DIAGNOSTICS_VACUUM_STRUCT.Compute_VolIntegrands_Every),
                        0,
                        NULL,
                        1,
                        "0:*", "You must set this value");

  CCTKi_ParameterCreate("N_phi",
                        "diagnostics_vacuum",
                        "INT",
                        "RESTRICTED",
                        CCTK_STEERABLE_ALWAYS,
                        "Surface integration: Actual Number of points in phi dimension w.r.t. symmetries",
                        "40",
                        &(RESTRICTED_DIAGNOSTICS_VACUUM_STRUCT.N_phi),
                        0,
                        NULL,
                        1,
                        "0:*", "Positive");

  CCTKi_ParameterCreate("N_theta",
                        "diagnostics_vacuum",
                        "INT",
                        "RESTRICTED",
                        CCTK_STEERABLE_ALWAYS,
                        "Surface integration: Actual Number of points in theta dimension w.r.t. symmetries",
                        "20",
                        &(RESTRICTED_DIAGNOSTICS_VACUUM_STRUCT.N_theta),
                        0,
                        NULL,
                        1,
                        "0:*", "Positive");

  CCTKi_ParameterCreate("WhichIntegral",
                        "diagnostics_vacuum",
                        "INT",
                        "RESTRICTED",
                        CCTK_STEERABLE_ALWAYS,
                        "Keeps track of which volume integral we've just evaluated",
                        "0",
                        &(RESTRICTED_DIAGNOSTICS_VACUUM_STRUCT.WhichIntegral),
                        0,
                        NULL,
                        1,
                        "*:*", "This value is set within the volume integration drivers.");

  CCTKi_ParameterCreate("arithsurf",
                        "diagnostics_vacuum",
                        "INT",
                        "RESTRICTED",
                        CCTK_STEERABLE_NEVER,
                        "Use arithmetic (1) or geometric (0) spacing for multiple integrations surfaces",
                        "1",
                        &(RESTRICTED_DIAGNOSTICS_VACUUM_STRUCT.arithsurf),
                        0,
                        NULL,
                        1,
                        "0:1", "Zero or one");

  CCTKi_ParameterCreate("dcostheta",
                        "diagnostics_vacuum",
                        "REAL",
                        "RESTRICTED",
                        CCTK_STEERABLE_ALWAYS,
                        "Change in cos(theta) for neighboring points",
                        "1",
                        &(RESTRICTED_DIAGNOSTICS_VACUUM_STRUCT.dcostheta),
                        0,
                        NULL,
                        1,
                        "0:*", "Positive");

  CCTKi_ParameterCreate("ddrbddr",
                        "diagnostics_vacuum",
                        "REAL",
                        "RESTRICTED",
                        CCTK_STEERABLE_ALWAYS,
                        "Surface integration: RadiusDerivative2 of surface: d^2r/drbar^2",
                        "0.0",
                        &(RESTRICTED_DIAGNOSTICS_VACUUM_STRUCT.ddrbddr),
                        0,
                        NULL,
                        1,
                        "0:*", "Anything positiive");

  CCTKi_ParameterCreate("dphi",
                        "diagnostics_vacuum",
                        "REAL",
                        "RESTRICTED",
                        CCTK_STEERABLE_ALWAYS,
                        "Change in phi for neighboring points",
                        "1",
                        &(RESTRICTED_DIAGNOSTICS_VACUUM_STRUCT.dphi),
                        0,
                        NULL,
                        1,
                        "0:*", "Positive");

  CCTKi_ParameterCreate("drbdr",
                        "diagnostics_vacuum",
                        "REAL",
                        "RESTRICTED",
                        CCTK_STEERABLE_ALWAYS,
                        "Surface integration: RadiusDerivative of surface: dr/drbar",
                        "1.0",
                        &(RESTRICTED_DIAGNOSTICS_VACUUM_STRUCT.drbdr),
                        0,
                        NULL,
                        1,
                        "0:*", "Anything. positive");

  CCTKi_ParameterCreate("enable_Jz_constraint",
                        "diagnostics_vacuum",
                        "INT",
                        "RESTRICTED",
                        CCTK_STEERABLE_ALWAYS,
                        "Compute Jz associated with momentum constraint violation? (0=no, 1=yes)",
                        "0",
                        &(RESTRICTED_DIAGNOSTICS_VACUUM_STRUCT.enable_Jz_constraint),
                        0,
                        NULL,
                        1,
                        "0:1", "yes or no");

  CCTKi_ParameterCreate("enable_M_constraint",
                        "diagnostics_vacuum",
                        "INT",
                        "RESTRICTED",
                        CCTK_STEERABLE_ALWAYS,
                        "Compute the mass associated with Hamiltonian constraint violation? (0=no, 1=yes)",
                        "0",
                        &(RESTRICTED_DIAGNOSTICS_VACUUM_STRUCT.enable_M_constraint),
                        0,
                        NULL,
                        1,
                        "0:1", "yes or no");

  CCTKi_ParameterCreate("enable_P_constraint",
                        "diagnostics_vacuum",
                        "INT",
                        "RESTRICTED",
                        CCTK_STEERABLE_ALWAYS,
                        "Compute momentum associated with momentum constraint violation? (0=no, 1=yes)",
                        "0",
                        &(RESTRICTED_DIAGNOSTICS_VACUUM_STRUCT.enable_P_constraint),
                        0,
                        NULL,
                        1,
                        "0:1", "yes or no");

  CCTKi_ParameterCreate("inner_volInt_radius",
                        "diagnostics_vacuum",
                        "REAL",
                        "RESTRICTED",
                        CCTK_STEERABLE_NEVER,
                        "Radius outside of which we exclude from Vol Int.  Note: For Ham constraint integral only!",
                        "32.0",
                        &(RESTRICTED_DIAGNOSTICS_VACUUM_STRUCT.inner_volInt_radius),
                        0,
                        NULL,
                        1,
                        "0:*", "anything positive");

  CCTKi_ParameterCreate("nsurf",
                        "diagnostics_vacuum",
                        "INT",
                        "RESTRICTED",
                        CCTK_STEERABLE_NEVER,
                        "number of surfaces at which to perform integrals",
                        "1",
                        &(RESTRICTED_DIAGNOSTICS_VACUUM_STRUCT.nsurf),
                        0,
                        NULL,
                        1,
                        "0:20", "positive, 20 or less for array allocation");

  CCTKi_ParameterCreate("ntot",
                        "diagnostics_vacuum",
                        "INT",
                        "RESTRICTED",
                        CCTK_STEERABLE_ALWAYS,
                        "Surface integration: Actual total Number of points both dimensions w.r.t. symmetries",
                        "640",
                        &(RESTRICTED_DIAGNOSTICS_VACUUM_STRUCT.ntot),
                        0,
                        NULL,
                        1,
                        "0:*", "Positive");

  CCTKi_ParameterCreate("num_BHs",
                        "diagnostics_vacuum",
                        "INT",
                        "RESTRICTED",
                        CCTK_STEERABLE_ALWAYS,
                        "Number of black holes",
                        "0",
                        &(RESTRICTED_DIAGNOSTICS_VACUUM_STRUCT.num_BHs),
                        0,
                        NULL,
                        1,
                        "0:*", "Greater than or equal to 0");

  CCTKi_ParameterCreate("numphi",
                        "diagnostics_vacuum",
                        "INT",
                        "RESTRICTED",
                        CCTK_STEERABLE_NEVER,
                        "Surface integration: Number of points in phi dimension if we used a full sphere",
                        "40",
                        &(RESTRICTED_DIAGNOSTICS_VACUUM_STRUCT.numphi),
                        0,
                        NULL,
                        1,
                        "0:*", "Positive");

  CCTKi_ParameterCreate("numtheta",
                        "diagnostics_vacuum",
                        "INT",
                        "RESTRICTED",
                        CCTK_STEERABLE_NEVER,
                        "Surface integration: Number of points in theta dimension if we used a full sphere",
                        "40",
                        &(RESTRICTED_DIAGNOSTICS_VACUUM_STRUCT.numtheta),
                        0,
                        NULL,
                        1,
                        "0:*", "Positive");

  CCTKi_ParameterCreate("rbr",
                        "diagnostics_vacuum",
                        "REAL",
                        "RESTRICTED",
                        CCTK_STEERABLE_ALWAYS,
                        "Surface integration: physical/fisheye radius of surface =  r/rbar",
                        "1.0",
                        &(RESTRICTED_DIAGNOSTICS_VACUUM_STRUCT.rbr),
                        0,
                        NULL,
                        1,
                        "0:*", "Anything poditive. This is reset in setup_fisheye if fisheye_enable=1");

  CCTKi_ParameterCreate("rsurf2",
                        "diagnostics_vacuum",
                        "REAL",
                        "RESTRICTED",
                        CCTK_STEERABLE_NEVER,
                        "The other extremal surfaces of integration; note scaledsurf above!",
                        "0.4",
                        &(RESTRICTED_DIAGNOSTICS_VACUUM_STRUCT.rsurf2),
                        0,
                        NULL,
                        1,
                        "0:*", "anything positive");

  CCTKi_ParameterCreate("scaledsurf",
                        "diagnostics_vacuum",
                        "INT",
                        "RESTRICTED",
                        CCTK_STEERABLE_ALWAYS,
                        "if surf_radius is negative, set to 1 and scale by size of grid.  otherwise, set to zero",
                        "0",
                        &(RESTRICTED_DIAGNOSTICS_VACUUM_STRUCT.scaledsurf),
                        0,
                        NULL,
                        1,
                        "0:1", "Zero or one");

  CCTKi_ParameterCreate("surf_radius",
                        "diagnostics_vacuum",
                        "REAL",
                        "RESTRICTED",
                        CCTK_STEERABLE_ALWAYS,
                        "Surface integration: Fisheye Radius of surface",
                        "-0.95",
                        &(RESTRICTED_DIAGNOSTICS_VACUUM_STRUCT.surf_radius),
                        0,
                        NULL,
                        1,
                        "*:*", "Anything.  Negative value will be reset by setup_surf...F90");

  CCTKi_ParameterCreate("sym_factor",
                        "diagnostics_vacuum",
                        "INT",
                        "RESTRICTED",
                        CCTK_STEERABLE_ALWAYS,
                        "Symmetry factor: how many of these grids make up a sphere",
                        "1",
                        &(RESTRICTED_DIAGNOSTICS_VACUUM_STRUCT.sym_factor),
                        0,
                        NULL,
                        1,
                        "1:*", "Greater than or equal to 1");

  return 0;
}

int CCTKi_Bindingsdiagnostics_vacuumParameterExtensions(void);
int CCTKi_Bindingsdiagnostics_vacuumParameterExtensions(void)
{
  return 0;
}

