/*@@
   @file    em_extraction_Parameters.c
   @author  Automatically generated by CreateParameterBindings.pl
   @desc
            Creates/extends parameters for this thorn
   @enddesc
 @@*/


#include <stdio.h>
#include <stdlib.h>
#include <stdarg.h>

#include "cctk_Config.h"
#include "cctk_Constants.h"
#include "ParameterBindings.h"
#include "CParameterStructNames.h"
#include "ParameterCRestrictedDIAGNOSTICS_VACUUM.h"
#include "ParameterCRestrictedIO.h"

/* structure containing all private parameters of thorn em_extraction */
struct
{
  CCTK_REAL compute_phi2_max_radius;
  CCTK_REAL compute_phi2_min_radius;
  CCTK_REAL radius_em_phi2[101];
  CCTK_INT num_extraction_radii_em;
  CCTK_INT radius_power_em;
  CCTK_INT scale_with_radius_em;
  CCTK_INT set_up_spherical_EM_wave_in_flat_spacetime;
} PRIVATE_EM_EXTRACTION_STRUCT;


/* structure containing all restricted parameters of thorn em_extraction */
struct
{
  CCTK_REAL dR_EM;
  CCTK_REAL ddR_EM;
  CCTK_REAL phi_EM;
  CCTK_REAL radius_EM;
  CCTK_REAL radius_EM_phys;
  CCTK_REAL theta_EM;
} RESTRICTED_EM_EXTRACTION_STRUCT;


int CCTKi_BindingsCreateem_extractionParameters(void);
int CCTKi_BindingsCreateem_extractionParameters(void)
{
  CCTKi_ParameterCreate("dR_EM",
                        "em_extraction",
                        "REAL",
                        "RESTRICTED",
                        CCTK_STEERABLE_NEVER,
                        "dR/dr",
                        "-1.0",
                        &(RESTRICTED_EM_EXTRACTION_STRUCT.dR_EM),
                        0,
                        NULL,
                        1,
                        "*:*", "Anything, negative means set = to surf_radius converted to phys coords!");

  CCTKi_ParameterCreate("ddR_EM",
                        "em_extraction",
                        "REAL",
                        "RESTRICTED",
                        CCTK_STEERABLE_NEVER,
                        "d^2R/dr^2",
                        "-1.0",
                        &(RESTRICTED_EM_EXTRACTION_STRUCT.ddR_EM),
                        0,
                        NULL,
                        1,
                        "*:*", "Anything, negative means set = to surf_radius converted to phys coords!");

  CCTKi_ParameterCreate("phi_EM",
                        "em_extraction",
                        "REAL",
                        "RESTRICTED",
                        CCTK_STEERABLE_ALWAYS,
                        "The angle phi in radians in which EM's are measured",
                        "0.52",
                        &(RESTRICTED_EM_EXTRACTION_STRUCT.phi_EM),
                        0,
                        NULL,
                        1,
                        "0:*", "Positive");

  CCTKi_ParameterCreate("radius_EM",
                        "em_extraction",
                        "REAL",
                        "RESTRICTED",
                        CCTK_STEERABLE_ALWAYS,
                        "The distance from the origin where EM's are measured",
                        "-1.0",
                        &(RESTRICTED_EM_EXTRACTION_STRUCT.radius_EM),
                        0,
                        NULL,
                        1,
                        "*:*", "Anything, negative means set = to surf_radius!");

  CCTKi_ParameterCreate("radius_EM_phys",
                        "em_extraction",
                        "REAL",
                        "RESTRICTED",
                        CCTK_STEERABLE_ALWAYS,
                        "The distance from the origin where EM's are measured, PHYSICAL COORDINATES!",
                        "-1.0",
                        &(RESTRICTED_EM_EXTRACTION_STRUCT.radius_EM_phys),
                        0,
                        NULL,
                        1,
                        "*:*", "Anything, negative means set = to surf_radius converted to phys coords!");

  CCTKi_ParameterCreate("theta_EM",
                        "em_extraction",
                        "REAL",
                        "RESTRICTED",
                        CCTK_STEERABLE_ALWAYS,
                        "The angle theta in radians in which EM's are measured",
                        "0.79",
                        &(RESTRICTED_EM_EXTRACTION_STRUCT.theta_EM),
                        0,
                        NULL,
                        1,
                        "0:*", "Positive");

  CCTKi_ParameterCreate("compute_phi2_max_radius",
                        "em_extraction",
                        "REAL",
                        "PRIVATE",
                        CCTK_STEERABLE_ALWAYS,
                        "Maximum radius at which to compute phi0 and phi2",
                        "100000.0",
                        &(PRIVATE_EM_EXTRACTION_STRUCT.compute_phi2_max_radius),
                        0,
                        NULL,
                        1,
                        "0:*", "Zero or positive");

  CCTKi_ParameterCreate("compute_phi2_min_radius",
                        "em_extraction",
                        "REAL",
                        "PRIVATE",
                        CCTK_STEERABLE_ALWAYS,
                        "Minimum radius at which to compute phi0 and phi2",
                        "0.0",
                        &(PRIVATE_EM_EXTRACTION_STRUCT.compute_phi2_min_radius),
                        0,
                        NULL,
                        1,
                        "0:*", "Zero or positive");

  CCTKi_ParameterCreate("num_extraction_radii_em",
                        "em_extraction",
                        "INT",
                        "PRIVATE",
                        CCTK_STEERABLE_NEVER,
                        "Number of extraction radii",
                        "10",
                        &(PRIVATE_EM_EXTRACTION_STRUCT.num_extraction_radii_em),
                        0,
                        NULL,
                        1,
                        "0:*", "Positive");

  CCTKi_ParameterCreate("radius_em_phi2",
                        "em_extraction",
                        "REAL",
                        "PRIVATE",
                        CCTK_STEERABLE_NEVER,
                        "extraction radii",
                        "0",
                        (PRIVATE_EM_EXTRACTION_STRUCT.radius_em_phi2),
                        101,
                        NULL,
                        1,
                        "0:*", "Zero or positive");

  CCTKi_ParameterCreate("radius_power_em",
                        "em_extraction",
                        "INT",
                        "PRIVATE",
                        CCTK_STEERABLE_NEVER,
                        "Power of radial coordinate to multiply by",
                        "1",
                        &(PRIVATE_EM_EXTRACTION_STRUCT.radius_power_em),
                        0,
                        NULL,
                        1,
                        "1:*", "");

  CCTKi_ParameterCreate("scale_with_radius_em",
                        "em_extraction",
                        "BOOLEAN",
                        "PRIVATE",
                        CCTK_STEERABLE_NEVER,
                        "Multiply all scalars by power of radial coordinate",
                        "no",
                        &(PRIVATE_EM_EXTRACTION_STRUCT.scale_with_radius_em),
                        0,
                        NULL,
                        0);

  CCTKi_ParameterCreate("set_up_spherical_EM_wave_in_flat_spacetime",
                        "em_extraction",
                        "INT",
                        "PRIVATE",
                        CCTK_STEERABLE_NEVER,
                        "0 = no, 1 = yes",
                        "0",
                        &(PRIVATE_EM_EXTRACTION_STRUCT.set_up_spherical_EM_wave_in_flat_spacetime),
                        0,
                        NULL,
                        1,
                        "0:1", "no or yes, this is to simply test the phi2 diagnostic in flat spacetime with a dipole EM wave of the form E=\hat\theta \sin(\theta)\cos(\omega t-k r), at time t=0");

  return 0;
}

int CCTKi_Bindingsem_extractionParameterExtensions(void);
int CCTKi_Bindingsem_extractionParameterExtensions(void)
{
  return 0;
}

