#define DECLARE_CCTK_PARAMETERS \
CCTK_REAL  excision_radius&&\
CCTK_REAL  run_time&&\
CCTK_INT Symmetry&&\
CCTK_INT bssn_enable&&\
CCTK_INT cowling_enable&&\
CCTK_INT excision_enable&&\
CCTK_INT fisheye_enable&&\
CCTK_INT iter_count&&\
CCTK_INT number_of_mol_ministeps&&\
CCTK_INT rot_metric&&\
CCTK_INT trA_detg_enforce&&\
COMMON /cctk_params_global/excision_radius,run_time,Symmetry,bssn_enable,cowling_enable,excision_enable,fisheye_enable,iter_count,number_of_mol_ministeps,rot_metric,trA_detg_enforce&&\
CCTK_REAL  initial_guess__Kerr_KerrSchild__mass(101)&&\
CCTK_REAL  initial_guess__Kerr_KerrSchild__spin(101)&&\
CCTK_REAL  initial_guess__Kerr_KerrSchild__x_posn(101)&&\
CCTK_REAL  initial_guess__Kerr_KerrSchild__y_posn(101)&&\
CCTK_REAL  initial_guess__Kerr_KerrSchild__z_posn(101)&&\
CCTK_REAL  initial_guess__Kerr_Kerr__mass(101)&&\
CCTK_REAL  initial_guess__Kerr_Kerr__spin(101)&&\
CCTK_REAL  initial_guess__Kerr_Kerr__x_posn(101)&&\
CCTK_REAL  initial_guess__Kerr_Kerr__y_posn(101)&&\
CCTK_REAL  initial_guess__Kerr_Kerr__z_posn(101)&&\
CCTK_REAL  initial_guess__coord_ellipsoid__x_center(101)&&\
CCTK_REAL  initial_guess__coord_ellipsoid__x_radius(101)&&\
CCTK_REAL  initial_guess__coord_ellipsoid__y_center(101)&&\
CCTK_REAL  initial_guess__coord_ellipsoid__y_radius(101)&&\
CCTK_REAL  initial_guess__coord_ellipsoid__z_center(101)&&\
CCTK_REAL  initial_guess__coord_ellipsoid__z_radius(101)&&\
CCTK_REAL  initial_guess__coord_sphere__radius(101)&&\
CCTK_REAL  initial_guess__coord_sphere__x_center(101)&&\
CCTK_REAL  initial_guess__coord_sphere__y_center(101)&&\
CCTK_REAL  initial_guess__coord_sphere__z_center(101)&&\
CCTK_REAL  origin_x(101)&&\
CCTK_REAL  origin_y(101)&&\
CCTK_REAL  origin_z(101)&&\
CCTK_STRING  initial_guess__read_from_named_file__file_name(101)&&\
CCTK_STRING  initial_guess_method(101)&&\
CCTK_INT move_origins&&\
CCTK_INT predict_origin_movement&&\
CCTK_INT reset_horizon_after_not_finding(101)&&\
CCTK_INT reshape_while_moving&&\
COMMON /AHFinderDirectrest/initial_guess__Kerr_KerrSchild__mass,initial_guess__Kerr_KerrSchild__spin,initial_guess__Kerr_KerrSchild__x_posn,initial_guess__Kerr_KerrSchild__y_posn,initial_guess__Kerr_KerrSchild__z_posn,initial_guess__Kerr_Kerr__mass,initial_guess__Kerr_Kerr__spin,initial_guess__Kerr_Kerr__x_posn,initial_guess__Kerr_Kerr__y_posn,initial_guess__Kerr_Kerr__z_posn,initial_guess__coord_ellipsoid__x_center,initial_guess__coord_ellipsoid__x_radius,initial_guess__coord_ellipsoid__y_center,initial_guess__coord_ellipsoid__y_radius,initial_guess__coord_ellipsoid__z_center,initial_guess__coord_ellipsoid__z_radius,initial_guess__coord_sphere__radius,initial_guess__coord_sphere__x_center,initial_guess__coord_sphere__y_center,initial_guess__coord_sphere__z_center,origin_x,origin_y,origin_z,initial_guess__read_from_named_file__file_name,initial_guess_method,move_origins,predict_origin_movement,reset_horizon_after_not_finding,reshape_while_moving&&\
CCTK_REAL  ILUCG__error_tolerance&&\
CCTK_REAL  Jacobian_perturbation_amplitude&&\
CCTK_REAL  Theta_norm_for_convergence&&\
CCTK_REAL  desired_value(101)&&\
CCTK_REAL  desired_value_factor(101)&&\
CCTK_REAL  desired_value_offset(101)&&\
CCTK_REAL  dont_find_after_individual_time(101)&&\
CCTK_REAL  find_after_individual_time(101)&&\
CCTK_REAL  geometry__Schwarzschild_EF__Delta_xyz&&\
CCTK_REAL  geometry__Schwarzschild_EF__epsilon&&\
CCTK_REAL  geometry__Schwarzschild_EF__mass&&\
CCTK_REAL  geometry__Schwarzschild_EF__x_posn&&\
CCTK_REAL  geometry__Schwarzschild_EF__y_posn&&\
CCTK_REAL  geometry__Schwarzschild_EF__z_posn&&\
CCTK_REAL  mask_buffer_thickness&&\
CCTK_REAL  mask_radius_multiplier&&\
CCTK_REAL  mask_radius_offset&&\
CCTK_REAL  max_allowable_Delta_h_over_h&&\
CCTK_REAL  max_allowable_Theta&&\
CCTK_REAL  max_allowable_horizon_radius(101)&&\
CCTK_REAL  min_horizon_radius_points_for_mask&&\
CCTK_REAL  old_style_mask_buffer_value&&\
CCTK_REAL  old_style_mask_inside_value&&\
CCTK_REAL  old_style_mask_outside_value&&\
CCTK_REAL  pretracking_delta(101)&&\
CCTK_REAL  pretracking_maximum_delta(101)&&\
CCTK_REAL  pretracking_maximum_value(101)&&\
CCTK_REAL  pretracking_minimum_delta(101)&&\
CCTK_REAL  pretracking_minimum_value(101)&&\
CCTK_REAL  pretracking_value(101)&&\
CCTK_REAL  shiftout_factor(101)&&\
CCTK_REAL  smoothing_factor(101)&&\
CCTK_STRING  ASCII_gnuplot_file_name_extension&&\
CCTK_STRING  BH_diagnostics_base_file_name&&\
CCTK_STRING  BH_diagnostics_directory&&\
CCTK_STRING  BH_diagnostics_file_name_extension&&\
CCTK_STRING  Delta_h_base_file_name&&\
CCTK_STRING  HDF5_file_name_extension&&\
CCTK_STRING  Jacobian_base_file_name&&\
CCTK_STRING  Jacobian_compute_method&&\
CCTK_STRING  Jacobian_store_solve_method&&\
CCTK_STRING  OpenDX_control_file_name_extension&&\
CCTK_STRING  Theta_base_file_name&&\
CCTK_STRING  coordinate_system_name&&\
CCTK_STRING  geometry_interpolator_name&&\
CCTK_STRING  geometry_interpolator_pars&&\
CCTK_STRING  h_base_file_name&&\
CCTK_STRING  h_directory&&\
CCTK_STRING  integral_method&&\
CCTK_STRING  interpatch_interpolator_name&&\
CCTK_STRING  interpatch_interpolator_pars&&\
CCTK_STRING  mean_curvature_base_file_name&&\
CCTK_STRING  method&&\
CCTK_STRING  metric_type&&\
CCTK_STRING  new_style_mask_bitfield_name&&\
CCTK_STRING  new_style_mask_buffer_value&&\
CCTK_STRING  new_style_mask_gridfn_name&&\
CCTK_STRING  new_style_mask_inside_value&&\
CCTK_STRING  new_style_mask_outside_value&&\
CCTK_STRING  old_style_mask_gridfn_name&&\
CCTK_STRING  patch_system_type(101)&&\
CCTK_STRING  surface_definition(101)&&\
CCTK_STRING  surface_interpolator_name&&\
CCTK_STRING  surface_interpolator_pars&&\
CCTK_STRING  surface_modification(101)&&\
CCTK_STRING  surface_selection(101)&&\
CCTK_STRING  verbose_level&&\
CCTK_INT ILUCG__limit_CG_iterations&&\
CCTK_INT N_horizons&&\
CCTK_INT N_zones_per_right_angle(101)&&\
CCTK_INT UMFPACK__N_II_iterations&&\
CCTK_INT check_that_geometry_is_finite&&\
CCTK_INT check_that_h_is_finite&&\
CCTK_INT debugging_output_at_each_Newton_iteration&&\
CCTK_INT depends_on(101)&&\
CCTK_INT disable_horizon(101)&&\
CCTK_INT dont_find_after_individual(101)&&\
CCTK_INT find_after_individual(101)&&\
CCTK_INT find_every&&\
CCTK_INT find_every_individual(101)&&\
CCTK_INT ghost_zone_width&&\
CCTK_INT h_min_digits&&\
CCTK_INT hardwire_Schwarzschild_EF_geometry&&\
CCTK_INT mask_is_noshrink&&\
CCTK_INT max_N_zones_per_right_angle&&\
CCTK_INT max_Newton_iterations__initial&&\
CCTK_INT max_Newton_iterations__subsequent&&\
CCTK_INT max_allowable_Theta_growth_iterations&&\
CCTK_INT max_allowable_Theta_nonshrink_iterations&&\
CCTK_INT output_ASCII_files&&\
CCTK_INT output_BH_diagnostics&&\
CCTK_INT output_HDF5_files&&\
CCTK_INT output_OpenDX_control_files&&\
CCTK_INT output_Theta_every&&\
CCTK_INT output_ghost_zones_for_h&&\
CCTK_INT output_h_every&&\
CCTK_INT output_initial_guess&&\
CCTK_INT output_mean_curvature_every&&\
CCTK_INT patch_overlap_width&&\
CCTK_INT pretracking_max_iterations(101)&&\
CCTK_INT print_timing_stats&&\
CCTK_INT run_at_CCTK_ANALYSIS&&\
CCTK_INT run_at_CCTK_POSTINITIAL&&\
CCTK_INT run_at_CCTK_POSTSTEP&&\
CCTK_INT run_at_CCTK_POST_RECOVER_VARIABLES&&\
CCTK_INT set_mask_for_all_horizons&&\
CCTK_INT set_mask_for_individual_horizon(101)&&\
CCTK_INT set_new_style_mask&&\
CCTK_INT set_old_style_mask&&\
CCTK_INT test_all_Jacobian_compute_methods&&\
CCTK_INT use_pretracking(101)&&\
CCTK_INT want_expansion_gradients&&\
CCTK_INT warn_level__gij_not_positive_definite__initial&&\
CCTK_INT warn_level__gij_not_positive_definite__subsequent&&\
CCTK_INT warn_level__nonfinite_geometry&&\
CCTK_INT warn_level__point_outside__initial&&\
CCTK_INT warn_level__point_outside__subsequent&&\
CCTK_INT warn_level__skipping_finite_check&&\
CCTK_INT which_horizon_to_announce_centroid&&\
CCTK_INT which_surface_to_store_info(101)&&\
COMMON /ahfinderdirectpriv/ILUCG__error_tolerance,Jacobian_perturbation_amplitude,Theta_norm_for_convergence,desired_value,desired_value_factor,desired_value_offset,dont_find_after_individual_time,find_after_individual_time,geometry__Schwarzschild_EF__Delta_xyz,geometry__Schwarzschild_EF__epsilon,geometry__Schwarzschild_EF__mass,geometry__Schwarzschild_EF__x_posn,geometry__Schwarzschild_EF__y_posn,geometry__Schwarzschild_EF__z_posn,mask_buffer_thickness,mask_radius_multiplier,mask_radius_offset,max_allowable_Delta_h_over_h,max_allowable_Theta,max_allowable_horizon_radius,min_horizon_radius_points_for_mask,old_style_mask_buffer_value,old_style_mask_inside_value,old_style_mask_outside_value,pretracking_delta,pretracking_maximum_delta,pretracking_maximum_value,pretracking_minimum_delta,pretracking_minimum_value,pretracking_value,shiftout_factor,smoothing_factor,ASCII_gnuplot_file_name_extension,BH_diagnostics_base_file_name,BH_diagnostics_directory,BH_diagnostics_file_name_extension,Delta_h_base_file_name,HDF5_file_name_extension,Jacobian_base_file_name,Jacobian_compute_method,Jacobian_store_solve_method,OpenDX_control_file_name_extension,Theta_base_file_name,coordinate_system_name,geometry_interpolator_name,geometry_interpolator_pars,h_base_file_name,h_directory,integral_method,interpatch_interpolator_name,interpatch_interpolator_pars,mean_curvature_base_file_name,method,metric_type,new_style_mask_bitfield_name,new_style_mask_buffer_value,new_style_mask_gridfn_name,new_style_mask_inside_value,new_style_mask_outside_value,old_style_mask_gridfn_name,patch_system_type,surface_definition,surface_interpolator_name,surface_interpolator_pars,surface_modification,surface_selection,verbose_level,ILUCG__limit_CG_iterations,N_horizons,N_zones_per_right_angle,UMFPACK__N_II_iterations,check_that_geometry_is_finite,check_that_h_is_finite,debugging_output_at_each_Newton_iteration,depends_on,disable_horizon,dont_find_after_individual,find_after_individual,find_every,find_every_individual,ghost_zone_width,h_min_digits,hardwire_Schwarzschild_EF_geometry,mask_is_noshrink,max_N_zones_per_right_angle,max_Newton_iterations__initial,max_Newton_iterations__subsequent,max_allowable_Theta_growth_iterations,max_allowable_Theta_nonshrink_iterations,output_ASCII_files,output_BH_diagnostics,output_HDF5_files,output_OpenDX_control_files,output_Theta_every,output_ghost_zones_for_h,output_h_every,output_initial_guess,output_mean_curvature_every,patch_overlap_width,pretracking_max_iterations,print_timing_stats,run_at_CCTK_ANALYSIS,run_at_CCTK_POSTINITIAL,run_at_CCTK_POSTSTEP,run_at_CCTK_POST_RECOVER_VARIABLES,set_mask_for_all_horizons,set_mask_for_individual_horizon,set_new_style_mask,set_old_style_mask,test_all_Jacobian_compute_methods,use_pretracking,want_expansion_gradients,warn_level__gij_not_positive_definite__initial,warn_level__gij_not_positive_definite__subsequent,warn_level__nonfinite_geometry,warn_level__point_outside__initial,warn_level__point_outside__subsequent,warn_level__skipping_finite_check,which_horizon_to_announce_centroid,which_surface_to_store_info&&\
CCTK_REAL  CCTKH0&&\
CCTK_REAL  CCTKH1&&\
CCTK_REAL  CCTKH2&&\
CCTK_REAL  CCTKH3&&\
CCTK_REAL  CCTKH11&&\
CCTK_REAL  CCTKH12&&\
CCTK_REAL  CCTKH13&&\
CCTK_REAL  CCTKH14&&\
CCTK_REAL  CCTKH15&&\
CCTK_REAL  CCTKH16&&\
CCTK_REAL  CCTKH17&&\
CCTK_REAL  CCTKH18&&\
CCTK_STRING  bitant_plane&&\
CCTK_STRING  domain&&\
CCTK_STRING  quadrant_direction&&\
CCTK_STRING  rotation_axis&&\
CCTK_STRING  CCTKH10&&\
CCTK_INT CCTKH4&&\
CCTK_INT CCTKH5&&\
CCTK_INT CCTKH6&&\
CCTK_INT CCTKH7&&\
CCTK_INT CCTKH8&&\
CCTK_INT CCTKH9&&\
COMMON /GRIDrest/CCTKH0,CCTKH1,CCTKH2,CCTKH3,CCTKH11,CCTKH12,CCTKH13,CCTKH14,CCTKH15,CCTKH16,CCTKH17,CCTKH18,bitant_plane,domain,quadrant_direction,rotation_axis,CCTKH10,CCTKH4,CCTKH5,CCTKH6,CCTKH7,CCTKH8,CCTKH9&&\
CCTK_REAL  CCTKH24&&\
CCTK_REAL  CCTKH37&&\
CCTK_REAL  CCTKH46&&\
CCTK_REAL  CCTKH48&&\
CCTK_REAL  CCTKH50&&\
CCTK_REAL  CCTKH52&&\
CCTK_REAL  CCTKH54&&\
CCTK_REAL  CCTKH56&&\
CCTK_REAL  CCTKH58&&\
CCTK_REAL  CCTKH60&&\
CCTK_REAL  CCTKH62&&\
CCTK_STRING  CCTKH21&&\
CCTK_STRING  CCTKH22&&\
CCTK_STRING  CCTKH25&&\
CCTK_STRING  CCTKH28&&\
CCTK_STRING  CCTKH29&&\
CCTK_STRING  CCTKH30&&\
CCTK_STRING  CCTKH33&&\
CCTK_STRING  out_dir&&\
CCTK_STRING  CCTKH39&&\
CCTK_STRING  CCTKH40&&\
CCTK_STRING  CCTKH42&&\
CCTK_STRING  CCTKH64&&\
CCTK_STRING  CCTKH66&&\
CCTK_STRING  CCTKH68&&\
CCTK_STRING  CCTKH70&&\
CCTK_STRING  CCTKH71&&\
CCTK_STRING  CCTKH74&&\
CCTK_INT CCTKH19&&\
CCTK_INT CCTKH20&&\
CCTK_INT CCTKH23&&\
CCTK_INT CCTKH26&&\
CCTK_INT CCTKH27&&\
CCTK_INT CCTKH31&&\
CCTK_INT CCTKH32&&\
CCTK_INT CCTKH34&&\
CCTK_INT CCTKH35&&\
CCTK_INT CCTKH36&&\
CCTK_INT CCTKH38&&\
CCTK_INT CCTKH41&&\
CCTK_INT CCTKH43&&\
CCTK_INT CCTKH44&&\
CCTK_INT CCTKH45&&\
CCTK_INT CCTKH47&&\
CCTK_INT CCTKH49&&\
CCTK_INT CCTKH51&&\
CCTK_INT CCTKH53&&\
CCTK_INT CCTKH55&&\
CCTK_INT CCTKH57&&\
CCTK_INT CCTKH59&&\
CCTK_INT CCTKH61&&\
CCTK_INT CCTKH63&&\
CCTK_INT CCTKH65&&\
CCTK_INT CCTKH67&&\
CCTK_INT CCTKH69&&\
CCTK_INT CCTKH72&&\
CCTK_INT CCTKH73&&\
COMMON /IOrest/CCTKH24,CCTKH37,CCTKH46,CCTKH48,CCTKH50,CCTKH52,CCTKH54,CCTKH56,CCTKH58,CCTKH60,CCTKH62,CCTKH21,CCTKH22,CCTKH25,CCTKH28,CCTKH29,CCTKH30,CCTKH33,out_dir,CCTKH39,CCTKH40,CCTKH42,CCTKH64,CCTKH66,CCTKH68,CCTKH70,CCTKH71,CCTKH74,CCTKH19,CCTKH20,CCTKH23,CCTKH26,CCTKH27,CCTKH31,CCTKH32,CCTKH34,CCTKH35,CCTKH36,CCTKH38,CCTKH41,CCTKH43,CCTKH44,CCTKH45,CCTKH47,CCTKH49,CCTKH51,CCTKH53,CCTKH55,CCTKH57,CCTKH59,CCTKH61,CCTKH63,CCTKH65,CCTKH67,CCTKH69,CCTKH72,CCTKH73&&\
CCTK_INT use_mask&&\
COMMON /SPACEMASKrest/use_mask&&\
CCTK_REAL  CCTKH77(42)&&\
CCTK_STRING  CCTKH76(42)&&\
CCTK_INT CCTKH75(42)&&\
CCTK_INT maxnphi&&\
CCTK_INT maxntheta&&\
CCTK_INT CCTKH78(42)&&\
CCTK_INT CCTKH79(42)&&\
CCTK_INT CCTKH80(42)&&\
CCTK_INT nsurfaces&&\
CCTK_INT CCTKH81(42)&&\
CCTK_INT CCTKH82(42)&&\
CCTK_INT CCTKH83(42)&&\
CCTK_INT CCTKH84(42)&&\
CCTK_INT CCTKH85&&\
COMMON /SPHERICALSURFACErest/CCTKH77,CCTKH76,CCTKH75,maxnphi,maxntheta,CCTKH78,CCTKH79,CCTKH80,nsurfaces,CCTKH81,CCTKH82,CCTKH83,CCTKH84,CCTKH85&&\

