/*@@
   @header  bbh_cookpfeiffer_rot_CParameters.h
   @author  Automatically generated by CreateParameterBindings.pl
   @desc
            Declares parameters of thorn bbh_cookpfeiffer_rot
   @enddesc
 @@*/


#ifndef _BBH_COOKPFEIFFER_ROT_PARAMETERS_H_
#define _BBH_COOKPFEIFFER_ROT_PARAMETERS_H_ 1

#include "ParameterCGlobal.h"
#include "ParameterCRestrictedBBH_COOKPFEIFFER_ROT.h"
#include "ParameterCPrivateBBH_COOKPFEIFFER_ROT.h"
#include "ParameterCRestrictedBSSN.h"
#include "ParameterCRestrictedDIAGNOSTICS_VACUUM.h"
#include "ParameterCRestrictedGRID.h"
#include "ParameterCRestrictedGW_EXTRACTION.h"
#include "ParameterCRestrictedIO.h"

#define DECLARE_CCTK_PARAMETERS \
  DECLARE_GLOBAL_PARAMETER_STRUCT_PARAMS \
  DECLARE_RESTRICTED_BBH_COOKPFEIFFER_ROT_STRUCT_PARAMS \
  DECLARE_PRIVATE_BBH_COOKPFEIFFER_ROT_STRUCT_PARAMS \
  CCTK_REAL const radmin_rot_interp_1 = RESTRICTED_BSSN_STRUCT.radmin_rot_interp_1; \
  CCTK_REAL const radmax_rot_interp_1 = RESTRICTED_BSSN_STRUCT.radmax_rot_interp_1; \
  CCTK_REAL const radmin_rot_interp_2 = RESTRICTED_BSSN_STRUCT.radmin_rot_interp_2; \
  CCTK_REAL const radmax_rot_interp_2 = RESTRICTED_BSSN_STRUCT.radmax_rot_interp_2; \
  CCTK_REAL const radmin_rot_interp_3 = RESTRICTED_BSSN_STRUCT.radmin_rot_interp_3; \
  CCTK_REAL const radmax_rot_interp_3 = RESTRICTED_BSSN_STRUCT.radmax_rot_interp_3; \
  CCTK_INT const Nlograd_rot_interp = RESTRICTED_BSSN_STRUCT.Nlograd_rot_interp; \
  CCTK_INT const Ntheta_rot_interp = RESTRICTED_BSSN_STRUCT.Ntheta_rot_interp; \
  CCTK_INT const Nphi_rot_interp = RESTRICTED_BSSN_STRUCT.Nphi_rot_interp; \
  CCTK_REAL const xbh1_initial = RESTRICTED_BSSN_STRUCT.xbh1_initial; \
  CCTK_REAL const xbh2_initial = RESTRICTED_BSSN_STRUCT.xbh2_initial; \
  CCTK_REAL const rah1_initial = RESTRICTED_BSSN_STRUCT.rah1_initial; \
  CCTK_REAL const rah2_initial = RESTRICTED_BSSN_STRUCT.rah2_initial; \
  CCTK_REAL const ah_excision_fac = RESTRICTED_BSSN_STRUCT.ah_excision_fac; \
  CCTK_REAL const binary_orb_freq = RESTRICTED_BSSN_STRUCT.binary_orb_freq; \
  CCTK_REAL const surf_radius = RESTRICTED_DIAGNOSTICS_VACUUM_STRUCT.surf_radius; \
  CCTK_REAL const rbr = RESTRICTED_DIAGNOSTICS_VACUUM_STRUCT.rbr; \
  CCTK_REAL const drbdr = RESTRICTED_DIAGNOSTICS_VACUUM_STRUCT.drbdr; \
  CCTK_REAL const ddrbddr = RESTRICTED_DIAGNOSTICS_VACUUM_STRUCT.ddrbddr; \
  CCTK_INT const scaledsurf = RESTRICTED_DIAGNOSTICS_VACUUM_STRUCT.scaledsurf; \
  CCTK_INT const nsurf = RESTRICTED_DIAGNOSTICS_VACUUM_STRUCT.nsurf; \
  CCTK_INT const arithsurf = RESTRICTED_DIAGNOSTICS_VACUUM_STRUCT.arithsurf; \
  CCTK_REAL const rsurf2 = RESTRICTED_DIAGNOSTICS_VACUUM_STRUCT.rsurf2; \
  const char * const domain = RESTRICTED_GRID_STRUCT.domain; \
  const char * const bitant_plane = RESTRICTED_GRID_STRUCT.bitant_plane; \
  CCTK_REAL const radius_GW = RESTRICTED_GW_EXTRACTION_STRUCT.radius_GW; \
  CCTK_REAL const theta_GW = RESTRICTED_GW_EXTRACTION_STRUCT.theta_GW; \
  CCTK_REAL const phi_GW = RESTRICTED_GW_EXTRACTION_STRUCT.phi_GW; \
  CCTK_INT const out_every = RESTRICTED_IO_STRUCT.out_every; \
  enum { \
      dummy_BSSN_radmin_rot_interp_1 = sizeof( radmin_rot_interp_1 ) \
    , dummy_BSSN_radmax_rot_interp_1 = sizeof( radmax_rot_interp_1 ) \
    , dummy_BSSN_radmin_rot_interp_2 = sizeof( radmin_rot_interp_2 ) \
    , dummy_BSSN_radmax_rot_interp_2 = sizeof( radmax_rot_interp_2 ) \
    , dummy_BSSN_radmin_rot_interp_3 = sizeof( radmin_rot_interp_3 ) \
    , dummy_BSSN_radmax_rot_interp_3 = sizeof( radmax_rot_interp_3 ) \
    , dummy_BSSN_Nlograd_rot_interp = sizeof( Nlograd_rot_interp ) \
    , dummy_BSSN_Ntheta_rot_interp = sizeof( Ntheta_rot_interp ) \
    , dummy_BSSN_Nphi_rot_interp = sizeof( Nphi_rot_interp ) \
    , dummy_BSSN_xbh1_initial = sizeof( xbh1_initial ) \
    , dummy_BSSN_xbh2_initial = sizeof( xbh2_initial ) \
    , dummy_BSSN_rah1_initial = sizeof( rah1_initial ) \
    , dummy_BSSN_rah2_initial = sizeof( rah2_initial ) \
    , dummy_BSSN_ah_excision_fac = sizeof( ah_excision_fac ) \
    , dummy_BSSN_binary_orb_freq = sizeof( binary_orb_freq ) \
    , dummy_DIAGNOSTICS_VACUUM_surf_radius = sizeof( surf_radius ) \
    , dummy_DIAGNOSTICS_VACUUM_rbr = sizeof( rbr ) \
    , dummy_DIAGNOSTICS_VACUUM_drbdr = sizeof( drbdr ) \
    , dummy_DIAGNOSTICS_VACUUM_ddrbddr = sizeof( ddrbddr ) \
    , dummy_DIAGNOSTICS_VACUUM_scaledsurf = sizeof( scaledsurf ) \
    , dummy_DIAGNOSTICS_VACUUM_nsurf = sizeof( nsurf ) \
    , dummy_DIAGNOSTICS_VACUUM_arithsurf = sizeof( arithsurf ) \
    , dummy_DIAGNOSTICS_VACUUM_rsurf2 = sizeof( rsurf2 ) \
    , dummy_GRID_domain = sizeof( domain ) \
    , dummy_GRID_bitant_plane = sizeof( bitant_plane ) \
    , dummy_GW_EXTRACTION_radius_GW = sizeof( radius_GW ) \
    , dummy_GW_EXTRACTION_theta_GW = sizeof( theta_GW ) \
    , dummy_GW_EXTRACTION_phi_GW = sizeof( phi_GW ) \
    , dummy_IO_out_every = sizeof( out_every ) \
  };

#endif  /* _BBH_COOKPFEIFFER_ROT_PARAMETERS_H_ */

