#define DECLARE_CCTK_PARAMETERS \
CCTK_REAL  excision_radius&&\
CCTK_REAL  run_time&&\
CCTK_INT Symmetry&&\
CCTK_INT bssn_enable&&\
CCTK_INT cowling_enable&&\
CCTK_INT excision_enable&&\
CCTK_INT fisheye_enable&&\
CCTK_INT iter_count&&\
CCTK_INT number_of_mol_ministeps&&\
CCTK_INT rot_metric&&\
CCTK_INT trA_detg_enforce&&\
COMMON /cctk_params_global/excision_radius,run_time,Symmetry,bssn_enable,cowling_enable,excision_enable,fisheye_enable,iter_count,number_of_mol_ministeps,rot_metric,trA_detg_enforce&&\
CCTK_INT iteration_to_compute_temp&&\
CCTK_INT iteration_to_insert_rad&&\
CCTK_INT num_CO&&\
COMMON /bhnsrest/iteration_to_compute_temp,iteration_to_insert_rad,num_CO&&\
CCTK_REAL  Aphi_power&&\
CCTK_REAL  BigM&&\
CCTK_REAL  Con_Pol&&\
CCTK_REAL  Con_Tor&&\
CCTK_REAL  Erad_over_rho&&\
CCTK_REAL  Iloop&&\
CCTK_REAL  Iloop2&&\
CCTK_REAL  MRI_wavelength_calculator_dxy&&\
CCTK_REAL  Omega_value&&\
CCTK_REAL  P_deplete_bhns&&\
CCTK_REAL  a2oa1_perturb&&\
CCTK_REAL  alpha_rho_cut_off&&\
CCTK_REAL  ampl_perturb&&\
CCTK_REAL  angle_to_tilt_magnetic_fields&&\
CCTK_REAL  angle_to_tilt_magnetic_fieldsII&&\
CCTK_REAL  beta_ext&&\
CCTK_REAL  betam1&&\
CCTK_REAL  betam1_2&&\
CCTK_REAL  bhns_P_max&&\
CCTK_REAL  bhns_P_max2&&\
CCTK_REAL  bhns_R_NS&&\
CCTK_REAL  bhns_R_NS2&&\
CCTK_REAL  bhns_avg_betam1&&\
CCTK_REAL  bhns_bh_filling_radius(100)&&\
CCTK_REAL  bhns_fac_atm&&\
CCTK_REAL  bhns_max_b2&&\
CCTK_REAL  bhns_max_b2_posn_x&&\
CCTK_REAL  bhns_max_b2_posn_y&&\
CCTK_REAL  bhns_max_b2_posn_z&&\
CCTK_REAL  bhns_max_rho_b&&\
CCTK_REAL  bhns_rho_b_max_posn_x&&\
CCTK_REAL  bhns_rho_b_max_posn_y&&\
CCTK_REAL  bhns_rho_b_max_posn_z&&\
CCTK_REAL  bhns_rhob_fac&&\
CCTK_REAL  bhns_rhob_max&&\
CCTK_REAL  bhns_tracer_r&&\
CCTK_REAL  bhns_tracer_rin&&\
CCTK_REAL  bhns_tracer_x0&&\
CCTK_REAL  bhns_tracer_y0&&\
CCTK_REAL  bhns_tracer_z0&&\
CCTK_REAL  bhns_vx_CM&&\
CCTK_REAL  bhns_vx_CM2&&\
CCTK_REAL  bhns_vy_CM&&\
CCTK_REAL  bhns_vy_CM2&&\
CCTK_REAL  bhns_vz_CM&&\
CCTK_REAL  bhns_vz_CM2&&\
CCTK_REAL  conloop1&&\
CCTK_REAL  conloop2&&\
CCTK_REAL  horiz_radius&&\
CCTK_REAL  initial_ns2_coord_x&&\
CCTK_REAL  initial_ns2_coord_y&&\
CCTK_REAL  initial_ns_coord_x&&\
CCTK_REAL  initial_ns_coord_y&&\
CCTK_REAL  initial_wd_coord_x&&\
CCTK_REAL  initial_wd_coord_y&&\
CCTK_REAL  lambda_perturb&&\
CCTK_REAL  moncrief_radius_GW(11)&&\
CCTK_REAL  mythbusters_boost_factor&&\
CCTK_REAL  p_c&&\
CCTK_REAL  particle_cone_angle&&\
CCTK_REAL  particle_cylinder_cone_zmax&&\
CCTK_REAL  particle_cylinder_cone_zmin&&\
CCTK_REAL  r0&&\
CCTK_REAL  r0_ah&&\
CCTK_REAL  rad_rhob_fac&&\
CCTK_REAL  radi_perturb&&\
CCTK_REAL  rhob_fac2&&\
CCTK_REAL  rhob_o_b2&&\
CCTK_REAL  rhobatm_falloff_power&&\
CCTK_REAL  rloop&&\
CCTK_REAL  rloop2&&\
CCTK_REAL  surfxmax&&\
CCTK_REAL  surfxmin&&\
CCTK_REAL  surfzmax&&\
CCTK_REAL  tracer_x_max&&\
CCTK_REAL  tracer_x_min&&\
CCTK_REAL  tracer_y_max&&\
CCTK_REAL  tracer_y_min&&\
CCTK_REAL  tracer_z_max&&\
CCTK_REAL  tracer_z_min&&\
CCTK_REAL  xh0&&\
CCTK_REAL  yh0&&\
CCTK_REAL  zh0&&\
CCTK_INT ATM_TYPE&&\
CCTK_INT INPUTARRAY_PHISIZE&&\
CCTK_INT INPUTARRAY_THETASIZE&&\
CCTK_INT ITERATION_TO_BOOST_MAGNETIC_FIELDS&&\
CCTK_INT ITERATION_TO_INSERT_MAGNETIC_FIELDS&&\
CCTK_INT ITERATION_TO_output_MRI_wavelength&&\
CCTK_INT MRI_wavelength_calculator_Nxy&&\
CCTK_INT NUM_ZERO_PTS&&\
CCTK_INT N_particles_to_trace&&\
CCTK_INT RADIAL_INTERP_ORDER&&\
CCTK_INT RESET_RHO_B_ATM&&\
CCTK_INT alpha_diagnostic&&\
CCTK_INT angle_to_tilt_90&&\
CCTK_INT bhns_B_v&&\
CCTK_INT bhns_domain&&\
CCTK_INT bhns_particle_tracer_start&&\
CCTK_INT bhns_regrid_input_enable&&\
CCTK_INT bhns_regrid_output_enable_iter&&\
CCTK_INT center_Bfields_around_BH_instead&&\
CCTK_INT chunklet_dump_every&&\
CCTK_INT chunklet_procs_at_a_time&&\
CCTK_INT em_field_type&&\
CCTK_INT genID_cmdline_output_enable&&\
CCTK_INT initial_particle_geometry&&\
CCTK_INT moncrief_gw_num_radii&&\
CCTK_INT nperturb&&\
CCTK_INT ntot_bhns&&\
CCTK_INT particle_center&&\
CCTK_INT particle_tracer_substep_every&&\
CCTK_INT piecewise&&\
CCTK_INT refill_horizons_magfields_every&&\
CCTK_INT reset_shift_lapse&&\
CCTK_INT subtract_off_Omega_r&&\
CCTK_INT superposition&&\
CCTK_INT surfphinum&&\
CCTK_INT surfxnum&&\
CCTK_INT surfznum&&\
CCTK_INT two_ns&&\
CCTK_INT unequalmass&&\
CCTK_INT use_new_bhns_initial_data&&\
COMMON /bhnspriv/Aphi_power,BigM,Con_Pol,Con_Tor,Erad_over_rho,Iloop,Iloop2,MRI_wavelength_calculator_dxy,Omega_value,P_deplete_bhns,a2oa1_perturb,alpha_rho_cut_off,ampl_perturb,angle_to_tilt_magnetic_fields,angle_to_tilt_magnetic_fieldsII,beta_ext,betam1,betam1_2,bhns_P_max,bhns_P_max2,bhns_R_NS,bhns_R_NS2,bhns_avg_betam1,bhns_bh_filling_radius,bhns_fac_atm,bhns_max_b2,bhns_max_b2_posn_x,bhns_max_b2_posn_y,bhns_max_b2_posn_z,bhns_max_rho_b,bhns_rho_b_max_posn_x,bhns_rho_b_max_posn_y,bhns_rho_b_max_posn_z,bhns_rhob_fac,bhns_rhob_max,bhns_tracer_r,bhns_tracer_rin,bhns_tracer_x0,bhns_tracer_y0,bhns_tracer_z0,bhns_vx_CM,bhns_vx_CM2,bhns_vy_CM,bhns_vy_CM2,bhns_vz_CM,bhns_vz_CM2,conloop1,conloop2,horiz_radius,initial_ns2_coord_x,initial_ns2_coord_y,initial_ns_coord_x,initial_ns_coord_y,initial_wd_coord_x,initial_wd_coord_y,lambda_perturb,moncrief_radius_GW,mythbusters_boost_factor,p_c,particle_cone_angle,particle_cylinder_cone_zmax,particle_cylinder_cone_zmin,r0,r0_ah,rad_rhob_fac,radi_perturb,rhob_fac2,rhob_o_b2,rhobatm_falloff_power,rloop,rloop2,surfxmax,surfxmin,surfzmax,tracer_x_max,tracer_x_min,tracer_y_max,tracer_y_min,tracer_z_max,tracer_z_min,xh0,yh0,zh0,ATM_TYPE,INPUTARRAY_PHISIZE,INPUTARRAY_THETASIZE,ITERATION_TO_BOOST_MAGNETIC_FIELDS,ITERATION_TO_INSERT_MAGNETIC_FIELDS,ITERATION_TO_output_MRI_wavelength,MRI_wavelength_calculator_Nxy,NUM_ZERO_PTS,N_particles_to_trace,RADIAL_INTERP_ORDER,RESET_RHO_B_ATM,alpha_diagnostic,angle_to_tilt_90,bhns_B_v,bhns_domain,bhns_particle_tracer_start,bhns_regrid_input_enable,bhns_regrid_output_enable_iter,center_Bfields_around_BH_instead,chunklet_dump_every,chunklet_procs_at_a_time,em_field_type,genID_cmdline_output_enable,initial_particle_geometry,moncrief_gw_num_radii,nperturb,ntot_bhns,particle_center,particle_tracer_substep_every,piecewise,refill_horizons_magfields_every,reset_shift_lapse,subtract_off_Omega_r,superposition,surfphinum,surfxnum,surfznum,two_ns,unequalmass,use_new_bhns_initial_data&&\
CCTK_REAL  CCTKH5&&\
CCTK_REAL  CCTKH6&&\
CCTK_REAL  CCTKH7&&\
CCTK_REAL  CCTKH8&&\
CCTK_REAL  binary_orb_freq&&\
CCTK_REAL  CCTKH11&&\
CCTK_REAL  CCTKH12&&\
CCTK_REAL  CCTKH13&&\
CCTK_REAL  CCTKH14&&\
CCTK_REAL  CCTKH15&&\
CCTK_REAL  CCTKH16&&\
CCTK_REAL  CCTKH17&&\
CCTK_REAL  CCTKH18&&\
CCTK_REAL  rotation_phase&&\
CCTK_REAL  CCTKH20&&\
CCTK_REAL  CCTKH21&&\
CCTK_REAL  CCTKH22&&\
CCTK_INT CCTKH0&&\
CCTK_INT CCTKH1&&\
CCTK_INT CCTKH2&&\
CCTK_INT CCTKH3&&\
CCTK_INT CCTKH4&&\
CCTK_INT CCTKH9&&\
CCTK_INT CCTKH10&&\
CCTK_INT CCTKH19&&\
CCTK_INT CCTKH23&&\
COMMON /BSSNrest/CCTKH5,CCTKH6,CCTKH7,CCTKH8,binary_orb_freq,CCTKH11,CCTKH12,CCTKH13,CCTKH14,CCTKH15,CCTKH16,CCTKH17,CCTKH18,rotation_phase,CCTKH20,CCTKH21,CCTKH22,CCTKH0,CCTKH1,CCTKH2,CCTKH3,CCTKH4,CCTKH9,CCTKH10,CCTKH19,CCTKH23&&\
CCTK_REAL  CCTKH24&&\
CCTK_REAL  M_ADM&&\
CCTK_REAL  initial_monopole_value&&\
CCTK_REAL  CCTKH30&&\
CCTK_REAL  CCTKH31&&\
CCTK_REAL  CCTKH33&&\
CCTK_REAL  CCTKH34&&\
CCTK_REAL  CCTKH35&&\
CCTK_REAL  CCTKH36&&\
CCTK_REAL  rhob_cutoff&&\
CCTK_REAL  CCTKH37&&\
CCTK_REAL  CCTKH38&&\
CCTK_REAL  CCTKH39&&\
CCTK_REAL  CCTKH40&&\
CCTK_INT CCTKH25&&\
CCTK_INT Nphi_points&&\
CCTK_INT CCTKH26&&\
CCTK_INT CCTKH27&&\
CCTK_INT CCTKH28&&\
CCTK_INT CCTKH29&&\
CCTK_INT CCTKH32&&\
COMMON /DIAGNOSTICS_MHDrest/CCTKH24,M_ADM,initial_monopole_value,CCTKH30,CCTKH31,CCTKH33,CCTKH34,CCTKH35,CCTKH36,rhob_cutoff,CCTKH37,CCTKH38,CCTKH39,CCTKH40,CCTKH25,Nphi_points,CCTKH26,CCTKH27,CCTKH28,CCTKH29,CCTKH32&&\
CCTK_REAL  BH_Vol_Excise_Radius&&\
CCTK_REAL  CCTKH43&&\
CCTK_REAL  ddrbddr&&\
CCTK_REAL  CCTKH44&&\
CCTK_REAL  drbdr&&\
CCTK_REAL  CCTKH48&&\
CCTK_REAL  rbr&&\
CCTK_REAL  rsurf2&&\
CCTK_REAL  surf_radius&&\
CCTK_INT CCTKH41&&\
CCTK_INT N_phi&&\
CCTK_INT N_theta&&\
CCTK_INT CCTKH42&&\
CCTK_INT arithsurf&&\
CCTK_INT CCTKH45&&\
CCTK_INT CCTKH46&&\
CCTK_INT CCTKH47&&\
CCTK_INT nsurf&&\
CCTK_INT CCTKH49&&\
CCTK_INT CCTKH50&&\
CCTK_INT CCTKH51&&\
CCTK_INT CCTKH52&&\
CCTK_INT scaledsurf&&\
CCTK_INT sym_factor&&\
COMMON /DIAGNOSTICS_VACUUMrest/BH_Vol_Excise_Radius,CCTKH43,ddrbddr,CCTKH44,drbdr,CCTKH48,rbr,rsurf2,surf_radius,CCTKH41,N_phi,N_theta,CCTKH42,arithsurf,CCTKH45,CCTKH46,CCTKH47,nsurf,CCTKH49,CCTKH50,CCTKH51,CCTKH52,scaledsurf,sym_factor&&\
CCTK_INT CCTKH53&&\
CCTK_INT CCTKH54&&\
CCTK_INT CCTKH55&&\
CCTK_INT CCTKH56&&\
COMMON /DRIVERrest/CCTKH53,CCTKH54,CCTKH55,CCTKH56&&\
CCTK_REAL  CCTKH57&&\
CCTK_REAL  CCTKH58&&\
CCTK_REAL  phi_GW&&\
CCTK_REAL  CCTKH59&&\
CCTK_REAL  CCTKH60&&\
CCTK_REAL  theta_GW&&\
COMMON /GW_EXTRACTIONrest/CCTKH57,CCTKH58,phi_GW,CCTKH59,CCTKH60,theta_GW&&\
CCTK_REAL  CCTKH66&&\
CCTK_REAL  CCTKH80&&\
CCTK_REAL  CCTKH88&&\
CCTK_REAL  CCTKH90&&\
CCTK_REAL  out_xyplane_z&&\
CCTK_REAL  out_xzplane_y&&\
CCTK_REAL  CCTKH94&&\
CCTK_REAL  CCTKH96&&\
CCTK_REAL  out_yzplane_x&&\
CCTK_REAL  CCTKH99&&\
CCTK_REAL  CCTKH101&&\
CCTK_STRING  CCTKH63&&\
CCTK_STRING  CCTKH64&&\
CCTK_STRING  CCTKH67&&\
CCTK_STRING  CCTKH70&&\
CCTK_STRING  CCTKH71&&\
CCTK_STRING  CCTKH72&&\
CCTK_STRING  CCTKH75&&\
CCTK_STRING  CCTKH76&&\
CCTK_STRING  CCTKH81&&\
CCTK_STRING  CCTKH82&&\
CCTK_STRING  CCTKH84&&\
CCTK_STRING  CCTKH103&&\
CCTK_STRING  CCTKH105&&\
CCTK_STRING  CCTKH107&&\
CCTK_STRING  CCTKH109&&\
CCTK_STRING  CCTKH110&&\
CCTK_STRING  CCTKH113&&\
CCTK_INT CCTKH61&&\
CCTK_INT CCTKH62&&\
CCTK_INT CCTKH65&&\
CCTK_INT CCTKH68&&\
CCTK_INT CCTKH69&&\
CCTK_INT CCTKH73&&\
CCTK_INT CCTKH74&&\
CCTK_INT CCTKH77&&\
CCTK_INT CCTKH78&&\
CCTK_INT CCTKH79&&\
CCTK_INT out_every&&\
CCTK_INT CCTKH83&&\
CCTK_INT CCTKH85&&\
CCTK_INT CCTKH86&&\
CCTK_INT CCTKH87&&\
CCTK_INT CCTKH89&&\
CCTK_INT CCTKH91&&\
CCTK_INT CCTKH92&&\
CCTK_INT CCTKH93&&\
CCTK_INT CCTKH95&&\
CCTK_INT CCTKH97&&\
CCTK_INT CCTKH98&&\
CCTK_INT CCTKH100&&\
CCTK_INT CCTKH102&&\
CCTK_INT CCTKH104&&\
CCTK_INT CCTKH106&&\
CCTK_INT CCTKH108&&\
CCTK_INT CCTKH111&&\
CCTK_INT CCTKH112&&\
COMMON /IOrest/CCTKH66,CCTKH80,CCTKH88,CCTKH90,out_xyplane_z,out_xzplane_y,CCTKH94,CCTKH96,out_yzplane_x,CCTKH99,CCTKH101,CCTKH63,CCTKH64,CCTKH67,CCTKH70,CCTKH71,CCTKH72,CCTKH75,CCTKH76,CCTKH81,CCTKH82,CCTKH84,CCTKH103,CCTKH105,CCTKH107,CCTKH109,CCTKH110,CCTKH113,CCTKH61,CCTKH62,CCTKH65,CCTKH68,CCTKH69,CCTKH73,CCTKH74,CCTKH77,CCTKH78,CCTKH79,out_every,CCTKH83,CCTKH85,CCTKH86,CCTKH87,CCTKH89,CCTKH91,CCTKH92,CCTKH93,CCTKH95,CCTKH97,CCTKH98,CCTKH100,CCTKH102,CCTKH104,CCTKH106,CCTKH108,CCTKH111,CCTKH112&&\
CCTK_REAL  CCTKH114&&\
CCTK_REAL  CCTKH115&&\
CCTK_REAL  CCTKH116&&\
CCTK_REAL  CCTKH120&&\
CCTK_REAL  CCTKH122&&\
CCTK_REAL  CCTKH123&&\
CCTK_REAL  CCTKH124&&\
CCTK_REAL  CCTKH125&&\
CCTK_STRING  CCTKH121&&\
CCTK_INT CCTKH117&&\
CCTK_INT CCTKH118&&\
CCTK_INT CCTKH119&&\
COMMON /MAGNETARrest/CCTKH114,CCTKH115,CCTKH116,CCTKH120,CCTKH122,CCTKH123,CCTKH124,CCTKH125,CCTKH121,CCTKH117,CCTKH118,CCTKH119&&\
CCTK_REAL  Erad_atm_cut&&\
CCTK_REAL  CCTKH127&&\
CCTK_REAL  K_poly&&\
CCTK_REAL  M_B&&\
CCTK_REAL  CCTKH131&&\
CCTK_REAL  P_fact&&\
CCTK_REAL  CCTKH132&&\
CCTK_REAL  Psi6threshold&&\
CCTK_REAL  Sym_Bz&&\
CCTK_REAL  T_fluid_cgs_atm&&\
CCTK_REAL  CCTKH137&&\
CCTK_REAL  CCTKH138&&\
CCTK_REAL  CCTKH140&&\
CCTK_REAL  eps_thermal_bhns&&\
CCTK_REAL  ergo_sigma&&\
CCTK_REAL  CCTKH145&&\
CCTK_REAL  gamma_th&&\
CCTK_REAL  CCTKH148&&\
CCTK_REAL  CCTKH150&&\
CCTK_REAL  CCTKH151&&\
CCTK_REAL  CCTKH152&&\
CCTK_REAL  CCTKH153&&\
CCTK_REAL  CCTKH154&&\
CCTK_REAL  pfloor&&\
CCTK_REAL  CCTKH156&&\
CCTK_REAL  rad_T_cutoff&&\
CCTK_REAL  rad_T_fac&&\
CCTK_REAL  rad_T_floor&&\
CCTK_REAL  rad_T_pow&&\
CCTK_REAL  CCTKH157&&\
CCTK_REAL  CCTKH158&&\
CCTK_REAL  CCTKH160&&\
CCTK_REAL  CCTKH161&&\
CCTK_REAL  rho_b_atm&&\
CCTK_REAL  rho_b_max&&\
CCTK_REAL  rho_fact&&\
CCTK_REAL  rhos_max&&\
CCTK_REAL  CCTKH164&&\
CCTK_REAL  CCTKH165&&\
CCTK_REAL  tau_atm&&\
CCTK_REAL  tau_fact&&\
CCTK_INT CCTKH126&&\
CCTK_INT EM_BC&&\
CCTK_INT CCTKH128&&\
CCTK_INT CCTKH129&&\
CCTK_INT CCTKH130&&\
CCTK_INT CCTKH133&&\
CCTK_INT CCTKH134&&\
CCTK_INT CCTKH135&&\
CCTK_INT CCTKH136&&\
CCTK_INT compute_microphysics&&\
CCTK_INT constrained_transport_scheme&&\
CCTK_INT CCTKH139&&\
CCTK_INT em_evolve_enable&&\
CCTK_INT em_gauge&&\
CCTK_INT CCTKH141&&\
CCTK_INT enable_OS_collapse&&\
CCTK_INT CCTKH142&&\
CCTK_INT CCTKH143&&\
CCTK_INT enable_shocktest_primitive_mode&&\
CCTK_INT enable_trace_field_line&&\
CCTK_INT eps_flag&&\
CCTK_INT ergo_star&&\
CCTK_INT CCTKH144&&\
CCTK_INT horizon_enforce_rho_profile&&\
CCTK_INT CCTKH146&&\
CCTK_INT CCTKH147&&\
CCTK_INT CCTKH149&&\
CCTK_INT microphysics_scheme&&\
CCTK_INT neos&&\
CCTK_INT CCTKH155&&\
CCTK_INT primitives_debug&&\
CCTK_INT primitives_solver&&\
CCTK_INT rad_closure_scheme&&\
CCTK_INT rad_evolve_enable&&\
CCTK_INT rad_fix&&\
CCTK_INT CCTKH159&&\
CCTK_INT CCTKH162&&\
CCTK_INT CCTKH163&&\
CCTK_INT tau_stildefix_enable&&\
CCTK_INT CCTKH166&&\
CCTK_INT CCTKH167&&\
CCTK_INT CCTKH168&&\
COMMON /MHD_EVOLVErest/Erad_atm_cut,CCTKH127,K_poly,M_B,CCTKH131,P_fact,CCTKH132,Psi6threshold,Sym_Bz,T_fluid_cgs_atm,CCTKH137,CCTKH138,CCTKH140,eps_thermal_bhns,ergo_sigma,CCTKH145,gamma_th,CCTKH148,CCTKH150,CCTKH151,CCTKH152,CCTKH153,CCTKH154,pfloor,CCTKH156,rad_T_cutoff,rad_T_fac,rad_T_floor,rad_T_pow,CCTKH157,CCTKH158,CCTKH160,CCTKH161,rho_b_atm,rho_b_max,rho_fact,rhos_max,CCTKH164,CCTKH165,tau_atm,tau_fact,CCTKH126,EM_BC,CCTKH128,CCTKH129,CCTKH130,CCTKH133,CCTKH134,CCTKH135,CCTKH136,compute_microphysics,constrained_transport_scheme,CCTKH139,em_evolve_enable,em_gauge,CCTKH141,enable_OS_collapse,CCTKH142,CCTKH143,enable_shocktest_primitive_mode,enable_trace_field_line,eps_flag,ergo_star,CCTKH144,horizon_enforce_rho_profile,CCTKH146,CCTKH147,CCTKH149,microphysics_scheme,neos,CCTKH155,primitives_debug,primitives_solver,rad_closure_scheme,rad_evolve_enable,rad_fix,CCTKH159,CCTKH162,CCTKH163,tau_stildefix_enable,CCTKH166,CCTKH167,CCTKH168&&\
CCTK_REAL  CCTKH170&&\
CCTK_REAL  CCTKH171&&\
CCTK_INT CCTKH169&&\
CCTK_INT track_bhns&&\
COMMON /MOVINGBOXrest/CCTKH170,CCTKH171,CCTKH169,track_bhns&&\

