/*@@
   @header  bhns_Prototypes.h
   @author  Automatically generated by CreateFunctionBindings.pl
   @desc
            Prototypes for overloaded functions used by this thorn
   @enddesc
  @@*/


#ifndef _BHNS_PROTOTYPES_H_
#define _BHNS_PROTOTYPES_H_  1

#ifdef CCODE
#ifdef __cplusplus
extern "C" {
#endif

CCTK_INT HorizonRadiusInDirection(const CCTK_INT horizon_number ,
 const CCTK_INT N_points ,
 const CCTK_REAL* x ,
 const CCTK_REAL* y ,
 const CCTK_REAL* z ,
 CCTK_REAL* radius);

#ifdef __cplusplus
}
#endif
#endif /* CCODE */

#ifdef FCODE
#ifdef F90CODE
#define DECLARE_BHNS_FUNCTIONS _DECLARE_CCTK_FUNCTIONS \
  interface &&\
     CCTK_INT function HorizonRadiusInDirection (horizon_number, N_points, x, y, z, radius) &&\
       implicit none &&\
       CCTK_INT horizon_number &&\
       CCTK_INT N_points &&\
       CCTK_REAL x(*) &&\
       CCTK_REAL y(*) &&\
       CCTK_REAL z(*) &&\
       CCTK_REAL radius(*) &&\
     end function HorizonRadiusInDirection &&\
  end interface &&\

#else /* ! F90CODE */

#define DECLARE_BHNS_FUNCTIONS _DECLARE_CCTK_FUNCTIONS \
  external HorizonRadiusInDirection &&\
  CCTK_INT HorizonRadiusInDirection &&\

#endif /* ! F90CODE */
#endif /* FCODE */

#endif

