#define DECLARE_CCTK_PARAMETERS \
CCTK_REAL  excision_radius&&\
CCTK_REAL  run_time&&\
CCTK_INT Symmetry&&\
CCTK_INT bssn_enable&&\
CCTK_INT cowling_enable&&\
CCTK_INT excision_enable&&\
CCTK_INT fisheye_enable&&\
CCTK_INT iter_count&&\
CCTK_INT number_of_mol_ministeps&&\
CCTK_INT rot_metric&&\
CCTK_INT trA_detg_enforce&&\
COMMON /cctk_params_global/excision_radius,run_time,Symmetry,bssn_enable,cowling_enable,excision_enable,fisheye_enable,iter_count,number_of_mol_ministeps,rot_metric,trA_detg_enforce&&\
CCTK_REAL  cctk_final_time&&\
CCTK_REAL  cctk_initial_time&&\
CCTK_REAL  max_runtime&&\
CCTK_STRING  terminate&&\
CCTK_INT cctk_itlast&&\
CCTK_INT terminate_next&&\
COMMON /Cactusrest/cctk_final_time,cctk_initial_time,max_runtime,terminate,cctk_itlast,terminate_next&&\
CCTK_STRING  cctk_run_title&&\
CCTK_STRING  cctk_timer_output&&\
CCTK_STRING  info_format&&\
CCTK_STRING  recovery_mode&&\
CCTK_INT allow_mixeddim_gfs&&\
CCTK_INT cctk_brief_output&&\
CCTK_INT cctk_full_warnings&&\
CCTK_INT cctk_show_banners&&\
CCTK_INT cctk_show_schedule&&\
CCTK_INT cctk_strong_param_check&&\
CCTK_INT highlight_warning_messages&&\
CCTK_INT manual_cache_setup&&\
CCTK_INT manual_cache_size&&\
CCTK_INT manual_cacheline_bytes&&\
COMMON /Cactuspriv/cctk_run_title,cctk_timer_output,info_format,recovery_mode,allow_mixeddim_gfs,cctk_brief_output,cctk_full_warnings,cctk_show_banners,cctk_show_schedule,cctk_strong_param_check,highlight_warning_messages,manual_cache_setup,manual_cache_size,manual_cacheline_bytes&&\

