#define DECLARE_CCTK_PARAMETERS \
CCTK_REAL  excision_radius&&\
CCTK_REAL  run_time&&\
CCTK_INT Symmetry&&\
CCTK_INT bssn_enable&&\
CCTK_INT cowling_enable&&\
CCTK_INT excision_enable&&\
CCTK_INT fisheye_enable&&\
CCTK_INT iter_count&&\
CCTK_INT number_of_mol_ministeps&&\
CCTK_INT rot_metric&&\
CCTK_INT trA_detg_enforce&&\
COMMON /cctk_params_global/excision_radius,run_time,Symmetry,bssn_enable,cowling_enable,excision_enable,fisheye_enable,iter_count,number_of_mol_ministeps,rot_metric,trA_detg_enforce&&\
CCTK_REAL  offsetx(10)&&\
CCTK_REAL  offsety(10)&&\
CCTK_REAL  offsetz(10)&&\
CCTK_INT num_offsets&&\
CCTK_INT offset_firstlevel&&\
COMMON /CarpetRegridrest/offsetx,offsety,offsetz,num_offsets,offset_firstlevel&&\
CCTK_REAL  l1xmax&&\
CCTK_REAL  l1xmin&&\
CCTK_REAL  l1ymax&&\
CCTK_REAL  l1ymin&&\
CCTK_REAL  l1zmax&&\
CCTK_REAL  l1zmin&&\
CCTK_REAL  l2xmax&&\
CCTK_REAL  l2xmin&&\
CCTK_REAL  l2ymax&&\
CCTK_REAL  l2ymin&&\
CCTK_REAL  l2zmax&&\
CCTK_REAL  l2zmin&&\
CCTK_REAL  l3xmax&&\
CCTK_REAL  l3xmin&&\
CCTK_REAL  l3ymax&&\
CCTK_REAL  l3ymin&&\
CCTK_REAL  l3zmax&&\
CCTK_REAL  l3zmin&&\
CCTK_REAL  maxerror&&\
CCTK_REAL  minfraction&&\
CCTK_REAL  moving_centre_x&&\
CCTK_REAL  moving_centre_y&&\
CCTK_REAL  moving_centre_z&&\
CCTK_REAL  moving_circle_frequency&&\
CCTK_REAL  moving_circle_radius&&\
CCTK_REAL  moving_region_radius&&\
CCTK_STRING  activate_levels_on_regrid&&\
CCTK_STRING  coordinates&&\
CCTK_STRING  errorvar&&\
CCTK_STRING  gridpoints&&\
CCTK_STRING  moving_trajectory&&\
CCTK_STRING  outerbounds&&\
CCTK_STRING  refined_regions&&\
CCTK_INT activate_next&&\
CCTK_INT keep_same_grid_structure&&\
CCTK_INT l1ixmax&&\
CCTK_INT l1ixmin&&\
CCTK_INT l1iymax&&\
CCTK_INT l1iymin&&\
CCTK_INT l1izmax&&\
CCTK_INT l1izmin&&\
CCTK_INT l2ixmax&&\
CCTK_INT l2ixmin&&\
CCTK_INT l2iymax&&\
CCTK_INT l2iymin&&\
CCTK_INT l2izmax&&\
CCTK_INT l2izmin&&\
CCTK_INT l3ixmax&&\
CCTK_INT l3ixmin&&\
CCTK_INT l3iymax&&\
CCTK_INT l3iymin&&\
CCTK_INT l3izmax&&\
CCTK_INT l3izmin&&\
CCTK_INT merge_overlapping_components&&\
CCTK_INT minwidth&&\
CCTK_INT num_new_levels&&\
CCTK_INT refinement_levels&&\
CCTK_INT regrid_every&&\
CCTK_INT smart_outer_boundaries&&\
CCTK_INT symmetry_x&&\
CCTK_INT symmetry_y&&\
CCTK_INT symmetry_z&&\
CCTK_INT tracking&&\
CCTK_INT verbose&&\
CCTK_INT veryverbose&&\
COMMON /CarpetRegridpriv/l1xmax,l1xmin,l1ymax,l1ymin,l1zmax,l1zmin,l2xmax,l2xmin,l2ymax,l2ymin,l2zmax,l2zmin,l3xmax,l3xmin,l3ymax,l3ymin,l3zmax,l3zmin,maxerror,minfraction,moving_centre_x,moving_centre_y,moving_centre_z,moving_circle_frequency,moving_circle_radius,moving_region_radius,activate_levels_on_regrid,coordinates,errorvar,gridpoints,moving_trajectory,outerbounds,refined_regions,activate_next,keep_same_grid_structure,l1ixmax,l1ixmin,l1iymax,l1iymin,l1izmax,l1izmin,l2ixmax,l2ixmin,l2iymax,l2iymin,l2izmax,l2izmin,l3ixmax,l3ixmin,l3iymax,l3iymin,l3izmax,l3izmin,merge_overlapping_components,minwidth,num_new_levels,refinement_levels,regrid_every,smart_outer_boundaries,symmetry_x,symmetry_y,symmetry_z,tracking,verbose,veryverbose&&\

