#define DECLARE_CCTK_PARAMETERS \
CCTK_REAL  excision_radius&&\
CCTK_REAL  run_time&&\
CCTK_INT Symmetry&&\
CCTK_INT bssn_enable&&\
CCTK_INT cowling_enable&&\
CCTK_INT excision_enable&&\
CCTK_INT fisheye_enable&&\
CCTK_INT iter_count&&\
CCTK_INT number_of_mol_ministeps&&\
CCTK_INT rot_metric&&\
CCTK_INT trA_detg_enforce&&\
COMMON /cctk_params_global/excision_radius,run_time,Symmetry,bssn_enable,cowling_enable,excision_enable,fisheye_enable,iter_count,number_of_mol_ministeps,rot_metric,trA_detg_enforce&&\
CCTK_STRING  memstat_file&&\
CCTK_STRING  timestat_file&&\
CCTK_INT barrier_between_stages&&\
CCTK_INT barriers&&\
CCTK_INT check_bboxes&&\
CCTK_INT combine_recompose&&\
CCTK_INT combine_sends&&\
CCTK_INT commstate_verbose&&\
CCTK_INT interleave_communications&&\
CCTK_INT max_allowed_memory_MB&&\
CCTK_INT output_bboxes&&\
CCTK_INT poison_new_memory&&\
CCTK_INT poison_value&&\
CCTK_INT print_memstats_every&&\
CCTK_INT print_timestats_every&&\
CCTK_INT reduce_mpi_waitall&&\
CCTK_INT use_mpi_send&&\
CCTK_INT use_mpi_ssend&&\
CCTK_INT vary_tags&&\
CCTK_INT verbose&&\
COMMON /CarpetLibpriv/memstat_file,timestat_file,barrier_between_stages,barriers,check_bboxes,combine_recompose,combine_sends,commstate_verbose,interleave_communications,max_allowed_memory_MB,output_bboxes,poison_new_memory,poison_value,print_memstats_every,print_timestats_every,reduce_mpi_waitall,use_mpi_send,use_mpi_ssend,vary_tags,verbose&&\
CCTK_REAL  CCTKH5&&\
CCTK_REAL  CCTKH18&&\
CCTK_REAL  CCTKH27&&\
CCTK_REAL  CCTKH29&&\
CCTK_REAL  CCTKH31&&\
CCTK_REAL  CCTKH33&&\
CCTK_REAL  CCTKH35&&\
CCTK_REAL  CCTKH37&&\
CCTK_REAL  CCTKH39&&\
CCTK_REAL  CCTKH41&&\
CCTK_REAL  CCTKH43&&\
CCTK_STRING  CCTKH2&&\
CCTK_STRING  CCTKH3&&\
CCTK_STRING  CCTKH6&&\
CCTK_STRING  CCTKH9&&\
CCTK_STRING  CCTKH10&&\
CCTK_STRING  CCTKH11&&\
CCTK_STRING  CCTKH14&&\
CCTK_STRING  out_dir&&\
CCTK_STRING  CCTKH20&&\
CCTK_STRING  CCTKH21&&\
CCTK_STRING  CCTKH23&&\
CCTK_STRING  CCTKH45&&\
CCTK_STRING  CCTKH47&&\
CCTK_STRING  CCTKH49&&\
CCTK_STRING  CCTKH51&&\
CCTK_STRING  CCTKH52&&\
CCTK_STRING  CCTKH55&&\
CCTK_INT CCTKH0&&\
CCTK_INT CCTKH1&&\
CCTK_INT CCTKH4&&\
CCTK_INT CCTKH7&&\
CCTK_INT CCTKH8&&\
CCTK_INT CCTKH12&&\
CCTK_INT CCTKH13&&\
CCTK_INT CCTKH15&&\
CCTK_INT CCTKH16&&\
CCTK_INT CCTKH17&&\
CCTK_INT CCTKH19&&\
CCTK_INT CCTKH22&&\
CCTK_INT CCTKH24&&\
CCTK_INT CCTKH25&&\
CCTK_INT CCTKH26&&\
CCTK_INT CCTKH28&&\
CCTK_INT CCTKH30&&\
CCTK_INT CCTKH32&&\
CCTK_INT CCTKH34&&\
CCTK_INT CCTKH36&&\
CCTK_INT CCTKH38&&\
CCTK_INT CCTKH40&&\
CCTK_INT CCTKH42&&\
CCTK_INT CCTKH44&&\
CCTK_INT CCTKH46&&\
CCTK_INT CCTKH48&&\
CCTK_INT CCTKH50&&\
CCTK_INT CCTKH53&&\
CCTK_INT CCTKH54&&\
COMMON /IOrest/CCTKH5,CCTKH18,CCTKH27,CCTKH29,CCTKH31,CCTKH33,CCTKH35,CCTKH37,CCTKH39,CCTKH41,CCTKH43,CCTKH2,CCTKH3,CCTKH6,CCTKH9,CCTKH10,CCTKH11,CCTKH14,out_dir,CCTKH20,CCTKH21,CCTKH23,CCTKH45,CCTKH47,CCTKH49,CCTKH51,CCTKH52,CCTKH55,CCTKH0,CCTKH1,CCTKH4,CCTKH7,CCTKH8,CCTKH12,CCTKH13,CCTKH15,CCTKH16,CCTKH17,CCTKH19,CCTKH22,CCTKH24,CCTKH25,CCTKH26,CCTKH28,CCTKH30,CCTKH32,CCTKH34,CCTKH36,CCTKH38,CCTKH40,CCTKH42,CCTKH44,CCTKH46,CCTKH48,CCTKH50,CCTKH53,CCTKH54&&\

