/*@@
   @header  CarpetIOHDF5_arguments.h
   @author  Automatically generated by GridFuncStuff.pl
   @desc
            Defines macros to declare/define/pass function arguments
            in calls from C to Fortran for thorn CarpetIOHDF5
   @enddesc
 @@*/


#ifdef FCODE
#define DECLARE_CARPETIOHDF5_PRIVATE_FARGUMENTS \
INTEGER last_output_iteration_slice_length&&\
INTEGER last_output_time_slice_length&&\
INTEGER this_iteration_slice_length&&\
CCTK_INT last_output_iteration_slice(last_output_iteration_slice_length)&&\
CCTK_REAL last_output_time_slice(last_output_time_slice_length)&&\
CCTK_INT next_output_iteration&&\
CCTK_REAL next_output_time&&\
CCTK_INT this_iteration&&\
CCTK_INT this_iteration_slice(this_iteration_slice_length)&&\


#define CARPETIOHDF5_PRIVATE_FARGUMENTS \
last_output_iteration_slice_length,last_output_time_slice_length,this_iteration_slice_length,last_output_iteration_slice,last_output_time_slice,next_output_iteration,next_output_time,this_iteration,this_iteration_slice

#endif /* FCODE */

#ifdef CCODE
#define DECLARE_CARPETIOHDF5_PRIVATE_CARGUMENTS \
CCTK_INT * CCTK_RESTRICT last_output_iteration_slice = (cctki_dummy_int = &last_output_iteration_slice - &last_output_iteration_slice, (CCTK_INT *) CCTKi_VarDataPtr(cctkGH, 0, "CARPETIOHDF5", "last_output_iteration_slice[0]")); \
CCTK_REAL * CCTK_RESTRICT last_output_time_slice = (cctki_dummy_int = &last_output_time_slice - &last_output_time_slice, (CCTK_REAL *) CCTKi_VarDataPtr(cctkGH, 0, "CARPETIOHDF5", "last_output_time_slice[0]")); \
CCTK_INT * CCTK_RESTRICT next_output_iteration = (cctki_dummy_int = &next_output_iteration - &next_output_iteration, (CCTK_INT *) CCTKi_VarDataPtr(cctkGH, 0, "CARPETIOHDF5", "next_output_iteration")); \
CCTK_REAL * CCTK_RESTRICT next_output_time = (cctki_dummy_int = &next_output_time - &next_output_time, (CCTK_REAL *) CCTKi_VarDataPtr(cctkGH, 0, "CARPETIOHDF5", "next_output_time")); \
CCTK_INT * CCTK_RESTRICT this_iteration = (cctki_dummy_int = &this_iteration - &this_iteration, (CCTK_INT *) CCTKi_VarDataPtr(cctkGH, 0, "CARPETIOHDF5", "this_iteration")); \
CCTK_INT * CCTK_RESTRICT this_iteration_slice = (cctki_dummy_int = &this_iteration_slice - &this_iteration_slice, (CCTK_INT *) CCTKi_VarDataPtr(cctkGH, 0, "CARPETIOHDF5", "this_iteration_slice[0]"));

#define DECLARE_CARPETIOHDF5_PRIVATE_C2F \
static int CCTKARGNUM_last_output_iteration_slice = -1; \
static int CCTKGROUPNUM_last_output_iteration_slice = -1; \
static int CCTKARGNUM_last_output_time_slice = -1; \
static int CCTKGROUPNUM_last_output_time_slice = -1; \
static int CCTKARGNUM_next_output_iteration = -1; \
static int CCTKGROUPNUM_next_output_iteration = -1; \
static int CCTKARGNUM_next_output_time = -1; \
static int CCTKGROUPNUM_next_output_time = -1; \
static int CCTKARGNUM_this_iteration = -1; \
static int CCTKGROUPNUM_this_iteration = -1; \
static int CCTKARGNUM_this_iteration_slice = -1; \
static int CCTKGROUPNUM_this_iteration_slice = -1;

#define INITIALISE_CARPETIOHDF5_PRIVATE_C2F \
if(CCTKARGNUM_last_output_iteration_slice == -1) CCTKARGNUM_last_output_iteration_slice = CCTK_VarIndex("CarpetIOHDF5::last_output_iteration_slice[0]"); \
if(CCTKGROUPNUM_last_output_iteration_slice == -1) CCTKGROUPNUM_last_output_iteration_slice = CCTK_GroupIndex("CarpetIOHDF5::last_output_iteration_slice"); \
if(CCTKARGNUM_last_output_time_slice == -1) CCTKARGNUM_last_output_time_slice = CCTK_VarIndex("CarpetIOHDF5::last_output_time_slice[0]"); \
if(CCTKGROUPNUM_last_output_time_slice == -1) CCTKGROUPNUM_last_output_time_slice = CCTK_GroupIndex("CarpetIOHDF5::last_output_time_slice"); \
if(CCTKARGNUM_next_output_iteration == -1) CCTKARGNUM_next_output_iteration = CCTK_VarIndex("CarpetIOHDF5::next_output_iteration"); \
if(CCTKGROUPNUM_next_output_iteration == -1) CCTKGROUPNUM_next_output_iteration = CCTK_GroupIndex("CarpetIOHDF5::next_output_iteration"); \
if(CCTKARGNUM_next_output_time == -1) CCTKARGNUM_next_output_time = CCTK_VarIndex("CarpetIOHDF5::next_output_time"); \
if(CCTKGROUPNUM_next_output_time == -1) CCTKGROUPNUM_next_output_time = CCTK_GroupIndex("CarpetIOHDF5::next_output_time"); \
if(CCTKARGNUM_this_iteration == -1) CCTKARGNUM_this_iteration = CCTK_VarIndex("CarpetIOHDF5::this_iteration"); \
if(CCTKGROUPNUM_this_iteration == -1) CCTKGROUPNUM_this_iteration = CCTK_GroupIndex("CarpetIOHDF5::this_iteration"); \
if(CCTKARGNUM_this_iteration_slice == -1) CCTKARGNUM_this_iteration_slice = CCTK_VarIndex("CarpetIOHDF5::this_iteration_slice[0]"); \
if(CCTKGROUPNUM_this_iteration_slice == -1) CCTKGROUPNUM_this_iteration_slice = CCTK_GroupIndex("CarpetIOHDF5::this_iteration_slice");

#define CARPETIOHDF5_PRIVATE_C2F_PROTO \
const int *,const int *,const int *,CCTK_INT *,CCTK_REAL *,CCTK_INT *,CCTK_REAL *,CCTK_INT *,CCTK_INT *

#define PASS_CARPETIOHDF5_PRIVATE_C2F(GH) \
PASS_GROUPLEN(CarpetIOHDF5, last_output_iteration_slice),\
PASS_GROUPLEN(CarpetIOHDF5, last_output_time_slice),\
PASS_GROUPLEN(CarpetIOHDF5, this_iteration_slice),\
(CCTK_INT *)(PASS_REFERENCE(last_output_iteration_slice, 0)),\
(CCTK_REAL *)(PASS_REFERENCE(last_output_time_slice, 0)),\
(CCTK_INT *)(PASS_REFERENCE(next_output_iteration, 0)),\
(CCTK_REAL *)(PASS_REFERENCE(next_output_time, 0)),\
(CCTK_INT *)(PASS_REFERENCE(this_iteration, 0)),\
(CCTK_INT *)(PASS_REFERENCE(this_iteration_slice, 0))

#endif /* CCODE */

#ifdef FCODE
#define DECLARE_CARPETIOHDF5_PROTECTED_FARGUMENTS \


#define CARPETIOHDF5_PROTECTED_FARGUMENTS \


#endif /* FCODE */

#ifdef CCODE
#define DECLARE_CARPETIOHDF5_PROTECTED_CARGUMENTS \


#define DECLARE_CARPETIOHDF5_PROTECTED_C2F \


#define INITIALISE_CARPETIOHDF5_PROTECTED_C2F \


#define CARPETIOHDF5_PROTECTED_C2F_PROTO \


#define PASS_CARPETIOHDF5_PROTECTED_C2F(GH) \


#endif /* CCODE */

#ifdef FCODE
#define DECLARE_CARPETIOHDF5_PUBLIC_FARGUMENTS \


#define CARPETIOHDF5_PUBLIC_FARGUMENTS \


#endif /* FCODE */

#ifdef CCODE
#define DECLARE_CARPETIOHDF5_PUBLIC_CARGUMENTS \


#define DECLARE_CARPETIOHDF5_PUBLIC_C2F \


#define INITIALISE_CARPETIOHDF5_PUBLIC_C2F \


#define CARPETIOHDF5_PUBLIC_C2F_PROTO \


#define PASS_CARPETIOHDF5_PUBLIC_C2F(GH) \


#endif /* CCODE */

#ifdef FCODE
#define CARPETIOHDF5_FARGUMENTS _CCTK_FARGUMENTS, CARPETIOHDF5_PRIVATE_FARGUMENTS

#define DECLARE_CARPETIOHDF5_FARGUMENTS _DECLARE_CCTK_FARGUMENTS DECLARE_CARPETIOHDF5_PRIVATE_FARGUMENTS

#endif /* FCODE */

#ifdef CCODE
#define DECLARE_CARPETIOHDF5_CARGUMENTS _DECLARE_CCTK_CARGUMENTS DECLARE_CARPETIOHDF5_PRIVATE_CARGUMENTS

#define CARPETIOHDF5_C2F_PROTO _CCTK_C2F_PROTO, CARPETIOHDF5_PRIVATE_C2F_PROTO

#define PASS_CARPETIOHDF5_C2F(GH) _PASS_CCTK_C2F(GH), PASS_CARPETIOHDF5_PRIVATE_C2F(GH)

#define DECLARE_CARPETIOHDF5_C2F _DECLARE_CCTK_C2F DECLARE_CARPETIOHDF5_PRIVATE_C2F

#define INITIALISE_CARPETIOHDF5_C2F _INITIALISE_CCTK_C2F INITIALISE_CARPETIOHDF5_PRIVATE_C2F

#define CARPETIOHDF5_CARGUMENTS cGH *cctkGH

#endif /* CCODE */
