#define DECLARE_CCTK_PARAMETERS \
CCTK_REAL  excision_radius&&\
CCTK_REAL  run_time&&\
CCTK_INT Symmetry&&\
CCTK_INT bssn_enable&&\
CCTK_INT cowling_enable&&\
CCTK_INT excision_enable&&\
CCTK_INT fisheye_enable&&\
CCTK_INT iter_count&&\
CCTK_INT number_of_mol_ministeps&&\
CCTK_INT rot_metric&&\
CCTK_INT trA_detg_enforce&&\
COMMON /cctk_params_global/excision_radius,run_time,Symmetry,bssn_enable,cowling_enable,excision_enable,fisheye_enable,iter_count,number_of_mol_ministeps,rot_metric,trA_detg_enforce&&\
CCTK_REAL  out0D_dt&&\
CCTK_REAL  out0D_point_x&&\
CCTK_REAL  out0D_point_y&&\
CCTK_REAL  out0D_point_z&&\
CCTK_REAL  out1D_dt&&\
CCTK_REAL  out1D_xline_y&&\
CCTK_REAL  out1D_xline_z&&\
CCTK_REAL  out1D_yline_x&&\
CCTK_REAL  out1D_yline_z&&\
CCTK_REAL  out1D_zline_x&&\
CCTK_REAL  out1D_zline_y&&\
CCTK_REAL  out2D_dt&&\
CCTK_REAL  out2D_xyplane_z&&\
CCTK_REAL  out2D_xzplane_y&&\
CCTK_REAL  out2D_yzplane_x&&\
CCTK_REAL  out3D_dt&&\
CCTK_STRING  out0D_criterion&&\
CCTK_STRING  out0D_dir&&\
CCTK_STRING  out0D_vars&&\
CCTK_STRING  out1D_criterion&&\
CCTK_STRING  out1D_dir&&\
CCTK_STRING  out1D_vars&&\
CCTK_STRING  out2D_criterion&&\
CCTK_STRING  out2D_dir&&\
CCTK_STRING  out2D_vars&&\
CCTK_STRING  out3D_criterion&&\
CCTK_STRING  out3D_dir&&\
CCTK_STRING  out3D_vars&&\
CCTK_INT one_file_per_group&&\
CCTK_INT out0D_every&&\
CCTK_INT out0D_point_xi&&\
CCTK_INT out0D_point_yi&&\
CCTK_INT out0D_point_zi&&\
CCTK_INT out1D_d&&\
CCTK_INT out1D_every&&\
CCTK_INT out1D_x&&\
CCTK_INT out1D_xline_yi&&\
CCTK_INT out1D_xline_zi&&\
CCTK_INT out1D_y&&\
CCTK_INT out1D_yline_xi&&\
CCTK_INT out1D_yline_zi&&\
CCTK_INT out1D_z&&\
CCTK_INT out1D_zline_xi&&\
CCTK_INT out1D_zline_yi&&\
CCTK_INT out2D_every&&\
CCTK_INT out2D_xy&&\
CCTK_INT out2D_xyplane_zi&&\
CCTK_INT out2D_xz&&\
CCTK_INT out2D_xzplane_yi&&\
CCTK_INT out2D_yz&&\
CCTK_INT out2D_yzplane_xi&&\
CCTK_INT out3D_every&&\
CCTK_INT out3D_ghosts&&\
CCTK_INT out3D_outer_ghosts&&\
CCTK_INT out_precision&&\
CCTK_INT output_all_timelevels&&\
CCTK_INT output_symmetry_points&&\
CCTK_INT separate_components&&\
CCTK_INT separate_grids&&\
COMMON /CarpetIOASCIIpriv/out0D_dt,out0D_point_x,out0D_point_y,out0D_point_z,out1D_dt,out1D_xline_y,out1D_xline_z,out1D_yline_x,out1D_yline_z,out1D_zline_x,out1D_zline_y,out2D_dt,out2D_xyplane_z,out2D_xzplane_y,out2D_yzplane_x,out3D_dt,out0D_criterion,out0D_dir,out0D_vars,out1D_criterion,out1D_dir,out1D_vars,out2D_criterion,out2D_dir,out2D_vars,out3D_criterion,out3D_dir,out3D_vars,one_file_per_group,out0D_every,out0D_point_xi,out0D_point_yi,out0D_point_zi,out1D_d,out1D_every,out1D_x,out1D_xline_yi,out1D_xline_zi,out1D_y,out1D_yline_xi,out1D_yline_zi,out1D_z,out1D_zline_xi,out1D_zline_yi,out2D_every,out2D_xy,out2D_xyplane_zi,out2D_xz,out2D_xzplane_yi,out2D_yz,out2D_yzplane_xi,out3D_every,out3D_ghosts,out3D_outer_ghosts,out_precision,output_all_timelevels,output_symmetry_points,separate_components,separate_grids&&\
CCTK_REAL  CCTKH5&&\
CCTK_REAL  out_dt&&\
CCTK_REAL  out_xline_y&&\
CCTK_REAL  out_xline_z&&\
CCTK_REAL  out_xyplane_z&&\
CCTK_REAL  out_xzplane_y&&\
CCTK_REAL  out_yline_x&&\
CCTK_REAL  out_yline_z&&\
CCTK_REAL  out_yzplane_x&&\
CCTK_REAL  out_zline_x&&\
CCTK_REAL  out_zline_y&&\
CCTK_STRING  CCTKH2&&\
CCTK_STRING  CCTKH3&&\
CCTK_STRING  CCTKH6&&\
CCTK_STRING  CCTKH9&&\
CCTK_STRING  CCTKH10&&\
CCTK_STRING  CCTKH11&&\
CCTK_STRING  out_criterion&&\
CCTK_STRING  out_dir&&\
CCTK_STRING  out_fileinfo&&\
CCTK_STRING  CCTKH16&&\
CCTK_STRING  CCTKH18&&\
CCTK_STRING  CCTKH22&&\
CCTK_STRING  CCTKH24&&\
CCTK_STRING  CCTKH26&&\
CCTK_STRING  CCTKH28&&\
CCTK_STRING  CCTKH29&&\
CCTK_STRING  verbose&&\
CCTK_INT CCTKH0&&\
CCTK_INT CCTKH1&&\
CCTK_INT CCTKH4&&\
CCTK_INT CCTKH7&&\
CCTK_INT CCTKH8&&\
CCTK_INT new_filename_scheme&&\
CCTK_INT CCTKH12&&\
CCTK_INT CCTKH13&&\
CCTK_INT CCTKH14&&\
CCTK_INT CCTKH15&&\
CCTK_INT out_every&&\
CCTK_INT CCTKH17&&\
CCTK_INT CCTKH19&&\
CCTK_INT CCTKH20&&\
CCTK_INT CCTKH21&&\
CCTK_INT out_xline_yi&&\
CCTK_INT out_xline_zi&&\
CCTK_INT out_xyplane_zi&&\
CCTK_INT out_xzplane_yi&&\
CCTK_INT out_yline_xi&&\
CCTK_INT out_yline_zi&&\
CCTK_INT out_yzplane_xi&&\
CCTK_INT out_zline_xi&&\
CCTK_INT out_zline_yi&&\
CCTK_INT CCTKH23&&\
CCTK_INT CCTKH25&&\
CCTK_INT CCTKH27&&\
CCTK_INT CCTKH30&&\
CCTK_INT strict_io_parameter_check&&\
COMMON /IOrest/CCTKH5,out_dt,out_xline_y,out_xline_z,out_xyplane_z,out_xzplane_y,out_yline_x,out_yline_z,out_yzplane_x,out_zline_x,out_zline_y,CCTKH2,CCTKH3,CCTKH6,CCTKH9,CCTKH10,CCTKH11,out_criterion,out_dir,out_fileinfo,CCTKH16,CCTKH18,CCTKH22,CCTKH24,CCTKH26,CCTKH28,CCTKH29,verbose,CCTKH0,CCTKH1,CCTKH4,CCTKH7,CCTKH8,new_filename_scheme,CCTKH12,CCTKH13,CCTKH14,CCTKH15,out_every,CCTKH17,CCTKH19,CCTKH20,CCTKH21,out_xline_yi,out_xline_zi,out_xyplane_zi,out_xzplane_yi,out_yline_xi,out_yline_zi,out_yzplane_xi,out_zline_xi,out_zline_yi,CCTKH23,CCTKH25,CCTKH27,CCTKH30,strict_io_parameter_check&&\

