/*@@
   @header  CarpetEvolutionMask_Prototypes.h
   @author  Automatically generated by CreateFunctionBindings.pl
   @desc
            Prototypes for overloaded functions used by this thorn
   @enddesc
  @@*/


#ifndef _CARPETEVOLUTIONMASK_PROTOTYPES_H_
#define _CARPETEVOLUTIONMASK_PROTOTYPES_H_  1

#ifdef CCODE
#ifdef __cplusplus
extern "C" {
#endif

CCTK_INT MoLQueryEvolvedRHS(const CCTK_INT EvolvedIndex);

#ifdef __cplusplus
}
#endif
#endif /* CCODE */

#ifdef FCODE
#ifdef F90CODE
#define DECLARE_CARPETEVOLUTIONMASK_FUNCTIONS _DECLARE_CCTK_FUNCTIONS \
  interface &&\
     CCTK_INT function MoLQueryEvolvedRHS (EvolvedIndex) &&\
       implicit none &&\
       CCTK_INT EvolvedIndex &&\
     end function MoLQueryEvolvedRHS &&\
  end interface &&\

#else /* ! F90CODE */

#define DECLARE_CARPETEVOLUTIONMASK_FUNCTIONS _DECLARE_CCTK_FUNCTIONS \
  external MoLQueryEvolvedRHS &&\
  CCTK_INT MoLQueryEvolvedRHS &&\

#endif /* ! F90CODE */
#endif /* FCODE */

#endif

