/*@@
   @header  CarpetTracker_CParameters.h
   @author  Automatically generated by CreateParameterBindings.pl
   @desc
            Declares parameters of thorn CarpetTracker
   @enddesc
 @@*/


#ifndef _CARPETTRACKER_PARAMETERS_H_
#define _CARPETTRACKER_PARAMETERS_H_ 1

#include "ParameterCGlobal.h"
#include "ParameterCPrivateCARPETTRACKER.h"
#include "ParameterCRestrictedSPHERICALSURFACE.h"

#define DECLARE_CCTK_PARAMETERS \
  DECLARE_GLOBAL_PARAMETER_STRUCT_PARAMS \
  DECLARE_PRIVATE_CARPETTRACKER_STRUCT_PARAMS \
  CCTK_INT const nsurfaces = RESTRICTED_SPHERICALSURFACE_STRUCT.nsurfaces; \
  enum { \
      dummy_SPHERICALSURFACE_nsurfaces = sizeof( nsurfaces ) \
  };

#endif  /* _CARPETTRACKER_PARAMETERS_H_ */

