#define DECLARE_CCTK_PARAMETERS \
CCTK_REAL  excision_radius&&\
CCTK_REAL  run_time&&\
CCTK_INT Symmetry&&\
CCTK_INT bssn_enable&&\
CCTK_INT cowling_enable&&\
CCTK_INT excision_enable&&\
CCTK_INT fisheye_enable&&\
CCTK_INT iter_count&&\
CCTK_INT number_of_mol_ministeps&&\
CCTK_INT rot_metric&&\
CCTK_INT trA_detg_enforce&&\
COMMON /cctk_params_global/excision_radius,run_time,Symmetry,bssn_enable,cowling_enable,excision_enable,fisheye_enable,iter_count,number_of_mol_ministeps,rot_metric,trA_detg_enforce&&\
CCTK_REAL  out0D_dt&&\
CCTK_REAL  out0D_point_x&&\
CCTK_REAL  out0D_point_y&&\
CCTK_REAL  out0D_point_z&&\
CCTK_REAL  out1D_dt&&\
CCTK_REAL  out1D_xline_y&&\
CCTK_REAL  out1D_xline_z&&\
CCTK_REAL  out1D_yline_x&&\
CCTK_REAL  out1D_yline_z&&\
CCTK_REAL  out1D_zline_x&&\
CCTK_REAL  out1D_zline_y&&\
CCTK_REAL  out2D_dt&&\
CCTK_REAL  out2D_xyplane_z&&\
CCTK_REAL  out2D_xzplane_y&&\
CCTK_REAL  out2D_yzplane_x&&\
CCTK_REAL  out_dt&&\
CCTK_STRING  out0D_criterion&&\
CCTK_STRING  out0D_dir&&\
CCTK_STRING  out0D_vars&&\
CCTK_STRING  out1D_criterion&&\
CCTK_STRING  out1D_dir&&\
CCTK_STRING  out1D_vars&&\
CCTK_STRING  out2D_criterion&&\
CCTK_STRING  out2D_dir&&\
CCTK_STRING  out2D_vars&&\
CCTK_STRING  out_criterion&&\
CCTK_STRING  out_dir&&\
CCTK_STRING  out_extension&&\
CCTK_STRING  out_vars&&\
CCTK_INT checkpoint&&\
CCTK_INT checkpoint_next&&\
CCTK_INT compression_level&&\
CCTK_INT one_file_per_group&&\
CCTK_INT open_one_input_file_at_a_time&&\
CCTK_INT out0D_every&&\
CCTK_INT out0D_point_xi&&\
CCTK_INT out0D_point_yi&&\
CCTK_INT out0D_point_zi&&\
CCTK_INT out1D_d&&\
CCTK_INT out1D_every&&\
CCTK_INT out1D_x&&\
CCTK_INT out1D_xline_yi&&\
CCTK_INT out1D_xline_zi&&\
CCTK_INT out1D_y&&\
CCTK_INT out1D_yline_xi&&\
CCTK_INT out1D_yline_zi&&\
CCTK_INT out1D_z&&\
CCTK_INT out1D_zline_xi&&\
CCTK_INT out1D_zline_yi&&\
CCTK_INT out2D_every&&\
CCTK_INT out2D_xy&&\
CCTK_INT out2D_xyplane_zi&&\
CCTK_INT out2D_xz&&\
CCTK_INT out2D_xzplane_yi&&\
CCTK_INT out2D_yz&&\
CCTK_INT out2D_yzplane_xi&&\
CCTK_INT out3D_ghosts&&\
CCTK_INT out3D_outer_ghosts&&\
CCTK_INT out_every&&\
CCTK_INT output_all_timelevels&&\
CCTK_INT output_index&&\
CCTK_INT output_symmetry_points&&\
CCTK_INT use_checksums&&\
CCTK_INT use_grid_structure_from_checkpoint&&\
CCTK_INT use_reflevels_from_checkpoint&&\
COMMON /CarpetIOHDF5priv/out0D_dt,out0D_point_x,out0D_point_y,out0D_point_z,out1D_dt,out1D_xline_y,out1D_xline_z,out1D_yline_x,out1D_yline_z,out1D_zline_x,out1D_zline_y,out2D_dt,out2D_xyplane_z,out2D_xzplane_y,out2D_yzplane_x,out_dt,out0D_criterion,out0D_dir,out0D_vars,out1D_criterion,out1D_dir,out1D_vars,out2D_criterion,out2D_dir,out2D_vars,out_criterion,out_dir,out_extension,out_vars,checkpoint,checkpoint_next,compression_level,one_file_per_group,open_one_input_file_at_a_time,out0D_every,out0D_point_xi,out0D_point_yi,out0D_point_zi,out1D_d,out1D_every,out1D_x,out1D_xline_yi,out1D_xline_zi,out1D_y,out1D_yline_xi,out1D_yline_zi,out1D_z,out1D_zline_xi,out1D_zline_yi,out2D_every,out2D_xy,out2D_xyplane_zi,out2D_xz,out2D_xzplane_yi,out2D_yz,out2D_yzplane_xi,out3D_ghosts,out3D_outer_ghosts,out_every,output_all_timelevels,output_index,output_symmetry_points,use_checksums,use_grid_structure_from_checkpoint,use_reflevels_from_checkpoint&&\
CCTK_REAL  CCTKH0&&\
CCTK_REAL  cctk_initial_time&&\
CCTK_REAL  CCTKH2&&\
CCTK_STRING  CCTKH3&&\
CCTK_INT CCTKH1&&\
CCTK_INT CCTKH4&&\
COMMON /CACTUSrest/CCTKH0,cctk_initial_time,CCTKH2,CCTKH3,CCTKH1,CCTKH4&&\
CCTK_REAL  checkpoint_every_walltime_hours&&\
CCTK_REAL  io_out_dt&&\
CCTK_REAL  out_xline_y&&\
CCTK_REAL  out_xline_z&&\
CCTK_REAL  out_xyplane_z&&\
CCTK_REAL  out_xzplane_y&&\
CCTK_REAL  out_yline_x&&\
CCTK_REAL  out_yline_z&&\
CCTK_REAL  out_yzplane_x&&\
CCTK_REAL  out_zline_x&&\
CCTK_REAL  out_zline_y&&\
CCTK_STRING  checkpoint_ID_file&&\
CCTK_STRING  checkpoint_dir&&\
CCTK_STRING  checkpoint_file&&\
CCTK_STRING  filereader_ID_dir&&\
CCTK_STRING  CCTKH5&&\
CCTK_STRING  CCTKH6&&\
CCTK_STRING  io_out_criterion&&\
CCTK_STRING  io_out_dir&&\
CCTK_STRING  CCTKH12&&\
CCTK_STRING  out_mode&&\
CCTK_STRING  out_save_parameters&&\
CCTK_STRING  CCTKH15&&\
CCTK_STRING  CCTKH17&&\
CCTK_STRING  recover&&\
CCTK_STRING  recover_dir&&\
CCTK_STRING  recover_file&&\
CCTK_STRING  verbose&&\
CCTK_INT abort_on_io_errors&&\
CCTK_INT checkpoint_ID&&\
CCTK_INT checkpoint_every&&\
CCTK_INT checkpoint_keep&&\
CCTK_INT checkpoint_on_terminate&&\
CCTK_INT CCTKH7&&\
CCTK_INT CCTKH8&&\
CCTK_INT CCTKH9&&\
CCTK_INT CCTKH10&&\
CCTK_INT CCTKH11&&\
CCTK_INT io_out_every&&\
CCTK_INT CCTKH13&&\
CCTK_INT out_single_precision&&\
CCTK_INT CCTKH14&&\
CCTK_INT io_out_unchunked&&\
CCTK_INT out_xline_yi&&\
CCTK_INT out_xline_zi&&\
CCTK_INT out_xyplane_zi&&\
CCTK_INT out_xzplane_yi&&\
CCTK_INT out_yline_xi&&\
CCTK_INT out_yline_zi&&\
CCTK_INT out_yzplane_xi&&\
CCTK_INT out_zline_xi&&\
CCTK_INT out_zline_yi&&\
CCTK_INT CCTKH16&&\
CCTK_INT CCTKH18&&\
CCTK_INT recover_and_remove&&\
CCTK_INT CCTKH19&&\
CCTK_INT strict_io_parameter_check&&\
COMMON /IOrest/checkpoint_every_walltime_hours,io_out_dt,out_xline_y,out_xline_z,out_xyplane_z,out_xzplane_y,out_yline_x,out_yline_z,out_yzplane_x,out_zline_x,out_zline_y,checkpoint_ID_file,checkpoint_dir,checkpoint_file,filereader_ID_dir,CCTKH5,CCTKH6,io_out_criterion,io_out_dir,CCTKH12,out_mode,out_save_parameters,CCTKH15,CCTKH17,recover,recover_dir,recover_file,verbose,abort_on_io_errors,checkpoint_ID,checkpoint_every,checkpoint_keep,checkpoint_on_terminate,CCTKH7,CCTKH8,CCTKH9,CCTKH10,CCTKH11,io_out_every,CCTKH13,out_single_precision,CCTKH14,io_out_unchunked,out_xline_yi,out_xline_zi,out_xyplane_zi,out_xzplane_yi,out_yline_xi,out_yline_zi,out_yzplane_xi,out_zline_xi,out_zline_yi,CCTKH16,CCTKH18,recover_and_remove,CCTKH19,strict_io_parameter_check&&\

