/*@@
   @header  Cartoon2D_CParameters.h
   @author  Automatically generated by CreateParameterBindings.pl
   @desc
            Declares parameters of thorn Cartoon2D
   @enddesc
 @@*/


#ifndef _CARTOON2D_PARAMETERS_H_
#define _CARTOON2D_PARAMETERS_H_ 1

#include "ParameterCGlobal.h"
#include "ParameterCPrivateCARTOON2D.h"

#define DECLARE_CCTK_PARAMETERS \
  DECLARE_GLOBAL_PARAMETER_STRUCT_PARAMS \
  DECLARE_PRIVATE_CARTOON2D_STRUCT_PARAMS \

#endif  /* _CARTOON2D_PARAMETERS_H_ */

