#define DECLARE_CCTK_PARAMETERS \
CCTK_REAL  excision_radius&&\
CCTK_REAL  run_time&&\
CCTK_INT Symmetry&&\
CCTK_INT bssn_enable&&\
CCTK_INT cowling_enable&&\
CCTK_INT excision_enable&&\
CCTK_INT fisheye_enable&&\
CCTK_INT iter_count&&\
CCTK_INT number_of_mol_ministeps&&\
CCTK_INT rot_metric&&\
CCTK_INT trA_detg_enforce&&\
COMMON /cctk_params_global/excision_radius,run_time,Symmetry,bssn_enable,cowling_enable,excision_enable,fisheye_enable,iter_count,number_of_mol_ministeps,rot_metric,trA_detg_enforce&&\
CCTK_REAL  dx&&\
CCTK_REAL  dxyz&&\
CCTK_REAL  dy&&\
CCTK_REAL  dz&&\
CCTK_REAL  xmax&&\
CCTK_REAL  xmin&&\
CCTK_REAL  xyzmax&&\
CCTK_REAL  xyzmin&&\
CCTK_REAL  ymax&&\
CCTK_REAL  ymin&&\
CCTK_REAL  zmax&&\
CCTK_REAL  zmin&&\
CCTK_STRING  bitant_plane&&\
CCTK_STRING  domain&&\
CCTK_STRING  quadrant_direction&&\
CCTK_STRING  rotation_axis&&\
CCTK_STRING  type&&\
CCTK_INT symmetry_xmax&&\
CCTK_INT symmetry_xmin&&\
CCTK_INT symmetry_ymax&&\
CCTK_INT symmetry_ymin&&\
CCTK_INT symmetry_zmax&&\
CCTK_INT symmetry_zmin&&\
COMMON /gridrest/dx,dxyz,dy,dz,xmax,xmin,xyzmax,xyzmin,ymax,ymin,zmax,zmin,bitant_plane,domain,quadrant_direction,rotation_axis,type,symmetry_xmax,symmetry_xmin,symmetry_ymax,symmetry_ymin,symmetry_zmax,symmetry_zmin&&\
CCTK_STRING  set_coordinate_ranges_on&&\
CCTK_INT avoid_origin&&\
CCTK_INT avoid_originx&&\
CCTK_INT avoid_originy&&\
CCTK_INT avoid_originz&&\
CCTK_INT no_origin&&\
CCTK_INT no_originx&&\
CCTK_INT no_originy&&\
CCTK_INT no_originz&&\
CCTK_INT register_default_coordinate_systems&&\
COMMON /CartGrid3Dpriv/set_coordinate_ranges_on,avoid_origin,avoid_originx,avoid_originy,avoid_originz,no_origin,no_originx,no_originy,no_originz,register_default_coordinate_systems&&\
CCTK_INT periodic&&\
CCTK_INT periodic_x&&\
CCTK_INT periodic_y&&\
CCTK_INT periodic_z&&\
COMMON /DRIVERrest/periodic,periodic_x,periodic_y,periodic_z&&\

