#define DECLARE_CCTK_PARAMETERS \
CCTK_REAL  excision_radius&&\
CCTK_REAL  run_time&&\
CCTK_INT Symmetry&&\
CCTK_INT bssn_enable&&\
CCTK_INT cowling_enable&&\
CCTK_INT excision_enable&&\
CCTK_INT fisheye_enable&&\
CCTK_INT iter_count&&\
CCTK_INT number_of_mol_ministeps&&\
CCTK_INT rot_metric&&\
CCTK_INT trA_detg_enforce&&\
COMMON /cctk_params_global/excision_radius,run_time,Symmetry,bssn_enable,cowling_enable,excision_enable,fisheye_enable,iter_count,number_of_mol_ministeps,rot_metric,trA_detg_enforce&&\
CCTK_REAL  dx&&\
CCTK_REAL  dy&&\
CCTK_REAL  dz&&\
CCTK_REAL  xextent&&\
CCTK_REAL  xmax&&\
CCTK_REAL  xmin&&\
CCTK_REAL  yextent&&\
CCTK_REAL  ymax&&\
CCTK_REAL  ymin&&\
CCTK_REAL  zextent&&\
CCTK_REAL  zmax&&\
CCTK_REAL  zmin&&\
CCTK_STRING  domainsize&&\
CCTK_STRING  spacing&&\
CCTK_INT boundary_internal_x_lower&&\
CCTK_INT boundary_internal_x_upper&&\
CCTK_INT boundary_internal_y_lower&&\
CCTK_INT boundary_internal_y_upper&&\
CCTK_INT boundary_internal_z_lower&&\
CCTK_INT boundary_internal_z_upper&&\
CCTK_INT boundary_shiftout_x_lower&&\
CCTK_INT boundary_shiftout_x_upper&&\
CCTK_INT boundary_shiftout_y_lower&&\
CCTK_INT boundary_shiftout_y_upper&&\
CCTK_INT boundary_shiftout_z_lower&&\
CCTK_INT boundary_shiftout_z_upper&&\
CCTK_INT boundary_size_x_lower&&\
CCTK_INT boundary_size_x_upper&&\
CCTK_INT boundary_size_y_lower&&\
CCTK_INT boundary_size_y_upper&&\
CCTK_INT boundary_size_z_lower&&\
CCTK_INT boundary_size_z_upper&&\
CCTK_INT boundary_staggered_x_lower&&\
CCTK_INT boundary_staggered_x_upper&&\
CCTK_INT boundary_staggered_y_lower&&\
CCTK_INT boundary_staggered_y_upper&&\
CCTK_INT boundary_staggered_z_lower&&\
CCTK_INT boundary_staggered_z_upper&&\
CCTK_INT ncells_x&&\
CCTK_INT ncells_y&&\
CCTK_INT ncells_z&&\
CCTK_INT zero_origin_x&&\
CCTK_INT zero_origin_y&&\
CCTK_INT zero_origin_z&&\
COMMON /CoordBasepriv/dx,dy,dz,xextent,xmax,xmin,yextent,ymax,ymin,zextent,zmax,zmin,domainsize,spacing,boundary_internal_x_lower,boundary_internal_x_upper,boundary_internal_y_lower,boundary_internal_y_upper,boundary_internal_z_lower,boundary_internal_z_upper,boundary_shiftout_x_lower,boundary_shiftout_x_upper,boundary_shiftout_y_lower,boundary_shiftout_y_upper,boundary_shiftout_z_lower,boundary_shiftout_z_upper,boundary_size_x_lower,boundary_size_x_upper,boundary_size_y_lower,boundary_size_y_upper,boundary_size_z_lower,boundary_size_z_upper,boundary_staggered_x_lower,boundary_staggered_x_upper,boundary_staggered_y_lower,boundary_staggered_y_upper,boundary_staggered_z_lower,boundary_staggered_z_upper,ncells_x,ncells_y,ncells_z,zero_origin_x,zero_origin_y,zero_origin_z&&\

