#define DECLARE_CCTK_PARAMETERS \
CCTK_REAL  excision_radius&&\
CCTK_REAL  run_time&&\
CCTK_INT Symmetry&&\
CCTK_INT bssn_enable&&\
CCTK_INT cowling_enable&&\
CCTK_INT excision_enable&&\
CCTK_INT fisheye_enable&&\
CCTK_INT iter_count&&\
CCTK_INT number_of_mol_ministeps&&\
CCTK_INT rot_metric&&\
CCTK_INT trA_detg_enforce&&\
COMMON /cctk_params_global/excision_radius,run_time,Symmetry,bssn_enable,cowling_enable,excision_enable,fisheye_enable,iter_count,number_of_mol_ministeps,rot_metric,trA_detg_enforce&&\
CCTK_REAL  BH_Vol_Excise_Radius&&\
CCTK_REAL  dcostheta&&\
CCTK_REAL  ddrbddr&&\
CCTK_REAL  dphi&&\
CCTK_REAL  drbdr&&\
CCTK_REAL  inner_volInt_radius&&\
CCTK_REAL  rbr&&\
CCTK_REAL  rsurf2&&\
CCTK_REAL  surf_radius&&\
CCTK_INT Compute_VolIntegrands_Every&&\
CCTK_INT N_phi&&\
CCTK_INT N_theta&&\
CCTK_INT WhichIntegral&&\
CCTK_INT arithsurf&&\
CCTK_INT enable_Jz_constraint&&\
CCTK_INT enable_M_constraint&&\
CCTK_INT enable_P_constraint&&\
CCTK_INT nsurf&&\
CCTK_INT ntot&&\
CCTK_INT num_BHs&&\
CCTK_INT numphi&&\
CCTK_INT numtheta&&\
CCTK_INT scaledsurf&&\
CCTK_INT sym_factor&&\
COMMON /diagnostics_vacuumrest/BH_Vol_Excise_Radius,dcostheta,ddrbddr,dphi,drbdr,inner_volInt_radius,rbr,rsurf2,surf_radius,Compute_VolIntegrands_Every,N_phi,N_theta,WhichIntegral,arithsurf,enable_Jz_constraint,enable_M_constraint,enable_P_constraint,nsurf,ntot,num_BHs,numphi,numtheta,scaledsurf,sym_factor&&\
CCTK_REAL  CCTKH0&&\
CCTK_REAL  CCTKH1&&\
CCTK_REAL  CCTKH2&&\
CCTK_REAL  CCTKH3&&\
CCTK_REAL  CCTKH13&&\
CCTK_REAL  CCTKH14&&\
CCTK_REAL  CCTKH15&&\
CCTK_REAL  CCTKH16&&\
CCTK_REAL  CCTKH17&&\
CCTK_REAL  CCTKH18&&\
CCTK_REAL  CCTKH19&&\
CCTK_REAL  CCTKH20&&\
CCTK_STRING  bitant_plane&&\
CCTK_STRING  domain&&\
CCTK_STRING  CCTKH4&&\
CCTK_STRING  CCTKH5&&\
CCTK_STRING  CCTKH12&&\
CCTK_INT CCTKH6&&\
CCTK_INT CCTKH7&&\
CCTK_INT CCTKH8&&\
CCTK_INT CCTKH9&&\
CCTK_INT CCTKH10&&\
CCTK_INT CCTKH11&&\
COMMON /GRIDrest/CCTKH0,CCTKH1,CCTKH2,CCTKH3,CCTKH13,CCTKH14,CCTKH15,CCTKH16,CCTKH17,CCTKH18,CCTKH19,CCTKH20,bitant_plane,domain,CCTKH4,CCTKH5,CCTKH12,CCTKH6,CCTKH7,CCTKH8,CCTKH9,CCTKH10,CCTKH11&&\
CCTK_REAL  CCTKH23&&\
CCTK_REAL  CCTKH24&&\
CCTK_REAL  CCTKH25&&\
CCTK_STRING  slicing_type&&\
CCTK_INT CCTKH21&&\
CCTK_INT CCTKH22&&\
CCTK_INT CCTKH26&&\
CCTK_INT CCTKH27&&\
CCTK_INT CCTKH28&&\
CCTK_INT CCTKH29&&\
CCTK_INT CCTKH30&&\
COMMON /LAPSErest/CCTKH23,CCTKH24,CCTKH25,slicing_type,CCTKH21,CCTKH22,CCTKH26,CCTKH27,CCTKH28,CCTKH29,CCTKH30&&\
CCTK_INT Spatial_Gauge&&\
CCTK_INT CCTKH31&&\
CCTK_INT CCTKH32&&\
COMMON /SHIFTrest/Spatial_Gauge,CCTKH31,CCTKH32&&\

