#define DECLARE_CCTK_PARAMETERS \
CCTK_REAL  excision_radius&&\
CCTK_REAL  run_time&&\
CCTK_INT Symmetry&&\
CCTK_INT bssn_enable&&\
CCTK_INT cowling_enable&&\
CCTK_INT excision_enable&&\
CCTK_INT fisheye_enable&&\
CCTK_INT iter_count&&\
CCTK_INT number_of_mol_ministeps&&\
CCTK_INT rot_metric&&\
CCTK_INT trA_detg_enforce&&\
COMMON /cctk_params_global/excision_radius,run_time,Symmetry,bssn_enable,cowling_enable,excision_enable,fisheye_enable,iter_count,number_of_mol_ministeps,rot_metric,trA_detg_enforce&&\
CCTK_REAL  KO_strength_falloff_dr&&\
CCTK_REAL  KO_strength_falloff_radius&&\
CCTK_REAL  KO_strength_final_value&&\
CCTK_REAL  ah_max_epsdis&&\
CCTK_REAL  ah_radius_offset&&\
CCTK_REAL  ah_slope&&\
CCTK_REAL  epsdis&&\
CCTK_REAL  epsdis_for_level(32)&&\
CCTK_REAL  ob_slope&&\
CCTK_REAL  outer_boundary_max_epsdis&&\
CCTK_STRING  vars&&\
CCTK_INT KO_strength_falloff_enable&&\
CCTK_INT extra_dissipation_at_outerbound&&\
CCTK_INT extra_dissipation_in_horizons&&\
CCTK_INT horizon_number(100)&&\
CCTK_INT order&&\
CCTK_INT outer_bound_npoints&&\
CCTK_INT respect_emask&&\
CCTK_INT surface_number(100)&&\
CCTK_INT update_ah_every&&\
CCTK_INT use_dissipation_near_excision&&\
CCTK_INT verbose&&\
COMMON /Dissipationrest/KO_strength_falloff_dr,KO_strength_falloff_radius,KO_strength_final_value,ah_max_epsdis,ah_radius_offset,ah_slope,epsdis,epsdis_for_level,ob_slope,outer_boundary_max_epsdis,vars,KO_strength_falloff_enable,extra_dissipation_at_outerbound,extra_dissipation_in_horizons,horizon_number,order,outer_bound_npoints,respect_emask,surface_number,update_ah_every,use_dissipation_near_excision,verbose&&\
CCTK_INT use_mask&&\
COMMON /SPACEMASKrest/use_mask&&\

