/*@@
   @header  Dissipation_Prototypes.h
   @author  Automatically generated by CreateFunctionBindings.pl
   @desc
            Prototypes for overloaded functions used by this thorn
   @enddesc
  @@*/


#ifndef _DISSIPATION_PROTOTYPES_H_
#define _DISSIPATION_PROTOTYPES_H_  1

#ifdef CCODE
#ifdef __cplusplus
extern "C" {
#endif

CCTK_INT HorizonRadiusInDirection(const CCTK_INT horizon_number ,
 const CCTK_INT N_points ,
 const CCTK_REAL* x ,
 const CCTK_REAL* y ,
 const CCTK_REAL* z ,
 CCTK_REAL* radius);

CCTK_INT MoLQueryEvolvedRHS(const CCTK_INT EvolvedIndex);

CCTK_INT SymmetryTableHandleForGrid(const CCTK_POINTER_TO_CONST cctkGH);

#ifdef __cplusplus
}
#endif
#endif /* CCODE */

#ifdef FCODE
#ifdef F90CODE
#define DECLARE_DISSIPATION_FUNCTIONS _DECLARE_CCTK_FUNCTIONS \
  interface &&\
     CCTK_INT function HorizonRadiusInDirection (horizon_number, N_points, x, y, z, radius) &&\
       implicit none &&\
       CCTK_INT horizon_number &&\
       CCTK_INT N_points &&\
       CCTK_REAL x(*) &&\
       CCTK_REAL y(*) &&\
       CCTK_REAL z(*) &&\
       CCTK_REAL radius(*) &&\
     end function HorizonRadiusInDirection &&\
  end interface &&\
  interface &&\
     CCTK_INT function MoLQueryEvolvedRHS (EvolvedIndex) &&\
       implicit none &&\
       CCTK_INT EvolvedIndex &&\
     end function MoLQueryEvolvedRHS &&\
  end interface &&\
  interface &&\
     CCTK_INT function SymmetryTableHandleForGrid (cctkGH) &&\
       implicit none &&\
       CCTK_POINTER_TO_CONST cctkGH &&\
     end function SymmetryTableHandleForGrid &&\
  end interface &&\

#else /* ! F90CODE */

#define DECLARE_DISSIPATION_FUNCTIONS _DECLARE_CCTK_FUNCTIONS \
  external HorizonRadiusInDirection &&\
  CCTK_INT HorizonRadiusInDirection &&\
  external MoLQueryEvolvedRHS &&\
  CCTK_INT MoLQueryEvolvedRHS &&\
  external SymmetryTableHandleForGrid &&\
  CCTK_INT SymmetryTableHandleForGrid &&\

#endif /* ! F90CODE */
#endif /* FCODE */

#endif

