/*@@
   @header  em_extraction_CParameters.h
   @author  Automatically generated by CreateParameterBindings.pl
   @desc
            Declares parameters of thorn em_extraction
   @enddesc
 @@*/


#ifndef _EM_EXTRACTION_PARAMETERS_H_
#define _EM_EXTRACTION_PARAMETERS_H_ 1

#include "ParameterCGlobal.h"
#include "ParameterCRestrictedEM_EXTRACTION.h"
#include "ParameterCPrivateEM_EXTRACTION.h"
#include "ParameterCRestrictedDIAGNOSTICS_VACUUM.h"
#include "ParameterCRestrictedIO.h"

#define DECLARE_CCTK_PARAMETERS \
  DECLARE_GLOBAL_PARAMETER_STRUCT_PARAMS \
  DECLARE_RESTRICTED_EM_EXTRACTION_STRUCT_PARAMS \
  DECLARE_PRIVATE_EM_EXTRACTION_STRUCT_PARAMS \
  CCTK_REAL const surf_radius = RESTRICTED_DIAGNOSTICS_VACUUM_STRUCT.surf_radius; \
  CCTK_INT const numtheta = RESTRICTED_DIAGNOSTICS_VACUUM_STRUCT.numtheta; \
  CCTK_INT const numphi = RESTRICTED_DIAGNOSTICS_VACUUM_STRUCT.numphi; \
  CCTK_INT const nsurf = RESTRICTED_DIAGNOSTICS_VACUUM_STRUCT.nsurf; \
  CCTK_INT const N_theta = RESTRICTED_DIAGNOSTICS_VACUUM_STRUCT.N_theta; \
  CCTK_INT const N_phi = RESTRICTED_DIAGNOSTICS_VACUUM_STRUCT.N_phi; \
  CCTK_INT const ntot = RESTRICTED_DIAGNOSTICS_VACUUM_STRUCT.ntot; \
  CCTK_INT const sym_factor = RESTRICTED_DIAGNOSTICS_VACUUM_STRUCT.sym_factor; \
  CCTK_REAL const dphi = RESTRICTED_DIAGNOSTICS_VACUUM_STRUCT.dphi; \
  CCTK_REAL const dcostheta = RESTRICTED_DIAGNOSTICS_VACUUM_STRUCT.dcostheta; \
  CCTK_REAL const rbr = RESTRICTED_DIAGNOSTICS_VACUUM_STRUCT.rbr; \
  CCTK_REAL const drbdr = RESTRICTED_DIAGNOSTICS_VACUUM_STRUCT.drbdr; \
  CCTK_REAL const ddrbddr = RESTRICTED_DIAGNOSTICS_VACUUM_STRUCT.ddrbddr; \
  CCTK_INT const out_every = RESTRICTED_IO_STRUCT.out_every; \
  enum { \
      dummy_DIAGNOSTICS_VACUUM_surf_radius = sizeof( surf_radius ) \
    , dummy_DIAGNOSTICS_VACUUM_numtheta = sizeof( numtheta ) \
    , dummy_DIAGNOSTICS_VACUUM_numphi = sizeof( numphi ) \
    , dummy_DIAGNOSTICS_VACUUM_nsurf = sizeof( nsurf ) \
    , dummy_DIAGNOSTICS_VACUUM_N_theta = sizeof( N_theta ) \
    , dummy_DIAGNOSTICS_VACUUM_N_phi = sizeof( N_phi ) \
    , dummy_DIAGNOSTICS_VACUUM_ntot = sizeof( ntot ) \
    , dummy_DIAGNOSTICS_VACUUM_sym_factor = sizeof( sym_factor ) \
    , dummy_DIAGNOSTICS_VACUUM_dphi = sizeof( dphi ) \
    , dummy_DIAGNOSTICS_VACUUM_dcostheta = sizeof( dcostheta ) \
    , dummy_DIAGNOSTICS_VACUUM_rbr = sizeof( rbr ) \
    , dummy_DIAGNOSTICS_VACUUM_drbdr = sizeof( drbdr ) \
    , dummy_DIAGNOSTICS_VACUUM_ddrbddr = sizeof( ddrbddr ) \
    , dummy_IO_out_every = sizeof( out_every ) \
  };

#endif  /* _EM_EXTRACTION_PARAMETERS_H_ */

