/*@@
   @header  fisheye_CParameters.h
   @author  Automatically generated by CreateParameterBindings.pl
   @desc
            Declares parameters of thorn fisheye
   @enddesc
 @@*/


#ifndef _FISHEYE_PARAMETERS_H_
#define _FISHEYE_PARAMETERS_H_ 1

#include "ParameterCGlobal.h"
#include "ParameterCRestrictedBSSN.h"
#include "ParameterCRestrictedGRID.h"
#include "ParameterCRestrictedIO.h"

#define DECLARE_CCTK_PARAMETERS \
  DECLARE_GLOBAL_PARAMETER_STRUCT_PARAMS \
  const char * const domain = RESTRICTED_GRID_STRUCT.domain; \
  const char * const bitant_plane = RESTRICTED_GRID_STRUCT.bitant_plane; \
  CCTK_INT const out_every = RESTRICTED_IO_STRUCT.out_every; \
  enum { \
      dummy_GRID_domain = sizeof( domain ) \
    , dummy_GRID_bitant_plane = sizeof( bitant_plane ) \
    , dummy_IO_out_every = sizeof( out_every ) \
  };

#endif  /* _FISHEYE_PARAMETERS_H_ */

