/*@@
   @header  GSL_CParameters.h
   @author  Automatically generated by CreateParameterBindings.pl
   @desc
            Declares parameters of thorn GSL
   @enddesc
 @@*/


#ifndef _GSL_PARAMETERS_H_
#define _GSL_PARAMETERS_H_ 1

#include "ParameterCGlobal.h"

#define DECLARE_CCTK_PARAMETERS \
  DECLARE_GLOBAL_PARAMETER_STRUCT_PARAMS \

#endif  /* _GSL_PARAMETERS_H_ */

