/*@@
   @header  HDF5_CParameters.h
   @author  Automatically generated by CreateParameterBindings.pl
   @desc
            Declares parameters of thorn HDF5
   @enddesc
 @@*/


#ifndef _HDF5_PARAMETERS_H_
#define _HDF5_PARAMETERS_H_ 1

#include "ParameterCGlobal.h"

#define DECLARE_CCTK_PARAMETERS \
  DECLARE_GLOBAL_PARAMETER_STRUCT_PARAMS \

#endif  /* _HDF5_PARAMETERS_H_ */

