#define DECLARE_CCTK_PARAMETERS \
CCTK_REAL  excision_radius&&\
CCTK_REAL  run_time&&\
CCTK_INT Symmetry&&\
CCTK_INT bssn_enable&&\
CCTK_INT cowling_enable&&\
CCTK_INT excision_enable&&\
CCTK_INT fisheye_enable&&\
CCTK_INT iter_count&&\
CCTK_INT number_of_mol_ministeps&&\
CCTK_INT rot_metric&&\
CCTK_INT trA_detg_enforce&&\
COMMON /cctk_params_global/excision_radius,run_time,Symmetry,bssn_enable,cowling_enable,excision_enable,fisheye_enable,iter_count,number_of_mol_ministeps,rot_metric,trA_detg_enforce&&\
CCTK_REAL  out1D_xline_y&&\
CCTK_REAL  out1D_xline_z&&\
CCTK_REAL  out1D_yline_x&&\
CCTK_REAL  out1D_yline_z&&\
CCTK_REAL  out1D_zline_x&&\
CCTK_REAL  out1D_zline_y&&\
CCTK_REAL  out2D_xyplane_z&&\
CCTK_REAL  out2D_xzplane_y&&\
CCTK_REAL  out2D_yzplane_x&&\
CCTK_STRING  out1D_dir&&\
CCTK_STRING  out1D_style&&\
CCTK_STRING  out1D_vars&&\
CCTK_STRING  out2D_dir&&\
CCTK_STRING  out2D_style&&\
CCTK_STRING  out2D_vars&&\
CCTK_STRING  out3D_dir&&\
CCTK_STRING  out3D_style&&\
CCTK_STRING  out3D_vars&&\
CCTK_STRING  out_format&&\
CCTK_INT out1D_d&&\
CCTK_INT out1D_every&&\
CCTK_INT out1D_x&&\
CCTK_INT out1D_xline_yi&&\
CCTK_INT out1D_xline_zi&&\
CCTK_INT out1D_y&&\
CCTK_INT out1D_yline_xi&&\
CCTK_INT out1D_yline_zi&&\
CCTK_INT out1D_z&&\
CCTK_INT out1D_zline_xi&&\
CCTK_INT out1D_zline_yi&&\
CCTK_INT out2D_every&&\
CCTK_INT out2D_xyplane_zi&&\
CCTK_INT out2D_xzplane_yi&&\
CCTK_INT out2D_yzplane_xi&&\
CCTK_INT out3D_every&&\
COMMON /IOASCIIpriv/out1D_xline_y,out1D_xline_z,out1D_yline_x,out1D_yline_z,out1D_zline_x,out1D_zline_y,out2D_xyplane_z,out2D_xzplane_y,out2D_yzplane_x,out1D_dir,out1D_style,out1D_vars,out2D_dir,out2D_style,out2D_vars,out3D_dir,out3D_style,out3D_vars,out_format,out1D_d,out1D_every,out1D_x,out1D_xline_yi,out1D_xline_zi,out1D_y,out1D_yline_xi,out1D_yline_zi,out1D_z,out1D_zline_xi,out1D_zline_yi,out2D_every,out2D_xyplane_zi,out2D_xzplane_yi,out2D_yzplane_xi,out3D_every&&\
CCTK_REAL  CCTKH5&&\
CCTK_REAL  CCTKH14&&\
CCTK_REAL  out_xline_y&&\
CCTK_REAL  out_xline_z&&\
CCTK_REAL  out_xyplane_z&&\
CCTK_REAL  out_xzplane_y&&\
CCTK_REAL  out_yline_x&&\
CCTK_REAL  out_yline_z&&\
CCTK_REAL  out_yzplane_x&&\
CCTK_REAL  out_zline_x&&\
CCTK_REAL  out_zline_y&&\
CCTK_STRING  CCTKH2&&\
CCTK_STRING  CCTKH3&&\
CCTK_STRING  CCTKH6&&\
CCTK_STRING  CCTKH9&&\
CCTK_STRING  CCTKH10&&\
CCTK_STRING  CCTKH11&&\
CCTK_STRING  CCTKH13&&\
CCTK_STRING  out_dir&&\
CCTK_STRING  out_fileinfo&&\
CCTK_STRING  CCTKH15&&\
CCTK_STRING  CCTKH17&&\
CCTK_STRING  CCTKH21&&\
CCTK_STRING  CCTKH23&&\
CCTK_STRING  CCTKH25&&\
CCTK_STRING  CCTKH27&&\
CCTK_STRING  CCTKH28&&\
CCTK_STRING  verbose&&\
CCTK_INT CCTKH0&&\
CCTK_INT CCTKH1&&\
CCTK_INT CCTKH4&&\
CCTK_INT CCTKH7&&\
CCTK_INT CCTKH8&&\
CCTK_INT new_filename_scheme&&\
CCTK_INT CCTKH12&&\
CCTK_INT out_downsample_x&&\
CCTK_INT out_downsample_y&&\
CCTK_INT out_downsample_z&&\
CCTK_INT out_every&&\
CCTK_INT CCTKH16&&\
CCTK_INT CCTKH18&&\
CCTK_INT CCTKH19&&\
CCTK_INT CCTKH20&&\
CCTK_INT out_xline_yi&&\
CCTK_INT out_xline_zi&&\
CCTK_INT out_xyplane_zi&&\
CCTK_INT out_xzplane_yi&&\
CCTK_INT out_yline_xi&&\
CCTK_INT out_yline_zi&&\
CCTK_INT out_yzplane_xi&&\
CCTK_INT out_zline_xi&&\
CCTK_INT out_zline_yi&&\
CCTK_INT CCTKH22&&\
CCTK_INT CCTKH24&&\
CCTK_INT CCTKH26&&\
CCTK_INT CCTKH29&&\
CCTK_INT strict_io_parameter_check&&\
COMMON /IOrest/CCTKH5,CCTKH14,out_xline_y,out_xline_z,out_xyplane_z,out_xzplane_y,out_yline_x,out_yline_z,out_yzplane_x,out_zline_x,out_zline_y,CCTKH2,CCTKH3,CCTKH6,CCTKH9,CCTKH10,CCTKH11,CCTKH13,out_dir,out_fileinfo,CCTKH15,CCTKH17,CCTKH21,CCTKH23,CCTKH25,CCTKH27,CCTKH28,verbose,CCTKH0,CCTKH1,CCTKH4,CCTKH7,CCTKH8,new_filename_scheme,CCTKH12,out_downsample_x,out_downsample_y,out_downsample_z,out_every,CCTKH16,CCTKH18,CCTKH19,CCTKH20,out_xline_yi,out_xline_zi,out_xyplane_zi,out_xzplane_yi,out_yline_xi,out_yline_zi,out_yzplane_xi,out_zline_xi,out_zline_yi,CCTKH22,CCTKH24,CCTKH26,CCTKH29,strict_io_parameter_check&&\

