#define DECLARE_CCTK_PARAMETERS \
CCTK_REAL  excision_radius&&\
CCTK_REAL  run_time&&\
CCTK_INT Symmetry&&\
CCTK_INT bssn_enable&&\
CCTK_INT cowling_enable&&\
CCTK_INT excision_enable&&\
CCTK_INT fisheye_enable&&\
CCTK_INT iter_count&&\
CCTK_INT number_of_mol_ministeps&&\
CCTK_INT rot_metric&&\
CCTK_INT trA_detg_enforce&&\
COMMON /cctk_params_global/excision_radius,run_time,Symmetry,bssn_enable,cowling_enable,excision_enable,fisheye_enable,iter_count,number_of_mol_ministeps,rot_metric,trA_detg_enforce&&\
CCTK_REAL  checkpoint_every_walltime_hours&&\
CCTK_REAL  out_dt&&\
CCTK_REAL  out_xline_y&&\
CCTK_REAL  out_xline_z&&\
CCTK_REAL  out_xyplane_z&&\
CCTK_REAL  out_xzplane_y&&\
CCTK_REAL  out_yline_x&&\
CCTK_REAL  out_yline_z&&\
CCTK_REAL  out_yzplane_x&&\
CCTK_REAL  out_zline_x&&\
CCTK_REAL  out_zline_y&&\
CCTK_STRING  checkpoint_ID_file&&\
CCTK_STRING  checkpoint_dir&&\
CCTK_STRING  checkpoint_file&&\
CCTK_STRING  filereader_ID_dir&&\
CCTK_STRING  filereader_ID_files&&\
CCTK_STRING  filereader_ID_vars&&\
CCTK_STRING  out_criterion&&\
CCTK_STRING  out_dir&&\
CCTK_STRING  out_fileinfo&&\
CCTK_STRING  out_mode&&\
CCTK_STRING  out_save_parameters&&\
CCTK_STRING  parfile_name&&\
CCTK_STRING  parfile_write&&\
CCTK_STRING  recover&&\
CCTK_STRING  recover_dir&&\
CCTK_STRING  recover_file&&\
CCTK_STRING  verbose&&\
CCTK_INT abort_on_io_errors&&\
CCTK_INT checkpoint_ID&&\
CCTK_INT checkpoint_every&&\
CCTK_INT checkpoint_keep&&\
CCTK_INT checkpoint_on_terminate&&\
CCTK_INT new_filename_scheme&&\
CCTK_INT out3D_septimefiles&&\
CCTK_INT out_downsample_x&&\
CCTK_INT out_downsample_y&&\
CCTK_INT out_downsample_z&&\
CCTK_INT out_every&&\
CCTK_INT out_proc_every&&\
CCTK_INT out_single_precision&&\
CCTK_INT out_timesteps_per_file&&\
CCTK_INT out_unchunked&&\
CCTK_INT out_xline_yi&&\
CCTK_INT out_xline_zi&&\
CCTK_INT out_xyplane_zi&&\
CCTK_INT out_xzplane_yi&&\
CCTK_INT out_yline_xi&&\
CCTK_INT out_yline_zi&&\
CCTK_INT out_yzplane_xi&&\
CCTK_INT out_zline_xi&&\
CCTK_INT out_zline_yi&&\
CCTK_INT parfile_update_every&&\
CCTK_INT print_timing_info&&\
CCTK_INT recover_and_remove&&\
CCTK_INT require_empty_output_directory&&\
CCTK_INT strict_io_parameter_check&&\
COMMON /IOrest/checkpoint_every_walltime_hours,out_dt,out_xline_y,out_xline_z,out_xyplane_z,out_xzplane_y,out_yline_x,out_yline_z,out_yzplane_x,out_zline_x,out_zline_y,checkpoint_ID_file,checkpoint_dir,checkpoint_file,filereader_ID_dir,filereader_ID_files,filereader_ID_vars,out_criterion,out_dir,out_fileinfo,out_mode,out_save_parameters,parfile_name,parfile_write,recover,recover_dir,recover_file,verbose,abort_on_io_errors,checkpoint_ID,checkpoint_every,checkpoint_keep,checkpoint_on_terminate,new_filename_scheme,out3D_septimefiles,out_downsample_x,out_downsample_y,out_downsample_z,out_every,out_proc_every,out_single_precision,out_timesteps_per_file,out_unchunked,out_xline_yi,out_xline_zi,out_xyplane_zi,out_xzplane_yi,out_yline_xi,out_yline_zi,out_yzplane_xi,out_zline_xi,out_zline_yi,parfile_update_every,print_timing_info,recover_and_remove,require_empty_output_directory,strict_io_parameter_check&&\
CCTK_INT truncate_files&&\
CCTK_INT truncate_files_after_recovering&&\
COMMON /IOUtilpriv/truncate_files,truncate_files_after_recovering&&\

