/*@@
   @header  jobsuicide_CParameters.h
   @author  Automatically generated by CreateParameterBindings.pl
   @desc
            Declares parameters of thorn jobsuicide
   @enddesc
 @@*/


#ifndef _JOBSUICIDE_PARAMETERS_H_
#define _JOBSUICIDE_PARAMETERS_H_ 1

#include "ParameterCGlobal.h"

#define DECLARE_CCTK_PARAMETERS \
  DECLARE_GLOBAL_PARAMETER_STRUCT_PARAMS \

#endif  /* _JOBSUICIDE_PARAMETERS_H_ */

