#define DECLARE_CCTK_PARAMETERS \
CCTK_REAL  excision_radius&&\
CCTK_REAL  run_time&&\
CCTK_INT Symmetry&&\
CCTK_INT bssn_enable&&\
CCTK_INT cowling_enable&&\
CCTK_INT excision_enable&&\
CCTK_INT fisheye_enable&&\
CCTK_INT iter_count&&\
CCTK_INT number_of_mol_ministeps&&\
CCTK_INT rot_metric&&\
CCTK_INT trA_detg_enforce&&\
COMMON /cctk_params_global/excision_radius,run_time,Symmetry,bssn_enable,cowling_enable,excision_enable,fisheye_enable,iter_count,number_of_mol_ministeps,rot_metric,trA_detg_enforce&&\
CCTK_REAL  hyper_a1&&\
CCTK_REAL  hyper_a2&&\
CCTK_REAL  hyper_a3&&\
CCTK_STRING  slicing_type&&\
CCTK_INT f_of_alpha&&\
CCTK_INT hyper_Integration_Order&&\
CCTK_INT lapse_MaxNumConstrainedVars&&\
CCTK_INT lapse_MaxNumEvolvedVars&&\
CCTK_INT opl_a0lap&&\
CCTK_INT opl_advect_enable&&\
CCTK_INT opl_alap&&\
COMMON /lapserest/hyper_a1,hyper_a2,hyper_a3,slicing_type,f_of_alpha,hyper_Integration_Order,lapse_MaxNumConstrainedVars,lapse_MaxNumEvolvedVars,opl_a0lap,opl_advect_enable,opl_alap&&\
CCTK_REAL  opl_lapse_floor&&\
COMMON /lapsepriv/opl_lapse_floor&&\
CCTK_REAL  Xcenter&&\
CCTK_REAL  Ycenter&&\
CCTK_REAL  Zcenter&&\
CCTK_REAL  CCTKH5&&\
CCTK_REAL  CCTKH6&&\
CCTK_REAL  CCTKH8&&\
CCTK_REAL  CCTKH9&&\
CCTK_REAL  CCTKH10&&\
CCTK_REAL  CCTKH11&&\
CCTK_REAL  CCTKH12&&\
CCTK_REAL  CCTKH13&&\
CCTK_REAL  CCTKH14&&\
CCTK_REAL  CCTKH15&&\
CCTK_REAL  CCTKH16&&\
CCTK_REAL  CCTKH18&&\
CCTK_REAL  CCTKH19&&\
CCTK_REAL  CCTKH20&&\
CCTK_INT CCTKH0&&\
CCTK_INT CCTKH1&&\
CCTK_INT CCTKH2&&\
CCTK_INT CCTKH3&&\
CCTK_INT CCTKH4&&\
CCTK_INT CCTKH7&&\
CCTK_INT enable_lower_order_at_boundaries&&\
CCTK_INT CCTKH17&&\
CCTK_INT CCTKH21&&\
COMMON /BSSNrest/Xcenter,Ycenter,Zcenter,CCTKH5,CCTKH6,CCTKH8,CCTKH9,CCTKH10,CCTKH11,CCTKH12,CCTKH13,CCTKH14,CCTKH15,CCTKH16,CCTKH18,CCTKH19,CCTKH20,CCTKH0,CCTKH1,CCTKH2,CCTKH3,CCTKH4,CCTKH7,enable_lower_order_at_boundaries,CCTKH17,CCTKH21&&\
CCTK_REAL  CCTKH22&&\
CCTK_REAL  CCTKH23&&\
CCTK_REAL  CCTKH24&&\
CCTK_REAL  CCTKH25&&\
CCTK_REAL  CCTKH33&&\
CCTK_REAL  CCTKH34&&\
CCTK_REAL  CCTKH35&&\
CCTK_REAL  CCTKH36&&\
CCTK_REAL  CCTKH37&&\
CCTK_REAL  CCTKH38&&\
CCTK_REAL  CCTKH39&&\
CCTK_REAL  CCTKH40&&\
CCTK_STRING  bitant_plane&&\
CCTK_STRING  domain&&\
CCTK_STRING  quadrant_direction&&\
CCTK_STRING  CCTKH26&&\
CCTK_STRING  type&&\
CCTK_INT CCTKH27&&\
CCTK_INT CCTKH28&&\
CCTK_INT CCTKH29&&\
CCTK_INT CCTKH30&&\
CCTK_INT CCTKH31&&\
CCTK_INT CCTKH32&&\
COMMON /GRIDrest/CCTKH22,CCTKH23,CCTKH24,CCTKH25,CCTKH33,CCTKH34,CCTKH35,CCTKH36,CCTKH37,CCTKH38,CCTKH39,CCTKH40,bitant_plane,domain,quadrant_direction,CCTKH26,type,CCTKH27,CCTKH28,CCTKH29,CCTKH30,CCTKH31,CCTKH32&&\
CCTK_INT CCTKH41&&\
CCTK_INT CCTKH42&&\
CCTK_INT CCTKH43&&\
CCTK_INT CCTKH44&&\
CCTK_INT CCTKH45&&\
CCTK_INT CCTKH46&&\
CCTK_INT CCTKH47&&\
CCTK_INT CCTKH48&&\
CCTK_INT CCTKH49&&\
CCTK_INT CCTKH50&&\
CCTK_INT CCTKH51&&\
CCTK_INT MoL_Num_Constrained_Vars&&\
CCTK_INT MoL_Num_Evolved_Vars&&\
CCTK_INT MoL_Num_SaveAndRestore_Vars&&\
CCTK_INT CCTKH52&&\
COMMON /METHODOFLINESrest/CCTKH41,CCTKH42,CCTKH43,CCTKH44,CCTKH45,CCTKH46,CCTKH47,CCTKH48,CCTKH49,CCTKH50,CCTKH51,MoL_Num_Constrained_Vars,MoL_Num_Evolved_Vars,MoL_Num_SaveAndRestore_Vars,CCTKH52&&\

