/*@@
   @header  linearized_wave_Prototypes.h
   @author  Automatically generated by CreateFunctionBindings.pl
   @desc
            Prototypes for overloaded functions used by this thorn
   @enddesc
  @@*/


#ifndef _LINEARIZED_WAVE_PROTOTYPES_H_
#define _LINEARIZED_WAVE_PROTOTYPES_H_  1

#ifdef CCODE
#ifdef __cplusplus
extern "C" {
#endif

#ifdef __cplusplus
}
#endif
#endif /* CCODE */

#ifdef FCODE
#ifdef F90CODE
#define DECLARE_LINEARIZED_WAVE_FUNCTIONS _DECLARE_CCTK_FUNCTIONS \

#else /* ! F90CODE */

#define DECLARE_LINEARIZED_WAVE_FUNCTIONS _DECLARE_CCTK_FUNCTIONS \

#endif /* ! F90CODE */
#endif /* FCODE */

#endif

