/*@@
   @header  linearized_wave_CParameters.h
   @author  Automatically generated by CreateParameterBindings.pl
   @desc
            Declares parameters of thorn linearized_wave
   @enddesc
 @@*/


#ifndef _LINEARIZED_WAVE_PARAMETERS_H_
#define _LINEARIZED_WAVE_PARAMETERS_H_ 1

#include "ParameterCGlobal.h"
#include "ParameterCRestrictedLINEARIZED_WAVE.h"
#include "ParameterCPrivateLINEARIZED_WAVE.h"
#include "ParameterCRestrictedDIAGNOSTICS_VACUUM.h"
#include "ParameterCRestrictedGRID.h"
#include "ParameterCRestrictedGW_EXTRACTION.h"
#include "ParameterCRestrictedIO.h"

#define DECLARE_CCTK_PARAMETERS \
  DECLARE_GLOBAL_PARAMETER_STRUCT_PARAMS \
  DECLARE_RESTRICTED_LINEARIZED_WAVE_STRUCT_PARAMS \
  DECLARE_PRIVATE_LINEARIZED_WAVE_STRUCT_PARAMS \
  CCTK_REAL const surf_radius = RESTRICTED_DIAGNOSTICS_VACUUM_STRUCT.surf_radius; \
  const char * const type = RESTRICTED_GRID_STRUCT.type; \
  const char * const domain = RESTRICTED_GRID_STRUCT.domain; \
  const char * const quadrant_direction = RESTRICTED_GRID_STRUCT.quadrant_direction; \
  const char * const bitant_plane = RESTRICTED_GRID_STRUCT.bitant_plane; \
  CCTK_REAL const radius_GW = RESTRICTED_GW_EXTRACTION_STRUCT.radius_GW; \
  CCTK_REAL const radius_GW_phys = RESTRICTED_GW_EXTRACTION_STRUCT.radius_GW_phys; \
  CCTK_REAL const theta_GW = RESTRICTED_GW_EXTRACTION_STRUCT.theta_GW; \
  CCTK_REAL const phi_GW = RESTRICTED_GW_EXTRACTION_STRUCT.phi_GW; \
  CCTK_INT const out_every = RESTRICTED_IO_STRUCT.out_every; \
  enum { \
      dummy_DIAGNOSTICS_VACUUM_surf_radius = sizeof( surf_radius ) \
    , dummy_GRID_type = sizeof( type ) \
    , dummy_GRID_domain = sizeof( domain ) \
    , dummy_GRID_quadrant_direction = sizeof( quadrant_direction ) \
    , dummy_GRID_bitant_plane = sizeof( bitant_plane ) \
    , dummy_GW_EXTRACTION_radius_GW = sizeof( radius_GW ) \
    , dummy_GW_EXTRACTION_radius_GW_phys = sizeof( radius_GW_phys ) \
    , dummy_GW_EXTRACTION_theta_GW = sizeof( theta_GW ) \
    , dummy_GW_EXTRACTION_phi_GW = sizeof( phi_GW ) \
    , dummy_IO_out_every = sizeof( out_every ) \
  };

#endif  /* _LINEARIZED_WAVE_PARAMETERS_H_ */

