#define DECLARE_CCTK_PARAMETERS \
CCTK_REAL  excision_radius&&\
CCTK_REAL  run_time&&\
CCTK_INT Symmetry&&\
CCTK_INT bssn_enable&&\
CCTK_INT cowling_enable&&\
CCTK_INT excision_enable&&\
CCTK_INT fisheye_enable&&\
CCTK_INT iter_count&&\
CCTK_INT number_of_mol_ministeps&&\
CCTK_INT rot_metric&&\
CCTK_INT trA_detg_enforce&&\
COMMON /cctk_params_global/excision_radius,run_time,Symmetry,bssn_enable,cowling_enable,excision_enable,fisheye_enable,iter_count,number_of_mol_ministeps,rot_metric,trA_detg_enforce&&\
CCTK_REAL  delayed_overhead_threshold&&\
CCTK_REAL  immediate_overhead_threshold&&\
CCTK_REAL  maximum_setup_overhead&&\
CCTK_REAL  probability_random_jump&&\
CCTK_REAL  probability_small_jump&&\
CCTK_REAL  siman_T_initial&&\
CCTK_REAL  siman_T_min&&\
CCTK_REAL  siman_k&&\
CCTK_REAL  siman_mu_T&&\
CCTK_REAL  siman_probability_change_topology&&\
CCTK_REAL  siman_step_size&&\
CCTK_INT cycle_j_tilings&&\
CCTK_INT debug&&\
CCTK_INT ignore_initial_overhead&&\
CCTK_INT lc_inpoints&&\
CCTK_INT lc_inthreads&&\
CCTK_INT lc_jnpoints&&\
CCTK_INT lc_jnthreads&&\
CCTK_INT lc_knpoints&&\
CCTK_INT lc_knthreads&&\
CCTK_INT legacy_init&&\
CCTK_INT max_jump_attempts&&\
CCTK_INT nsteps&&\
CCTK_INT nx&&\
CCTK_INT ny&&\
CCTK_INT nz&&\
CCTK_INT overhead_threshold_delay&&\
CCTK_INT printstats&&\
CCTK_INT run_demo&&\
CCTK_INT siman_iters_fixed_T&&\
CCTK_INT small_jump_distance&&\
CCTK_INT use_random_restart_hill_climbing&&\
CCTK_INT use_simulated_annealing&&\
CCTK_INT verbose&&\
COMMON /LoopControlpriv/delayed_overhead_threshold,immediate_overhead_threshold,maximum_setup_overhead,probability_random_jump,probability_small_jump,siman_T_initial,siman_T_min,siman_k,siman_mu_T,siman_probability_change_topology,siman_step_size,cycle_j_tilings,debug,ignore_initial_overhead,lc_inpoints,lc_inthreads,lc_jnpoints,lc_jnthreads,lc_knpoints,lc_knthreads,legacy_init,max_jump_attempts,nsteps,nx,ny,nz,overhead_threshold_delay,printstats,run_demo,siman_iters_fixed_T,small_jump_distance,use_random_restart_hill_climbing,use_simulated_annealing,verbose&&\

