/*@@
   @header  mag_bondi_CParameters.h
   @author  Automatically generated by CreateParameterBindings.pl
   @desc
            Declares parameters of thorn mag_bondi
   @enddesc
 @@*/


#ifndef _MAG_BONDI_PARAMETERS_H_
#define _MAG_BONDI_PARAMETERS_H_ 1

#include "ParameterCGlobal.h"
#include "ParameterCRestrictedMAG_BONDI.h"
#include "ParameterCPrivateMAG_BONDI.h"
#include "ParameterCRestrictedDIAGNOSTICS_MHD.h"
#include "ParameterCRestrictedDIAGNOSTICS_VACUUM.h"
#include "ParameterCRestrictedGRID.h"
#include "ParameterCRestrictedIO.h"
#include "ParameterCRestrictedMHD_EVOLVE.h"

#define DECLARE_CCTK_PARAMETERS \
  DECLARE_GLOBAL_PARAMETER_STRUCT_PARAMS \
  DECLARE_RESTRICTED_MAG_BONDI_STRUCT_PARAMS \
  DECLARE_PRIVATE_MAG_BONDI_STRUCT_PARAMS \
  CCTK_REAL const initial_monopole_value = RESTRICTED_DIAGNOSTICS_MHD_STRUCT.initial_monopole_value; \
  CCTK_REAL const surf_radius = RESTRICTED_DIAGNOSTICS_VACUUM_STRUCT.surf_radius; \
  CCTK_INT const out_every = RESTRICTED_IO_STRUCT.out_every; \
  CCTK_INT const Reconstruction = RESTRICTED_MHD_EVOLVE_STRUCT.Reconstruction; \
  CCTK_INT const Matter_BC = RESTRICTED_MHD_EVOLVE_STRUCT.Matter_BC; \
  CCTK_INT const neos = RESTRICTED_MHD_EVOLVE_STRUCT.neos; \
  CCTK_REAL const gamma_th = RESTRICTED_MHD_EVOLVE_STRUCT.gamma_th; \
  CCTK_REAL const Sym_Bz = RESTRICTED_MHD_EVOLVE_STRUCT.Sym_Bz; \
  CCTK_REAL const K_poly = RESTRICTED_MHD_EVOLVE_STRUCT.K_poly; \
  CCTK_INT const constrained_transport_scheme = RESTRICTED_MHD_EVOLVE_STRUCT.constrained_transport_scheme; \
  CCTK_REAL const P_max = RESTRICTED_MHD_EVOLVE_STRUCT.P_max; \
  CCTK_REAL const P_fact = RESTRICTED_MHD_EVOLVE_STRUCT.P_fact; \
  CCTK_REAL const pfloor = RESTRICTED_MHD_EVOLVE_STRUCT.pfloor; \
  CCTK_REAL const rho_b_max = RESTRICTED_MHD_EVOLVE_STRUCT.rho_b_max; \
  CCTK_REAL const rho_fact = RESTRICTED_MHD_EVOLVE_STRUCT.rho_fact; \
  CCTK_REAL const rho_b_atm = RESTRICTED_MHD_EVOLVE_STRUCT.rho_b_atm; \
  CCTK_REAL const tau_fact = RESTRICTED_MHD_EVOLVE_STRUCT.tau_fact; \
  CCTK_REAL const tau_atm = RESTRICTED_MHD_EVOLVE_STRUCT.tau_atm; \
  CCTK_INT const tau_stildefix_enable = RESTRICTED_MHD_EVOLVE_STRUCT.tau_stildefix_enable; \
  CCTK_INT const enable_shocktest_primitive_mode = RESTRICTED_MHD_EVOLVE_STRUCT.enable_shocktest_primitive_mode; \
  CCTK_INT const enable_primitives_disk = RESTRICTED_MHD_EVOLVE_STRUCT.enable_primitives_disk; \
  CCTK_INT const primitives_solver = RESTRICTED_MHD_EVOLVE_STRUCT.primitives_solver; \
  CCTK_REAL const sdots_o_rhot = RESTRICTED_MHD_EVOLVE_STRUCT.sdots_o_rhot; \
  CCTK_INT const use_HARM_primitives = RESTRICTED_MHD_EVOLVE_STRUCT.use_HARM_primitives; \
  CCTK_INT const enable_HARM_energyvariable = RESTRICTED_MHD_EVOLVE_STRUCT.enable_HARM_energyvariable; \
  CCTK_INT const force_font_fix_fail = RESTRICTED_MHD_EVOLVE_STRUCT.force_font_fix_fail; \
  enum { \
      dummy_DIAGNOSTICS_MHD_initial_monopole_value = sizeof( initial_monopole_value ) \
    , dummy_DIAGNOSTICS_VACUUM_surf_radius = sizeof( surf_radius ) \
    , dummy_IO_out_every = sizeof( out_every ) \
    , dummy_MHD_EVOLVE_Reconstruction = sizeof( Reconstruction ) \
    , dummy_MHD_EVOLVE_Matter_BC = sizeof( Matter_BC ) \
    , dummy_MHD_EVOLVE_neos = sizeof( neos ) \
    , dummy_MHD_EVOLVE_gamma_th = sizeof( gamma_th ) \
    , dummy_MHD_EVOLVE_Sym_Bz = sizeof( Sym_Bz ) \
    , dummy_MHD_EVOLVE_K_poly = sizeof( K_poly ) \
    , dummy_MHD_EVOLVE_constrained_transport_scheme = sizeof( constrained_transport_scheme ) \
    , dummy_MHD_EVOLVE_P_max = sizeof( P_max ) \
    , dummy_MHD_EVOLVE_P_fact = sizeof( P_fact ) \
    , dummy_MHD_EVOLVE_pfloor = sizeof( pfloor ) \
    , dummy_MHD_EVOLVE_rho_b_max = sizeof( rho_b_max ) \
    , dummy_MHD_EVOLVE_rho_fact = sizeof( rho_fact ) \
    , dummy_MHD_EVOLVE_rho_b_atm = sizeof( rho_b_atm ) \
    , dummy_MHD_EVOLVE_tau_fact = sizeof( tau_fact ) \
    , dummy_MHD_EVOLVE_tau_atm = sizeof( tau_atm ) \
    , dummy_MHD_EVOLVE_tau_stildefix_enable = sizeof( tau_stildefix_enable ) \
    , dummy_MHD_EVOLVE_enable_shocktest_primitive_mode = sizeof( enable_shocktest_primitive_mode ) \
    , dummy_MHD_EVOLVE_enable_primitives_disk = sizeof( enable_primitives_disk ) \
    , dummy_MHD_EVOLVE_primitives_solver = sizeof( primitives_solver ) \
    , dummy_MHD_EVOLVE_sdots_o_rhot = sizeof( sdots_o_rhot ) \
    , dummy_MHD_EVOLVE_use_HARM_primitives = sizeof( use_HARM_primitives ) \
    , dummy_MHD_EVOLVE_enable_HARM_energyvariable = sizeof( enable_HARM_energyvariable ) \
    , dummy_MHD_EVOLVE_force_font_fix_fail = sizeof( force_font_fix_fail ) \
  };

#endif  /* _MAG_BONDI_PARAMETERS_H_ */

