#define DECLARE_CCTK_PARAMETERS \
CCTK_REAL  excision_radius&&\
CCTK_REAL  run_time&&\
CCTK_INT Symmetry&&\
CCTK_INT bssn_enable&&\
CCTK_INT cowling_enable&&\
CCTK_INT excision_enable&&\
CCTK_INT fisheye_enable&&\
CCTK_INT iter_count&&\
CCTK_INT number_of_mol_ministeps&&\
CCTK_INT rot_metric&&\
CCTK_INT trA_detg_enforce&&\
COMMON /cctk_params_global/excision_radius,run_time,Symmetry,bssn_enable,cowling_enable,excision_enable,fisheye_enable,iter_count,number_of_mol_ministeps,rot_metric,trA_detg_enforce&&\
CCTK_REAL  Erad_atm_cut&&\
CCTK_REAL  Erad_cut&&\
CCTK_REAL  K_poly&&\
CCTK_REAL  M_B&&\
CCTK_REAL  OS_T_Rmax&&\
CCTK_REAL  P_fact&&\
CCTK_REAL  P_max&&\
CCTK_REAL  Psi6threshold&&\
CCTK_REAL  Sym_Bz&&\
CCTK_REAL  T_fluid_cgs_atm&&\
CCTK_REAL  c_h_default&&\
CCTK_REAL  c_p_default&&\
CCTK_REAL  dxvec&&\
CCTK_REAL  eps_thermal_bhns&&\
CCTK_REAL  ergo_sigma&&\
CCTK_REAL  gamma_OS&&\
CCTK_REAL  gamma_th&&\
CCTK_REAL  lambda_line&&\
CCTK_REAL  mhd_bigp&&\
CCTK_REAL  mhd_mbh&&\
CCTK_REAL  mhd_mdot&&\
CCTK_REAL  mhd_r_crit&&\
CCTK_REAL  min_BH_radius&&\
CCTK_REAL  pfloor&&\
CCTK_REAL  r_ex_line&&\
CCTK_REAL  rad_T_cutoff&&\
CCTK_REAL  rad_T_fac&&\
CCTK_REAL  rad_T_floor&&\
CCTK_REAL  rad_T_pow&&\
CCTK_REAL  rad_emissivity_abs&&\
CCTK_REAL  rad_emissivity_sct&&\
CCTK_REAL  rad_opacity_abs&&\
CCTK_REAL  rad_opacity_sct&&\
CCTK_REAL  rho_b_atm&&\
CCTK_REAL  rho_b_max&&\
CCTK_REAL  rho_fact&&\
CCTK_REAL  rhos_max&&\
CCTK_REAL  sdots_o_rhot&&\
CCTK_REAL  t_cool&&\
CCTK_REAL  tau_atm&&\
CCTK_REAL  tau_fact&&\
CCTK_INT A_BC_rad_mag_bondi_enable&&\
CCTK_INT EM_BC&&\
CCTK_INT MHD_MaxNumConstrainedVars&&\
CCTK_INT MHD_MaxNumEvolvedVars&&\
CCTK_INT Matter_BC&&\
CCTK_INT Reconstruction&&\
CCTK_INT adm_ppm_b&&\
CCTK_INT allow_negative_eps_th&&\
CCTK_INT artificial_cooling_enable&&\
CCTK_INT compute_microphysics&&\
CCTK_INT constrained_transport_scheme&&\
CCTK_INT cooling_in_St_eq&&\
CCTK_INT em_evolve_enable&&\
CCTK_INT em_gauge&&\
CCTK_INT enable_HARM_energyvariable&&\
CCTK_INT enable_OS_collapse&&\
CCTK_INT enable_disk_em_flux_induction&&\
CCTK_INT enable_primitives_disk&&\
CCTK_INT enable_shocktest_primitive_mode&&\
CCTK_INT enable_trace_field_line&&\
CCTK_INT eps_flag&&\
CCTK_INT ergo_star&&\
CCTK_INT force_font_fix_fail&&\
CCTK_INT horizon_enforce_rho_profile&&\
CCTK_INT hyperbolic_divergence_cleaning_centered_differencing&&\
CCTK_INT hyperbolic_divergence_cleaning_enable&&\
CCTK_INT m&&\
CCTK_INT microphysics_scheme&&\
CCTK_INT neos&&\
CCTK_INT nrhovec&&\
CCTK_INT primitives_debug&&\
CCTK_INT primitives_solver&&\
CCTK_INT rad_closure_scheme&&\
CCTK_INT rad_evolve_enable&&\
CCTK_INT rad_fix&&\
CCTK_INT rad_fourforce_enable&&\
CCTK_INT reconstruct_Bitildes_instead_of_Bis&&\
CCTK_INT reconstruct_Pthermal_instead_of_P&&\
CCTK_INT tau_stildefix_enable&&\
CCTK_INT use_HARM_primitives&&\
CCTK_INT use_central_scheme_instead_of_hll&&\
CCTK_INT use_new_code&&\
COMMON /mhd_evolverest/Erad_atm_cut,Erad_cut,K_poly,M_B,OS_T_Rmax,P_fact,P_max,Psi6threshold,Sym_Bz,T_fluid_cgs_atm,c_h_default,c_p_default,dxvec,eps_thermal_bhns,ergo_sigma,gamma_OS,gamma_th,lambda_line,mhd_bigp,mhd_mbh,mhd_mdot,mhd_r_crit,min_BH_radius,pfloor,r_ex_line,rad_T_cutoff,rad_T_fac,rad_T_floor,rad_T_pow,rad_emissivity_abs,rad_emissivity_sct,rad_opacity_abs,rad_opacity_sct,rho_b_atm,rho_b_max,rho_fact,rhos_max,sdots_o_rhot,t_cool,tau_atm,tau_fact,A_BC_rad_mag_bondi_enable,EM_BC,MHD_MaxNumConstrainedVars,MHD_MaxNumEvolvedVars,Matter_BC,Reconstruction,adm_ppm_b,allow_negative_eps_th,artificial_cooling_enable,compute_microphysics,constrained_transport_scheme,cooling_in_St_eq,em_evolve_enable,em_gauge,enable_HARM_energyvariable,enable_OS_collapse,enable_disk_em_flux_induction,enable_primitives_disk,enable_shocktest_primitive_mode,enable_trace_field_line,eps_flag,ergo_star,force_font_fix_fail,horizon_enforce_rho_profile,hyperbolic_divergence_cleaning_centered_differencing,hyperbolic_divergence_cleaning_enable,m,microphysics_scheme,neos,nrhovec,primitives_debug,primitives_solver,rad_closure_scheme,rad_evolve_enable,rad_fix,rad_fourforce_enable,reconstruct_Bitildes_instead_of_Bis,reconstruct_Pthermal_instead_of_P,tau_stildefix_enable,use_HARM_primitives,use_central_scheme_instead_of_hll,use_new_code&&\
CCTK_REAL  KO_hydro_inside_BH&&\
CCTK_REAL  KO_inside_BH&&\
CCTK_REAL  KO_refbd&&\
CCTK_REAL  damp_lorenz&&\
CCTK_INT number_of_points_apply_KO_outside_refboundaries&&\
CCTK_INT really_want_gamma_th_of_1_point_3&&\
CCTK_INT use_disk_bcs&&\
CCTK_INT use_std_PPM_instead_of_efficient_3_gz_version&&\
COMMON /mhd_evolvepriv/KO_hydro_inside_BH,KO_inside_BH,KO_refbd,damp_lorenz,number_of_points_apply_KO_outside_refboundaries,really_want_gamma_th_of_1_point_3,use_disk_bcs,use_std_PPM_instead_of_efficient_3_gz_version&&\
CCTK_INT CCTKH0&&\
CCTK_INT iteration_to_insert_rad&&\
CCTK_INT CCTKH1&&\
COMMON /BHNSrest/CCTKH0,iteration_to_insert_rad,CCTKH1&&\
CCTK_REAL  CCTKH7&&\
CCTK_REAL  CCTKH8&&\
CCTK_REAL  CCTKH9&&\
CCTK_REAL  CCTKH10&&\
CCTK_REAL  CCTKH11&&\
CCTK_REAL  CCTKH14&&\
CCTK_REAL  CCTKH15&&\
CCTK_REAL  CCTKH16&&\
CCTK_REAL  CCTKH17&&\
CCTK_REAL  CCTKH18&&\
CCTK_REAL  CCTKH19&&\
CCTK_REAL  CCTKH20&&\
CCTK_REAL  CCTKH21&&\
CCTK_REAL  CCTKH22&&\
CCTK_REAL  CCTKH24&&\
CCTK_REAL  CCTKH25&&\
CCTK_REAL  CCTKH26&&\
CCTK_INT CCTKH2&&\
CCTK_INT CCTKH3&&\
CCTK_INT CCTKH4&&\
CCTK_INT CCTKH5&&\
CCTK_INT CCTKH6&&\
CCTK_INT CCTKH12&&\
CCTK_INT CCTKH13&&\
CCTK_INT CCTKH23&&\
CCTK_INT zero_out_matter_source_terms&&\
COMMON /BSSNrest/CCTKH7,CCTKH8,CCTKH9,CCTKH10,CCTKH11,CCTKH14,CCTKH15,CCTKH16,CCTKH17,CCTKH18,CCTKH19,CCTKH20,CCTKH21,CCTKH22,CCTKH24,CCTKH25,CCTKH26,CCTKH2,CCTKH3,CCTKH4,CCTKH5,CCTKH6,CCTKH12,CCTKH13,CCTKH23,zero_out_matter_source_terms&&\
CCTK_REAL  CCTKH27&&\
CCTK_REAL  CCTKH33&&\
CCTK_REAL  CCTKH34&&\
CCTK_REAL  CCTKH35&&\
CCTK_REAL  CCTKH36&&\
CCTK_REAL  CCTKH40&&\
CCTK_REAL  CCTKH45&&\
CCTK_REAL  CCTKH46&&\
CCTK_REAL  CCTKH48&&\
CCTK_INT CCTKH28&&\
CCTK_INT CCTKH29&&\
CCTK_INT CCTKH30&&\
CCTK_INT CCTKH31&&\
CCTK_INT CCTKH32&&\
CCTK_INT CCTKH37&&\
CCTK_INT CCTKH38&&\
CCTK_INT CCTKH39&&\
CCTK_INT CCTKH41&&\
CCTK_INT CCTKH42&&\
CCTK_INT num_BHs&&\
CCTK_INT CCTKH43&&\
CCTK_INT CCTKH44&&\
CCTK_INT CCTKH47&&\
CCTK_INT CCTKH49&&\
COMMON /DIAGNOSTICS_VACUUMrest/CCTKH27,CCTKH33,CCTKH34,CCTKH35,CCTKH36,CCTKH40,CCTKH45,CCTKH46,CCTKH48,CCTKH28,CCTKH29,CCTKH30,CCTKH31,CCTKH32,CCTKH37,CCTKH38,CCTKH39,CCTKH41,CCTKH42,num_BHs,CCTKH43,CCTKH44,CCTKH47,CCTKH49&&\
CCTK_REAL  CCTKH50&&\
CCTK_REAL  CCTKH51&&\
CCTK_REAL  CCTKH52&&\
CCTK_REAL  CCTKH53&&\
CCTK_REAL  CCTKH63&&\
CCTK_REAL  CCTKH64&&\
CCTK_REAL  CCTKH65&&\
CCTK_REAL  CCTKH66&&\
CCTK_REAL  CCTKH67&&\
CCTK_REAL  CCTKH68&&\
CCTK_REAL  CCTKH69&&\
CCTK_REAL  CCTKH70&&\
CCTK_STRING  bitant_plane&&\
CCTK_STRING  domain&&\
CCTK_STRING  CCTKH54&&\
CCTK_STRING  CCTKH55&&\
CCTK_STRING  CCTKH62&&\
CCTK_INT CCTKH56&&\
CCTK_INT CCTKH57&&\
CCTK_INT CCTKH58&&\
CCTK_INT CCTKH59&&\
CCTK_INT CCTKH60&&\
CCTK_INT CCTKH61&&\
COMMON /GRIDrest/CCTKH50,CCTKH51,CCTKH52,CCTKH53,CCTKH63,CCTKH64,CCTKH65,CCTKH66,CCTKH67,CCTKH68,CCTKH69,CCTKH70,bitant_plane,domain,CCTKH54,CCTKH55,CCTKH62,CCTKH56,CCTKH57,CCTKH58,CCTKH59,CCTKH60,CCTKH61&&\
CCTK_REAL  CCTKH73&&\
CCTK_REAL  CCTKH74&&\
CCTK_REAL  CCTKH75&&\
CCTK_STRING  slicing_type&&\
CCTK_INT CCTKH71&&\
CCTK_INT CCTKH72&&\
CCTK_INT CCTKH76&&\
CCTK_INT CCTKH77&&\
CCTK_INT CCTKH78&&\
CCTK_INT CCTKH79&&\
CCTK_INT CCTKH80&&\
COMMON /LAPSErest/CCTKH73,CCTKH74,CCTKH75,slicing_type,CCTKH71,CCTKH72,CCTKH76,CCTKH77,CCTKH78,CCTKH79,CCTKH80&&\
CCTK_INT CCTKH81&&\
CCTK_INT CCTKH82&&\
CCTK_INT CCTKH83&&\
CCTK_INT CCTKH84&&\
CCTK_INT CCTKH85&&\
CCTK_INT CCTKH86&&\
CCTK_INT CCTKH87&&\
CCTK_INT CCTKH88&&\
CCTK_INT CCTKH89&&\
CCTK_INT CCTKH90&&\
CCTK_INT CCTKH91&&\
CCTK_INT MoL_Num_Constrained_Vars&&\
CCTK_INT MoL_Num_Evolved_Vars&&\
CCTK_INT MoL_Num_SaveAndRestore_Vars&&\
CCTK_INT CCTKH92&&\
COMMON /METHODOFLINESrest/CCTKH81,CCTKH82,CCTKH83,CCTKH84,CCTKH85,CCTKH86,CCTKH87,CCTKH88,CCTKH89,CCTKH90,CCTKH91,MoL_Num_Constrained_Vars,MoL_Num_Evolved_Vars,MoL_Num_SaveAndRestore_Vars,CCTKH92&&\
CCTK_INT Spatial_Gauge&&\
CCTK_INT CCTKH93&&\
CCTK_INT CCTKH94&&\
COMMON /SHIFTrest/Spatial_Gauge,CCTKH93,CCTKH94&&\

