#define DECLARE_CCTK_PARAMETERS \
CCTK_REAL  excision_radius&&\
CCTK_REAL  run_time&&\
CCTK_INT Symmetry&&\
CCTK_INT bssn_enable&&\
CCTK_INT cowling_enable&&\
CCTK_INT excision_enable&&\
CCTK_INT fisheye_enable&&\
CCTK_INT iter_count&&\
CCTK_INT number_of_mol_ministeps&&\
CCTK_INT rot_metric&&\
CCTK_INT trA_detg_enforce&&\
COMMON /cctk_params_global/excision_radius,run_time,Symmetry,bssn_enable,cowling_enable,excision_enable,fisheye_enable,iter_count,number_of_mol_ministeps,rot_metric,trA_detg_enforce&&\
CCTK_INT MoL_Max_Evolved_Array_Size&&\
CCTK_INT MoL_Max_Evolved_ComplexArray_Size&&\
CCTK_INT MoL_Num_ArrayConstrained_Vars&&\
CCTK_INT MoL_Num_ArrayEvolved_Vars&&\
CCTK_INT MoL_Num_ArraySaveAndRestore_Vars&&\
CCTK_INT MoL_Num_ComplexArrayConstrained_Vars&&\
CCTK_INT MoL_Num_ComplexArrayEvolved_Vars&&\
CCTK_INT MoL_Num_ComplexArraySaveAndRestore_Vars&&\
CCTK_INT MoL_Num_ComplexConstrained_Vars&&\
CCTK_INT MoL_Num_ComplexEvolved_Vars&&\
CCTK_INT MoL_Num_ComplexSaveAndRestore_Vars&&\
CCTK_INT MoL_Num_Constrained_Vars&&\
CCTK_INT MoL_Num_Evolved_Vars&&\
CCTK_INT MoL_Num_SaveAndRestore_Vars&&\
CCTK_INT MoL_Num_Scratch_Levels&&\
COMMON /MethodOfLinesrest/MoL_Max_Evolved_Array_Size,MoL_Max_Evolved_ComplexArray_Size,MoL_Num_ArrayConstrained_Vars,MoL_Num_ArrayEvolved_Vars,MoL_Num_ArraySaveAndRestore_Vars,MoL_Num_ComplexArrayConstrained_Vars,MoL_Num_ComplexArrayEvolved_Vars,MoL_Num_ComplexArraySaveAndRestore_Vars,MoL_Num_ComplexConstrained_Vars,MoL_Num_ComplexEvolved_Vars,MoL_Num_ComplexSaveAndRestore_Vars,MoL_Num_Constrained_Vars,MoL_Num_Evolved_Vars,MoL_Num_SaveAndRestore_Vars,MoL_Num_Scratch_Levels&&\
CCTK_REAL  ICN_avg_theta&&\
CCTK_REAL  MoL_Tiny&&\
CCTK_REAL  RHS_error_weight&&\
CCTK_REAL  maximum_absolute_error&&\
CCTK_REAL  maximum_decrease&&\
CCTK_REAL  maximum_increase&&\
CCTK_REAL  maximum_relative_error&&\
CCTK_REAL  safety_factor&&\
CCTK_STRING  Generic_Method_Descriptor&&\
CCTK_STRING  Generic_Type&&\
CCTK_STRING  ODE_Method&&\
CCTK_STRING  verbose&&\
CCTK_INT ICN_avg_swapped&&\
CCTK_INT MoL_Intermediate_Steps&&\
CCTK_INT MoL_Memory_Always_On&&\
CCTK_INT MoL_NaN_Check&&\
CCTK_INT adaptive_stepsize&&\
CCTK_INT copy_ID_after_MoL_PostStep&&\
CCTK_INT disable_prolongation&&\
CCTK_INT initial_data_is_crap&&\
COMMON /MoLpriv/ICN_avg_theta,MoL_Tiny,RHS_error_weight,maximum_absolute_error,maximum_decrease,maximum_increase,maximum_relative_error,safety_factor,Generic_Method_Descriptor,Generic_Type,ODE_Method,verbose,ICN_avg_swapped,MoL_Intermediate_Steps,MoL_Memory_Always_On,MoL_NaN_Check,adaptive_stepsize,copy_ID_after_MoL_PostStep,disable_prolongation,initial_data_is_crap&&\

