/*@@
   @header  movingbox_CParameters.h
   @author  Automatically generated by CreateParameterBindings.pl
   @desc
            Declares parameters of thorn movingbox
   @enddesc
 @@*/


#ifndef _MOVINGBOX_PARAMETERS_H_
#define _MOVINGBOX_PARAMETERS_H_ 1

#include "ParameterCGlobal.h"
#include "ParameterCRestrictedMOVINGBOX.h"
#include "ParameterCPrivateMOVINGBOX.h"
#include "ParameterCRestrictedDIAGNOSTICS_VACUUM.h"
#include "ParameterCRestrictedDRIVER.h"
#include "ParameterCRestrictedIO.h"

#define DECLARE_CCTK_PARAMETERS \
  DECLARE_GLOBAL_PARAMETER_STRUCT_PARAMS \
  DECLARE_RESTRICTED_MOVINGBOX_STRUCT_PARAMS \
  DECLARE_PRIVATE_MOVINGBOX_STRUCT_PARAMS \
  CCTK_INT const num_BHs = RESTRICTED_DIAGNOSTICS_VACUUM_STRUCT.num_BHs; \
  CCTK_INT const Compute_VolIntegrands_Every = RESTRICTED_DIAGNOSTICS_VACUUM_STRUCT.Compute_VolIntegrands_Every; \
  CCTK_INT const WhichIntegral = RESTRICTED_DIAGNOSTICS_VACUUM_STRUCT.WhichIntegral; \
  CCTK_INT const out_every = RESTRICTED_IO_STRUCT.out_every; \
  enum { \
      dummy_DIAGNOSTICS_VACUUM_num_BHs = sizeof( num_BHs ) \
    , dummy_DIAGNOSTICS_VACUUM_Compute_VolIntegrands_Every = sizeof( Compute_VolIntegrands_Every ) \
    , dummy_DIAGNOSTICS_VACUUM_WhichIntegral = sizeof( WhichIntegral ) \
    , dummy_IO_out_every = sizeof( out_every ) \
  };

#endif  /* _MOVINGBOX_PARAMETERS_H_ */

