/*@@
   @header  nonlinear_alfven_wave_CParameters.h
   @author  Automatically generated by CreateParameterBindings.pl
   @desc
            Declares parameters of thorn nonlinear_alfven_wave
   @enddesc
 @@*/


#ifndef _NONLINEAR_ALFVEN_WAVE_PARAMETERS_H_
#define _NONLINEAR_ALFVEN_WAVE_PARAMETERS_H_ 1

#include "ParameterCGlobal.h"
#include "ParameterCPrivateNONLINEAR_ALFVEN_WAVE.h"
#include "ParameterCRestrictedCACTUS.h"
#include "ParameterCRestrictedGRID.h"
#include "ParameterCRestrictedIO.h"
#include "ParameterCRestrictedMHD_EVOLVE.h"

#define DECLARE_CCTK_PARAMETERS \
  DECLARE_GLOBAL_PARAMETER_STRUCT_PARAMS \
  DECLARE_PRIVATE_NONLINEAR_ALFVEN_WAVE_STRUCT_PARAMS \
  CCTK_INT const cctk_itlast = RESTRICTED_CACTUS_STRUCT.cctk_itlast; \
  CCTK_INT const out_every = RESTRICTED_IO_STRUCT.out_every; \
  CCTK_INT const tau_stildefix_enable = RESTRICTED_MHD_EVOLVE_STRUCT.tau_stildefix_enable; \
  CCTK_INT const constrained_transport_scheme = RESTRICTED_MHD_EVOLVE_STRUCT.constrained_transport_scheme; \
  CCTK_INT const force_font_fix_fail = RESTRICTED_MHD_EVOLVE_STRUCT.force_font_fix_fail; \
  CCTK_INT const enable_primitives_disk = RESTRICTED_MHD_EVOLVE_STRUCT.enable_primitives_disk; \
  CCTK_INT const primitives_solver = RESTRICTED_MHD_EVOLVE_STRUCT.primitives_solver; \
  CCTK_INT const enable_shocktest_primitive_mode = RESTRICTED_MHD_EVOLVE_STRUCT.enable_shocktest_primitive_mode; \
  CCTK_INT const enable_HARM_energyvariable = RESTRICTED_MHD_EVOLVE_STRUCT.enable_HARM_energyvariable; \
  CCTK_REAL const rho_b_atm = RESTRICTED_MHD_EVOLVE_STRUCT.rho_b_atm; \
  CCTK_REAL const rho_fact = RESTRICTED_MHD_EVOLVE_STRUCT.rho_fact; \
  CCTK_REAL const tau_atm = RESTRICTED_MHD_EVOLVE_STRUCT.tau_atm; \
  CCTK_REAL const tau_fact = RESTRICTED_MHD_EVOLVE_STRUCT.tau_fact; \
  CCTK_REAL const pfloor = RESTRICTED_MHD_EVOLVE_STRUCT.pfloor; \
  CCTK_REAL const P_fact = RESTRICTED_MHD_EVOLVE_STRUCT.P_fact; \
  CCTK_INT const neos = RESTRICTED_MHD_EVOLVE_STRUCT.neos; \
  CCTK_REAL const gamma_th = RESTRICTED_MHD_EVOLVE_STRUCT.gamma_th; \
  CCTK_INT const eps_flag = RESTRICTED_MHD_EVOLVE_STRUCT.eps_flag; \
  CCTK_REAL const Sym_Bz = RESTRICTED_MHD_EVOLVE_STRUCT.Sym_Bz; \
  CCTK_REAL const K_poly = RESTRICTED_MHD_EVOLVE_STRUCT.K_poly; \
  enum { \
      dummy_CACTUS_cctk_itlast = sizeof( cctk_itlast ) \
    , dummy_IO_out_every = sizeof( out_every ) \
    , dummy_MHD_EVOLVE_tau_stildefix_enable = sizeof( tau_stildefix_enable ) \
    , dummy_MHD_EVOLVE_constrained_transport_scheme = sizeof( constrained_transport_scheme ) \
    , dummy_MHD_EVOLVE_force_font_fix_fail = sizeof( force_font_fix_fail ) \
    , dummy_MHD_EVOLVE_enable_primitives_disk = sizeof( enable_primitives_disk ) \
    , dummy_MHD_EVOLVE_primitives_solver = sizeof( primitives_solver ) \
    , dummy_MHD_EVOLVE_enable_shocktest_primitive_mode = sizeof( enable_shocktest_primitive_mode ) \
    , dummy_MHD_EVOLVE_enable_HARM_energyvariable = sizeof( enable_HARM_energyvariable ) \
    , dummy_MHD_EVOLVE_rho_b_atm = sizeof( rho_b_atm ) \
    , dummy_MHD_EVOLVE_rho_fact = sizeof( rho_fact ) \
    , dummy_MHD_EVOLVE_tau_atm = sizeof( tau_atm ) \
    , dummy_MHD_EVOLVE_tau_fact = sizeof( tau_fact ) \
    , dummy_MHD_EVOLVE_pfloor = sizeof( pfloor ) \
    , dummy_MHD_EVOLVE_P_fact = sizeof( P_fact ) \
    , dummy_MHD_EVOLVE_neos = sizeof( neos ) \
    , dummy_MHD_EVOLVE_gamma_th = sizeof( gamma_th ) \
    , dummy_MHD_EVOLVE_eps_flag = sizeof( eps_flag ) \
    , dummy_MHD_EVOLVE_Sym_Bz = sizeof( Sym_Bz ) \
    , dummy_MHD_EVOLVE_K_poly = sizeof( K_poly ) \
  };

#endif  /* _NONLINEAR_ALFVEN_WAVE_PARAMETERS_H_ */

