#define DECLARE_CCTK_PARAMETERS \
CCTK_REAL  excision_radius&&\
CCTK_REAL  run_time&&\
CCTK_INT Symmetry&&\
CCTK_INT bssn_enable&&\
CCTK_INT cowling_enable&&\
CCTK_INT excision_enable&&\
CCTK_INT fisheye_enable&&\
CCTK_INT iter_count&&\
CCTK_INT number_of_mol_ministeps&&\
CCTK_INT rot_metric&&\
CCTK_INT trA_detg_enforce&&\
COMMON /cctk_params_global/excision_radius,run_time,Symmetry,bssn_enable,cowling_enable,excision_enable,fisheye_enable,iter_count,number_of_mol_ministeps,rot_metric,trA_detg_enforce&&\
CCTK_INT WaveMoL_MaxNumConstrainedVars&&\
CCTK_INT WaveMoL_MaxNumEvolvedVars&&\
COMMON /scalarwaveMoLrest/WaveMoL_MaxNumConstrainedVars,WaveMoL_MaxNumEvolvedVars&&\
CCTK_REAL  amplitude&&\
CCTK_REAL  width&&\
CCTK_STRING  bound&&\
CCTK_INT enable_moving_grid&&\
CCTK_INT scalarwave_Symmetry&&\
COMMON /scalarwaveMoLpriv/amplitude,width,bound,enable_moving_grid,scalarwave_Symmetry&&\
CCTK_REAL  CCTKH0&&\
CCTK_REAL  CCTKH1&&\
CCTK_REAL  CCTKH2&&\
CCTK_REAL  CCTKH3&&\
CCTK_REAL  CCTKH11&&\
CCTK_REAL  CCTKH12&&\
CCTK_REAL  CCTKH13&&\
CCTK_REAL  CCTKH14&&\
CCTK_REAL  CCTKH15&&\
CCTK_REAL  CCTKH16&&\
CCTK_REAL  CCTKH17&&\
CCTK_REAL  CCTKH18&&\
CCTK_STRING  bitant_plane&&\
CCTK_STRING  domain&&\
CCTK_STRING  quadrant_direction&&\
CCTK_STRING  CCTKH4&&\
CCTK_STRING  type&&\
CCTK_INT CCTKH5&&\
CCTK_INT CCTKH6&&\
CCTK_INT CCTKH7&&\
CCTK_INT CCTKH8&&\
CCTK_INT CCTKH9&&\
CCTK_INT CCTKH10&&\
COMMON /GRIDrest/CCTKH0,CCTKH1,CCTKH2,CCTKH3,CCTKH11,CCTKH12,CCTKH13,CCTKH14,CCTKH15,CCTKH16,CCTKH17,CCTKH18,bitant_plane,domain,quadrant_direction,CCTKH4,type,CCTKH5,CCTKH6,CCTKH7,CCTKH8,CCTKH9,CCTKH10&&\
CCTK_INT CCTKH19&&\
CCTK_INT CCTKH20&&\
CCTK_INT CCTKH21&&\
CCTK_INT CCTKH22&&\
CCTK_INT CCTKH23&&\
CCTK_INT CCTKH24&&\
CCTK_INT CCTKH25&&\
CCTK_INT CCTKH26&&\
CCTK_INT CCTKH27&&\
CCTK_INT CCTKH28&&\
CCTK_INT CCTKH29&&\
CCTK_INT MoL_Num_Constrained_Vars&&\
CCTK_INT MoL_Num_Evolved_Vars&&\
CCTK_INT MoL_Num_SaveAndRestore_Vars&&\
CCTK_INT CCTKH30&&\
COMMON /METHODOFLINESrest/CCTKH19,CCTKH20,CCTKH21,CCTKH22,CCTKH23,CCTKH24,CCTKH25,CCTKH26,CCTKH27,CCTKH28,CCTKH29,MoL_Num_Constrained_Vars,MoL_Num_Evolved_Vars,MoL_Num_SaveAndRestore_Vars,CCTKH30&&\

