#define DECLARE_CCTK_PARAMETERS \
CCTK_REAL  excision_radius&&\
CCTK_REAL  run_time&&\
CCTK_INT Symmetry&&\
CCTK_INT bssn_enable&&\
CCTK_INT cowling_enable&&\
CCTK_INT excision_enable&&\
CCTK_INT fisheye_enable&&\
CCTK_INT iter_count&&\
CCTK_INT number_of_mol_ministeps&&\
CCTK_INT rot_metric&&\
CCTK_INT trA_detg_enforce&&\
COMMON /cctk_params_global/excision_radius,run_time,Symmetry,bssn_enable,cowling_enable,excision_enable,fisheye_enable,iter_count,number_of_mol_ministeps,rot_metric,trA_detg_enforce&&\
CCTK_INT Spatial_Gauge&&\
CCTK_INT shift_MaxNumConstrainedVars&&\
CCTK_INT shift_MaxNumEvolvedVars&&\
COMMON /shiftrest/Spatial_Gauge,shift_MaxNumConstrainedVars,shift_MaxNumEvolvedVars&&\
CCTK_REAL  eta&&\
CCTK_REAL  eta_falloff_dr&&\
CCTK_REAL  eta_falloff_radius&&\
CCTK_REAL  eta_final_value&&\
CCTK_REAL  hyper_Rscale&&\
CCTK_REAL  hyper_b1&&\
CCTK_REAL  hyper_b2&&\
CCTK_REAL  hyper_b3&&\
CCTK_REAL  hyper_phi_init&&\
CCTK_REAL  hyper_psi6_init&&\
CCTK_REAL  time_to_switch_to_eta_final_value&&\
CCTK_STRING  shift_interp_operator&&\
CCTK_INT eta_falloff_enable&&\
CCTK_INT firstorder_shift_convert_Gammai_fisheye_to_physical&&\
CCTK_INT hbpunc_advect_enable&&\
CCTK_INT hbpuncture_shift_convert_Gammai_fisheye_to_physical&&\
CCTK_INT hyper_Integration_Order&&\
CCTK_INT punc_shift_bc_radial_falloff_power&&\
CCTK_INT shift_bc_type&&\
COMMON /shiftpriv/eta,eta_falloff_dr,eta_falloff_radius,eta_final_value,hyper_Rscale,hyper_b1,hyper_b2,hyper_b3,hyper_phi_init,hyper_psi6_init,time_to_switch_to_eta_final_value,shift_interp_operator,eta_falloff_enable,firstorder_shift_convert_Gammai_fisheye_to_physical,hbpunc_advect_enable,hbpuncture_shift_convert_Gammai_fisheye_to_physical,hyper_Integration_Order,punc_shift_bc_radial_falloff_power,shift_bc_type&&\
CCTK_REAL  Xcenter&&\
CCTK_REAL  Ycenter&&\
CCTK_REAL  Zcenter&&\
CCTK_REAL  CCTKH5&&\
CCTK_REAL  CCTKH6&&\
CCTK_REAL  CCTKH7&&\
CCTK_REAL  CCTKH8&&\
CCTK_REAL  CCTKH9&&\
CCTK_REAL  CCTKH10&&\
CCTK_REAL  CCTKH11&&\
CCTK_REAL  CCTKH12&&\
CCTK_REAL  CCTKH13&&\
CCTK_REAL  CCTKH14&&\
CCTK_REAL  CCTKH15&&\
CCTK_REAL  CCTKH16&&\
CCTK_REAL  CCTKH17&&\
CCTK_REAL  CCTKH18&&\
CCTK_INT CCTKH0&&\
CCTK_INT CCTKH1&&\
CCTK_INT CCTKH2&&\
CCTK_INT CCTKH3&&\
CCTK_INT CCTKH4&&\
CCTK_INT bssn_enable_shift_upwind&&\
CCTK_INT enable_lower_order_at_boundaries&&\
CCTK_INT use_trans_fish_phys_new&&\
CCTK_INT CCTKH19&&\
COMMON /BSSNrest/Xcenter,Ycenter,Zcenter,CCTKH5,CCTKH6,CCTKH7,CCTKH8,CCTKH9,CCTKH10,CCTKH11,CCTKH12,CCTKH13,CCTKH14,CCTKH15,CCTKH16,CCTKH17,CCTKH18,CCTKH0,CCTKH1,CCTKH2,CCTKH3,CCTKH4,bssn_enable_shift_upwind,enable_lower_order_at_boundaries,use_trans_fish_phys_new,CCTKH19&&\
CCTK_REAL  CCTKH20&&\
CCTK_REAL  CCTKH21&&\
CCTK_REAL  CCTKH22&&\
CCTK_REAL  CCTKH23&&\
CCTK_REAL  CCTKH31&&\
CCTK_REAL  CCTKH32&&\
CCTK_REAL  CCTKH33&&\
CCTK_REAL  CCTKH34&&\
CCTK_REAL  CCTKH35&&\
CCTK_REAL  CCTKH36&&\
CCTK_REAL  CCTKH37&&\
CCTK_REAL  CCTKH38&&\
CCTK_STRING  bitant_plane&&\
CCTK_STRING  domain&&\
CCTK_STRING  quadrant_direction&&\
CCTK_STRING  CCTKH24&&\
CCTK_STRING  type&&\
CCTK_INT CCTKH25&&\
CCTK_INT CCTKH26&&\
CCTK_INT CCTKH27&&\
CCTK_INT CCTKH28&&\
CCTK_INT CCTKH29&&\
CCTK_INT CCTKH30&&\
COMMON /GRIDrest/CCTKH20,CCTKH21,CCTKH22,CCTKH23,CCTKH31,CCTKH32,CCTKH33,CCTKH34,CCTKH35,CCTKH36,CCTKH37,CCTKH38,bitant_plane,domain,quadrant_direction,CCTKH24,type,CCTKH25,CCTKH26,CCTKH27,CCTKH28,CCTKH29,CCTKH30&&\
CCTK_INT CCTKH39&&\
CCTK_INT CCTKH40&&\
CCTK_INT CCTKH41&&\
CCTK_INT CCTKH42&&\
CCTK_INT CCTKH43&&\
CCTK_INT CCTKH44&&\
CCTK_INT CCTKH45&&\
CCTK_INT CCTKH46&&\
CCTK_INT CCTKH47&&\
CCTK_INT CCTKH48&&\
CCTK_INT CCTKH49&&\
CCTK_INT MoL_Num_Constrained_Vars&&\
CCTK_INT MoL_Num_Evolved_Vars&&\
CCTK_INT MoL_Num_SaveAndRestore_Vars&&\
CCTK_INT CCTKH50&&\
COMMON /METHODOFLINESrest/CCTKH39,CCTKH40,CCTKH41,CCTKH42,CCTKH43,CCTKH44,CCTKH45,CCTKH46,CCTKH47,CCTKH48,CCTKH49,MoL_Num_Constrained_Vars,MoL_Num_Evolved_Vars,MoL_Num_SaveAndRestore_Vars,CCTKH50&&\

