#define DECLARE_CCTK_PARAMETERS \
CCTK_REAL  excision_radius&&\
CCTK_REAL  run_time&&\
CCTK_INT Symmetry&&\
CCTK_INT bssn_enable&&\
CCTK_INT cowling_enable&&\
CCTK_INT excision_enable&&\
CCTK_INT fisheye_enable&&\
CCTK_INT iter_count&&\
CCTK_INT number_of_mol_ministeps&&\
CCTK_INT rot_metric&&\
CCTK_INT trA_detg_enforce&&\
COMMON /cctk_params_global/excision_radius,run_time,Symmetry,bssn_enable,cowling_enable,excision_enable,fisheye_enable,iter_count,number_of_mol_ministeps,rot_metric,trA_detg_enforce&&\
CCTK_STRING  timestep_method&&\
CCTK_INT timestep_outonly&&\
COMMON /timerest/timestep_method,timestep_outonly&&\
CCTK_REAL  courant_fac&&\
CCTK_REAL  dtfac&&\
CCTK_REAL  timestep&&\
CCTK_INT timestep_outevery&&\
CCTK_INT verbose&&\
COMMON /Timepriv/courant_fac,dtfac,timestep,timestep_outevery,verbose&&\
CCTK_REAL  cctk_final_time&&\
CCTK_REAL  CCTKH0&&\
CCTK_REAL  CCTKH2&&\
CCTK_STRING  terminate&&\
CCTK_INT CCTKH1&&\
CCTK_INT CCTKH3&&\
COMMON /CACTUSrest/cctk_final_time,CCTKH0,CCTKH2,terminate,CCTKH1,CCTKH3&&\

