/*@@
   @header  WaveToyMoL_CParameters.h
   @author  Automatically generated by CreateParameterBindings.pl
   @desc
            Declares parameters of thorn WaveToyMoL
   @enddesc
 @@*/


#ifndef _WAVETOYMOL_PARAMETERS_H_
#define _WAVETOYMOL_PARAMETERS_H_ 1

#include "ParameterCGlobal.h"
#include "ParameterCRestrictedWAVETOYMOL.h"
#include "ParameterCPrivateWAVETOYMOL.h"
#include "ParameterCRestrictedMETHODOFLINES.h"

#define DECLARE_CCTK_PARAMETERS \
  DECLARE_GLOBAL_PARAMETER_STRUCT_PARAMS \
  DECLARE_RESTRICTED_WAVETOYMOL_STRUCT_PARAMS \
  DECLARE_PRIVATE_WAVETOYMOL_STRUCT_PARAMS \
  CCTK_INT const MoL_Num_Evolved_Vars = RESTRICTED_METHODOFLINES_STRUCT.MoL_Num_Evolved_Vars; \
  enum { \
      dummy_METHODOFLINES_MoL_Num_Evolved_Vars = sizeof( MoL_Num_Evolved_Vars ) \
  };

#endif  /* _WAVETOYMOL_PARAMETERS_H_ */

