/*@@
   @header  zlib_arguments.h
   @author  Automatically generated by GridFuncStuff.pl
   @desc
            Defines macros to declare/define/pass function arguments
            in calls from C to Fortran for thorn zlib
   @enddesc
 @@*/


#ifdef FCODE
#define DECLARE_ZLIB_PRIVATE_FARGUMENTS \


#define ZLIB_PRIVATE_FARGUMENTS \


#endif /* FCODE */

#ifdef CCODE
#define DECLARE_ZLIB_PRIVATE_CARGUMENTS \


#define DECLARE_ZLIB_PRIVATE_C2F \


#define INITIALISE_ZLIB_PRIVATE_C2F \


#define ZLIB_PRIVATE_C2F_PROTO \


#define PASS_ZLIB_PRIVATE_C2F(GH) \


#endif /* CCODE */

#ifdef FCODE
#define DECLARE_ZLIB_PROTECTED_FARGUMENTS \


#define ZLIB_PROTECTED_FARGUMENTS \


#endif /* FCODE */

#ifdef CCODE
#define DECLARE_ZLIB_PROTECTED_CARGUMENTS \


#define DECLARE_ZLIB_PROTECTED_C2F \


#define INITIALISE_ZLIB_PROTECTED_C2F \


#define ZLIB_PROTECTED_C2F_PROTO \


#define PASS_ZLIB_PROTECTED_C2F(GH) \


#endif /* CCODE */

#ifdef FCODE
#define DECLARE_ZLIB_PUBLIC_FARGUMENTS \


#define ZLIB_PUBLIC_FARGUMENTS \


#endif /* FCODE */

#ifdef CCODE
#define DECLARE_ZLIB_PUBLIC_CARGUMENTS \


#define DECLARE_ZLIB_PUBLIC_C2F \


#define INITIALISE_ZLIB_PUBLIC_C2F \


#define ZLIB_PUBLIC_C2F_PROTO \


#define PASS_ZLIB_PUBLIC_C2F(GH) \


#endif /* CCODE */

#ifdef FCODE
#define ZLIB_FARGUMENTS _CCTK_FARGUMENTS

#define DECLARE_ZLIB_FARGUMENTS _DECLARE_CCTK_FARGUMENTS

#endif /* FCODE */

#ifdef CCODE
#define DECLARE_ZLIB_CARGUMENTS _DECLARE_CCTK_CARGUMENTS

#define ZLIB_C2F_PROTO _CCTK_C2F_PROTO

#define PASS_ZLIB_C2F(GH) _PASS_CCTK_C2F(GH)

#define DECLARE_ZLIB_C2F _DECLARE_CCTK_C2F

#define INITIALISE_ZLIB_C2F _INITIALISE_CCTK_C2F

#define ZLIB_CARGUMENTS cGH *cctkGH

#endif /* CCODE */
