/*@@
   @file       ScheduleCarpetIOHDF5.c
   @author     Automatically generated by CreateScheduleBindings.pl
   @desc
               Creates the schedule and parameter recovery bindings 
               for thorn CarpetIOHDF5
   @enddesc
@@*/

#define THORN_IS_CarpetIOHDF5

#include "cctk.h"
#include "cctk_Parameters.h"
#include "cctki_ScheduleBindings.h"

/* prototypes for schedule bindings functions to be registered */
/* Note that this is a cheat, we just need a function pointer. */
extern int CarpetIOHDF5_Startup(void);
extern int CarpetIOHDF5_Init(void);
extern int CarpetIOHDF5_InitCheckpointingIntervals(void);
extern int CarpetIOHDF5_InitialDataCheckpoint(void);
extern int CarpetIOHDF5_EvolutionCheckpoint(void);
extern int CarpetIOHDF5_TerminationCheckpoint(void);
extern int CarpetIOHDF5_CloseFiles(void);
extern int CarpetIOHDF5_SetNumRefinementLevels(void);
extern int CarpetIOHDF5_CloseFiles(void);


void CCTKi_BindingsSchedule_CarpetIOHDF5(void);
void CCTKi_BindingsSchedule_CarpetIOHDF5(void)
{
  DECLARE_CCTK_PARAMETERS
  CCTKi_ScheduleGroupStorage("CarpetIOHDF5::next_output_iteration",1);
  CCTKi_ScheduleGroupStorage("CarpetIOHDF5::next_output_time",1);
  CCTKi_ScheduleGroupStorage("CarpetIOHDF5::this_iteration",1);
  CCTKi_ScheduleGroupStorage("CarpetIOHDF5::last_output_iteration_slice",1);
  CCTKi_ScheduleGroupStorage("CarpetIOHDF5::last_output_time_slice",1);
  CCTKi_ScheduleGroupStorage("CarpetIOHDF5::this_iteration_slice",1);
  {
    int cctkschedulei_tlevelarray[] = {0};
    CCTKi_ScheduleFunction((void *)CarpetIOHDF5_Startup,
                           "CarpetIOHDF5_Startup",
                           "CarpetIOHDF5",
                           "IOHDF5",
                           "Startup routine",
                           "CCTK_STARTUP",
                           "C",
                           0,  /* Number of STORAGE  groups   */
                           0,  /* Number of COMM     groups   */
                           0,  /* Number of TRIGGERS groups   */
                           0,  /* Number of SYNC     groups   */
                           0,  /* Number of Options           */
                           0,  /* Number of BEFORE  routines  */
                           1,  /* Number of AFTER   routines  */
                           0,  /* Number of WHILE   variables */
                           0,  /* Number of IF   variables */
                           cctkschedulei_tlevelarray  /* Array of timelevel data for storage groups */,
                           "IOUtil_Startup");
  }
  {
    int cctkschedulei_tlevelarray[] = {0};
    CCTKi_ScheduleFunction((void *)CarpetIOHDF5_Init,
                           "CarpetIOHDF5_Init",
                           "CarpetIOHDF5",
                           "IOHDF5",
                           "Initialisation routine",
                           "CCTK_BASEGRID",
                           "C",
                           0,  /* Number of STORAGE  groups   */
                           0,  /* Number of COMM     groups   */
                           0,  /* Number of TRIGGERS groups   */
                           0,  /* Number of SYNC     groups   */
                           1,  /* Number of Options           */
                           0,  /* Number of BEFORE  routines  */
                           0,  /* Number of AFTER   routines  */
                           0,  /* Number of WHILE   variables */
                           0,  /* Number of IF   variables */
                           cctkschedulei_tlevelarray  /* Array of timelevel data for storage groups */,
                           "global");
  }
  {
    int cctkschedulei_tlevelarray[] = {0};
    CCTKi_ScheduleFunction((void *)CarpetIOHDF5_InitCheckpointingIntervals,
                           "CarpetIOHDF5_InitCheckpointingIntervals",
                           "CarpetIOHDF5",
                           "IOHDF5",
                           "Initialisation of checkpointing intervals after recovery",
                           "CCTK_POST_RECOVER_VARIABLES",
                           "C",
                           0,  /* Number of STORAGE  groups   */
                           0,  /* Number of COMM     groups   */
                           0,  /* Number of TRIGGERS groups   */
                           0,  /* Number of SYNC     groups   */
                           1,  /* Number of Options           */
                           0,  /* Number of BEFORE  routines  */
                           0,  /* Number of AFTER   routines  */
                           0,  /* Number of WHILE   variables */
                           0,  /* Number of IF   variables */
                           cctkschedulei_tlevelarray  /* Array of timelevel data for storage groups */,
                           "global");
  }
  {
    int cctkschedulei_tlevelarray[] = {0};
    CCTKi_ScheduleFunction((void *)CarpetIOHDF5_InitialDataCheckpoint,
                           "CarpetIOHDF5_InitialDataCheckpoint",
                           "CarpetIOHDF5",
                           "IOHDF5",
                           "Initial data checkpoint routine",
                           "CCTK_CPINITIAL",
                           "C",
                           0,  /* Number of STORAGE  groups   */
                           0,  /* Number of COMM     groups   */
                           0,  /* Number of TRIGGERS groups   */
                           0,  /* Number of SYNC     groups   */
                           1,  /* Number of Options           */
                           0,  /* Number of BEFORE  routines  */
                           0,  /* Number of AFTER   routines  */
                           0,  /* Number of WHILE   variables */
                           0,  /* Number of IF   variables */
                           cctkschedulei_tlevelarray  /* Array of timelevel data for storage groups */,
                           "meta");
  }
  {
    int cctkschedulei_tlevelarray[] = {0};
    CCTKi_ScheduleFunction((void *)CarpetIOHDF5_EvolutionCheckpoint,
                           "CarpetIOHDF5_EvolutionCheckpoint",
                           "CarpetIOHDF5",
                           "IOHDF5",
                           "Evolution checkpoint routine",
                           "CCTK_CHECKPOINT",
                           "C",
                           0,  /* Number of STORAGE  groups   */
                           0,  /* Number of COMM     groups   */
                           0,  /* Number of TRIGGERS groups   */
                           0,  /* Number of SYNC     groups   */
                           1,  /* Number of Options           */
                           0,  /* Number of BEFORE  routines  */
                           0,  /* Number of AFTER   routines  */
                           0,  /* Number of WHILE   variables */
                           0,  /* Number of IF   variables */
                           cctkschedulei_tlevelarray  /* Array of timelevel data for storage groups */,
                           "meta");
  }
  {
    int cctkschedulei_tlevelarray[] = {0};
    CCTKi_ScheduleFunction((void *)CarpetIOHDF5_TerminationCheckpoint,
                           "CarpetIOHDF5_TerminationCheckpoint",
                           "CarpetIOHDF5",
                           "IOHDF5",
                           "Termination checkpoint routine",
                           "CCTK_TERMINATE",
                           "C",
                           0,  /* Number of STORAGE  groups   */
                           0,  /* Number of COMM     groups   */
                           0,  /* Number of TRIGGERS groups   */
                           0,  /* Number of SYNC     groups   */
                           1,  /* Number of Options           */
                           0,  /* Number of BEFORE  routines  */
                           0,  /* Number of AFTER   routines  */
                           0,  /* Number of WHILE   variables */
                           0,  /* Number of IF   variables */
                           cctkschedulei_tlevelarray  /* Array of timelevel data for storage groups */,
                           "meta");
  }
  {
    int cctkschedulei_tlevelarray[] = {0};
    CCTKi_ScheduleFunction((void *)CarpetIOHDF5_CloseFiles,
                           "CarpetIOHDF5_CloseFiles",
                           "CarpetIOHDF5",
                           "IOHDF5",
                           "Close all filereader input files",
                           "CCTK_POSTINITIAL",
                           "C",
                           0,  /* Number of STORAGE  groups   */
                           0,  /* Number of COMM     groups   */
                           0,  /* Number of TRIGGERS groups   */
                           0,  /* Number of SYNC     groups   */
                           1,  /* Number of Options           */
                           0,  /* Number of BEFORE  routines  */
                           0,  /* Number of AFTER   routines  */
                           0,  /* Number of WHILE   variables */
                           0,  /* Number of IF   variables */
                           cctkschedulei_tlevelarray  /* Array of timelevel data for storage groups */,
                           "global");
  }
if (! CCTK_Equals (recover, "no") && *recover_file)
{
  if (use_reflevels_from_checkpoint)
  {
  {
    int cctkschedulei_tlevelarray[] = {0};
    CCTKi_ScheduleFunction((void *)CarpetIOHDF5_SetNumRefinementLevels,
                           "CarpetIOHDF5_SetNumRefinementLevels",
                           "CarpetIOHDF5",
                           "IOHDF5",
                           "Overwrite 'CarpetRegird::refinement_levels' with the number of levels found in the checkpoint file",
                           "CCTK_STARTUP",
                           "C",
                           0,  /* Number of STORAGE  groups   */
                           0,  /* Number of COMM     groups   */
                           0,  /* Number of TRIGGERS groups   */
                           0,  /* Number of SYNC     groups   */
                           1,  /* Number of Options           */
                           1,  /* Number of BEFORE  routines  */
                           0,  /* Number of AFTER   routines  */
                           0,  /* Number of WHILE   variables */
                           0,  /* Number of IF   variables */
                           cctkschedulei_tlevelarray  /* Array of timelevel data for storage groups */,
                           "meta",
                           "CarpetIOHDF5_Startup");
  }
  }
  {
    int cctkschedulei_tlevelarray[] = {0};
    CCTKi_ScheduleFunction((void *)CarpetIOHDF5_CloseFiles,
                           "CarpetIOHDF5_CloseFiles",
                           "CarpetIOHDF5",
                           "IOHDF5",
                           "Close all initial data checkpoint files after recovery",
                           "CCTK_POST_RECOVER_VARIABLES",
                           "C",
                           0,  /* Number of STORAGE  groups   */
                           0,  /* Number of COMM     groups   */
                           0,  /* Number of TRIGGERS groups   */
                           0,  /* Number of SYNC     groups   */
                           1,  /* Number of Options           */
                           0,  /* Number of BEFORE  routines  */
                           0,  /* Number of AFTER   routines  */
                           0,  /* Number of WHILE   variables */
                           0,  /* Number of IF   variables */
                           cctkschedulei_tlevelarray  /* Array of timelevel data for storage groups */,
                           "meta");
  }
}
}

/*@@
  @routine    CCTKi_BindingsParameterRecovery_CarpetIOHDF5
  @author     Automatically generated by CreateScheduleBindings.pl
  @desc
              Creates the parameter recovery bindings for thorn CarpetIOHDF5
  @enddesc
@@*/

/* prototypes of parameter recovery functions to be registered. */
extern int CarpetIOHDF5_RecoverParameters(void);

int CCTKi_BindingsParameterRecovery_CarpetIOHDF5(void);
int CCTKi_BindingsParameterRecovery_CarpetIOHDF5(void)
{
  DECLARE_CCTK_PARAMETERS
  int result = 0;

if (! CCTK_Equals (recover, "no") && *recover_file)
{
result =  CarpetIOHDF5_RecoverParameters();
  if (use_reflevels_from_checkpoint)
  {
  }
}

  return (result);
}

