/*@@
   @file       SchedulescalarwaveMoL.c
   @author     Automatically generated by CreateScheduleBindings.pl
   @desc
               Creates the schedule and parameter recovery bindings 
               for thorn scalarwaveMoL
   @enddesc
@@*/

#define THORN_IS_scalarwaveMoL

#include "cctk.h"
#include "cctk_Parameters.h"
#include "cctki_ScheduleBindings.h"

/* prototypes for schedule bindings functions to be registered */
/* Note that this is a cheat, we just need a function pointer. */
extern int scalarwaveMoL_CheckParameters(void);
extern int CCTK_FNAME(scalarwaveMoL_print_time)(void);
extern int scalarwaveMoL_Startup(void);
extern int scalarwaveMoL_InitSymBound(void);
extern int ABE_ScalarWave_Setup_InitialData(void);
extern int scalarwaveMoL_RegisterVars(void);
extern int scalarwaveMoL_compute_rhs(void);
extern int CCTK_FNAME(scalarwaveMoL_update_boundary)(void);
extern int Compute_Difference_Numerical_Analytic(void);
extern int CCTK_FNAME(update_movingbox)(void);


void CCTKi_BindingsSchedule_scalarwaveMoL(void);
void CCTKi_BindingsSchedule_scalarwaveMoL(void)
{
  DECLARE_CCTK_PARAMETERS
  CCTKi_ScheduleGroupStorage("scalarwaveMoL::scalarMoLevolve",3);
  CCTKi_ScheduleGroupStorage("scalarwaveMoL::scalarMoLrhs",1);
  CCTKi_ScheduleGroupStorage("scalarwaveMoL::scalarMoLstagger",3);
  CCTKi_ScheduleGroupStorage("scalarwaveMoL::scalarMoLstaggerrhs",1);
  CCTKi_ScheduleGroupStorage("scalarwaveMoL::scalarMoLanalytic",1);
  CCTKi_ScheduleGroupStorage("scalarwaveMoL::scawave_have_global_boundary",1);
  {
    int cctkschedulei_tlevelarray[] = {0};
    CCTKi_ScheduleFunction((void *)scalarwaveMoL_CheckParameters,
                           "scalarwaveMoL_CheckParameters",
                           "scalarwaveMoL",
                           "scalarwaveMoL",
                           "Check parameters",
                           "CCTK_PARAMCHECK",
                           "C",
                           0,  /* Number of STORAGE  groups   */
                           0,  /* Number of COMM     groups   */
                           0,  /* Number of TRIGGERS groups   */
                           0,  /* Number of SYNC     groups   */
                           0,  /* Number of Options           */
                           0,  /* Number of BEFORE  routines  */
                           0,  /* Number of AFTER   routines  */
                           0,  /* Number of WHILE   variables */
                           0,  /* Number of IF   variables */
                           cctkschedulei_tlevelarray  /* Array of timelevel data for storage groups */);
  }
  {
    int cctkschedulei_tlevelarray[] = {0};
    CCTKi_ScheduleFunction((void *)CCTK_FNAME(scalarwaveMoL_print_time),
                           "scalarwaveMoL_print_time",
                           "scalarwaveMoL",
                           "scalarwaveMoL",
                           "Print the iteration number and time.",
                           "MoL_PreStep",
                           "Fortran",
                           0,  /* Number of STORAGE  groups   */
                           0,  /* Number of COMM     groups   */
                           0,  /* Number of TRIGGERS groups   */
                           0,  /* Number of SYNC     groups   */
                           0,  /* Number of Options           */
                           0,  /* Number of BEFORE  routines  */
                           0,  /* Number of AFTER   routines  */
                           0,  /* Number of WHILE   variables */
                           0,  /* Number of IF   variables */
                           cctkschedulei_tlevelarray  /* Array of timelevel data for storage groups */);
  }
  {
    int cctkschedulei_tlevelarray[] = {0};
    CCTKi_ScheduleFunction((void *)scalarwaveMoL_Startup,
                           "scalarwaveMoL_Startup",
                           "scalarwaveMoL",
                           "scalarwaveMoL",
                           "Register banner",
                           "CCTK_STARTUP",
                           "C",
                           0,  /* Number of STORAGE  groups   */
                           0,  /* Number of COMM     groups   */
                           0,  /* Number of TRIGGERS groups   */
                           0,  /* Number of SYNC     groups   */
                           0,  /* Number of Options           */
                           0,  /* Number of BEFORE  routines  */
                           0,  /* Number of AFTER   routines  */
                           0,  /* Number of WHILE   variables */
                           0,  /* Number of IF   variables */
                           cctkschedulei_tlevelarray  /* Array of timelevel data for storage groups */);
  }
  {
    int cctkschedulei_tlevelarray[] = {0};
    CCTKi_ScheduleFunction((void *)scalarwaveMoL_InitSymBound,
                           "scalarwaveMoL_InitSymBound",
                           "scalarwaveMoL",
                           "scalarwaveMoL",
                           "Schedule symmetries",
                           "CCTK_BASEGRID",
                           "C",
                           0,  /* Number of STORAGE  groups   */
                           0,  /* Number of COMM     groups   */
                           0,  /* Number of TRIGGERS groups   */
                           0,  /* Number of SYNC     groups   */
                           1,  /* Number of Options           */
                           0,  /* Number of BEFORE  routines  */
                           0,  /* Number of AFTER   routines  */
                           0,  /* Number of WHILE   variables */
                           0,  /* Number of IF   variables */
                           cctkschedulei_tlevelarray  /* Array of timelevel data for storage groups */,
                           "META");
  }
  {
    int cctkschedulei_tlevelarray[] = {0};
    CCTKi_ScheduleFunction((void *)ABE_ScalarWave_Setup_InitialData,
                           "ABE_ScalarWave_Setup_InitialData",
                           "scalarwaveMoL",
                           "scalarwaveMoL",
                           "Setup initial data",
                           "CCTK_INITIAL",
                           "C",
                           0,  /* Number of STORAGE  groups   */
                           0,  /* Number of COMM     groups   */
                           0,  /* Number of TRIGGERS groups   */
                           0,  /* Number of SYNC     groups   */
                           0,  /* Number of Options           */
                           0,  /* Number of BEFORE  routines  */
                           0,  /* Number of AFTER   routines  */
                           0,  /* Number of WHILE   variables */
                           0,  /* Number of IF   variables */
                           cctkschedulei_tlevelarray  /* Array of timelevel data for storage groups */);
  }
  {
    int cctkschedulei_tlevelarray[] = {0};
    CCTKi_ScheduleFunction((void *)scalarwaveMoL_RegisterVars,
                           "scalarwaveMoL_RegisterVars",
                           "scalarwaveMoL",
                           "scalarwaveMoL",
                           "Register variables for MoL",
                           "MoL_Register",
                           "C",
                           0,  /* Number of STORAGE  groups   */
                           0,  /* Number of COMM     groups   */
                           0,  /* Number of TRIGGERS groups   */
                           0,  /* Number of SYNC     groups   */
                           1,  /* Number of Options           */
                           0,  /* Number of BEFORE  routines  */
                           0,  /* Number of AFTER   routines  */
                           0,  /* Number of WHILE   variables */
                           0,  /* Number of IF   variables */
                           cctkschedulei_tlevelarray  /* Array of timelevel data for storage groups */,
                           "META");
  }
  {
    int cctkschedulei_tlevelarray[] = {0};
    CCTKi_ScheduleFunction((void *)scalarwaveMoL_compute_rhs,
                           "scalarwaveMoL_compute_rhs",
                           "scalarwaveMoL",
                           "scalarwaveMoL",
                           "Register RHS calculation for MoL",
                           "MoL_CalcRHS",
                           "C",
                           0,  /* Number of STORAGE  groups   */
                           0,  /* Number of COMM     groups   */
                           0,  /* Number of TRIGGERS groups   */
                           0,  /* Number of SYNC     groups   */
                           0,  /* Number of Options           */
                           0,  /* Number of BEFORE  routines  */
                           0,  /* Number of AFTER   routines  */
                           0,  /* Number of WHILE   variables */
                           0,  /* Number of IF   variables */
                           cctkschedulei_tlevelarray  /* Array of timelevel data for storage groups */);
  }
  {
    int cctkschedulei_tlevelarray[] = {0};
    CCTKi_ScheduleFunction((void *)CCTK_FNAME(scalarwaveMoL_update_boundary),
                           "scalarwaveMoL_Boundaries",
                           "scalarwaveMoL",
                           "scalarwaveMoL",
                           "Apply boundary conditions for scalarwaveMoL",
                           "MoL_PostStep",
                           "Fortran",
                           0,  /* Number of STORAGE  groups   */
                           0,  /* Number of COMM     groups   */
                           0,  /* Number of TRIGGERS groups   */
                           2,  /* Number of SYNC     groups   */
                           0,  /* Number of Options           */
                           0,  /* Number of BEFORE  routines  */
                           0,  /* Number of AFTER   routines  */
                           0,  /* Number of WHILE   variables */
                           0,  /* Number of IF   variables */
                           cctkschedulei_tlevelarray  /* Array of timelevel data for storage groups */,
                           "scalarwaveMoL::scalarMoLevolve",
                           "scalarwaveMoL::scalarMoLstagger");
  }
  {
    int cctkschedulei_tlevelarray[] = {0};
    CCTKi_ScheduleFunction((void *)Compute_Difference_Numerical_Analytic,
                           "C_A",
                           "scalarwaveMoL",
                           "scalarwaveMoL",
                           "Compute Analytic Solution",
                           "CCTK_ANALYSIS",
                           "C",
                           0,  /* Number of STORAGE  groups   */
                           0,  /* Number of COMM     groups   */
                           0,  /* Number of TRIGGERS groups   */
                           3,  /* Number of SYNC     groups   */
                           0,  /* Number of Options           */
                           0,  /* Number of BEFORE  routines  */
                           0,  /* Number of AFTER   routines  */
                           0,  /* Number of WHILE   variables */
                           0,  /* Number of IF   variables */
                           cctkschedulei_tlevelarray  /* Array of timelevel data for storage groups */,
                           "scalarwaveMoL::scalarMoLevolve",
                           "scalarwaveMoL::scalarMoLstagger",
                           "scalarwaveMoL::scalarMoLanalytic");
  }
  {
    int cctkschedulei_tlevelarray[] = {0};
    CCTKi_ScheduleFunction((void *)CCTK_FNAME(update_movingbox),
                           "update_movingbox",
                           "scalarwaveMoL",
                           "scalarwaveMoL",
                           "Update moving box center",
                           "CCTK_ANALYSIS",
                           "Fortran",
                           0,  /* Number of STORAGE  groups   */
                           0,  /* Number of COMM     groups   */
                           0,  /* Number of TRIGGERS groups   */
                           0,  /* Number of SYNC     groups   */
                           1,  /* Number of Options           */
                           0,  /* Number of BEFORE  routines  */
                           1,  /* Number of AFTER   routines  */
                           0,  /* Number of WHILE   variables */
                           0,  /* Number of IF   variables */
                           cctkschedulei_tlevelarray  /* Array of timelevel data for storage groups */,
                           "global",
                           "C_A");
  }
}

/*@@
  @routine    CCTKi_BindingsParameterRecovery_scalarwaveMoL
  @author     Automatically generated by CreateScheduleBindings.pl
  @desc
              Creates the parameter recovery bindings for thorn scalarwaveMoL
  @enddesc
@@*/

int CCTKi_BindingsParameterRecovery_scalarwaveMoL(void);
int CCTKi_BindingsParameterRecovery_scalarwaveMoL(void)
{
  /* this thorn doesn't define any parameter recovery routines */
  return (0);
}

