/*@@
   @file       Scheduleexcision.c
   @author     Automatically generated by CreateScheduleBindings.pl
   @desc
               Creates the schedule and parameter recovery bindings 
               for thorn excision
   @enddesc
@@*/

#define THORN_IS_excision

#include "cctk.h"
#include "cctk_Parameters.h"
#include "cctki_ScheduleBindings.h"

/* prototypes for schedule bindings functions to be registered */
/* Note that this is a cheat, we just need a function pointer. */


void CCTKi_BindingsSchedule_excision(void);
void CCTKi_BindingsSchedule_excision(void)
{
  DECLARE_CCTK_PARAMETERS
}

/*@@
  @routine    CCTKi_BindingsParameterRecovery_excision
  @author     Automatically generated by CreateScheduleBindings.pl
  @desc
              Creates the parameter recovery bindings for thorn excision
  @enddesc
@@*/

int CCTKi_BindingsParameterRecovery_excision(void);
int CCTKi_BindingsParameterRecovery_excision(void)
{
  /* this thorn doesn't define any parameter recovery routines */
  return (0);
}

