/*@@
   @file       Schedulediagnostics_vacuum.c
   @author     Automatically generated by CreateScheduleBindings.pl
   @desc
               Creates the schedule and parameter recovery bindings 
               for thorn diagnostics_vacuum
   @enddesc
@@*/

#define THORN_IS_diagnostics_vacuum

#include "cctk.h"
#include "cctk_Parameters.h"
#include "cctki_ScheduleBindings.h"

/* prototypes for schedule bindings functions to be registered */
/* Note that this is a cheat, we just need a function pointer. */
extern int CCTK_FNAME(setup_surface_integration)(void);
extern int CCTK_FNAME(setup_multiple_surfaces)(void);
extern int CCTK_FNAME(setup_surface_integration)(void);
extern int CCTK_FNAME(setup_multiple_surfaces)(void);
extern int initialize_bh_posns(void);
extern int update_bh_posns(void);
extern int update_bh_posns(void);
extern int CCTK_FNAME(ADM_mass_integrand)(void);
extern int CCTK_FNAME(Integrate_vol_integrand)(void);
extern int CCTK_FNAME(angular_momentum_integrand)(void);
extern int CCTK_FNAME(Integrate_vol_integrand)(void);
extern int CCTK_FNAME(Ham_constraint_integrand)(void);
extern int CCTK_FNAME(Integrate_vol_integrand)(void);
extern int CCTK_FNAME(Ham_constraint_excised_integrand)(void);
extern int CCTK_FNAME(Integrate_vol_integrand)(void);
extern int CCTK_FNAME(mom_constraint_integrand)(void);
extern int CCTK_FNAME(Integrate_vol_integrand)(void);
extern int CCTK_FNAME(mom_constraint_excised_integrand)(void);
extern int CCTK_FNAME(Integrate_vol_integrand)(void);
extern int CCTK_FNAME(Gam_constraint_integrand)(void);
extern int CCTK_FNAME(Integrate_vol_integrand)(void);
extern int CCTK_FNAME(M_Ham_constraint_excised_integrand)(void);
extern int CCTK_FNAME(Integrate_vol_integrand)(void);
extern int CCTK_FNAME(Jz_mom_constraint_excised_integrand)(void);
extern int CCTK_FNAME(Integrate_vol_integrand)(void);
extern int CCTK_FNAME(P_mom_constraint_excised_integrand)(void);
extern int CCTK_FNAME(Integrate_vol_integrand)(void);
extern int CCTK_FNAME(P_mom_constraint_excised_integrand)(void);
extern int CCTK_FNAME(Integrate_vol_integrand)(void);


void CCTKi_BindingsSchedule_diagnostics_vacuum(void);
void CCTKi_BindingsSchedule_diagnostics_vacuum(void)
{
  DECLARE_CCTK_PARAMETERS
  CCTKi_ScheduleGroupStorage("BSSN::BSSN_vars",3);
  CCTKi_ScheduleGroupStorage("BSSN::BSSN_gupij",1);
  CCTKi_ScheduleGroupStorage("BSSN::BSSN_matter",1);
  CCTKi_ScheduleGroupStorage("BSSN::BSSN_AH",1);
  CCTKi_ScheduleGroupStorage("BSSN::BSSN_aux_restrict2",1);
  CCTKi_ScheduleGroupStorage("BSSN::phi_derivs",1);
  CCTKi_ScheduleGroupStorage("BSSN::BSSN_diag_restrict",1);
  CCTKi_ScheduleGroupStorage("lapse::lapse_vars",3);
  CCTKi_ScheduleGroupStorage("lapse::lapse_derivatives",1);
  CCTKi_ScheduleGroupStorage("lapse::lapse_vars_aux",1);
  CCTKi_ScheduleGroupStorage("shift::shift_vars",3);
  CCTKi_ScheduleGroupStorage("shift::shift_vars_temp",1);
  CCTKi_ScheduleGroupStorage("fisheye::fisheye_vars",1);
  CCTKi_ScheduleGroupStorage("excision::excision_int_gfs",1);
  CCTKi_ScheduleGroupStorage("diagnostics_vacuum::surf_params",1);
  CCTKi_ScheduleGroupStorage("diagnostics_vacuum::diag_vacuum_gf",1);
  CCTKi_ScheduleGroupStorage("diagnostics_vacuum::volIntegrals",1);
  CCTKi_ScheduleGroupStorage("diagnostics_vacuum::bh_posns",1);
  {
    int cctkschedulei_tlevelarray[] = {0};
    CCTKi_ScheduleFunction((void *)CCTK_FNAME(setup_surface_integration),
                           "one_surface",
                           "diagnostics_vacuum",
                           "diagnostics_vacuum",
                           "Set up variables for surface integration routine (e.g., N_theta, N_phi, etc)",
                           "CCTK_ANALYSIS",
                           "Fortran",
                           0,  /* Number of STORAGE  groups   */
                           0,  /* Number of COMM     groups   */
                           0,  /* Number of TRIGGERS groups   */
                           0,  /* Number of SYNC     groups   */
                           1,  /* Number of Options           */
                           0,  /* Number of BEFORE  routines  */
                           2,  /* Number of AFTER   routines  */
                           0,  /* Number of WHILE   variables */
                           0,  /* Number of IF   variables */
                           cctkschedulei_tlevelarray  /* Array of timelevel data for storage groups */,
                           "GLOBAL",
                           "setup_global_coords",
                           "Setup_Fisheye_Coords");
  }
if(nsurf >= 1)
{
  {
    int cctkschedulei_tlevelarray[] = {0};
    CCTKi_ScheduleFunction((void *)CCTK_FNAME(setup_multiple_surfaces),
                           "many_surfaces",
                           "diagnostics_vacuum",
                           "diagnostics_vacuum",
                           "Set up multiple integration surfaces",
                           "CCTK_ANALYSIS",
                           "Fortran",
                           0,  /* Number of STORAGE  groups   */
                           0,  /* Number of COMM     groups   */
                           0,  /* Number of TRIGGERS groups   */
                           0,  /* Number of SYNC     groups   */
                           1,  /* Number of Options           */
                           0,  /* Number of BEFORE  routines  */
                           1,  /* Number of AFTER   routines  */
                           0,  /* Number of WHILE   variables */
                           0,  /* Number of IF   variables */
                           cctkschedulei_tlevelarray  /* Array of timelevel data for storage groups */,
                           "GLOBAL",
                           "one_surface");
  }
}
  {
    int cctkschedulei_tlevelarray[] = {0};
    CCTKi_ScheduleFunction((void *)CCTK_FNAME(setup_surface_integration),
                           "one_surface",
                           "diagnostics_vacuum",
                           "diagnostics_vacuum",
                           "Set up variables for surface integration routine (e.g., N_theta, N_phi, etc)",
                           "CCTK_POST_RECOVER_VARIABLES",
                           "Fortran",
                           0,  /* Number of STORAGE  groups   */
                           0,  /* Number of COMM     groups   */
                           0,  /* Number of TRIGGERS groups   */
                           0,  /* Number of SYNC     groups   */
                           1,  /* Number of Options           */
                           0,  /* Number of BEFORE  routines  */
                           0,  /* Number of AFTER   routines  */
                           0,  /* Number of WHILE   variables */
                           0,  /* Number of IF   variables */
                           cctkschedulei_tlevelarray  /* Array of timelevel data for storage groups */,
                           "GLOBAL");
  }
if(nsurf >= 1)
{
  {
    int cctkschedulei_tlevelarray[] = {0};
    CCTKi_ScheduleFunction((void *)CCTK_FNAME(setup_multiple_surfaces),
                           "many_surfaces",
                           "diagnostics_vacuum",
                           "diagnostics_vacuum",
                           "Set up multiple integration surfaces",
                           "CCTK_POST_RECOVER_VARIABLES",
                           "Fortran",
                           0,  /* Number of STORAGE  groups   */
                           0,  /* Number of COMM     groups   */
                           0,  /* Number of TRIGGERS groups   */
                           0,  /* Number of SYNC     groups   */
                           1,  /* Number of Options           */
                           0,  /* Number of BEFORE  routines  */
                           1,  /* Number of AFTER   routines  */
                           0,  /* Number of WHILE   variables */
                           0,  /* Number of IF   variables */
                           cctkschedulei_tlevelarray  /* Array of timelevel data for storage groups */,
                           "GLOBAL",
                           "one_surface");
  }
}
  {
    int cctkschedulei_tlevelarray[] = {0};
    CCTKi_ScheduleFunction((void *)initialize_bh_posns,
                           "initialize_bh_posns",
                           "diagnostics_vacuum",
                           "diagnostics_vacuum",
                           "Initialize BH positions to (0,0,0).",
                           "CCTK_ANALYSIS",
                           "C",
                           0,  /* Number of STORAGE  groups   */
                           0,  /* Number of COMM     groups   */
                           0,  /* Number of TRIGGERS groups   */
                           0,  /* Number of SYNC     groups   */
                           1,  /* Number of Options           */
                           3,  /* Number of BEFORE  routines  */
                           1,  /* Number of AFTER   routines  */
                           0,  /* Number of WHILE   variables */
                           0,  /* Number of IF   variables */
                           cctkschedulei_tlevelarray  /* Array of timelevel data for storage groups */,
                           "GLOBAL",
                           "M_ADM_integrand",
                           "poststep",
                           "update_bh_psns",
                           "many_surfaces");
  }
if(num_BHs > 0)
{
  {
    int cctkschedulei_tlevelarray[] = {0};
    CCTKi_ScheduleFunction((void *)update_bh_posns,
                           "update_bh_psns",
                           "diagnostics_vacuum",
                           "diagnostics_vacuum",
                           "Update bh positions",
                           "CCTK_ANALYSIS",
                           "C",
                           0,  /* Number of STORAGE  groups   */
                           0,  /* Number of COMM     groups   */
                           0,  /* Number of TRIGGERS groups   */
                           0,  /* Number of SYNC     groups   */
                           1,  /* Number of Options           */
                           2,  /* Number of BEFORE  routines  */
                           0,  /* Number of AFTER   routines  */
                           0,  /* Number of WHILE   variables */
                           0,  /* Number of IF   variables */
                           cctkschedulei_tlevelarray  /* Array of timelevel data for storage groups */,
                           "GLOBAL",
                           "M_ADM_integrand",
                           "poststep");
  }
  {
    int cctkschedulei_tlevelarray[] = {0};
    CCTKi_ScheduleFunction((void *)update_bh_posns,
                           "update_bh_psns",
                           "diagnostics_vacuum",
                           "diagnostics_vacuum",
                           "Update bh positions",
                           "CCTK_POST_RECOVER_VARIABLES",
                           "C",
                           0,  /* Number of STORAGE  groups   */
                           0,  /* Number of COMM     groups   */
                           0,  /* Number of TRIGGERS groups   */
                           0,  /* Number of SYNC     groups   */
                           1,  /* Number of Options           */
                           2,  /* Number of BEFORE  routines  */
                           0,  /* Number of AFTER   routines  */
                           0,  /* Number of WHILE   variables */
                           0,  /* Number of IF   variables */
                           cctkschedulei_tlevelarray  /* Array of timelevel data for storage groups */,
                           "GLOBAL",
                           "M_ADM_integrand",
                           "poststep");
  }
}
  {
    int cctkschedulei_tlevelarray[] = {0};
    CCTKi_ScheduleFunction((void *)CCTK_FNAME(ADM_mass_integrand),
                           "M_ADM_integrand",
                           "diagnostics_vacuum",
                           "diagnostics_vacuum",
                           "Fill in ADM mass volume integrand",
                           "CCTK_ANALYSIS",
                           "Fortran",
                           0,  /* Number of STORAGE  groups   */
                           0,  /* Number of COMM     groups   */
                           0,  /* Number of TRIGGERS groups   */
                           0,  /* Number of SYNC     groups   */
                           2,  /* Number of Options           */
                           1,  /* Number of BEFORE  routines  */
                           0,  /* Number of AFTER   routines  */
                           0,  /* Number of WHILE   variables */
                           0,  /* Number of IF   variables */
                           cctkschedulei_tlevelarray  /* Array of timelevel data for storage groups */,
                           "GLOBAL",
                           "loop-local",
                           "poststep");
  }
  {
    int cctkschedulei_tlevelarray[] = {0};
    CCTKi_ScheduleFunction((void *)CCTK_FNAME(Integrate_vol_integrand),
                           "M_ADM_integrate",
                           "diagnostics_vacuum",
                           "diagnostics_vacuum",
                           "Integrate ADM mass, output to M_ADM_VolInt",
                           "CCTK_ANALYSIS",
                           "Fortran",
                           0,  /* Number of STORAGE  groups   */
                           0,  /* Number of COMM     groups   */
                           0,  /* Number of TRIGGERS groups   */
                           0,  /* Number of SYNC     groups   */
                           1,  /* Number of Options           */
                           1,  /* Number of BEFORE  routines  */
                           1,  /* Number of AFTER   routines  */
                           0,  /* Number of WHILE   variables */
                           0,  /* Number of IF   variables */
                           cctkschedulei_tlevelarray  /* Array of timelevel data for storage groups */,
                           "GLOBAL",
                           "poststep",
                           "M_ADM_integrand");
  }
  {
    int cctkschedulei_tlevelarray[] = {0};
    CCTKi_ScheduleFunction((void *)CCTK_FNAME(angular_momentum_integrand),
                           "J_integrand",
                           "diagnostics_vacuum",
                           "diagnostics_vacuum",
                           "Fill in angular momentum volume integrand",
                           "CCTK_ANALYSIS",
                           "Fortran",
                           0,  /* Number of STORAGE  groups   */
                           0,  /* Number of COMM     groups   */
                           0,  /* Number of TRIGGERS groups   */
                           0,  /* Number of SYNC     groups   */
                           2,  /* Number of Options           */
                           1,  /* Number of BEFORE  routines  */
                           1,  /* Number of AFTER   routines  */
                           0,  /* Number of WHILE   variables */
                           0,  /* Number of IF   variables */
                           cctkschedulei_tlevelarray  /* Array of timelevel data for storage groups */,
                           "GLOBAL",
                           "loop-local",
                           "poststep",
                           "M_ADM_integrate");
  }
  {
    int cctkschedulei_tlevelarray[] = {0};
    CCTKi_ScheduleFunction((void *)CCTK_FNAME(Integrate_vol_integrand),
                           "J_ADM_integrate",
                           "diagnostics_vacuum",
                           "diagnostics_vacuum",
                           "Integrate angular momentum, output to J_ADM_VolInt",
                           "CCTK_ANALYSIS",
                           "Fortran",
                           0,  /* Number of STORAGE  groups   */
                           0,  /* Number of COMM     groups   */
                           0,  /* Number of TRIGGERS groups   */
                           0,  /* Number of SYNC     groups   */
                           1,  /* Number of Options           */
                           1,  /* Number of BEFORE  routines  */
                           1,  /* Number of AFTER   routines  */
                           0,  /* Number of WHILE   variables */
                           0,  /* Number of IF   variables */
                           cctkschedulei_tlevelarray  /* Array of timelevel data for storage groups */,
                           "GLOBAL",
                           "Ham_integrand",
                           "J_integrand");
  }
  {
    int cctkschedulei_tlevelarray[] = {0};
    CCTKi_ScheduleFunction((void *)CCTK_FNAME(Ham_constraint_integrand),
                           "Ham_integrand",
                           "diagnostics_vacuum",
                           "diagnostics_vacuum",
                           "Fill in Hamiltonian constraint volume integrand",
                           "CCTK_ANALYSIS",
                           "Fortran",
                           0,  /* Number of STORAGE  groups   */
                           0,  /* Number of COMM     groups   */
                           0,  /* Number of TRIGGERS groups   */
                           0,  /* Number of SYNC     groups   */
                           2,  /* Number of Options           */
                           1,  /* Number of BEFORE  routines  */
                           1,  /* Number of AFTER   routines  */
                           0,  /* Number of WHILE   variables */
                           0,  /* Number of IF   variables */
                           cctkschedulei_tlevelarray  /* Array of timelevel data for storage groups */,
                           "GLOBAL",
                           "loop-local",
                           "poststep",
                           "J_integrate");
  }
  {
    int cctkschedulei_tlevelarray[] = {0};
    CCTKi_ScheduleFunction((void *)CCTK_FNAME(Integrate_vol_integrand),
                           "Ham_integrate",
                           "diagnostics_vacuum",
                           "diagnostics_vacuum",
                           "Integrate Hamiltonian constraint, output to Ham_const_VolintN & Ham_const_VolintD (where N=numerator, D=denominator)",
                           "CCTK_ANALYSIS",
                           "Fortran",
                           0,  /* Number of STORAGE  groups   */
                           0,  /* Number of COMM     groups   */
                           0,  /* Number of TRIGGERS groups   */
                           0,  /* Number of SYNC     groups   */
                           1,  /* Number of Options           */
                           1,  /* Number of BEFORE  routines  */
                           1,  /* Number of AFTER   routines  */
                           0,  /* Number of WHILE   variables */
                           0,  /* Number of IF   variables */
                           cctkschedulei_tlevelarray  /* Array of timelevel data for storage groups */,
                           "GLOBAL",
                           "poststep",
                           "Ham_integrand");
  }
  {
    int cctkschedulei_tlevelarray[] = {0};
    CCTKi_ScheduleFunction((void *)CCTK_FNAME(Ham_constraint_excised_integrand),
                           "Ham_excised_integrand",
                           "diagnostics_vacuum",
                           "diagnostics_vacuum",
                           "Fill in excised Hamiltonian constraint volume integrand",
                           "CCTK_ANALYSIS",
                           "Fortran",
                           0,  /* Number of STORAGE  groups   */
                           0,  /* Number of COMM     groups   */
                           0,  /* Number of TRIGGERS groups   */
                           0,  /* Number of SYNC     groups   */
                           2,  /* Number of Options           */
                           1,  /* Number of BEFORE  routines  */
                           1,  /* Number of AFTER   routines  */
                           0,  /* Number of WHILE   variables */
                           0,  /* Number of IF   variables */
                           cctkschedulei_tlevelarray  /* Array of timelevel data for storage groups */,
                           "GLOBAL",
                           "loop-local",
                           "poststep",
                           "Ham_integrate");
  }
  {
    int cctkschedulei_tlevelarray[] = {0};
    CCTKi_ScheduleFunction((void *)CCTK_FNAME(Integrate_vol_integrand),
                           "Ham_excised_integrate",
                           "diagnostics_vacuum",
                           "diagnostics_vacuum",
                           "Integrate excised Hamiltonian constraint, output to Ham_const_excised_VolintN & Ham_const_excised_VolintD (where N=numerator, D=denominator)",
                           "CCTK_ANALYSIS",
                           "Fortran",
                           0,  /* Number of STORAGE  groups   */
                           0,  /* Number of COMM     groups   */
                           0,  /* Number of TRIGGERS groups   */
                           0,  /* Number of SYNC     groups   */
                           1,  /* Number of Options           */
                           1,  /* Number of BEFORE  routines  */
                           1,  /* Number of AFTER   routines  */
                           0,  /* Number of WHILE   variables */
                           0,  /* Number of IF   variables */
                           cctkschedulei_tlevelarray  /* Array of timelevel data for storage groups */,
                           "GLOBAL",
                           "poststep",
                           "Ham_excised_integrand");
  }
  {
    int cctkschedulei_tlevelarray[] = {0};
    CCTKi_ScheduleFunction((void *)CCTK_FNAME(mom_constraint_integrand),
                           "mom_integrand",
                           "diagnostics_vacuum",
                           "diagnostics_vacuum",
                           "Fill in momentum constraint volume integrand",
                           "CCTK_ANALYSIS",
                           "Fortran",
                           0,  /* Number of STORAGE  groups   */
                           0,  /* Number of COMM     groups   */
                           0,  /* Number of TRIGGERS groups   */
                           0,  /* Number of SYNC     groups   */
                           2,  /* Number of Options           */
                           1,  /* Number of BEFORE  routines  */
                           1,  /* Number of AFTER   routines  */
                           0,  /* Number of WHILE   variables */
                           0,  /* Number of IF   variables */
                           cctkschedulei_tlevelarray  /* Array of timelevel data for storage groups */,
                           "GLOBAL",
                           "loop-local",
                           "poststep",
                           "Ham_excised_integrate");
  }
  {
    int cctkschedulei_tlevelarray[] = {0};
    CCTKi_ScheduleFunction((void *)CCTK_FNAME(Integrate_vol_integrand),
                           "mom_integrate",
                           "diagnostics_vacuum",
                           "diagnostics_vacuum",
                           "Integrate momentum constraint, output to momx_const_VolintN,momy_const_VolintN,momz_const_VolintN,mom_const_VolintD (where N=numerator, D=denominator)",
                           "CCTK_ANALYSIS",
                           "Fortran",
                           0,  /* Number of STORAGE  groups   */
                           0,  /* Number of COMM     groups   */
                           0,  /* Number of TRIGGERS groups   */
                           0,  /* Number of SYNC     groups   */
                           1,  /* Number of Options           */
                           1,  /* Number of BEFORE  routines  */
                           1,  /* Number of AFTER   routines  */
                           0,  /* Number of WHILE   variables */
                           0,  /* Number of IF   variables */
                           cctkschedulei_tlevelarray  /* Array of timelevel data for storage groups */,
                           "GLOBAL",
                           "poststep",
                           "mom_integrand");
  }
  {
    int cctkschedulei_tlevelarray[] = {0};
    CCTKi_ScheduleFunction((void *)CCTK_FNAME(mom_constraint_excised_integrand),
                           "mom_excised_integrand",
                           "diagnostics_vacuum",
                           "diagnostics_vacuum",
                           "Fill in excised momentum constraint volume integrand",
                           "CCTK_ANALYSIS",
                           "Fortran",
                           0,  /* Number of STORAGE  groups   */
                           0,  /* Number of COMM     groups   */
                           0,  /* Number of TRIGGERS groups   */
                           0,  /* Number of SYNC     groups   */
                           2,  /* Number of Options           */
                           1,  /* Number of BEFORE  routines  */
                           1,  /* Number of AFTER   routines  */
                           0,  /* Number of WHILE   variables */
                           0,  /* Number of IF   variables */
                           cctkschedulei_tlevelarray  /* Array of timelevel data for storage groups */,
                           "GLOBAL",
                           "loop-local",
                           "poststep",
                           "mom_integrate");
  }
  {
    int cctkschedulei_tlevelarray[] = {0};
    CCTKi_ScheduleFunction((void *)CCTK_FNAME(Integrate_vol_integrand),
                           "mom_excised_integrate",
                           "diagnostics_vacuum",
                           "diagnostics_vacuum",
                           "Integrate excised momentum constraint, output to momx_const_excised_VolintN,momy_const_excised_VolintN,momz_const_excised_VolintN,mom_const_excised_VolintD (where N=numerator, D=denominator)",
                           "CCTK_ANALYSIS",
                           "Fortran",
                           0,  /* Number of STORAGE  groups   */
                           0,  /* Number of COMM     groups   */
                           0,  /* Number of TRIGGERS groups   */
                           0,  /* Number of SYNC     groups   */
                           1,  /* Number of Options           */
                           1,  /* Number of BEFORE  routines  */
                           1,  /* Number of AFTER   routines  */
                           0,  /* Number of WHILE   variables */
                           0,  /* Number of IF   variables */
                           cctkschedulei_tlevelarray  /* Array of timelevel data for storage groups */,
                           "GLOBAL",
                           "poststep",
                           "mom_excised_integrand");
  }
  {
    int cctkschedulei_tlevelarray[] = {0};
    CCTKi_ScheduleFunction((void *)CCTK_FNAME(Gam_constraint_integrand),
                           "gam_integrand",
                           "diagnostics_vacuum",
                           "diagnostics_vacuum",
                           "Fill in Gamma constraint volume integrand",
                           "CCTK_ANALYSIS",
                           "Fortran",
                           0,  /* Number of STORAGE  groups   */
                           0,  /* Number of COMM     groups   */
                           0,  /* Number of TRIGGERS groups   */
                           0,  /* Number of SYNC     groups   */
                           2,  /* Number of Options           */
                           1,  /* Number of BEFORE  routines  */
                           1,  /* Number of AFTER   routines  */
                           0,  /* Number of WHILE   variables */
                           0,  /* Number of IF   variables */
                           cctkschedulei_tlevelarray  /* Array of timelevel data for storage groups */,
                           "GLOBAL",
                           "loop-local",
                           "poststep",
                           "mom_excised_integrate");
  }
  {
    int cctkschedulei_tlevelarray[] = {0};
    CCTKi_ScheduleFunction((void *)CCTK_FNAME(Integrate_vol_integrand),
                           "Gam_integrate",
                           "diagnostics_vacuum",
                           "diagnostics_vacuum",
                           "Integrate mom constraint, output to Gamx_const_VolInt,Gamy_const_VolInt,Gamz_const_VolInt",
                           "CCTK_ANALYSIS",
                           "Fortran",
                           0,  /* Number of STORAGE  groups   */
                           0,  /* Number of COMM     groups   */
                           0,  /* Number of TRIGGERS groups   */
                           0,  /* Number of SYNC     groups   */
                           1,  /* Number of Options           */
                           1,  /* Number of BEFORE  routines  */
                           1,  /* Number of AFTER   routines  */
                           0,  /* Number of WHILE   variables */
                           0,  /* Number of IF   variables */
                           cctkschedulei_tlevelarray  /* Array of timelevel data for storage groups */,
                           "GLOBAL",
                           "poststep",
                           "gam_integrand");
  }
if (enable_M_constraint==1) {
  {
    int cctkschedulei_tlevelarray[] = {0};
    CCTKi_ScheduleFunction((void *)CCTK_FNAME(M_Ham_constraint_excised_integrand),
                           "M_Ham_excised_integrand",
                           "diagnostics_vacuum",
                           "diagnostics_vacuum",
                           "Fill in excised mass associated with Hamiltonian constraint violation volume integrand",
                           "CCTK_ANALYSIS",
                           "Fortran",
                           0,  /* Number of STORAGE  groups   */
                           0,  /* Number of COMM     groups   */
                           0,  /* Number of TRIGGERS groups   */
                           0,  /* Number of SYNC     groups   */
                           2,  /* Number of Options           */
                           1,  /* Number of BEFORE  routines  */
                           1,  /* Number of AFTER   routines  */
                           0,  /* Number of WHILE   variables */
                           0,  /* Number of IF   variables */
                           cctkschedulei_tlevelarray  /* Array of timelevel data for storage groups */,
                           "GLOBAL",
                           "loop-local",
                           "poststep",
                           "Gam_integrate");
  }
  {
    int cctkschedulei_tlevelarray[] = {0};
    CCTKi_ScheduleFunction((void *)CCTK_FNAME(Integrate_vol_integrand),
                           "M_Ham_excised_integrate",
                           "diagnostics_vacuum",
                           "diagnostics_vacuum",
                           "Integrate excised mass associated with the Hamiltonian constraint violation, output to M_constraint, M_constraint_inner",
                           "CCTK_ANALYSIS",
                           "Fortran",
                           0,  /* Number of STORAGE  groups   */
                           0,  /* Number of COMM     groups   */
                           0,  /* Number of TRIGGERS groups   */
                           0,  /* Number of SYNC     groups   */
                           1,  /* Number of Options           */
                           1,  /* Number of BEFORE  routines  */
                           1,  /* Number of AFTER   routines  */
                           0,  /* Number of WHILE   variables */
                           0,  /* Number of IF   variables */
                           cctkschedulei_tlevelarray  /* Array of timelevel data for storage groups */,
                           "GLOBAL",
                           "poststep",
                           "M_Ham_excised_integrand");
  }
}
if (enable_Jz_constraint==1) {
  {
    int cctkschedulei_tlevelarray[] = {0};
    CCTKi_ScheduleFunction((void *)CCTK_FNAME(Jz_mom_constraint_excised_integrand),
                           "Jz_mom_excised_integrand",
                           "diagnostics_vacuum",
                           "diagnostics_vacuum",
                           "Fill in excised Jz associated with momentum constraint violation volume integrand",
                           "CCTK_ANALYSIS",
                           "Fortran",
                           0,  /* Number of STORAGE  groups   */
                           0,  /* Number of COMM     groups   */
                           0,  /* Number of TRIGGERS groups   */
                           0,  /* Number of SYNC     groups   */
                           2,  /* Number of Options           */
                           1,  /* Number of BEFORE  routines  */
                           2,  /* Number of AFTER   routines  */
                           0,  /* Number of WHILE   variables */
                           0,  /* Number of IF   variables */
                           cctkschedulei_tlevelarray  /* Array of timelevel data for storage groups */,
                           "GLOBAL",
                           "loop-local",
                           "poststep",
                           "Gam_integrate",
                           "M_Ham_excised_integrate");
  }
  {
    int cctkschedulei_tlevelarray[] = {0};
    CCTKi_ScheduleFunction((void *)CCTK_FNAME(Integrate_vol_integrand),
                           "Jz_mom_excised_integrate",
                           "diagnostics_vacuum",
                           "diagnostics_vacuum",
                           "Integrate excised Jz associated with momentum constraint violation, output to Jz_constraint, Jz_constraint_inner",
                           "CCTK_ANALYSIS",
                           "Fortran",
                           0,  /* Number of STORAGE  groups   */
                           0,  /* Number of COMM     groups   */
                           0,  /* Number of TRIGGERS groups   */
                           0,  /* Number of SYNC     groups   */
                           1,  /* Number of Options           */
                           1,  /* Number of BEFORE  routines  */
                           1,  /* Number of AFTER   routines  */
                           0,  /* Number of WHILE   variables */
                           0,  /* Number of IF   variables */
                           cctkschedulei_tlevelarray  /* Array of timelevel data for storage groups */,
                           "GLOBAL",
                           "poststep",
                           "Jz_mom_excised_integrand");
  }
}
if (enable_Jz_constraint==1 && enable_P_constraint==1) {
  {
    int cctkschedulei_tlevelarray[] = {0};
    CCTKi_ScheduleFunction((void *)CCTK_FNAME(P_mom_constraint_excised_integrand),
                           "P_mom_excised_integrand",
                           "diagnostics_vacuum",
                           "diagnostics_vacuum",
                           "Fill in excised P associated with momentum constraint violation volume integrand",
                           "CCTK_ANALYSIS",
                           "Fortran",
                           0,  /* Number of STORAGE  groups   */
                           0,  /* Number of COMM     groups   */
                           0,  /* Number of TRIGGERS groups   */
                           0,  /* Number of SYNC     groups   */
                           2,  /* Number of Options           */
                           1,  /* Number of BEFORE  routines  */
                           3,  /* Number of AFTER   routines  */
                           0,  /* Number of WHILE   variables */
                           0,  /* Number of IF   variables */
                           cctkschedulei_tlevelarray  /* Array of timelevel data for storage groups */,
                           "GLOBAL",
                           "loop-local",
                           "poststep",
                           "Gam_integrate",
                           "M_Ham_excised_integrate",
                           "Jz_mom_excised_integrate");
  }
  {
    int cctkschedulei_tlevelarray[] = {0};
    CCTKi_ScheduleFunction((void *)CCTK_FNAME(Integrate_vol_integrand),
                           "P_mom_excised_integrate",
                           "diagnostics_vacuum",
                           "diagnostics_vacuum",
                           "Integrate excised P associated with momentum constraint violation, output to P_constraint, P_constraint_inner",
                           "CCTK_ANALYSIS",
                           "Fortran",
                           0,  /* Number of STORAGE  groups   */
                           0,  /* Number of COMM     groups   */
                           0,  /* Number of TRIGGERS groups   */
                           0,  /* Number of SYNC     groups   */
                           1,  /* Number of Options           */
                           1,  /* Number of BEFORE  routines  */
                           1,  /* Number of AFTER   routines  */
                           0,  /* Number of WHILE   variables */
                           0,  /* Number of IF   variables */
                           cctkschedulei_tlevelarray  /* Array of timelevel data for storage groups */,
                           "GLOBAL",
                           "poststep",
                           "P_mom_excised_integrand");
  }
}
if (enable_Jz_constraint==0 && enable_P_constraint==1) {
  {
    int cctkschedulei_tlevelarray[] = {0};
    CCTKi_ScheduleFunction((void *)CCTK_FNAME(P_mom_constraint_excised_integrand),
                           "P_mom_excised_integrand",
                           "diagnostics_vacuum",
                           "diagnostics_vacuum",
                           "Fill in excised P associated with momentum constraint violation volume integrand",
                           "CCTK_ANALYSIS",
                           "Fortran",
                           0,  /* Number of STORAGE  groups   */
                           0,  /* Number of COMM     groups   */
                           0,  /* Number of TRIGGERS groups   */
                           0,  /* Number of SYNC     groups   */
                           2,  /* Number of Options           */
                           1,  /* Number of BEFORE  routines  */
                           2,  /* Number of AFTER   routines  */
                           0,  /* Number of WHILE   variables */
                           0,  /* Number of IF   variables */
                           cctkschedulei_tlevelarray  /* Array of timelevel data for storage groups */,
                           "GLOBAL",
                           "loop-local",
                           "poststep",
                           "Gam_integrate",
                           "M_Ham_excised_integrate");
  }
  {
    int cctkschedulei_tlevelarray[] = {0};
    CCTKi_ScheduleFunction((void *)CCTK_FNAME(Integrate_vol_integrand),
                           "P_mom_excised_integrate",
                           "diagnostics_vacuum",
                           "diagnostics_vacuum",
                           "Integrate excised P associated with momentum constraint violation, output to P_constraint, P_constraint_inner",
                           "CCTK_ANALYSIS",
                           "Fortran",
                           0,  /* Number of STORAGE  groups   */
                           0,  /* Number of COMM     groups   */
                           0,  /* Number of TRIGGERS groups   */
                           0,  /* Number of SYNC     groups   */
                           1,  /* Number of Options           */
                           1,  /* Number of BEFORE  routines  */
                           1,  /* Number of AFTER   routines  */
                           0,  /* Number of WHILE   variables */
                           0,  /* Number of IF   variables */
                           cctkschedulei_tlevelarray  /* Array of timelevel data for storage groups */,
                           "GLOBAL",
                           "poststep",
                           "P_mom_excised_integrand");
  }
}
}

/*@@
  @routine    CCTKi_BindingsParameterRecovery_diagnostics_vacuum
  @author     Automatically generated by CreateScheduleBindings.pl
  @desc
              Creates the parameter recovery bindings for thorn diagnostics_vacuum
  @enddesc
@@*/

int CCTKi_BindingsParameterRecovery_diagnostics_vacuum(void);
int CCTKi_BindingsParameterRecovery_diagnostics_vacuum(void)
{
  /* this thorn doesn't define any parameter recovery routines */
  return (0);
}

