/*@@
   @file       Scheduleahfinderdirect.c
   @author     Automatically generated by CreateScheduleBindings.pl
   @desc
               Creates the schedule and parameter recovery bindings 
               for thorn ahfinderdirect
   @enddesc
@@*/

#define THORN_IS_ahfinderdirect

#include "cctk.h"
#include "cctk_Parameters.h"
#include "cctki_ScheduleBindings.h"

/* prototypes for schedule bindings functions to be registered */
/* Note that this is a cheat, we just need a function pointer. */
extern int AHFinderDirect_setup(void);
extern int AHFinderDirect_recover(void);
extern int AHFinderDirect_find_horizons(void);
extern int AHFinderDirect_find_horizons(void);
extern int AHFinderDirect_find_horizons(void);
extern int AHFinderDirect_find_horizons(void);
extern int AHFinderDirect_import_mask(void);
extern int AHFinderDirect_store(void);
extern int AHFinderDirect_save(void);
extern int AHFinderDirect_announce(void);
extern int AHFinderDirect_maybe_do_masks(void);
extern int AHFinderDirect_import_mask(void);
extern int AHFinderDirect_store(void);
extern int AHFinderDirect_save(void);
extern int AHFinderDirect_announce(void);
extern int AHFinderDirect_maybe_do_masks(void);
extern int AHFinderDirect_import_mask(void);
extern int AHFinderDirect_store(void);
extern int AHFinderDirect_save(void);
extern int AHFinderDirect_announce(void);
extern int AHFinderDirect_maybe_do_masks(void);
extern int AHFinderDirect_import_mask(void);
extern int AHFinderDirect_store(void);
extern int AHFinderDirect_save(void);
extern int AHFinderDirect_announce(void);
extern int AHFinderDirect_maybe_do_masks(void);
extern int AHFinderDirect_maybe_do_masks(void);
extern int AHFinderDirect_maybe_do_masks(void);


void CCTKi_BindingsSchedule_ahfinderdirect(void);
void CCTKi_BindingsSchedule_ahfinderdirect(void)
{
  DECLARE_CCTK_PARAMETERS
  CCTKi_ScheduleGroupStorage("AHFinderDirect::ah_radius",1);
  CCTKi_ScheduleGroupStorage("AHFinderDirect::ah_origin",1);
  CCTKi_ScheduleGroupStorage("AHFinderDirect::ah_centroid",1);
  CCTKi_ScheduleGroupStorage("AHFinderDirect::ah_flags",1);
  CCTKi_ScheduleGroupStorage("ahfinderdirect::ahmask",3);
  {
    int cctkschedulei_tlevelarray[] = {0};
    CCTKi_ScheduleFunction((void *)AHFinderDirect_setup,
                           "AHFinderDirect_setup",
                           "ahfinderdirect",
                           "AHFinderDirect",
                           "setup data structures",
                           "CCTK_BASEGRID",
                           "C",
                           0,  /* Number of STORAGE  groups   */
                           0,  /* Number of COMM     groups   */
                           0,  /* Number of TRIGGERS groups   */
                           0,  /* Number of SYNC     groups   */
                           1,  /* Number of Options           */
                           0,  /* Number of BEFORE  routines  */
                           1,  /* Number of AFTER   routines  */
                           0,  /* Number of WHILE   variables */
                           0,  /* Number of IF   variables */
                           cctkschedulei_tlevelarray  /* Array of timelevel data for storage groups */,
                           "global",
                           "SpatialCoordinates");
  }
  {
    int cctkschedulei_tlevelarray[] = {0};
    CCTKi_ScheduleFunction((void *)AHFinderDirect_recover,
                           "AHFinderDirect_recover",
                           "ahfinderdirect",
                           "AHFinderDirect",
                           "import horizon data from Cactus variables",
                           "CCTK_POST_RECOVER_VARIABLES",
                           "C",
                           0,  /* Number of STORAGE  groups   */
                           0,  /* Number of COMM     groups   */
                           0,  /* Number of TRIGGERS groups   */
                           0,  /* Number of SYNC     groups   */
                           1,  /* Number of Options           */
                           0,  /* Number of BEFORE  routines  */
                           0,  /* Number of AFTER   routines  */
                           0,  /* Number of WHILE   variables */
                           0,  /* Number of IF   variables */
                           cctkschedulei_tlevelarray  /* Array of timelevel data for storage groups */,
                           "global");
  }
if (run_at_CCTK_ANALYSIS != 0)
	{
  {
    int cctkschedulei_tlevelarray[] = {0};
    CCTKi_ScheduleFunction((void *)AHFinderDirect_find_horizons,
                           "AHFinderDirect_find_horizons",
                           "ahfinderdirect",
                           "AHFinderDirect",
                           "find apparent horizon(s) after this time step",
                           "CCTK_ANALYSIS",
                           "C",
                           0,  /* Number of STORAGE  groups   */
                           0,  /* Number of COMM     groups   */
                           0,  /* Number of TRIGGERS groups   */
                           0,  /* Number of SYNC     groups   */
                           1,  /* Number of Options           */
                           0,  /* Number of BEFORE  routines  */
                           0,  /* Number of AFTER   routines  */
                           0,  /* Number of WHILE   variables */
                           0,  /* Number of IF   variables */
                           cctkschedulei_tlevelarray  /* Array of timelevel data for storage groups */,
                           "global");
  }
	}
if (run_at_CCTK_POSTSTEP != 0)
	{
  {
    int cctkschedulei_tlevelarray[] = {0};
    CCTKi_ScheduleFunction((void *)AHFinderDirect_find_horizons,
                           "AHFinderDirect_find_horizons",
                           "ahfinderdirect",
                           "AHFinderDirect",
                           "find apparent horizon(s) after this time step",
                           "CCTK_POSTSTEP",
                           "C",
                           0,  /* Number of STORAGE  groups   */
                           0,  /* Number of COMM     groups   */
                           0,  /* Number of TRIGGERS groups   */
                           0,  /* Number of SYNC     groups   */
                           1,  /* Number of Options           */
                           0,  /* Number of BEFORE  routines  */
                           0,  /* Number of AFTER   routines  */
                           0,  /* Number of WHILE   variables */
                           0,  /* Number of IF   variables */
                           cctkschedulei_tlevelarray  /* Array of timelevel data for storage groups */,
                           "global");
  }
	}
if (run_at_CCTK_POSTINITIAL != 0)
	{
  {
    int cctkschedulei_tlevelarray[] = {0};
    CCTKi_ScheduleFunction((void *)AHFinderDirect_find_horizons,
                           "AHFinderDirect_find_horizons",
                           "ahfinderdirect",
                           "AHFinderDirect",
                           "find apparent horizon(s) after this time step",
                           "CCTK_POSTINITIAL",
                           "C",
                           0,  /* Number of STORAGE  groups   */
                           0,  /* Number of COMM     groups   */
                           0,  /* Number of TRIGGERS groups   */
                           0,  /* Number of SYNC     groups   */
                           1,  /* Number of Options           */
                           0,  /* Number of BEFORE  routines  */
                           0,  /* Number of AFTER   routines  */
                           0,  /* Number of WHILE   variables */
                           0,  /* Number of IF   variables */
                           cctkschedulei_tlevelarray  /* Array of timelevel data for storage groups */,
                           "global");
  }
	}
if (run_at_CCTK_POST_RECOVER_VARIABLES != 0)
	{
  {
    int cctkschedulei_tlevelarray[] = {0};
    CCTKi_ScheduleFunction((void *)AHFinderDirect_find_horizons,
                           "AHFinderDirect_find_horizons",
                           "ahfinderdirect",
                           "AHFinderDirect",
                           "find apparent horizon(s) after this time step",
                           "CCTK_POST_RECOVER_VARIABLES",
                           "C",
                           0,  /* Number of STORAGE  groups   */
                           0,  /* Number of COMM     groups   */
                           0,  /* Number of TRIGGERS groups   */
                           0,  /* Number of SYNC     groups   */
                           1,  /* Number of Options           */
                           0,  /* Number of BEFORE  routines  */
                           0,  /* Number of AFTER   routines  */
                           0,  /* Number of WHILE   variables */
                           0,  /* Number of IF   variables */
                           cctkschedulei_tlevelarray  /* Array of timelevel data for storage groups */,
                           "global");
  }
	}
if (run_at_CCTK_ANALYSIS != 0)
	{
  {
    int cctkschedulei_tlevelarray[] = {0};
    CCTKi_ScheduleFunction((void *)AHFinderDirect_import_mask,
                           "AHFinderDirect_import_mask",
                           "ahfinderdirect",
                           "AHFinderDirect",
                           "import the excision mask",
                           "CCTK_ANALYSIS",
                           "C",
                           0,  /* Number of STORAGE  groups   */
                           0,  /* Number of COMM     groups   */
                           0,  /* Number of TRIGGERS groups   */
                           0,  /* Number of SYNC     groups   */
                           2,  /* Number of Options           */
                           1,  /* Number of BEFORE  routines  */
                           0,  /* Number of AFTER   routines  */
                           0,  /* Number of WHILE   variables */
                           0,  /* Number of IF   variables */
                           cctkschedulei_tlevelarray  /* Array of timelevel data for storage groups */,
                           "global",
                           "loop-local",
                           "AHFinderDirect_find_horizons");
  }
  {
    int cctkschedulei_tlevelarray[] = {0};
    CCTKi_ScheduleFunction((void *)AHFinderDirect_store,
                           "AHFinderDirect_store",
                           "ahfinderdirect",
                           "AHFinderDirect",
                           "store apparent horizon(s) into spherical surface(s)",
                           "CCTK_ANALYSIS",
                           "C",
                           0,  /* Number of STORAGE  groups   */
                           0,  /* Number of COMM     groups   */
                           0,  /* Number of TRIGGERS groups   */
                           0,  /* Number of SYNC     groups   */
                           1,  /* Number of Options           */
                           1,  /* Number of BEFORE  routines  */
                           1,  /* Number of AFTER   routines  */
                           0,  /* Number of WHILE   variables */
                           0,  /* Number of IF   variables */
                           cctkschedulei_tlevelarray  /* Array of timelevel data for storage groups */,
                           "global",
                           "SphericalSurface_HasBeenSet",
                           "AHFinderDirect_find_horizons");
  }
  {
    int cctkschedulei_tlevelarray[] = {0};
    CCTKi_ScheduleFunction((void *)AHFinderDirect_save,
                           "AHFinderDirect_save",
                           "ahfinderdirect",
                           "AHFinderDirect",
                           "save apparent horizon(s) into Cactus variables",
                           "CCTK_ANALYSIS",
                           "C",
                           0,  /* Number of STORAGE  groups   */
                           0,  /* Number of COMM     groups   */
                           0,  /* Number of TRIGGERS groups   */
                           0,  /* Number of SYNC     groups   */
                           1,  /* Number of Options           */
                           0,  /* Number of BEFORE  routines  */
                           1,  /* Number of AFTER   routines  */
                           0,  /* Number of WHILE   variables */
                           0,  /* Number of IF   variables */
                           cctkschedulei_tlevelarray  /* Array of timelevel data for storage groups */,
                           "global",
                           "AHFinderDirect_find_horizons");
  }
	if (which_horizon_to_announce_centroid != 0)
		{
  {
    int cctkschedulei_tlevelarray[] = {0};
    CCTKi_ScheduleFunction((void *)AHFinderDirect_announce,
                           "AHFinderDirect_announce",
                           "ahfinderdirect",
                           "AHFinderDirect",
                           "announce horizon position(s) to other thorns",
                           "CCTK_ANALYSIS",
                           "C",
                           0,  /* Number of STORAGE  groups   */
                           0,  /* Number of COMM     groups   */
                           0,  /* Number of TRIGGERS groups   */
                           0,  /* Number of SYNC     groups   */
                           1,  /* Number of Options           */
                           1,  /* Number of BEFORE  routines  */
                           1,  /* Number of AFTER   routines  */
                           0,  /* Number of WHILE   variables */
                           0,  /* Number of IF   variables */
                           cctkschedulei_tlevelarray  /* Array of timelevel data for storage groups */,
                           "global",
                           "DriftCorrect",
                           "AHFinderDirect_find_horizons");
  }
		}
  {
    int cctkschedulei_tlevelarray[] = {0};
    CCTKi_ScheduleFunction((void *)AHFinderDirect_maybe_do_masks,
                           "AHFinderDirect_maybe_do_masks",
                           "ahfinderdirect",
                           "AHFinderDirect",
                           "set mask(s) based on apparent horizon position(s)",
                           "CCTK_ANALYSIS",
                           "C",
                           0,  /* Number of STORAGE  groups   */
                           0,  /* Number of COMM     groups   */
                           0,  /* Number of TRIGGERS groups   */
                           0,  /* Number of SYNC     groups   */
                           2,  /* Number of Options           */
                           0,  /* Number of BEFORE  routines  */
                           1,  /* Number of AFTER   routines  */
                           0,  /* Number of WHILE   variables */
                           0,  /* Number of IF   variables */
                           cctkschedulei_tlevelarray  /* Array of timelevel data for storage groups */,
                           "global",
                           "loop-local",
                           "AHFinderDirect_find_horizons");
  }
	}
if (run_at_CCTK_POSTSTEP != 0)
	{
  {
    int cctkschedulei_tlevelarray[] = {0};
    CCTKi_ScheduleFunction((void *)AHFinderDirect_import_mask,
                           "AHFinderDirect_import_mask",
                           "ahfinderdirect",
                           "AHFinderDirect",
                           "import the excision mask",
                           "CCTK_POSTSTEP",
                           "C",
                           0,  /* Number of STORAGE  groups   */
                           0,  /* Number of COMM     groups   */
                           0,  /* Number of TRIGGERS groups   */
                           0,  /* Number of SYNC     groups   */
                           2,  /* Number of Options           */
                           1,  /* Number of BEFORE  routines  */
                           0,  /* Number of AFTER   routines  */
                           0,  /* Number of WHILE   variables */
                           0,  /* Number of IF   variables */
                           cctkschedulei_tlevelarray  /* Array of timelevel data for storage groups */,
                           "global",
                           "loop-local",
                           "AHFinderDirect_find_horizons");
  }
  {
    int cctkschedulei_tlevelarray[] = {0};
    CCTKi_ScheduleFunction((void *)AHFinderDirect_store,
                           "AHFinderDirect_store",
                           "ahfinderdirect",
                           "AHFinderDirect",
                           "store apparent horizon(s) into spherical surface(s)",
                           "CCTK_POSTSTEP",
                           "C",
                           0,  /* Number of STORAGE  groups   */
                           0,  /* Number of COMM     groups   */
                           0,  /* Number of TRIGGERS groups   */
                           0,  /* Number of SYNC     groups   */
                           1,  /* Number of Options           */
                           1,  /* Number of BEFORE  routines  */
                           1,  /* Number of AFTER   routines  */
                           0,  /* Number of WHILE   variables */
                           0,  /* Number of IF   variables */
                           cctkschedulei_tlevelarray  /* Array of timelevel data for storage groups */,
                           "global",
                           "SphericalSurface_HasBeenSet",
                           "AHFinderDirect_find_horizons");
  }
  {
    int cctkschedulei_tlevelarray[] = {0};
    CCTKi_ScheduleFunction((void *)AHFinderDirect_save,
                           "AHFinderDirect_save",
                           "ahfinderdirect",
                           "AHFinderDirect",
                           "save apparent horizon(s) into Cactus variables",
                           "CCTK_POSTSTEP",
                           "C",
                           0,  /* Number of STORAGE  groups   */
                           0,  /* Number of COMM     groups   */
                           0,  /* Number of TRIGGERS groups   */
                           0,  /* Number of SYNC     groups   */
                           1,  /* Number of Options           */
                           0,  /* Number of BEFORE  routines  */
                           1,  /* Number of AFTER   routines  */
                           0,  /* Number of WHILE   variables */
                           0,  /* Number of IF   variables */
                           cctkschedulei_tlevelarray  /* Array of timelevel data for storage groups */,
                           "global",
                           "AHFinderDirect_find_horizons");
  }
	if (which_horizon_to_announce_centroid != 0)
		{
  {
    int cctkschedulei_tlevelarray[] = {0};
    CCTKi_ScheduleFunction((void *)AHFinderDirect_announce,
                           "AHFinderDirect_announce",
                           "ahfinderdirect",
                           "AHFinderDirect",
                           "announce horizon position(s) to other thorns",
                           "CCTK_POSTSTEP",
                           "C",
                           0,  /* Number of STORAGE  groups   */
                           0,  /* Number of COMM     groups   */
                           0,  /* Number of TRIGGERS groups   */
                           0,  /* Number of SYNC     groups   */
                           1,  /* Number of Options           */
                           1,  /* Number of BEFORE  routines  */
                           1,  /* Number of AFTER   routines  */
                           0,  /* Number of WHILE   variables */
                           0,  /* Number of IF   variables */
                           cctkschedulei_tlevelarray  /* Array of timelevel data for storage groups */,
                           "global",
                           "DriftCorrect",
                           "AHFinderDirect_find_horizons");
  }
		}
  {
    int cctkschedulei_tlevelarray[] = {0};
    CCTKi_ScheduleFunction((void *)AHFinderDirect_maybe_do_masks,
                           "AHFinderDirect_maybe_do_masks",
                           "ahfinderdirect",
                           "AHFinderDirect",
                           "set mask(s) based on apparent horizon position(s)",
                           "CCTK_POSTSTEP",
                           "C",
                           0,  /* Number of STORAGE  groups   */
                           0,  /* Number of COMM     groups   */
                           0,  /* Number of TRIGGERS groups   */
                           0,  /* Number of SYNC     groups   */
                           2,  /* Number of Options           */
                           0,  /* Number of BEFORE  routines  */
                           1,  /* Number of AFTER   routines  */
                           0,  /* Number of WHILE   variables */
                           0,  /* Number of IF   variables */
                           cctkschedulei_tlevelarray  /* Array of timelevel data for storage groups */,
                           "global",
                           "loop-local",
                           "AHFinderDirect_find_horizons");
  }
	}
if (run_at_CCTK_POSTINITIAL != 0)
	{
  {
    int cctkschedulei_tlevelarray[] = {0};
    CCTKi_ScheduleFunction((void *)AHFinderDirect_import_mask,
                           "AHFinderDirect_import_mask",
                           "ahfinderdirect",
                           "AHFinderDirect",
                           "import the excision mask",
                           "CCTK_POSTINITIAL",
                           "C",
                           0,  /* Number of STORAGE  groups   */
                           0,  /* Number of COMM     groups   */
                           0,  /* Number of TRIGGERS groups   */
                           0,  /* Number of SYNC     groups   */
                           2,  /* Number of Options           */
                           1,  /* Number of BEFORE  routines  */
                           0,  /* Number of AFTER   routines  */
                           0,  /* Number of WHILE   variables */
                           0,  /* Number of IF   variables */
                           cctkschedulei_tlevelarray  /* Array of timelevel data for storage groups */,
                           "global",
                           "loop-local",
                           "AHFinderDirect_find_horizons");
  }
  {
    int cctkschedulei_tlevelarray[] = {0};
    CCTKi_ScheduleFunction((void *)AHFinderDirect_store,
                           "AHFinderDirect_store",
                           "ahfinderdirect",
                           "AHFinderDirect",
                           "store apparent horizon(s) into spherical surface(s)",
                           "CCTK_POSTINITIAL",
                           "C",
                           0,  /* Number of STORAGE  groups   */
                           0,  /* Number of COMM     groups   */
                           0,  /* Number of TRIGGERS groups   */
                           0,  /* Number of SYNC     groups   */
                           1,  /* Number of Options           */
                           1,  /* Number of BEFORE  routines  */
                           1,  /* Number of AFTER   routines  */
                           0,  /* Number of WHILE   variables */
                           0,  /* Number of IF   variables */
                           cctkschedulei_tlevelarray  /* Array of timelevel data for storage groups */,
                           "global",
                           "SphericalSurface_HasBeenSet",
                           "AHFinderDirect_find_horizons");
  }
  {
    int cctkschedulei_tlevelarray[] = {0};
    CCTKi_ScheduleFunction((void *)AHFinderDirect_save,
                           "AHFinderDirect_save",
                           "ahfinderdirect",
                           "AHFinderDirect",
                           "save apparent horizon(s) into Cactus variables",
                           "CCTK_POSTINITIAL",
                           "C",
                           0,  /* Number of STORAGE  groups   */
                           0,  /* Number of COMM     groups   */
                           0,  /* Number of TRIGGERS groups   */
                           0,  /* Number of SYNC     groups   */
                           1,  /* Number of Options           */
                           0,  /* Number of BEFORE  routines  */
                           1,  /* Number of AFTER   routines  */
                           0,  /* Number of WHILE   variables */
                           0,  /* Number of IF   variables */
                           cctkschedulei_tlevelarray  /* Array of timelevel data for storage groups */,
                           "global",
                           "AHFinderDirect_find_horizons");
  }
	if (which_horizon_to_announce_centroid != 0)
		{
  {
    int cctkschedulei_tlevelarray[] = {0};
    CCTKi_ScheduleFunction((void *)AHFinderDirect_announce,
                           "AHFinderDirect_announce",
                           "ahfinderdirect",
                           "AHFinderDirect",
                           "announce horizon position(s) to other thorns",
                           "CCTK_POSTINITIAL",
                           "C",
                           0,  /* Number of STORAGE  groups   */
                           0,  /* Number of COMM     groups   */
                           0,  /* Number of TRIGGERS groups   */
                           0,  /* Number of SYNC     groups   */
                           1,  /* Number of Options           */
                           1,  /* Number of BEFORE  routines  */
                           1,  /* Number of AFTER   routines  */
                           0,  /* Number of WHILE   variables */
                           0,  /* Number of IF   variables */
                           cctkschedulei_tlevelarray  /* Array of timelevel data for storage groups */,
                           "global",
                           "DriftCorrect",
                           "AHFinderDirect_find_horizons");
  }
		}
  {
    int cctkschedulei_tlevelarray[] = {0};
    CCTKi_ScheduleFunction((void *)AHFinderDirect_maybe_do_masks,
                           "AHFinderDirect_maybe_do_masks",
                           "ahfinderdirect",
                           "AHFinderDirect",
                           "set mask(s) based on apparent horizon position(s)",
                           "CCTK_POSTINITIAL",
                           "C",
                           0,  /* Number of STORAGE  groups   */
                           0,  /* Number of COMM     groups   */
                           0,  /* Number of TRIGGERS groups   */
                           0,  /* Number of SYNC     groups   */
                           2,  /* Number of Options           */
                           0,  /* Number of BEFORE  routines  */
                           1,  /* Number of AFTER   routines  */
                           0,  /* Number of WHILE   variables */
                           0,  /* Number of IF   variables */
                           cctkschedulei_tlevelarray  /* Array of timelevel data for storage groups */,
                           "global",
                           "loop-local",
                           "AHFinderDirect_find_horizons");
  }
	}
if (run_at_CCTK_POST_RECOVER_VARIABLES != 0)
	{
  {
    int cctkschedulei_tlevelarray[] = {0};
    CCTKi_ScheduleFunction((void *)AHFinderDirect_import_mask,
                           "AHFinderDirect_import_mask",
                           "ahfinderdirect",
                           "AHFinderDirect",
                           "import the excision mask",
                           "CCTK_POST_RECOVER_VARIABLES",
                           "C",
                           0,  /* Number of STORAGE  groups   */
                           0,  /* Number of COMM     groups   */
                           0,  /* Number of TRIGGERS groups   */
                           0,  /* Number of SYNC     groups   */
                           2,  /* Number of Options           */
                           1,  /* Number of BEFORE  routines  */
                           0,  /* Number of AFTER   routines  */
                           0,  /* Number of WHILE   variables */
                           0,  /* Number of IF   variables */
                           cctkschedulei_tlevelarray  /* Array of timelevel data for storage groups */,
                           "global",
                           "loop-local",
                           "AHFinderDirect_find_horizons");
  }
  {
    int cctkschedulei_tlevelarray[] = {0};
    CCTKi_ScheduleFunction((void *)AHFinderDirect_store,
                           "AHFinderDirect_store",
                           "ahfinderdirect",
                           "AHFinderDirect",
                           "store apparent horizon(s) into spherical surface(s)",
                           "CCTK_POST_RECOVER_VARIABLES",
                           "C",
                           0,  /* Number of STORAGE  groups   */
                           0,  /* Number of COMM     groups   */
                           0,  /* Number of TRIGGERS groups   */
                           0,  /* Number of SYNC     groups   */
                           1,  /* Number of Options           */
                           1,  /* Number of BEFORE  routines  */
                           1,  /* Number of AFTER   routines  */
                           0,  /* Number of WHILE   variables */
                           0,  /* Number of IF   variables */
                           cctkschedulei_tlevelarray  /* Array of timelevel data for storage groups */,
                           "global",
                           "SphericalSurface_HasBeenSet",
                           "AHFinderDirect_find_horizons");
  }
  {
    int cctkschedulei_tlevelarray[] = {0};
    CCTKi_ScheduleFunction((void *)AHFinderDirect_save,
                           "AHFinderDirect_save",
                           "ahfinderdirect",
                           "AHFinderDirect",
                           "save apparent horizon(s) into Cactus variables",
                           "CCTK_POST_RECOVER_VARIABLES",
                           "C",
                           0,  /* Number of STORAGE  groups   */
                           0,  /* Number of COMM     groups   */
                           0,  /* Number of TRIGGERS groups   */
                           0,  /* Number of SYNC     groups   */
                           1,  /* Number of Options           */
                           0,  /* Number of BEFORE  routines  */
                           1,  /* Number of AFTER   routines  */
                           0,  /* Number of WHILE   variables */
                           0,  /* Number of IF   variables */
                           cctkschedulei_tlevelarray  /* Array of timelevel data for storage groups */,
                           "global",
                           "AHFinderDirect_find_horizons");
  }
	if (which_horizon_to_announce_centroid != 0)
		{
  {
    int cctkschedulei_tlevelarray[] = {0};
    CCTKi_ScheduleFunction((void *)AHFinderDirect_announce,
                           "AHFinderDirect_announce",
                           "ahfinderdirect",
                           "AHFinderDirect",
                           "announce horizon position(s) to other thorns",
                           "CCTK_POST_RECOVER_VARIABLES",
                           "C",
                           0,  /* Number of STORAGE  groups   */
                           0,  /* Number of COMM     groups   */
                           0,  /* Number of TRIGGERS groups   */
                           0,  /* Number of SYNC     groups   */
                           1,  /* Number of Options           */
                           1,  /* Number of BEFORE  routines  */
                           1,  /* Number of AFTER   routines  */
                           0,  /* Number of WHILE   variables */
                           0,  /* Number of IF   variables */
                           cctkschedulei_tlevelarray  /* Array of timelevel data for storage groups */,
                           "global",
                           "DriftCorrect",
                           "AHFinderDirect_find_horizons");
  }
		}
  {
    int cctkschedulei_tlevelarray[] = {0};
    CCTKi_ScheduleFunction((void *)AHFinderDirect_maybe_do_masks,
                           "AHFinderDirect_maybe_do_masks",
                           "ahfinderdirect",
                           "AHFinderDirect",
                           "set mask(s) based on apparent horizon position(s)",
                           "CCTK_POST_RECOVER_VARIABLES",
                           "C",
                           0,  /* Number of STORAGE  groups   */
                           0,  /* Number of COMM     groups   */
                           0,  /* Number of TRIGGERS groups   */
                           0,  /* Number of SYNC     groups   */
                           2,  /* Number of Options           */
                           0,  /* Number of BEFORE  routines  */
                           1,  /* Number of AFTER   routines  */
                           0,  /* Number of WHILE   variables */
                           0,  /* Number of IF   variables */
                           cctkschedulei_tlevelarray  /* Array of timelevel data for storage groups */,
                           "global",
                           "loop-local",
                           "AHFinderDirect_find_horizons");
  }
	}
  {
    int cctkschedulei_tlevelarray[] = {0};
    CCTKi_ScheduleFunction((void *)AHFinderDirect_maybe_do_masks,
                           "AHFinderDirect_maybe_do_masks",
                           "ahfinderdirect",
                           "AHFinderDirect",
                           "set mask(s) based on apparent horizon position(s)",
                           "CCTK_POSTREGRIDINITIAL",
                           "C",
                           0,  /* Number of STORAGE  groups   */
                           0,  /* Number of COMM     groups   */
                           0,  /* Number of TRIGGERS groups   */
                           0,  /* Number of SYNC     groups   */
                           2,  /* Number of Options           */
                           0,  /* Number of BEFORE  routines  */
                           2,  /* Number of AFTER   routines  */
                           0,  /* Number of WHILE   variables */
                           0,  /* Number of IF   variables */
                           cctkschedulei_tlevelarray  /* Array of timelevel data for storage groups */,
                           "global",
                           "loop-local",
                           "MaskOne",
                           "MaskZero");
  }
  {
    int cctkschedulei_tlevelarray[] = {0};
    CCTKi_ScheduleFunction((void *)AHFinderDirect_maybe_do_masks,
                           "AHFinderDirect_maybe_do_masks",
                           "ahfinderdirect",
                           "AHFinderDirect",
                           "set mask(s) based on apparent horizon position(s)",
                           "CCTK_POSTREGRID",
                           "C",
                           0,  /* Number of STORAGE  groups   */
                           0,  /* Number of COMM     groups   */
                           0,  /* Number of TRIGGERS groups   */
                           0,  /* Number of SYNC     groups   */
                           2,  /* Number of Options           */
                           0,  /* Number of BEFORE  routines  */
                           2,  /* Number of AFTER   routines  */
                           0,  /* Number of WHILE   variables */
                           0,  /* Number of IF   variables */
                           cctkschedulei_tlevelarray  /* Array of timelevel data for storage groups */,
                           "global",
                           "loop-local",
                           "MaskOne",
                           "MaskZero");
  }
}

/*@@
  @routine    CCTKi_BindingsParameterRecovery_ahfinderdirect
  @author     Automatically generated by CreateScheduleBindings.pl
  @desc
              Creates the parameter recovery bindings for thorn ahfinderdirect
  @enddesc
@@*/

int CCTKi_BindingsParameterRecovery_ahfinderdirect(void);
int CCTKi_BindingsParameterRecovery_ahfinderdirect(void)
{
  /* this thorn doesn't define any parameter recovery routines */
  return (0);
}

