/*@@
   @file       ScheduleCarpetSlab.c
   @author     Automatically generated by CreateScheduleBindings.pl
   @desc
               Creates the schedule and parameter recovery bindings 
               for thorn CarpetSlab
   @enddesc
@@*/

#define THORN_IS_CarpetSlab

#include "cctk.h"
#include "cctk_Parameters.h"
#include "cctki_ScheduleBindings.h"

/* prototypes for schedule bindings functions to be registered */
/* Note that this is a cheat, we just need a function pointer. */


void CCTKi_BindingsSchedule_CarpetSlab(void);
void CCTKi_BindingsSchedule_CarpetSlab(void)
{
  DECLARE_CCTK_PARAMETERS
}

/*@@
  @routine    CCTKi_BindingsParameterRecovery_CarpetSlab
  @author     Automatically generated by CreateScheduleBindings.pl
  @desc
              Creates the parameter recovery bindings for thorn CarpetSlab
  @enddesc
@@*/

int CCTKi_BindingsParameterRecovery_CarpetSlab(void);
int CCTKi_BindingsParameterRecovery_CarpetSlab(void)
{
  /* this thorn doesn't define any parameter recovery routines */
  return (0);
}

