/*@@
   @file       Schedulebhns.c
   @author     Automatically generated by CreateScheduleBindings.pl
   @desc
               Creates the schedule and parameter recovery bindings 
               for thorn bhns
   @enddesc
@@*/

#define THORN_IS_bhns

#include "cctk.h"
#include "cctk_Parameters.h"
#include "cctki_ScheduleBindings.h"

/* prototypes for schedule bindings functions to be registered */
/* Note that this is a cheat, we just need a function pointer. */
extern int Magnetar_initialdata_readfiles_bhns(void);
extern int Magnetar_initialdata_readfiles_bhns(void);
extern int CCTK_FNAME(magnetar_setup_Aijs_Gammais_bhns)(void);
extern int CCTK_FNAME(bhns_initialdata_read_binfile_driver)(void);
extern int CCTK_FNAME(bhns_initialdata_local)(void);
extern int CCTK_FNAME(bhns_initialdata_global)(void);
extern int CCTK_FNAME(bhns_initialdata_local2)(void);
extern int CCTK_FNAME(bhns_initia_velpert)(void);
extern int CCTK_FNAME(bhns_initialdata_global2)(void);
extern int CCTK_FNAME(bhns_regridder_reader_driver)(void);
extern int CCTK_FNAME(bhns_compute_B_from_A)(void);
extern int CCTK_FNAME(bhns_regridder_reader_driver_part2_primitives_etc)(void);
extern int CCTK_FNAME(bhns_diagnostics_local)(void);
extern int CCTK_FNAME(bhns_diagnostics_global0)(void);
extern int CCTK_FNAME(bhns_diagnostics_local2)(void);
extern int CCTK_FNAME(fill_in_bh_Afields_part1_interpolate_to_spheres)(void);
extern int CCTK_FNAME(fill_in_bh_Afields_part2_fill_interior)(void);
extern int CCTK_FNAME(bhns_sanitycheck_restore_Aij)(void);
extern int CCTK_FNAME(bhns_diagnostics)(void);
extern int CCTK_FNAME(magnetar_diagnostics_bhns)(void);
extern int CCTK_FNAME(bhns_diagnostics_tracer_compute_u_0)(void);
extern int CCTK_FNAME(bhns_diagnostics_trace_particles_circle)(void);
extern int CCTK_FNAME(bhns_diagnostics_trace_particles)(void);
extern int CCTK_FNAME(BHNS_setup_emfield_part1_Pmax)(void);
extern int CCTK_FNAME(BHNS_setup_emfield_part2_local_setBi)(void);
extern int CCTK_FNAME(BHNS_setup_emfield_part2p5_local_consrv)(void);
extern int CCTK_FNAME(Integrate_vol_integrand_bhns_emfields_compute_avgbetam1)(void);
extern int CCTK_FNAME(driver_setup_emfields_part4_local_rescaleB_set_conservs)(void);
extern int CCTK_FNAME(bhns_regridder_unstagger_driver)(void);
extern int CCTK_FNAME(bhns_regridder_writer_driver)(void);
extern int CCTK_FNAME(BHNS_setup_emfield_part1_Pmax)(void);
extern int CCTK_FNAME(BHNS_setup_emfield_part1_Pmax)(void);
extern int CCTK_FNAME(find_CoM_velocity)(void);
extern int CCTK_FNAME(BHNS_setup_emfield_part2_local_setBi_after_checkpoint)(void);
extern int CCTK_FNAME(BHNS_setup_emfield_part2p5_local_consrv_aftercp)(void);
extern int CCTK_FNAME(Integrate_vol_integrand_bhns_emfields_compute_avgbetam1)(void);
extern int CCTK_FNAME(driver_setup_emfields_part4_local_rescaleB_set_conservs)(void);
extern int CCTK_FNAME(BHNS_setup_thermal_pressure_preset)(void);
extern int CCTK_FNAME(BHNS_setup_thermal_pressure_after_checkpoint)(void);
extern int CCTK_FNAME(BHNS_setup_thermal_pressure_afterset)(void);
extern int CCTK_FNAME(BHNS_insert_radiation_preset)(void);
extern int CCTK_FNAME(BHNS_insert_radiation_after_checkpoint)(void);
extern int CCTK_FNAME(BHNS_insert_radiation_afterset)(void);


void CCTKi_BindingsSchedule_bhns(void);
void CCTKi_BindingsSchedule_bhns(void)
{
  DECLARE_CCTK_PARAMETERS
  CCTKi_ScheduleGroupStorage("BSSN::BSSN_vars",3);
  CCTKi_ScheduleGroupStorage("lapse::lapse_vars",3);
  CCTKi_ScheduleGroupStorage("shift::shift_vars",3);
  CCTKi_ScheduleGroupStorage("mhd_evolve::em_conservativex",3);
  CCTKi_ScheduleGroupStorage("mhd_evolve::em_conservativey",3);
  CCTKi_ScheduleGroupStorage("mhd_evolve::em_conservativez",3);
  CCTKi_ScheduleGroupStorage("mhd_evolve::mhd_conservatives",3);
  CCTKi_ScheduleGroupStorage("mhd_evolve::em_Ax",3);
  CCTKi_ScheduleGroupStorage("mhd_evolve::em_Ay",3);
  CCTKi_ScheduleGroupStorage("mhd_evolve::em_Az",3);
  CCTKi_ScheduleGroupStorage("mhd_evolve::em_Phi",3);
  CCTKi_ScheduleGroupStorage("mhd_evolve::em_Blagrangemultiplier",3);
  CCTKi_ScheduleGroupStorage("mhd_evolve::Stagger_Bs",1);
  CCTKi_ScheduleGroupStorage("BSSN::BSSN_gupij",1);
  CCTKi_ScheduleGroupStorage("BSSN::BSSN_matter",1);
  CCTKi_ScheduleGroupStorage("BSSN::BSSN_AH",1);
  CCTKi_ScheduleGroupStorage("BSSN::BSSN_aux_restrict2",1);
  CCTKi_ScheduleGroupStorage("BSSN::phi_derivs",1);
  CCTKi_ScheduleGroupStorage("BSSN::BSSN_diag_restrict",1);
  CCTKi_ScheduleGroupStorage("BSSN::BSSN_refbd",3);
  CCTKi_ScheduleGroupStorage("mhd_evolve::mhd_primitives",1);
  CCTKi_ScheduleGroupStorage("mhd_evolve::mhd_vs",1);
  CCTKi_ScheduleGroupStorage("mhd_evolve::mhd_temps",1);
  CCTKi_ScheduleGroupStorage("mhd_evolve::disk_atmosphere",1);
  CCTKi_ScheduleGroupStorage("mhd_evolve::eos_params1",1);
  CCTKi_ScheduleGroupStorage("mhd_evolve::eos_params2",1);
  CCTKi_ScheduleGroupStorage("mhd_evolve::mhdscalar",1);
  CCTKi_ScheduleGroupStorage("mhd_evolve::field_line_variables",3);
  CCTKi_ScheduleGroupStorage("mhd_evolve::rad_conservatives",3);
  CCTKi_ScheduleGroupStorage("mhd_evolve::rad_primitives",1);
  CCTKi_ScheduleGroupStorage("mhd_evolve::rad_pressure",1);
  CCTKi_ScheduleGroupStorage("mhd_evolve::mhd_nosync",1);
  CCTKi_ScheduleGroupStorage("mhd_evolve::micphys_conservatives",3);
  CCTKi_ScheduleGroupStorage("mhd_evolve::microphys_primitives",1);
  CCTKi_ScheduleGroupStorage("fisheye::fisheye_vars",1);
  CCTKi_ScheduleGroupStorage("excision::excision_int_gfs",1);
  CCTKi_ScheduleGroupStorage("diagnostics_vacuum::surf_params",1);
  CCTKi_ScheduleGroupStorage("diagnostics_vacuum::volIntegrals",1);
  CCTKi_ScheduleGroupStorage("diagnostics_mhd::volIntegrals_mhd",1);
  CCTKi_ScheduleGroupStorage("bhns::int_Mdot",1);
  CCTKi_ScheduleGroupStorage("bhns::last_ah_data",1);
  CCTKi_ScheduleGroupStorage("bhns::Axyzintrgroup",1);
  CCTKi_ScheduleGroupStorage("movingbox::volIntegrals_movingbox",1);
  CCTKi_ScheduleGroupStorage("bhns::Tracergroup",1);
  CCTKi_ScheduleGroupStorage("bhns::Tracer_rhs_group",1);
  CCTKi_ScheduleGroupStorage("bhns::Tracer_substep_count",1);
 if(bhns_regrid_input_enable==0) {   
if (use_new_bhns_initial_data==-1){
  {
    int cctkschedulei_tlevelarray[] = {0};
    CCTKi_ScheduleFunction((void *)Magnetar_initialdata_readfiles_bhns,
                           "first_initialdata_ID",
                           "bhns",
                           "bhns",
                           "Used for generating regrid infor for ID used for other thorns",
                           "CCTK_INITIAL",
                           "C",
                           0,  /* Number of STORAGE  groups   */
                           0,  /* Number of COMM     groups   */
                           0,  /* Number of TRIGGERS groups   */
                           0,  /* Number of SYNC     groups   */
                           1,  /* Number of Options           */
                           0,  /* Number of BEFORE  routines  */
                           0,  /* Number of AFTER   routines  */
                           0,  /* Number of WHILE   variables */
                           0,  /* Number of IF   variables */
                           cctkschedulei_tlevelarray  /* Array of timelevel data for storage groups */,
                           "LOCAL");
  }
}
else{
 if(use_new_bhns_initial_data==5){
  {
    int cctkschedulei_tlevelarray[] = {0};
    CCTKi_ScheduleFunction((void *)Magnetar_initialdata_readfiles_bhns,
                           "first_initialdata",
                           "bhns",
                           "bhns",
                           "Read in initial data for magnetar star evolver from Cook code data.",
                           "CCTK_INITIAL",
                           "C",
                           0,  /* Number of STORAGE  groups   */
                           0,  /* Number of COMM     groups   */
                           0,  /* Number of TRIGGERS groups   */
                           0,  /* Number of SYNC     groups   */
                           1,  /* Number of Options           */
                           0,  /* Number of BEFORE  routines  */
                           0,  /* Number of AFTER   routines  */
                           0,  /* Number of WHILE   variables */
                           0,  /* Number of IF   variables */
                           cctkschedulei_tlevelarray  /* Array of timelevel data for storage groups */,
                           "LOCAL");
  }
  {
    int cctkschedulei_tlevelarray[] = {0};
    CCTKi_ScheduleFunction((void *)CCTK_FNAME(magnetar_setup_Aijs_Gammais_bhns),
                           "second_initialdata",
                           "bhns",
                           "bhns",
                           "Set up Aij's, Gammai's",
                           "CCTK_INITIAL",
                           "Fortran",
                           0,  /* Number of STORAGE  groups   */
                           0,  /* Number of COMM     groups   */
                           0,  /* Number of TRIGGERS groups   */
                           1,  /* Number of SYNC     groups   */
                           0,  /* Number of Options           */
                           0,  /* Number of BEFORE  routines  */
                           1,  /* Number of AFTER   routines  */
                           0,  /* Number of WHILE   variables */
                           0,  /* Number of IF   variables */
                           cctkschedulei_tlevelarray  /* Array of timelevel data for storage groups */,
                           "BSSN::BSSN_vars",
                           "first_initialdata");
  }
 }
 else { 
  {
    int cctkschedulei_tlevelarray[] = {0};
    CCTKi_ScheduleFunction((void *)CCTK_FNAME(bhns_initialdata_read_binfile_driver),
                           "first_initialdata",
                           "bhns",
                           "bhns",
                           "Read in initial data for BHNS evolver from Keisuke's or SpEC binary data",
                           "CCTK_INITIAL",
                           "Fortran",
                           0,  /* Number of STORAGE  groups   */
                           0,  /* Number of COMM     groups   */
                           0,  /* Number of TRIGGERS groups   */
                           0,  /* Number of SYNC     groups   */
                           1,  /* Number of Options           */
                           0,  /* Number of BEFORE  routines  */
                           0,  /* Number of AFTER   routines  */
                           0,  /* Number of WHILE   variables */
                           0,  /* Number of IF   variables */
                           cctkschedulei_tlevelarray  /* Array of timelevel data for storage groups */,
                           "LOCAL");
  }
  {
    int cctkschedulei_tlevelarray[] = {0};
    CCTKi_ScheduleFunction((void *)CCTK_FNAME(bhns_initialdata_local),
                           "second_initialdata",
                           "bhns",
                           "bhns",
                           "Fill in metric quantities",
                           "CCTK_INITIAL",
                           "Fortran",
                           0,  /* Number of STORAGE  groups   */
                           0,  /* Number of COMM     groups   */
                           0,  /* Number of TRIGGERS groups   */
                           1,  /* Number of SYNC     groups   */
                           0,  /* Number of Options           */
                           0,  /* Number of BEFORE  routines  */
                           1,  /* Number of AFTER   routines  */
                           0,  /* Number of WHILE   variables */
                           0,  /* Number of IF   variables */
                           cctkschedulei_tlevelarray  /* Array of timelevel data for storage groups */,
                           "BSSN::BSSN_vars",
                           "first_initialdata");
  }
  }
  {
    int cctkschedulei_tlevelarray[] = {0};
    CCTKi_ScheduleGroup("bhns_postid",
"bhns_postid",
                        "bhns",
                        "bhns",
                        "Finish up BHNS initial data.  Need to schedule several GLOBAL function calls that don't work in CCTK_INITIAL. :(",
                        "CCTK_POSTPOSTINITIAL",
                        0,  /* Number of STORAGE  groups   */
                        0,  /* Number of COMM     groups   */
                        0,  /* Number of TRIGGERS groups   */
                        0,  /* Number of SYNC     groups   */
                        0,  /* Number of Options           */
                        2,  /* Number of BEFORE  routines  */
                        0,  /* Number of AFTER   routines  */
                        0,  /* Number of WHILE   variables */
                        0,  /* Number of IF   variables */
                        cctkschedulei_tlevelarray  /* Array of timelevel data for storage groups */,
                        "ABE_PostInitial",
                        "MoL_PostStep");
  }
  {
    int cctkschedulei_tlevelarray[] = {0};
    CCTKi_ScheduleFunction((void *)CCTK_FNAME(bhns_initialdata_global),
                           "third_initialdata",
                           "bhns",
                           "bhns",
                           "Set rho_b_atm, etc.",
                           "bhns_postid",
                           "Fortran",
                           0,  /* Number of STORAGE  groups   */
                           0,  /* Number of COMM     groups   */
                           0,  /* Number of TRIGGERS groups   */
                           0,  /* Number of SYNC     groups   */
                           1,  /* Number of Options           */
                           0,  /* Number of BEFORE  routines  */
                           0,  /* Number of AFTER   routines  */
                           0,  /* Number of WHILE   variables */
                           0,  /* Number of IF   variables */
                           cctkschedulei_tlevelarray  /* Array of timelevel data for storage groups */,
                           "GLOBAL");
  }
  {
    int cctkschedulei_tlevelarray[] = {0};
    CCTKi_ScheduleFunction((void *)CCTK_FNAME(bhns_initialdata_local2),
                           "fourth_initialdata",
                           "bhns",
                           "bhns",
                           "Fill in matter quantities.  Note that rho_b depends on rho_b_atm, and most hydro vars depend on rho_b",
                           "bhns_postid",
                           "Fortran",
                           0,  /* Number of STORAGE  groups   */
                           0,  /* Number of COMM     groups   */
                           0,  /* Number of TRIGGERS groups   */
                           1,  /* Number of SYNC     groups   */
                           2,  /* Number of Options           */
                           0,  /* Number of BEFORE  routines  */
                           1,  /* Number of AFTER   routines  */
                           0,  /* Number of WHILE   variables */
                           0,  /* Number of IF   variables */
                           cctkschedulei_tlevelarray  /* Array of timelevel data for storage groups */,
                           "BSSN::BSSN_vars",
                           "GLOBAL",
                           "LOOP-LOCAL",
                           "third_initialdata");
  }
   if(use_new_bhns_initial_data==5){
  {
    int cctkschedulei_tlevelarray[] = {0};
    CCTKi_ScheduleFunction((void *)CCTK_FNAME(bhns_initia_velpert),
                           "fifth_initialdata",
                           "bhns",
                           "bhns",
                           "add the perturbation in v's",
                           "bhns_postid",
                           "Fortran",
                           0,  /* Number of STORAGE  groups   */
                           0,  /* Number of COMM     groups   */
                           0,  /* Number of TRIGGERS groups   */
                           0,  /* Number of SYNC     groups   */
                           2,  /* Number of Options           */
                           0,  /* Number of BEFORE  routines  */
                           1,  /* Number of AFTER   routines  */
                           0,  /* Number of WHILE   variables */
                           0,  /* Number of IF   variables */
                           cctkschedulei_tlevelarray  /* Array of timelevel data for storage groups */,
                           "GLOBAL",
                           "LOOP-LOCAL",
                           "fourth_initialdata");
  }
   }
  {
    int cctkschedulei_tlevelarray[] = {0};
    CCTKi_ScheduleFunction((void *)CCTK_FNAME(bhns_initialdata_global2),
                           "sixth_initialdata",
                           "bhns",
                           "bhns",
                           "Set tau_atm, which depends on tau, which depends on rho_b, etc.",
                           "bhns_postid",
                           "Fortran",
                           0,  /* Number of STORAGE  groups   */
                           0,  /* Number of COMM     groups   */
                           0,  /* Number of TRIGGERS groups   */
                           0,  /* Number of SYNC     groups   */
                           1,  /* Number of Options           */
                           0,  /* Number of BEFORE  routines  */
                           1,  /* Number of AFTER   routines  */
                           0,  /* Number of WHILE   variables */
                           0,  /* Number of IF   variables */
                           cctkschedulei_tlevelarray  /* Array of timelevel data for storage groups */,
                           "GLOBAL",
                           "fifth_initialdata");
  }
}
} else {
  {
    int cctkschedulei_tlevelarray[] = {0};
    CCTKi_ScheduleGroup("regridder_postid",
"regridder_postid",
                        "bhns",
                        "bhns",
                        "Finish up regridder initial data.  Need to schedule several GLOBAL function calls that don't work in CCTK_INITIAL. :(",
                        "CCTK_POSTPOSTINITIAL",
                        0,  /* Number of STORAGE  groups   */
                        0,  /* Number of COMM     groups   */
                        0,  /* Number of TRIGGERS groups   */
                        0,  /* Number of SYNC     groups   */
                        0,  /* Number of Options           */
                        2,  /* Number of BEFORE  routines  */
                        0,  /* Number of AFTER   routines  */
                        0,  /* Number of WHILE   variables */
                        0,  /* Number of IF   variables */
                        cctkschedulei_tlevelarray  /* Array of timelevel data for storage groups */,
                        "ABE_PostInitial",
                        "MoL_PostStep");
  }
  {
    int cctkschedulei_tlevelarray[] = {0};
    CCTKi_ScheduleFunction((void *)CCTK_FNAME(bhns_regridder_reader_driver),
                           "first_initialdata",
                           "bhns",
                           "bhns",
                           "Set up regridded initialdata -- part 1: read in files",
                           "regridder_postid",
                           "Fortran",
                           0,  /* Number of STORAGE  groups   */
                           0,  /* Number of COMM     groups   */
                           0,  /* Number of TRIGGERS groups   */
                           0,  /* Number of SYNC     groups   */
                           2,  /* Number of Options           */
                           0,  /* Number of BEFORE  routines  */
                           0,  /* Number of AFTER   routines  */
                           0,  /* Number of WHILE   variables */
                           0,  /* Number of IF   variables */
                           cctkschedulei_tlevelarray  /* Array of timelevel data for storage groups */,
                           "GLOBAL",
                           "LOOP-LOCAL");
  }
  {
    int cctkschedulei_tlevelarray[] = {0};
    CCTKi_ScheduleFunction((void *)CCTK_FNAME(bhns_compute_B_from_A),
                           "first_postinitialdata",
                           "bhns",
                           "bhns",
                           "Set up regridded initialdata -- part 2: compute B from A, then SYNC B's",
                           "regridder_postid",
                           "Fortran",
                           0,  /* Number of STORAGE  groups   */
                           0,  /* Number of COMM     groups   */
                           0,  /* Number of TRIGGERS groups   */
                           6,  /* Number of SYNC     groups   */
                           2,  /* Number of Options           */
                           1,  /* Number of BEFORE  routines  */
                           0,  /* Number of AFTER   routines  */
                           0,  /* Number of WHILE   variables */
                           0,  /* Number of IF   variables */
                           cctkschedulei_tlevelarray  /* Array of timelevel data for storage groups */,
                           "MHD_EVOLVE::Stagger_Bs",
                           "MHD_EVOLVE::mhd_primitives",
                           "MHD_EVOLVE::em_Ax",
                           "MHD_EVOLVE::em_Ay",
                           "MHD_EVOLVE::em_Az",
                           "MHD_EVOLVE::em_Phi",
                           "GLOBAL",
                           "LOOP-LOCAL",
                           "postid");
  }
  {
    int cctkschedulei_tlevelarray[] = {0};
    CCTKi_ScheduleFunction((void *)CCTK_FNAME(bhns_regridder_reader_driver_part2_primitives_etc),
                           "second_postinitialdata",
                           "bhns",
                           "bhns",
                           "Set up regridded initialdata -- part 3: Compute primitives, etc.",
                           "ABE_PostInitial",
                           "Fortran",
                           0,  /* Number of STORAGE  groups   */
                           0,  /* Number of COMM     groups   */
                           0,  /* Number of TRIGGERS groups   */
                           9,  /* Number of SYNC     groups   */
                           2,  /* Number of Options           */
                           1,  /* Number of BEFORE  routines  */
                           0,  /* Number of AFTER   routines  */
                           0,  /* Number of WHILE   variables */
                           0,  /* Number of IF   variables */
                           cctkschedulei_tlevelarray  /* Array of timelevel data for storage groups */,
                           "MHD_EVOLVE::Stagger_Bs",
                           "MHD_EVOLVE::mhd_primitives",
                           "MHD_EVOLVE::em_Ax",
                           "MHD_EVOLVE::em_Ay",
                           "MHD_EVOLVE::em_Az",
                           "MHD_EVOLVE::em_Phi",
                           "MHD_EVOLVE::rad_primitives",
                           "MHD_EVOLVE::microphys_primitives",
                           "MHD_EVOLVE::rad_pressure",
                           "GLOBAL",
                           "LOOP-LOCAL",
                           "postid");
  }
}
if (use_new_bhns_initial_data!=-1){
if(1==1 && em_evolve_enable==1) {
  {
    int cctkschedulei_tlevelarray[] = {0};
    CCTKi_ScheduleFunction((void *)CCTK_FNAME(bhns_diagnostics_local),
                           "diag_local",
                           "bhns",
                           "bhns",
                           "Set b2 array",
                           "CCTK_ANALYSIS",
                           "Fortran",
                           0,  /* Number of STORAGE  groups   */
                           0,  /* Number of COMM     groups   */
                           0,  /* Number of TRIGGERS groups   */
                           0,  /* Number of SYNC     groups   */
                           2,  /* Number of Options           */
                           1,  /* Number of BEFORE  routines  */
                           0,  /* Number of AFTER   routines  */
                           0,  /* Number of WHILE   variables */
                           0,  /* Number of IF   variables */
                           cctkschedulei_tlevelarray  /* Array of timelevel data for storage groups */,
                           "LEVEL",
                           "LOOP-LOCAL",
                           "T_integrand");
  }
  {
    int cctkschedulei_tlevelarray[] = {0};
    CCTKi_ScheduleFunction((void *)CCTK_FNAME(bhns_diagnostics_global0),
                           "globalzero",
                           "bhns",
                           "bhns",
                           "Compute bhns_max_b2",
                           "CCTK_ANALYSIS",
                           "Fortran",
                           0,  /* Number of STORAGE  groups   */
                           0,  /* Number of COMM     groups   */
                           0,  /* Number of TRIGGERS groups   */
                           0,  /* Number of SYNC     groups   */
                           1,  /* Number of Options           */
                           1,  /* Number of BEFORE  routines  */
                           1,  /* Number of AFTER   routines  */
                           0,  /* Number of WHILE   variables */
                           0,  /* Number of IF   variables */
                           cctkschedulei_tlevelarray  /* Array of timelevel data for storage groups */,
                           "GLOBAL",
                           "T_integrand",
                           "diag_local");
  }
  {
    int cctkschedulei_tlevelarray[] = {0};
    CCTKi_ScheduleFunction((void *)CCTK_FNAME(bhns_diagnostics_local2),
                           "diag_localtwo",
                           "bhns",
                           "bhns",
                           "Compute coordinates of bhns_max_b2",
                           "CCTK_ANALYSIS",
                           "Fortran",
                           0,  /* Number of STORAGE  groups   */
                           0,  /* Number of COMM     groups   */
                           0,  /* Number of TRIGGERS groups   */
                           0,  /* Number of SYNC     groups   */
                           2,  /* Number of Options           */
                           1,  /* Number of BEFORE  routines  */
                           1,  /* Number of AFTER   routines  */
                           0,  /* Number of WHILE   variables */
                           0,  /* Number of IF   variables */
                           cctkschedulei_tlevelarray  /* Array of timelevel data for storage groups */,
                           "GLOBAL",
                           "LOOP-LOCAL",
                           "T_integrand",
                           "globalzero");
  }
  {
    int cctkschedulei_tlevelarray[] = {0};
    CCTKi_ScheduleFunction((void *)CCTK_FNAME(fill_in_bh_Afields_part1_interpolate_to_spheres),
                           "fillbh1",
                           "bhns",
                           "bhns",
                           "Fill BH with smoothed Afields: Part 1 -- interpolate onto two spheres to get parameters for smoothing polynomial.",
                           "CCTK_ANALYSIS",
                           "Fortran",
                           0,  /* Number of STORAGE  groups   */
                           0,  /* Number of COMM     groups   */
                           0,  /* Number of TRIGGERS groups   */
                           0,  /* Number of SYNC     groups   */
                           1,  /* Number of Options           */
                           1,  /* Number of BEFORE  routines  */
                           1,  /* Number of AFTER   routines  */
                           0,  /* Number of WHILE   variables */
                           0,  /* Number of IF   variables */
                           cctkschedulei_tlevelarray  /* Array of timelevel data for storage groups */,
                           "GLOBAL",
                           "T_integrand",
                           "diag_localtwo");
  }
  {
    int cctkschedulei_tlevelarray[] = {0};
    CCTKi_ScheduleFunction((void *)CCTK_FNAME(fill_in_bh_Afields_part2_fill_interior),
                           "fillbh2",
                           "bhns",
                           "bhns",
                           "Fill BH with smoothed Afields: Part 2 -- fill in BH with smoothed Afields.",
                           "CCTK_ANALYSIS",
                           "Fortran",
                           0,  /* Number of STORAGE  groups   */
                           0,  /* Number of COMM     groups   */
                           0,  /* Number of TRIGGERS groups   */
                           0,  /* Number of SYNC     groups   */
                           2,  /* Number of Options           */
                           1,  /* Number of BEFORE  routines  */
                           1,  /* Number of AFTER   routines  */
                           0,  /* Number of WHILE   variables */
                           0,  /* Number of IF   variables */
                           cctkschedulei_tlevelarray  /* Array of timelevel data for storage groups */,
                           "GLOBAL",
                           "LOOP-LOCAL",
                           "T_integrand",
                           "fillbh1");
  }
}
  {
    int cctkschedulei_tlevelarray[] = {0};
    CCTKi_ScheduleFunction((void *)CCTK_FNAME(bhns_sanitycheck_restore_Aij),
                           "sanitycheck_restore_Aij",
                           "bhns",
                           "bhns",
                           "Sanity check, Restore Aij",
                           "CCTK_ANALYSIS",
                           "Fortran",
                           0,  /* Number of STORAGE  groups   */
                           0,  /* Number of COMM     groups   */
                           0,  /* Number of TRIGGERS groups   */
                           0,  /* Number of SYNC     groups   */
                           0,  /* Number of Options           */
                           0,  /* Number of BEFORE  routines  */
                           1,  /* Number of AFTER   routines  */
                           0,  /* Number of WHILE   variables */
                           0,  /* Number of IF   variables */
                           cctkschedulei_tlevelarray  /* Array of timelevel data for storage groups */,
                           "diag_local");
  }
  {
    int cctkschedulei_tlevelarray[] = {1,0};
    CCTKi_ScheduleFunction((void *)CCTK_FNAME(bhns_diagnostics),
                           "poststep",
                           "bhns",
                           "bhns",
                           "Evaluate diagnostic integrals",
                           "CCTK_ANALYSIS",
                           "Fortran",
                           1,  /* Number of STORAGE  groups   */
                           0,  /* Number of COMM     groups   */
                           0,  /* Number of TRIGGERS groups   */
                           0,  /* Number of SYNC     groups   */
                           1,  /* Number of Options           */
                           0,  /* Number of BEFORE  routines  */
                           1,  /* Number of AFTER   routines  */
                           0,  /* Number of WHILE   variables */
                           0,  /* Number of IF   variables */
                           cctkschedulei_tlevelarray  /* Array of timelevel data for storage groups */,
                           "MOVINGBOX::volIntegrals_movingbox",
                           "GLOBAL",
                           "sanitycheck_restore_Aij");
  }
if (use_new_bhns_initial_data==5){
  {
    int cctkschedulei_tlevelarray[] = {0};
    CCTKi_ScheduleFunction((void *)CCTK_FNAME(magnetar_diagnostics_bhns),
                           "poststep2",
                           "bhns",
                           "bhns",
                           "Evaluate diagnostic integrals",
                           "CCTK_ANALYSIS",
                           "Fortran",
                           0,  /* Number of STORAGE  groups   */
                           0,  /* Number of COMM     groups   */
                           0,  /* Number of TRIGGERS groups   */
                           0,  /* Number of SYNC     groups   */
                           1,  /* Number of Options           */
                           0,  /* Number of BEFORE  routines  */
                           1,  /* Number of AFTER   routines  */
                           0,  /* Number of WHILE   variables */
                           0,  /* Number of IF   variables */
                           cctkschedulei_tlevelarray  /* Array of timelevel data for storage groups */,
                           "GLOBAL",
                           "poststep");
  }
}
  {
    int cctkschedulei_tlevelarray[] = {0};
    CCTKi_ScheduleFunction((void *)CCTK_FNAME(bhns_diagnostics_tracer_compute_u_0),
                           "particle_tracer_u_0",
                           "bhns",
                           "bhns",
                           "BHNS Particle tracer algorithm: compute u_0, store in temp1",
                           "CCTK_ANALYSIS",
                           "Fortran",
                           0,  /* Number of STORAGE  groups   */
                           0,  /* Number of COMM     groups   */
                           0,  /* Number of TRIGGERS groups   */
                           0,  /* Number of SYNC     groups   */
                           2,  /* Number of Options           */
                           0,  /* Number of BEFORE  routines  */
                           2,  /* Number of AFTER   routines  */
                           0,  /* Number of WHILE   variables */
                           0,  /* Number of IF   variables */
                           cctkschedulei_tlevelarray  /* Array of timelevel data for storage groups */,
                           "GLOBAL",
                           "LOOP-LOCAL",
                           "poststep",
                           "sanitycheck_restore_Aij");
  }
if(initial_particle_geometry==3){	   
  {
    int cctkschedulei_tlevelarray[] = {0};
    CCTKi_ScheduleFunction((void *)CCTK_FNAME(bhns_diagnostics_trace_particles_circle),
                           "particle_tracer",
                           "bhns",
                           "bhns",
                           "BHNS Particle tracer algorithm on a circle",
                           "CCTK_ANALYSIS",
                           "Fortran",
                           0,  /* Number of STORAGE  groups   */
                           0,  /* Number of COMM     groups   */
                           0,  /* Number of TRIGGERS groups   */
                           0,  /* Number of SYNC     groups   */
                           1,  /* Number of Options           */
                           0,  /* Number of BEFORE  routines  */
                           3,  /* Number of AFTER   routines  */
                           0,  /* Number of WHILE   variables */
                           0,  /* Number of IF   variables */
                           cctkschedulei_tlevelarray  /* Array of timelevel data for storage groups */,
                           "GLOBAL",
                           "particle_tracer_u_0",
                           "poststep",
                           "sanitycheck_restore_Aij");
  }
   }
 else{
  {
    int cctkschedulei_tlevelarray[] = {0};
    CCTKi_ScheduleFunction((void *)CCTK_FNAME(bhns_diagnostics_trace_particles),
                           "particle_tracer",
                           "bhns",
                           "bhns",
                           "BHNS Particle tracer algorithm",
                           "CCTK_ANALYSIS",
                           "Fortran",
                           0,  /* Number of STORAGE  groups   */
                           0,  /* Number of COMM     groups   */
                           0,  /* Number of TRIGGERS groups   */
                           0,  /* Number of SYNC     groups   */
                           1,  /* Number of Options           */
                           0,  /* Number of BEFORE  routines  */
                           3,  /* Number of AFTER   routines  */
                           0,  /* Number of WHILE   variables */
                           0,  /* Number of IF   variables */
                           cctkschedulei_tlevelarray  /* Array of timelevel data for storage groups */,
                           "GLOBAL",
                           "particle_tracer_u_0",
                           "poststep",
                           "sanitycheck_restore_Aij");
  }
}
if(em_evolve_enable==1) {
  {
    int cctkschedulei_tlevelarray[] = {0};
    CCTKi_ScheduleFunction((void *)CCTK_FNAME(BHNS_setup_emfield_part1_Pmax),
                           "bhns_em_pt1",
                           "bhns",
                           "bhns",
                           "Setup BHNS EMFields, part 1",
                           "bhns_postid",
                           "Fortran",
                           0,  /* Number of STORAGE  groups   */
                           0,  /* Number of COMM     groups   */
                           0,  /* Number of TRIGGERS groups   */
                           0,  /* Number of SYNC     groups   */
                           1,  /* Number of Options           */
                           0,  /* Number of BEFORE  routines  */
                           1,  /* Number of AFTER   routines  */
                           0,  /* Number of WHILE   variables */
                           0,  /* Number of IF   variables */
                           cctkschedulei_tlevelarray  /* Array of timelevel data for storage groups */,
                           "GLOBAL",
                           "fifth_initialdata");
  }
  {
    int cctkschedulei_tlevelarray[] = {0};
    CCTKi_ScheduleFunction((void *)CCTK_FNAME(BHNS_setup_emfield_part2_local_setBi),
                           "bhns_em_pt2",
                           "bhns",
                           "bhns",
                           "Setup BHNS EMFields, part 2",
                           "bhns_postid",
                           "Fortran",
                           0,  /* Number of STORAGE  groups   */
                           0,  /* Number of COMM     groups   */
                           0,  /* Number of TRIGGERS groups   */
                           7,  /* Number of SYNC     groups   */
                           2,  /* Number of Options           */
                           0,  /* Number of BEFORE  routines  */
                           1,  /* Number of AFTER   routines  */
                           0,  /* Number of WHILE   variables */
                           0,  /* Number of IF   variables */
                           cctkschedulei_tlevelarray  /* Array of timelevel data for storage groups */,
                           "mhd_evolve::Stagger_Bs",
                           "mhd_evolve::mhd_primitives",
                           "mhd_evolve::em_Ax",
                           "mhd_evolve::em_Ay",
                           "mhd_evolve::em_Az",
                           "mhd_evolve::em_Phi",
                           "mhd_evolve::mhd_conservatives",
                           "GLOBAL",
                           "loop-local",
                           "bhns_em_pt1");
  }
  {
    int cctkschedulei_tlevelarray[] = {0};
    CCTKi_ScheduleFunction((void *)CCTK_FNAME(BHNS_setup_emfield_part2p5_local_consrv),
                           "bhns_em_pt2p5",
                           "bhns",
                           "bhns",
                           "Setup BHNS EMFields, part 2.5",
                           "bhns_postid",
                           "Fortran",
                           0,  /* Number of STORAGE  groups   */
                           0,  /* Number of COMM     groups   */
                           0,  /* Number of TRIGGERS groups   */
                           8,  /* Number of SYNC     groups   */
                           2,  /* Number of Options           */
                           0,  /* Number of BEFORE  routines  */
                           1,  /* Number of AFTER   routines  */
                           0,  /* Number of WHILE   variables */
                           0,  /* Number of IF   variables */
                           cctkschedulei_tlevelarray  /* Array of timelevel data for storage groups */,
                           "mhd_evolve::Stagger_Bs",
                           "mhd_evolve::mhd_primitives",
                           "mhd_evolve::em_Ax",
                           "mhd_evolve::em_Ay",
                           "mhd_evolve::em_Az",
                           "mhd_evolve::em_Phi",
                           "mhd_evolve::mhd_conservatives",
                           "mhd_evolve::rad_pressure",
                           "GLOBAL",
                           "loop-local",
                           "bhns_em_pt2");
  }
  {
    int cctkschedulei_tlevelarray[] = {0};
    CCTKi_ScheduleFunction((void *)CCTK_FNAME(Integrate_vol_integrand_bhns_emfields_compute_avgbetam1),
                           "bhns_em_pt3",
                           "bhns",
                           "bhns",
                           "Setup BHNS EMFields, part 3",
                           "bhns_postid",
                           "Fortran",
                           0,  /* Number of STORAGE  groups   */
                           0,  /* Number of COMM     groups   */
                           0,  /* Number of TRIGGERS groups   */
                           0,  /* Number of SYNC     groups   */
                           1,  /* Number of Options           */
                           0,  /* Number of BEFORE  routines  */
                           1,  /* Number of AFTER   routines  */
                           0,  /* Number of WHILE   variables */
                           0,  /* Number of IF   variables */
                           cctkschedulei_tlevelarray  /* Array of timelevel data for storage groups */,
                           "GLOBAL",
                           "bhns_em_pt2p5");
  }
  {
    int cctkschedulei_tlevelarray[] = {0};
    CCTKi_ScheduleFunction((void *)CCTK_FNAME(driver_setup_emfields_part4_local_rescaleB_set_conservs),
                           "bhns_em_pt4",
                           "bhns",
                           "bhns",
                           "Setup BHNS EMFields, part 4",
                           "bhns_postid",
                           "Fortran",
                           0,  /* Number of STORAGE  groups   */
                           0,  /* Number of COMM     groups   */
                           0,  /* Number of TRIGGERS groups   */
                           0,  /* Number of SYNC     groups   */
                           2,  /* Number of Options           */
                           0,  /* Number of BEFORE  routines  */
                           1,  /* Number of AFTER   routines  */
                           0,  /* Number of WHILE   variables */
                           0,  /* Number of IF   variables */
                           cctkschedulei_tlevelarray  /* Array of timelevel data for storage groups */,
                           "GLOBAL",
                           "loop-local",
                           "bhns_em_pt3");
  }
}
}
  {
    int cctkschedulei_tlevelarray[] = {0};
    CCTKi_ScheduleGroup("bhns_regrid_output",
"bhns_regrid_output",
                        "bhns",
                        "bhns",
                        "Perform a regridding at the specified time",
                        "CCTK_ANALYSIS",
                        0,  /* Number of STORAGE  groups   */
                        0,  /* Number of COMM     groups   */
                        0,  /* Number of TRIGGERS groups   */
                        0,  /* Number of SYNC     groups   */
                        0,  /* Number of Options           */
                        0,  /* Number of BEFORE  routines  */
                        1,  /* Number of AFTER   routines  */
                        0,  /* Number of WHILE   variables */
                        0,  /* Number of IF   variables */
                        cctkschedulei_tlevelarray  /* Array of timelevel data for storage groups */,
                        "poststep");
  }
  {
    int cctkschedulei_tlevelarray[] = {0};
    CCTKi_ScheduleFunction((void *)CCTK_FNAME(bhns_regridder_unstagger_driver),
                           "bhns_regrid_unstagger_driver",
                           "bhns",
                           "bhns",
                           "Driver for unstaggering A^{\mu}",
                           "bhns_regrid_output",
                           "Fortran",
                           0,  /* Number of STORAGE  groups   */
                           0,  /* Number of COMM     groups   */
                           0,  /* Number of TRIGGERS groups   */
                           4,  /* Number of SYNC     groups   */
                           2,  /* Number of Options           */
                           0,  /* Number of BEFORE  routines  */
                           0,  /* Number of AFTER   routines  */
                           0,  /* Number of WHILE   variables */
                           0,  /* Number of IF   variables */
                           cctkschedulei_tlevelarray  /* Array of timelevel data for storage groups */,
                           "mhd_evolve::em_conservativex",
                           "mhd_evolve::em_conservativey",
                           "mhd_evolve::em_conservativez",
                           "MHD_EVOLVE::em_Blagrangemultiplier",
                           "GLOBAL",
                           "loop-local");
  }
  {
    int cctkschedulei_tlevelarray[] = {0};
    CCTKi_ScheduleFunction((void *)CCTK_FNAME(bhns_regridder_writer_driver),
                           "bhns_regrid_writer_driver",
                           "bhns",
                           "bhns",
                           "Driver for regridding output",
                           "bhns_regrid_output",
                           "Fortran",
                           0,  /* Number of STORAGE  groups   */
                           0,  /* Number of COMM     groups   */
                           0,  /* Number of TRIGGERS groups   */
                           0,  /* Number of SYNC     groups   */
                           1,  /* Number of Options           */
                           0,  /* Number of BEFORE  routines  */
                           1,  /* Number of AFTER   routines  */
                           0,  /* Number of WHILE   variables */
                           0,  /* Number of IF   variables */
                           cctkschedulei_tlevelarray  /* Array of timelevel data for storage groups */,
                           "GLOBAL",
                           "bhns_regrid_unstagger_driver");
  }
if (use_new_bhns_initial_data!=-1){
if(em_evolve_enable==1) {
  {
    int cctkschedulei_tlevelarray[] = {0};
    CCTKi_ScheduleFunction((void *)CCTK_FNAME(BHNS_setup_emfield_part1_Pmax),
                           "BHNS_setup_emfield_part1_Pmax",
                           "bhns",
                           "bhns",
                           "Setup BHNS EMFields, part 1",
                           "CCTK_ANALYSIS",
                           "Fortran",
                           0,  /* Number of STORAGE  groups   */
                           0,  /* Number of COMM     groups   */
                           0,  /* Number of TRIGGERS groups   */
                           0,  /* Number of SYNC     groups   */
                           1,  /* Number of Options           */
                           1,  /* Number of BEFORE  routines  */
                           1,  /* Number of AFTER   routines  */
                           0,  /* Number of WHILE   variables */
                           0,  /* Number of IF   variables */
                           cctkschedulei_tlevelarray  /* Array of timelevel data for storage groups */,
                           "GLOBAL",
                           "bhns_add_em_fields_after_checkpoint",
                           "poststep");
  }
}
  {
    int cctkschedulei_tlevelarray[] = {0};
    CCTKi_ScheduleGroup("bhns_add_em_fields_after_checkpoint",
"bhns_add_em_fields_after_checkpoint",
                        "bhns",
                        "bhns",
                        "Add EM fields after some checkpoint.  Need to schedule several GLOBAL function calls that don't work in CCTK_INITIAL. :(",
                        "CCTK_ANALYSIS",
                        0,  /* Number of STORAGE  groups   */
                        0,  /* Number of COMM     groups   */
                        0,  /* Number of TRIGGERS groups   */
                        0,  /* Number of SYNC     groups   */
                        0,  /* Number of Options           */
                        0,  /* Number of BEFORE  routines  */
                        1,  /* Number of AFTER   routines  */
                        1,  /* Number of WHILE   variables */
                        0,  /* Number of IF   variables */
                        cctkschedulei_tlevelarray  /* Array of timelevel data for storage groups */,
                        "poststep",
                        "bhns::bhnsinsertBNOW");
  }
  {
    int cctkschedulei_tlevelarray[] = {0};
    CCTKi_ScheduleFunction((void *)CCTK_FNAME(BHNS_setup_emfield_part1_Pmax),
                           "bhns_em_checkpoint_pt1",
                           "bhns",
                           "bhns",
                           "Setup BHNS EMFields, part 1",
                           "bhns_add_em_fields_after_checkpoint",
                           "Fortran",
                           0,  /* Number of STORAGE  groups   */
                           0,  /* Number of COMM     groups   */
                           0,  /* Number of TRIGGERS groups   */
                           0,  /* Number of SYNC     groups   */
                           1,  /* Number of Options           */
                           0,  /* Number of BEFORE  routines  */
                           0,  /* Number of AFTER   routines  */
                           0,  /* Number of WHILE   variables */
                           0,  /* Number of IF   variables */
                           cctkschedulei_tlevelarray  /* Array of timelevel data for storage groups */,
                           "GLOBAL");
  }
  {
    int cctkschedulei_tlevelarray[] = {0};
    CCTKi_ScheduleFunction((void *)CCTK_FNAME(find_CoM_velocity),
                           "bhns_CoM_velocity",
                           "bhns",
                           "bhns",
                           "Setup BHNS EMFields, part 1",
                           "bhns_add_em_fields_after_checkpoint",
                           "Fortran",
                           0,  /* Number of STORAGE  groups   */
                           0,  /* Number of COMM     groups   */
                           0,  /* Number of TRIGGERS groups   */
                           0,  /* Number of SYNC     groups   */
                           1,  /* Number of Options           */
                           0,  /* Number of BEFORE  routines  */
                           1,  /* Number of AFTER   routines  */
                           0,  /* Number of WHILE   variables */
                           0,  /* Number of IF   variables */
                           cctkschedulei_tlevelarray  /* Array of timelevel data for storage groups */,
                           "GLOBAL",
                           "bhns_em_checkpoint_pt1");
  }
  {
    int cctkschedulei_tlevelarray[] = {0};
    CCTKi_ScheduleFunction((void *)CCTK_FNAME(BHNS_setup_emfield_part2_local_setBi_after_checkpoint),
                           "bhns_em_checkpoint_pt2",
                           "bhns",
                           "bhns",
                           "Setup BHNS EMFields, part 2",
                           "bhns_add_em_fields_after_checkpoint",
                           "Fortran",
                           0,  /* Number of STORAGE  groups   */
                           0,  /* Number of COMM     groups   */
                           0,  /* Number of TRIGGERS groups   */
                           12,  /* Number of SYNC     groups   */
                           2,  /* Number of Options           */
                           0,  /* Number of BEFORE  routines  */
                           1,  /* Number of AFTER   routines  */
                           0,  /* Number of WHILE   variables */
                           0,  /* Number of IF   variables */
                           cctkschedulei_tlevelarray  /* Array of timelevel data for storage groups */,
                           "mhd_evolve::Stagger_Bs",
                           "mhd_evolve::mhd_primitives",
                           "mhd_evolve::em_Ax",
                           "mhd_evolve::em_Ay",
                           "mhd_evolve::em_Az",
                           "mhd_evolve::em_Phi",
                           "mhd_evolve::mhd_conservatives",
                           "mhd_evolve::rad_primitives",
                           "mhd_evolve::microphys_primitives",
                           "mhd_evolve::rad_conservatives",
                           "mhd_evolve::micphys_conservatives",
                           "mhd_evolve::rad_pressure",
                           "GLOBAL",
                           "loop-local",
                           "bhns_CoM_velocity");
  }
  {
    int cctkschedulei_tlevelarray[] = {0};
    CCTKi_ScheduleFunction((void *)CCTK_FNAME(BHNS_setup_emfield_part2p5_local_consrv_aftercp),
                           "bhns_em_checkpoint_pt2p5",
                           "bhns",
                           "bhns",
                           "Setup BHNS EMFields, part 2.5",
                           "bhns_add_em_fields_after_checkpoint",
                           "Fortran",
                           0,  /* Number of STORAGE  groups   */
                           0,  /* Number of COMM     groups   */
                           0,  /* Number of TRIGGERS groups   */
                           7,  /* Number of SYNC     groups   */
                           2,  /* Number of Options           */
                           0,  /* Number of BEFORE  routines  */
                           1,  /* Number of AFTER   routines  */
                           0,  /* Number of WHILE   variables */
                           0,  /* Number of IF   variables */
                           cctkschedulei_tlevelarray  /* Array of timelevel data for storage groups */,
                           "mhd_evolve::Stagger_Bs",
                           "mhd_evolve::mhd_primitives",
                           "mhd_evolve::em_Ax",
                           "mhd_evolve::em_Ay",
                           "mhd_evolve::em_Az",
                           "mhd_evolve::em_Phi",
                           "mhd_evolve::mhd_conservatives",
                           "GLOBAL",
                           "loop-local",
                           "bhns_em_checkpoint_pt2");
  }
  {
    int cctkschedulei_tlevelarray[] = {0};
    CCTKi_ScheduleFunction((void *)CCTK_FNAME(Integrate_vol_integrand_bhns_emfields_compute_avgbetam1),
                           "bhns_em_checkpoint_pt3",
                           "bhns",
                           "bhns",
                           "Setup BHNS EMFields, part 3",
                           "bhns_add_em_fields_after_checkpoint",
                           "Fortran",
                           0,  /* Number of STORAGE  groups   */
                           0,  /* Number of COMM     groups   */
                           0,  /* Number of TRIGGERS groups   */
                           0,  /* Number of SYNC     groups   */
                           1,  /* Number of Options           */
                           0,  /* Number of BEFORE  routines  */
                           1,  /* Number of AFTER   routines  */
                           0,  /* Number of WHILE   variables */
                           0,  /* Number of IF   variables */
                           cctkschedulei_tlevelarray  /* Array of timelevel data for storage groups */,
                           "GLOBAL",
                           "bhns_em_checkpoint_pt2p5");
  }
  {
    int cctkschedulei_tlevelarray[] = {0};
    CCTKi_ScheduleFunction((void *)CCTK_FNAME(driver_setup_emfields_part4_local_rescaleB_set_conservs),
                           "bhns_em_checkpoint_pt4",
                           "bhns",
                           "bhns",
                           "Setup BHNS EMFields, part 4",
                           "bhns_add_em_fields_after_checkpoint",
                           "Fortran",
                           0,  /* Number of STORAGE  groups   */
                           0,  /* Number of COMM     groups   */
                           0,  /* Number of TRIGGERS groups   */
                           0,  /* Number of SYNC     groups   */
                           2,  /* Number of Options           */
                           0,  /* Number of BEFORE  routines  */
                           1,  /* Number of AFTER   routines  */
                           0,  /* Number of WHILE   variables */
                           0,  /* Number of IF   variables */
                           cctkschedulei_tlevelarray  /* Array of timelevel data for storage groups */,
                           "GLOBAL",
                           "loop-local",
                           "bhns_em_checkpoint_pt3");
  }
}
if (use_new_bhns_initial_data!=-1){
if(compute_microphysics==1) {
  {
    int cctkschedulei_tlevelarray[] = {0};
    CCTKi_ScheduleFunction((void *)CCTK_FNAME(BHNS_setup_thermal_pressure_preset),
                           "BHNS_setup_thermal_pressure_preset",
                           "bhns",
                           "bhns",
                           "Setup BHNS Thermal Pressure based on temperature: preset flag",
                           "CCTK_ANALYSIS",
                           "Fortran",
                           0,  /* Number of STORAGE  groups   */
                           0,  /* Number of COMM     groups   */
                           0,  /* Number of TRIGGERS groups   */
                           0,  /* Number of SYNC     groups   */
                           1,  /* Number of Options           */
                           1,  /* Number of BEFORE  routines  */
                           1,  /* Number of AFTER   routines  */
                           0,  /* Number of WHILE   variables */
                           0,  /* Number of IF   variables */
                           cctkschedulei_tlevelarray  /* Array of timelevel data for storage groups */,
                           "GLOBAL",
                           "bhns_add_therm_after_checkpoint",
                           "poststep");
  }
}
  {
    int cctkschedulei_tlevelarray[] = {0};
    CCTKi_ScheduleGroup("bhns_add_therm_after_checkpoint",
"bhns_add_therm_after_checkpoint",
                        "bhns",
                        "bhns",
                        "Add thermal energy after checkpoint",
                        "CCTK_ANALYSIS",
                        0,  /* Number of STORAGE  groups   */
                        0,  /* Number of COMM     groups   */
                        0,  /* Number of TRIGGERS groups   */
                        0,  /* Number of SYNC     groups   */
                        0,  /* Number of Options           */
                        1,  /* Number of BEFORE  routines  */
                        1,  /* Number of AFTER   routines  */
                        1,  /* Number of WHILE   variables */
                        0,  /* Number of IF   variables */
                        cctkschedulei_tlevelarray  /* Array of timelevel data for storage groups */,
                        "bhns_regrid_output",
                        "poststep",
                        "bhns::bhnsEthermalNOW");
  }
  {
    int cctkschedulei_tlevelarray[] = {0};
    CCTKi_ScheduleFunction((void *)CCTK_FNAME(BHNS_setup_thermal_pressure_after_checkpoint),
                           "bhns_thermal_pressure",
                           "bhns",
                           "bhns",
                           "Setup BHNS Thermal Pressure based on temperature",
                           "bhns_add_therm_after_checkpoint",
                           "Fortran",
                           0,  /* Number of STORAGE  groups   */
                           0,  /* Number of COMM     groups   */
                           0,  /* Number of TRIGGERS groups   */
                           12,  /* Number of SYNC     groups   */
                           2,  /* Number of Options           */
                           1,  /* Number of BEFORE  routines  */
                           0,  /* Number of AFTER   routines  */
                           0,  /* Number of WHILE   variables */
                           0,  /* Number of IF   variables */
                           cctkschedulei_tlevelarray  /* Array of timelevel data for storage groups */,
                           "mhd_evolve::Stagger_Bs",
                           "mhd_evolve::mhd_primitives",
                           "mhd_evolve::em_Ax",
                           "mhd_evolve::em_Ay",
                           "mhd_evolve::em_Az",
                           "mhd_evolve::em_Phi",
                           "mhd_evolve::mhd_conservatives",
                           "mhd_evolve::rad_primitives",
                           "mhd_evolve::microphys_primitives",
                           "mhd_evolve::rad_conservatives",
                           "mhd_evolve::micphys_conservatives",
                           "mhd_evolve::rad_pressure",
                           "GLOBAL",
                           "loop-local",
                           "bhns_thermal_pressure_after");
  }
  {
    int cctkschedulei_tlevelarray[] = {0};
    CCTKi_ScheduleFunction((void *)CCTK_FNAME(BHNS_setup_thermal_pressure_afterset),
                           "bhns_thermal_pressure_after",
                           "bhns",
                           "bhns",
                           "Unset bhnsEthermalNOW",
                           "bhns_add_therm_after_checkpoint",
                           "Fortran",
                           0,  /* Number of STORAGE  groups   */
                           0,  /* Number of COMM     groups   */
                           0,  /* Number of TRIGGERS groups   */
                           0,  /* Number of SYNC     groups   */
                           2,  /* Number of Options           */
                           0,  /* Number of BEFORE  routines  */
                           1,  /* Number of AFTER   routines  */
                           0,  /* Number of WHILE   variables */
                           0,  /* Number of IF   variables */
                           cctkschedulei_tlevelarray  /* Array of timelevel data for storage groups */,
                           "GLOBAL",
                           "loop-local",
                           "bhns_thermal_pressure");
  }
}
if (use_new_bhns_initial_data!=-1){
if(rad_evolve_enable==1) {
  {
    int cctkschedulei_tlevelarray[] = {0};
    CCTKi_ScheduleFunction((void *)CCTK_FNAME(BHNS_insert_radiation_preset),
                           "BHNS_insert_radiation_preset",
                           "bhns",
                           "bhns",
                           "Insert BHNS radiation: preset flag",
                           "CCTK_ANALYSIS",
                           "Fortran",
                           0,  /* Number of STORAGE  groups   */
                           0,  /* Number of COMM     groups   */
                           0,  /* Number of TRIGGERS groups   */
                           0,  /* Number of SYNC     groups   */
                           1,  /* Number of Options           */
                           1,  /* Number of BEFORE  routines  */
                           1,  /* Number of AFTER   routines  */
                           0,  /* Number of WHILE   variables */
                           0,  /* Number of IF   variables */
                           cctkschedulei_tlevelarray  /* Array of timelevel data for storage groups */,
                           "GLOBAL",
                           "bhns_insert_rad_checkpoint",
                           "poststep");
  }
  {
    int cctkschedulei_tlevelarray[] = {0};
    CCTKi_ScheduleGroup("bhns_insert_rad_checkpoint",
"bhns_insert_rad_checkpoint",
                        "bhns",
                        "bhns",
                        "Add BHNS radiation after checkpoint",
                        "CCTK_ANALYSIS",
                        0,  /* Number of STORAGE  groups   */
                        0,  /* Number of COMM     groups   */
                        0,  /* Number of TRIGGERS groups   */
                        0,  /* Number of SYNC     groups   */
                        0,  /* Number of Options           */
                        0,  /* Number of BEFORE  routines  */
                        1,  /* Number of AFTER   routines  */
                        1,  /* Number of WHILE   variables */
                        0,  /* Number of IF   variables */
                        cctkschedulei_tlevelarray  /* Array of timelevel data for storage groups */,
                        "poststep",
                        "bhns::bhnsinsertRADNOW");
  }
  {
    int cctkschedulei_tlevelarray[] = {0};
    CCTKi_ScheduleFunction((void *)CCTK_FNAME(BHNS_insert_radiation_after_checkpoint),
                           "bhns_insert_rad",
                           "bhns",
                           "bhns",
                           "Setup BHNS Thermal Pressure based on temperature",
                           "bhns_insert_rad_checkpoint",
                           "Fortran",
                           0,  /* Number of STORAGE  groups   */
                           0,  /* Number of COMM     groups   */
                           0,  /* Number of TRIGGERS groups   */
                           12,  /* Number of SYNC     groups   */
                           2,  /* Number of Options           */
                           1,  /* Number of BEFORE  routines  */
                           0,  /* Number of AFTER   routines  */
                           0,  /* Number of WHILE   variables */
                           0,  /* Number of IF   variables */
                           cctkschedulei_tlevelarray  /* Array of timelevel data for storage groups */,
                           "mhd_evolve::Stagger_Bs",
                           "mhd_evolve::mhd_primitives",
                           "mhd_evolve::em_Ax",
                           "mhd_evolve::em_Ay",
                           "mhd_evolve::em_Az",
                           "mhd_evolve::em_Phi",
                           "mhd_evolve::mhd_conservatives",
                           "mhd_evolve::rad_primitives",
                           "mhd_evolve::microphys_primitives",
                           "mhd_evolve::rad_conservatives",
                           "mhd_evolve::micphys_conservatives",
                           "mhd_evolve::rad_pressure",
                           "GLOBAL",
                           "loop-local",
                           "bhns_insert_rad_after");
  }
  {
    int cctkschedulei_tlevelarray[] = {0};
    CCTKi_ScheduleFunction((void *)CCTK_FNAME(BHNS_insert_radiation_afterset),
                           "bhns_insert_rad_after",
                           "bhns",
                           "bhns",
                           "Unset bhnsinsertRADNOW",
                           "bhns_insert_rad_checkpoint",
                           "Fortran",
                           0,  /* Number of STORAGE  groups   */
                           0,  /* Number of COMM     groups   */
                           0,  /* Number of TRIGGERS groups   */
                           0,  /* Number of SYNC     groups   */
                           2,  /* Number of Options           */
                           0,  /* Number of BEFORE  routines  */
                           1,  /* Number of AFTER   routines  */
                           0,  /* Number of WHILE   variables */
                           0,  /* Number of IF   variables */
                           cctkschedulei_tlevelarray  /* Array of timelevel data for storage groups */,
                           "GLOBAL",
                           "loop-local",
                           "bhns_insert_rad");
  }
}
}
}

/*@@
  @routine    CCTKi_BindingsParameterRecovery_bhns
  @author     Automatically generated by CreateScheduleBindings.pl
  @desc
              Creates the parameter recovery bindings for thorn bhns
  @enddesc
@@*/

int CCTKi_BindingsParameterRecovery_bhns(void);
int CCTKi_BindingsParameterRecovery_bhns(void)
{
  /* this thorn doesn't define any parameter recovery routines */
  return (0);
}

