/*@@
   @file       ScheduleNaNChecker.c
   @author     Automatically generated by CreateScheduleBindings.pl
   @desc
               Creates the schedule and parameter recovery bindings 
               for thorn NaNChecker
   @enddesc
@@*/

#define THORN_IS_NaNChecker

#include "cctk.h"
#include "cctk_Parameters.h"
#include "cctki_ScheduleBindings.h"

/* prototypes for schedule bindings functions to be registered */
/* Note that this is a cheat, we just need a function pointer. */
extern int NaNChecker_ResetCounter(void);
extern int NaNChecker_NaNCheck(void);
extern int NaNChecker_TakeAction(void);


void CCTKi_BindingsSchedule_NaNChecker(void);
void CCTKi_BindingsSchedule_NaNChecker(void)
{
  DECLARE_CCTK_PARAMETERS
if (*check_vars && check_every > 0)
{
  CCTKi_ScheduleGroupStorage("NaNChecker::NaNmask",1);
  CCTKi_ScheduleGroupStorage("NaNChecker::NaNsFound",1);
  {
    int cctkschedulei_tlevelarray[] = {0};
    CCTKi_ScheduleFunction((void *)NaNChecker_ResetCounter,
                           "NaNChecker_ResetCounter",
                           "NaNChecker",
                           "NaNChecker",
                           "Reset the NaNChecker::NaNsFound counter",
                           "CCTK_POSTSTEP",
                           "C",
                           0,  /* Number of STORAGE  groups   */
                           0,  /* Number of COMM     groups   */
                           0,  /* Number of TRIGGERS groups   */
                           0,  /* Number of SYNC     groups   */
                           1,  /* Number of Options           */
                           1,  /* Number of BEFORE  routines  */
                           0,  /* Number of AFTER   routines  */
                           0,  /* Number of WHILE   variables */
                           0,  /* Number of IF   variables */
                           cctkschedulei_tlevelarray  /* Array of timelevel data for storage groups */,
                           "level",
                           "NaNChecker_NaNCheck");
  }
  {
    int cctkschedulei_tlevelarray[] = {0};
    CCTKi_ScheduleFunction((void *)NaNChecker_NaNCheck,
                           "NaNChecker_NaNCheck",
                           "NaNChecker",
                           "NaNChecker",
                           "Check for NaNs and count them in NaNChecker::NaNsFound",
                           "CCTK_POSTSTEP",
                           "C",
                           0,  /* Number of STORAGE  groups   */
                           0,  /* Number of COMM     groups   */
                           0,  /* Number of TRIGGERS groups   */
                           0,  /* Number of SYNC     groups   */
                           1,  /* Number of Options           */
                           0,  /* Number of BEFORE  routines  */
                           0,  /* Number of AFTER   routines  */
                           0,  /* Number of WHILE   variables */
                           0,  /* Number of IF   variables */
                           cctkschedulei_tlevelarray  /* Array of timelevel data for storage groups */,
                           "local");
  }
  {
    int cctkschedulei_tlevelarray[] = {0};
    CCTKi_ScheduleFunction((void *)NaNChecker_TakeAction,
                           "NaNChecker_TakeAction",
                           "NaNChecker",
                           "NaNChecker",
                           "Output NaNChecker::NaNmask and take action according to NaNChecker::action_if_found",
                           "CCTK_POSTSTEP",
                           "C",
                           0,  /* Number of STORAGE  groups   */
                           0,  /* Number of COMM     groups   */
                           0,  /* Number of TRIGGERS groups   */
                           0,  /* Number of SYNC     groups   */
                           2,  /* Number of Options           */
                           0,  /* Number of BEFORE  routines  */
                           1,  /* Number of AFTER   routines  */
                           0,  /* Number of WHILE   variables */
                           0,  /* Number of IF   variables */
                           cctkschedulei_tlevelarray  /* Array of timelevel data for storage groups */,
                           "global",
                           "loop-level",
                           "NaNChecker_NaNCheck");
  }
}
}

/*@@
  @routine    CCTKi_BindingsParameterRecovery_NaNChecker
  @author     Automatically generated by CreateScheduleBindings.pl
  @desc
              Creates the parameter recovery bindings for thorn NaNChecker
  @enddesc
@@*/

int CCTKi_BindingsParameterRecovery_NaNChecker(void);
int CCTKi_BindingsParameterRecovery_NaNChecker(void)
{
  /* this thorn doesn't define any parameter recovery routines */
  return (0);
}

