/*@@
   @file    WaveMoL_Functions.c
   @author  Automatically generated by CreateFunctionBindings.pl
   @desc
            The wrappers for functions provided by thorn WaveMoL.
   @enddesc
 @@*/


#include <stdio.h>
#include <stdlib.h>
#include <string.h>

#include "cctk_Flesh.h"
#include "cctk_WarnLevel.h"


CCTK_INT Register_WaveMoL(void);
CCTK_INT Register_WaveMoL(void)
{
  CCTK_INT ierr;

  ierr = 0;

  return ierr;
}
