/*@@
   @file    Carpet.c
   @author  Automatically generated by GridFuncStuff.pl
   @desc
            Creates the CCTK variables for thorn Carpet
   @enddesc
 @@*/


#define THORN_IS_Carpet 1

#include <stddef.h>

#include "cctk.h"
#include "cctk_Arguments.h"
#include "cctk_Parameter.h"
#include "cctk_WarnLevel.h"
#include "cctki_Groups.h"
#include "cctki_FortranWrappers.h"

int CactusBindingsVariables_Carpet_Initialise(void);
static int CCTKi_BindingsFortranWrapperCarpet(void *_GH, void *fpointer);

static int CCTKi_BindingsFortranWrapperCarpet(void *_GH, void *fpointer)
{
  cGH *GH = _GH;
  const int _cctk_zero = 0;
#ifndef CCTK_DEBUG
  CCTK_COMPLEX _cctk_dummy_var[4];
#endif
  void (*function)(CARPET_C2F_PROTO);
  DECLARE_CARPET_C2F
  INITIALISE_CARPET_C2F
  (void) (_cctk_zero + 0);
#ifndef CCTK_DEBUG
  (void) (_cctk_dummy_var + 0);
#endif

  function = (void (*) (CARPET_C2F_PROTO)) fpointer;
  function (PASS_CARPET_C2F (GH));

  return (0);
}

int CactusBindingsVariables_Carpet_Initialise(void)
{
  const char * warn_mixeddim_gfs = "";
  int warn_mixeddim = 0;
  const CCTK_INT *allow_mixeddim_gfs;


  allow_mixeddim_gfs = CCTK_ParameterGet ("allow_mixeddim_gfs", "Cactus", 0);

  if (CCTKi_CreateGroup ("TIMING", "CARPET", "DRIVER",
                         "SCALAR", "REAL", "PRIVATE",
                         0, 1,
                         "NONE", "CONSTANT",
                         "", "",
                         "checkpoint=\"no\"",
                         NULL,
                         21,
                         "physical_time_per_hour",
                         "time_total",
                         "time_computing",
                         "time_communicating",
                         "time_io",
                         "local_grid_points_per_second",
                         "total_grid_points_per_second",
                         "local_grid_point_updates_count",
                         "total_grid_point_updates_count",
                         "io_per_second",
                         "io_bytes_per_second",
                         "io_bytes_ascii_per_second",
                         "io_bytes_binary_per_second",
                         "io_count",
                         "io_bytes_count",
                         "io_bytes_ascii_count",
                         "io_bytes_binary_count",
                         "comm_per_second",
                         "comm_bytes_per_second",
                         "comm_count",
                         "comm_bytes_count") == 1)
  {
    warn_mixeddim_gfs = "timing";
    warn_mixeddim = 0;
  }
  if (CCTKi_CreateGroup ("TIMING2", "CARPET", "DRIVER",
                         "ARRAY", "REAL", "PRIVATE",
                         1, 1,
                         "NONE", "CONSTANT",
                         "1", "",
                         "checkpoint=\"no\"",
                         NULL,
                         2,
                         "grid_points_per_second",
                         "grid_point_updates_count") == 1)
  {
    warn_mixeddim_gfs = "timing2";
    warn_mixeddim = 1;
  }

  if (*warn_mixeddim_gfs)
  {
    if (allow_mixeddim_gfs && *allow_mixeddim_gfs)
    {
      CCTK_VWarn (2, __LINE__, __FILE__, "Cactus",
                  "CCTKi_CreateGroup: Working dimension already set, "
                  "creating GF group '%s' with different dimension %d",
                  warn_mixeddim_gfs, warn_mixeddim);
    }
    else
    {
      CCTK_VWarn (0, __LINE__, __FILE__, "Cactus",
                  "CCTKi_CreateGroup: Working dimension already set, "
                  "cannot create GF group '%s' with dimension %d",
                  warn_mixeddim_gfs, warn_mixeddim);
    }
 }

  CCTKi_RegisterFortranWrapper("Carpet", CCTKi_BindingsFortranWrapperCarpet);

  return 0;
}

