/*@@
   @file    CarpetIOBasic.c
   @author  Automatically generated by GridFuncStuff.pl
   @desc
            Creates the CCTK variables for thorn CarpetIOBasic
   @enddesc
 @@*/


#define THORN_IS_CarpetIOBasic 1

#include <stddef.h>

#include "cctk.h"
#include "cctk_Arguments.h"
#include "cctk_Parameter.h"
#include "cctk_WarnLevel.h"
#include "cctki_Groups.h"
#include "cctki_FortranWrappers.h"

int CactusBindingsVariables_CarpetIOBasic_Initialise(void);
static int CCTKi_BindingsFortranWrapperCarpetIOBasic(void *_GH, void *fpointer);

static int CCTKi_BindingsFortranWrapperCarpetIOBasic(void *_GH, void *fpointer)
{
  cGH *GH = _GH;
  const int _cctk_zero = 0;
#ifndef CCTK_DEBUG
  CCTK_COMPLEX _cctk_dummy_var[4];
#endif
  void (*function)(CARPETIOBASIC_C2F_PROTO);
  DECLARE_CARPETIOBASIC_C2F
  INITIALISE_CARPETIOBASIC_C2F
  (void) (_cctk_zero + 0);
#ifndef CCTK_DEBUG
  (void) (_cctk_dummy_var + 0);
#endif

  function = (void (*) (CARPETIOBASIC_C2F_PROTO)) fpointer;
  function (PASS_CARPETIOBASIC_C2F (GH));

  return (0);
}

int CactusBindingsVariables_CarpetIOBasic_Initialise(void)
{
  const char * warn_mixeddim_gfs = "";
  int warn_mixeddim = 0;
  const CCTK_INT *allow_mixeddim_gfs;


  allow_mixeddim_gfs = CCTK_ParameterGet ("allow_mixeddim_gfs", "Cactus", 0);

  if (CCTKi_CreateGroup ("LAST_OUTPUT_ITERATION", "CARPETIOBASIC", "IOBASIC",
                         "SCALAR", "INT", "PRIVATE",
                         0, 1,
                         "NONE", "CONSTANT",
                         "", "",
                         "",
                         NULL,
                         1,
                         "last_output_iteration") == 1)
  {
    warn_mixeddim_gfs = "last_output_iteration";
    warn_mixeddim = 0;
  }
  if (CCTKi_CreateGroup ("LAST_OUTPUT_TIME", "CARPETIOBASIC", "IOBASIC",
                         "SCALAR", "REAL", "PRIVATE",
                         0, 1,
                         "NONE", "CONSTANT",
                         "", "",
                         "",
                         NULL,
                         1,
                         "last_output_time") == 1)
  {
    warn_mixeddim_gfs = "last_output_time";
    warn_mixeddim = 0;
  }
  if (CCTKi_CreateGroup ("THIS_ITERATION", "CARPETIOBASIC", "IOBASIC",
                         "SCALAR", "INT", "PRIVATE",
                         0, 1,
                         "NONE", "CONSTANT",
                         "", "",
                         "",
                         NULL,
                         1,
                         "this_iteration") == 1)
  {
    warn_mixeddim_gfs = "this_iteration";
    warn_mixeddim = 0;
  }

  if (*warn_mixeddim_gfs)
  {
    if (allow_mixeddim_gfs && *allow_mixeddim_gfs)
    {
      CCTK_VWarn (2, __LINE__, __FILE__, "Cactus",
                  "CCTKi_CreateGroup: Working dimension already set, "
                  "creating GF group '%s' with different dimension %d",
                  warn_mixeddim_gfs, warn_mixeddim);
    }
    else
    {
      CCTK_VWarn (0, __LINE__, __FILE__, "Cactus",
                  "CCTKi_CreateGroup: Working dimension already set, "
                  "cannot create GF group '%s' with dimension %d",
                  warn_mixeddim_gfs, warn_mixeddim);
    }
 }

  CCTKi_RegisterFortranWrapper("CarpetIOBasic", CCTKi_BindingsFortranWrapperCarpetIOBasic);

  return 0;
}

