/*@@
   @file    mag_bondi.c
   @author  Automatically generated by GridFuncStuff.pl
   @desc
            Creates the CCTK variables for thorn mag_bondi
   @enddesc
 @@*/


#define THORN_IS_mag_bondi 1

#include <stddef.h>

#include "cctk.h"
#include "cctk_Arguments.h"
#include "cctk_Parameter.h"
#include "cctk_WarnLevel.h"
#include "cctki_Groups.h"
#include "cctki_FortranWrappers.h"

int CactusBindingsVariables_mag_bondi_Initialise(void);
static int CCTKi_BindingsFortranWrappermag_bondi(void *_GH, void *fpointer);

static int CCTKi_BindingsFortranWrappermag_bondi(void *_GH, void *fpointer)
{
  cGH *GH = _GH;
  const int _cctk_zero = 0;
#ifndef CCTK_DEBUG
  CCTK_COMPLEX _cctk_dummy_var[4];
#endif
  void (*function)(MAG_BONDI_C2F_PROTO);
  DECLARE_MAG_BONDI_C2F
  INITIALISE_MAG_BONDI_C2F
  (void) (_cctk_zero + 0);
#ifndef CCTK_DEBUG
  (void) (_cctk_dummy_var + 0);
#endif

  function = (void (*) (MAG_BONDI_C2F_PROTO)) fpointer;
  function (PASS_MAG_BONDI_C2F (GH));

  return (0);
}

int CactusBindingsVariables_mag_bondi_Initialise(void)
{
  const char * warn_mixeddim_gfs = "";
  int warn_mixeddim = 0;
  const CCTK_INT *allow_mixeddim_gfs;


  allow_mixeddim_gfs = CCTK_ParameterGet ("allow_mixeddim_gfs", "Cactus", 0);

  if (CCTKi_CreateGroup ("HORIZON_DATA_ARRAYS", "MAG_BONDI", "MAG_BONDI",
                         "ARRAY", "REAL", "PRIVATE",
                         1, 1,
                         "NONE", "CONSTANT",
                         "N_THETA*N_PHI", "",
                         "",
                         NULL,
                         7,
                         "xn_d",
                         "yn_d",
                         "zn_d",
                         "nx_d",
                         "ny_d",
                         "nz_d",
                         "nn_d") == 1)
  {
    warn_mixeddim_gfs = "horizon_data_arrays";
    warn_mixeddim = 1;
  }
  if (CCTKi_CreateGroup ("AUX_VAR", "MAG_BONDI", "MAG_BONDI",
                         "SCALAR", "REAL", "PRIVATE",
                         0, 1,
                         "NONE", "CONSTANT",
                         "", "",
                         "",
                         NULL,
                         2,
                         "xmax_bondi",
                         "zmax_bondi") == 1)
  {
    warn_mixeddim_gfs = "aux_var";
    warn_mixeddim = 0;
  }

  if (*warn_mixeddim_gfs)
  {
    if (allow_mixeddim_gfs && *allow_mixeddim_gfs)
    {
      CCTK_VWarn (2, __LINE__, __FILE__, "Cactus",
                  "CCTKi_CreateGroup: Working dimension already set, "
                  "creating GF group '%s' with different dimension %d",
                  warn_mixeddim_gfs, warn_mixeddim);
    }
    else
    {
      CCTK_VWarn (0, __LINE__, __FILE__, "Cactus",
                  "CCTKi_CreateGroup: Working dimension already set, "
                  "cannot create GF group '%s' with dimension %d",
                  warn_mixeddim_gfs, warn_mixeddim);
    }
 }

  CCTKi_RegisterFortranWrapper("mag_bondi", CCTKi_BindingsFortranWrappermag_bondi);

  return 0;
}

