/*@@
   @file    movingbox.c
   @author  Automatically generated by GridFuncStuff.pl
   @desc
            Creates the CCTK variables for thorn movingbox
   @enddesc
 @@*/


#define THORN_IS_movingbox 1

#include <stddef.h>

#include "cctk.h"
#include "cctk_Arguments.h"
#include "cctk_Parameter.h"
#include "cctk_WarnLevel.h"
#include "cctki_Groups.h"
#include "cctki_FortranWrappers.h"

int CactusBindingsVariables_movingbox_Initialise(void);
static int CCTKi_BindingsFortranWrappermovingbox(void *_GH, void *fpointer);

static int CCTKi_BindingsFortranWrappermovingbox(void *_GH, void *fpointer)
{
  cGH *GH = _GH;
  const int _cctk_zero = 0;
#ifndef CCTK_DEBUG
  CCTK_COMPLEX _cctk_dummy_var[4];
#endif
  void (*function)(MOVINGBOX_C2F_PROTO);
  DECLARE_MOVINGBOX_C2F
  INITIALISE_MOVINGBOX_C2F
  (void) (_cctk_zero + 0);
#ifndef CCTK_DEBUG
  (void) (_cctk_dummy_var + 0);
#endif

  function = (void (*) (MOVINGBOX_C2F_PROTO)) fpointer;
  function (PASS_MOVINGBOX_C2F (GH));

  return (0);
}

int CactusBindingsVariables_movingbox_Initialise(void)
{
  const char * warn_mixeddim_gfs = "";
  int warn_mixeddim = 0;
  const CCTK_INT *allow_mixeddim_gfs;


  allow_mixeddim_gfs = CCTK_ParameterGet ("allow_mixeddim_gfs", "Cactus", 0);

  if (CCTKi_CreateGroup ("VOLINTEGRALS_MOVINGBOX", "MOVINGBOX", "MOVINGBOX",
                         "SCALAR", "REAL", "PROTECTED",
                         0, 1,
                         "NONE", "CONSTANT",
                         "", "",
                         "",
                         NULL,
                         14,
                         "Box1X_VolInt",
                         "Box1Y_VolInt",
                         "Box1Z_VolInt",
                         "Box1denom_VolInt",
                         "Box1X_VolInt1",
                         "Box1Y_VolInt1",
                         "Box1Z_VolInt1",
                         "Box1denom_VolInt1",
                         "Box1X_VolInt2",
                         "Box1Y_VolInt2",
                         "Box1Z_VolInt2",
                         "Box1denom_VolInt2",
                         "mass_star1",
                         "mass_star2") == 1)
  {
    warn_mixeddim_gfs = "volIntegrals_movingbox";
    warn_mixeddim = 0;
  }
  if (CCTKi_CreateGroup ("DIAG_MOVINGBOX_GF", "MOVINGBOX", "MOVINGBOX",
                         "GF", "REAL", "PRIVATE",
                         3, 1,
                         "NONE", "DEFAULT",
                         "", "",
                         "InterpNumTimelevels=1 prolongation=\"none\"",
                         NULL,
                         4,
                         "box_x",
                         "box_y",
                         "box_z",
                         "box_denom") == 1)
  {
    warn_mixeddim_gfs = "diag_movingbox_gf";
    warn_mixeddim = 3;
  }

  if (*warn_mixeddim_gfs)
  {
    if (allow_mixeddim_gfs && *allow_mixeddim_gfs)
    {
      CCTK_VWarn (2, __LINE__, __FILE__, "Cactus",
                  "CCTKi_CreateGroup: Working dimension already set, "
                  "creating GF group '%s' with different dimension %d",
                  warn_mixeddim_gfs, warn_mixeddim);
    }
    else
    {
      CCTK_VWarn (0, __LINE__, __FILE__, "Cactus",
                  "CCTKi_CreateGroup: Working dimension already set, "
                  "cannot create GF group '%s' with dimension %d",
                  warn_mixeddim_gfs, warn_mixeddim);
    }
 }

  CCTKi_RegisterFortranWrapper("movingbox", CCTKi_BindingsFortranWrappermovingbox);

  return 0;
}

