/*@@
   @file    shift.c
   @author  Automatically generated by GridFuncStuff.pl
   @desc
            Creates the CCTK variables for thorn shift
   @enddesc
 @@*/


#define THORN_IS_shift 1

#include <stddef.h>

#include "cctk.h"
#include "cctk_Arguments.h"
#include "cctk_Parameter.h"
#include "cctk_WarnLevel.h"
#include "cctki_Groups.h"
#include "cctki_FortranWrappers.h"

int CactusBindingsVariables_shift_Initialise(void);
static int CCTKi_BindingsFortranWrappershift(void *_GH, void *fpointer);

static int CCTKi_BindingsFortranWrappershift(void *_GH, void *fpointer)
{
  cGH *GH = _GH;
  const int _cctk_zero = 0;
#ifndef CCTK_DEBUG
  CCTK_COMPLEX _cctk_dummy_var[4];
#endif
  void (*function)(SHIFT_C2F_PROTO);
  DECLARE_SHIFT_C2F
  INITIALISE_SHIFT_C2F
  (void) (_cctk_zero + 0);
#ifndef CCTK_DEBUG
  (void) (_cctk_dummy_var + 0);
#endif

  function = (void (*) (SHIFT_C2F_PROTO)) fpointer;
  function (PASS_SHIFT_C2F (GH));

  return (0);
}

int CactusBindingsVariables_shift_Initialise(void)
{
  const char * warn_mixeddim_gfs = "";
  int warn_mixeddim = 0;
  const CCTK_INT *allow_mixeddim_gfs;


  allow_mixeddim_gfs = CCTK_ParameterGet ("allow_mixeddim_gfs", "Cactus", 0);

  if (CCTKi_CreateGroup ("SHIFT_VARS", "SHIFT", "SHIFT",
                         "GF", "REAL", "PROTECTED",
                         3, 3,
                         "NONE", "DEFAULT",
                         "", "",
                         "",
                         NULL,
                         6,
                         "shiftx",
                         "shifty",
                         "shiftz",
                         "shiftxt",
                         "shiftyt",
                         "shiftzt") == 1)
  {
    warn_mixeddim_gfs = "shift_vars";
    warn_mixeddim = 3;
  }
  if (CCTKi_CreateGroup ("SHIFT_RHS", "SHIFT", "SHIFT",
                         "GF", "REAL", "PROTECTED",
                         3, 1,
                         "NONE", "DEFAULT",
                         "", "",
                         "Checkpoint=\"no\"",
                         NULL,
                         6,
                         "shiftx_rhs",
                         "shifty_rhs",
                         "shiftz_rhs",
                         "shiftxt_rhs",
                         "shiftyt_rhs",
                         "shiftzt_rhs") == 1)
  {
    warn_mixeddim_gfs = "shift_rhs";
    warn_mixeddim = 3;
  }
  if (CCTKi_CreateGroup ("SHIFT_VARS_TEMP", "SHIFT", "SHIFT",
                         "GF", "REAL", "PROTECTED",
                         3, 1,
                         "NONE", "DEFAULT",
                         "", "",
                         "Checkpoint=\"no\"",
                         NULL,
                         6,
                         "Gammax_drive",
                         "Gammay_drive",
                         "Gammaz_drive",
                         "shiftxt_timederiv",
                         "shiftyt_timederiv",
                         "shiftzt_timederiv") == 1)
  {
    warn_mixeddim_gfs = "shift_vars_temp";
    warn_mixeddim = 3;
  }

  if (*warn_mixeddim_gfs)
  {
    if (allow_mixeddim_gfs && *allow_mixeddim_gfs)
    {
      CCTK_VWarn (2, __LINE__, __FILE__, "Cactus",
                  "CCTKi_CreateGroup: Working dimension already set, "
                  "creating GF group '%s' with different dimension %d",
                  warn_mixeddim_gfs, warn_mixeddim);
    }
    else
    {
      CCTK_VWarn (0, __LINE__, __FILE__, "Cactus",
                  "CCTKi_CreateGroup: Working dimension already set, "
                  "cannot create GF group '%s' with dimension %d",
                  warn_mixeddim_gfs, warn_mixeddim);
    }
 }

  CCTKi_RegisterFortranWrapper("shift", CCTKi_BindingsFortranWrappershift);

  return 0;
}

