/*@@
   @file    shock_mhd.c
   @author  Automatically generated by GridFuncStuff.pl
   @desc
            Creates the CCTK variables for thorn shock_mhd
   @enddesc
 @@*/


#define THORN_IS_shock_mhd 1

#include <stddef.h>

#include "cctk.h"
#include "cctk_Arguments.h"
#include "cctk_Parameter.h"
#include "cctk_WarnLevel.h"
#include "cctki_Groups.h"
#include "cctki_FortranWrappers.h"

int CactusBindingsVariables_shock_mhd_Initialise(void);
static int CCTKi_BindingsFortranWrappershock_mhd(void *_GH, void *fpointer);

static int CCTKi_BindingsFortranWrappershock_mhd(void *_GH, void *fpointer)
{
  cGH *GH = _GH;
  const int _cctk_zero = 0;
#ifndef CCTK_DEBUG
  CCTK_COMPLEX _cctk_dummy_var[4];
#endif
  void (*function)(SHOCK_MHD_C2F_PROTO);
  DECLARE_SHOCK_MHD_C2F
  INITIALISE_SHOCK_MHD_C2F
  (void) (_cctk_zero + 0);
#ifndef CCTK_DEBUG
  (void) (_cctk_dummy_var + 0);
#endif

  function = (void (*) (SHOCK_MHD_C2F_PROTO)) fpointer;
  function (PASS_SHOCK_MHD_C2F (GH));

  return (0);
}

int CactusBindingsVariables_shock_mhd_Initialise(void)
{
  const char * warn_mixeddim_gfs = "";
  int warn_mixeddim = 0;
  const CCTK_INT *allow_mixeddim_gfs;


  allow_mixeddim_gfs = CCTK_ParameterGet ("allow_mixeddim_gfs", "Cactus", 0);

  if (CCTKi_CreateGroup ("MHD_SHOCK_VOLINT", "SHOCK_MHD", "MHD_SHOCK",
                         "SCALAR", "REAL", "PRIVATE",
                         0, 1,
                         "NONE", "CONSTANT",
                         "", "",
                         "",
                         NULL,
                         1,
                         "shock_restmass_VolInt") == 1)
  {
    warn_mixeddim_gfs = "mhd_shock_VolInt";
    warn_mixeddim = 0;
  }
  if (CCTKi_CreateGroup ("MHD_SHOCK_PRIVATE", "SHOCK_MHD", "MHD_SHOCK",
                         "GF", "REAL", "PRIVATE",
                         3, 1,
                         "NONE", "DEFAULT",
                         "", "",
                         "prolongation=\"none\" InterpNumTimelevels=1",
                         NULL,
                         1,
                         "shock_rest_mass_integrand") == 1)
  {
    warn_mixeddim_gfs = "mhd_shock_private";
    warn_mixeddim = 3;
  }

  if (*warn_mixeddim_gfs)
  {
    if (allow_mixeddim_gfs && *allow_mixeddim_gfs)
    {
      CCTK_VWarn (2, __LINE__, __FILE__, "Cactus",
                  "CCTKi_CreateGroup: Working dimension already set, "
                  "creating GF group '%s' with different dimension %d",
                  warn_mixeddim_gfs, warn_mixeddim);
    }
    else
    {
      CCTK_VWarn (0, __LINE__, __FILE__, "Cactus",
                  "CCTKi_CreateGroup: Working dimension already set, "
                  "cannot create GF group '%s' with dimension %d",
                  warn_mixeddim_gfs, warn_mixeddim);
    }
 }

  CCTKi_RegisterFortranWrapper("shock_mhd", CCTKi_BindingsFortranWrappershock_mhd);

  return 0;
}

