/*@@
   @file    SphericalSurface.c
   @author  Automatically generated by GridFuncStuff.pl
   @desc
            Creates the CCTK variables for thorn SphericalSurface
   @enddesc
 @@*/


#define THORN_IS_SphericalSurface 1

#include <stddef.h>

#include "cctk.h"
#include "cctk_Arguments.h"
#include "cctk_Parameter.h"
#include "cctk_WarnLevel.h"
#include "cctki_Groups.h"
#include "cctki_FortranWrappers.h"

int CactusBindingsVariables_SphericalSurface_Initialise(void);
static int CCTKi_BindingsFortranWrapperSphericalSurface(void *_GH, void *fpointer);

static int CCTKi_BindingsFortranWrapperSphericalSurface(void *_GH, void *fpointer)
{
  cGH *GH = _GH;
  const int _cctk_zero = 0;
#ifndef CCTK_DEBUG
  CCTK_COMPLEX _cctk_dummy_var[4];
#endif
  void (*function)(SPHERICALSURFACE_C2F_PROTO);
  DECLARE_SPHERICALSURFACE_C2F
  INITIALISE_SPHERICALSURFACE_C2F
  (void) (_cctk_zero + 0);
#ifndef CCTK_DEBUG
  (void) (_cctk_dummy_var + 0);
#endif

  function = (void (*) (SPHERICALSURFACE_C2F_PROTO)) fpointer;
  function (PASS_SPHERICALSURFACE_C2F (GH));

  return (0);
}

int CactusBindingsVariables_SphericalSurface_Initialise(void)
{
  const char * warn_mixeddim_gfs = "";
  int warn_mixeddim = 0;
  const CCTK_INT *allow_mixeddim_gfs;


  allow_mixeddim_gfs = CCTK_ParameterGet ("allow_mixeddim_gfs", "Cactus", 0);

  if (CCTKi_CreateGroup ("SF_ACTIVE", "SPHERICALSURFACE", "SPHERICALSURFACE",
                         "SCALAR", "INT", "PUBLIC",
                         0, 1,
                         "NONE", "CONSTANT",
                         "", "",
                         "",
                         "nsurfaces",
                         1,
                         "sf_active") == 1)
  {
    warn_mixeddim_gfs = "sf_active";
    warn_mixeddim = 0;
  }
  if (CCTKi_CreateGroup ("SF_VALID", "SPHERICALSURFACE", "SPHERICALSURFACE",
                         "SCALAR", "INT", "PUBLIC",
                         0, 1,
                         "NONE", "CONSTANT",
                         "", "",
                         "",
                         "nsurfaces",
                         1,
                         "sf_valid") == 1)
  {
    warn_mixeddim_gfs = "sf_valid";
    warn_mixeddim = 0;
  }
  if (CCTKi_CreateGroup ("SF_INFO", "SPHERICALSURFACE", "SPHERICALSURFACE",
                         "SCALAR", "REAL", "PUBLIC",
                         0, 1,
                         "NONE", "CONSTANT",
                         "", "",
                         "",
                         "nsurfaces",
                         19,
                         "sf_area",
                         "sf_mean_radius",
                         "sf_centroid_x",
                         "sf_centroid_y",
                         "sf_centroid_z",
                         "sf_quadrupole_xx",
                         "sf_quadrupole_xy",
                         "sf_quadrupole_xz",
                         "sf_quadrupole_yy",
                         "sf_quadrupole_yz",
                         "sf_quadrupole_zz",
                         "sf_min_radius",
                         "sf_max_radius",
                         "sf_min_x",
                         "sf_min_y",
                         "sf_min_z",
                         "sf_max_x",
                         "sf_max_y",
                         "sf_max_z") == 1)
  {
    warn_mixeddim_gfs = "sf_info";
    warn_mixeddim = 0;
  }
  if (CCTKi_CreateGroup ("SF_MINREFLEVEL", "SPHERICALSURFACE", "SPHERICALSURFACE",
                         "SCALAR", "INT", "PUBLIC",
                         0, 1,
                         "NONE", "CONSTANT",
                         "", "",
                         "",
                         "nsurfaces",
                         1,
                         "sf_minreflevel") == 1)
  {
    warn_mixeddim_gfs = "sf_minreflevel";
    warn_mixeddim = 0;
  }
  if (CCTKi_CreateGroup ("SF_MAXREFLEVEL", "SPHERICALSURFACE", "SPHERICALSURFACE",
                         "SCALAR", "INT", "PUBLIC",
                         0, 1,
                         "NONE", "CONSTANT",
                         "", "",
                         "",
                         "nsurfaces",
                         1,
                         "sf_maxreflevel") == 1)
  {
    warn_mixeddim_gfs = "sf_maxreflevel";
    warn_mixeddim = 0;
  }
  if (CCTKi_CreateGroup ("SF_RADIUS", "SPHERICALSURFACE", "SPHERICALSURFACE",
                         "ARRAY", "REAL", "PUBLIC",
                         2, 1,
                         "NONE", "CONSTANT",
                         "MAXNTHETA,MAXNPHI", "",
                         "",
                         "nsurfaces",
                         1,
                         "sf_radius") == 1)
  {
    warn_mixeddim_gfs = "sf_radius";
    warn_mixeddim = 2;
  }
  if (CCTKi_CreateGroup ("SF_ORIGIN", "SPHERICALSURFACE", "SPHERICALSURFACE",
                         "SCALAR", "REAL", "PUBLIC",
                         0, 1,
                         "NONE", "CONSTANT",
                         "", "",
                         "",
                         "nsurfaces",
                         3,
                         "sf_origin_x",
                         "sf_origin_y",
                         "sf_origin_z") == 1)
  {
    warn_mixeddim_gfs = "sf_origin";
    warn_mixeddim = 0;
  }
  if (CCTKi_CreateGroup ("SF_COORDINATE_DESCRIPTORS", "SPHERICALSURFACE", "SPHERICALSURFACE",
                         "SCALAR", "REAL", "PUBLIC",
                         0, 1,
                         "NONE", "CONSTANT",
                         "", "",
                         "",
                         "nsurfaces",
                         4,
                         "sf_origin_theta",
                         "sf_origin_phi",
                         "sf_delta_theta",
                         "sf_delta_phi") == 1)
  {
    warn_mixeddim_gfs = "sf_coordinate_descriptors";
    warn_mixeddim = 0;
  }
  if (CCTKi_CreateGroup ("SF_SHAPE_DESCRIPTORS", "SPHERICALSURFACE", "SPHERICALSURFACE",
                         "SCALAR", "INT", "PUBLIC",
                         0, 1,
                         "NONE", "CONSTANT",
                         "", "",
                         "",
                         "nsurfaces",
                         4,
                         "sf_ntheta",
                         "sf_nphi",
                         "sf_nghoststheta",
                         "sf_nghostsphi") == 1)
  {
    warn_mixeddim_gfs = "sf_shape_descriptors";
    warn_mixeddim = 0;
  }
  if (CCTKi_CreateGroup ("SF_COORDINATE_ESTIMATORS", "SPHERICALSURFACE", "SPHERICALSURFACE",
                         "SCALAR", "REAL", "PRIVATE",
                         0, 1,
                         "NONE", "CONSTANT",
                         "", "",
                         "",
                         "nsurfaces",
                         2,
                         "sf_delta_theta_estimate",
                         "sf_delta_phi_estimate") == 1)
  {
    warn_mixeddim_gfs = "sf_coordinate_estimators";
    warn_mixeddim = 0;
  }

  if (*warn_mixeddim_gfs)
  {
    if (allow_mixeddim_gfs && *allow_mixeddim_gfs)
    {
      CCTK_VWarn (2, __LINE__, __FILE__, "Cactus",
                  "CCTKi_CreateGroup: Working dimension already set, "
                  "creating GF group '%s' with different dimension %d",
                  warn_mixeddim_gfs, warn_mixeddim);
    }
    else
    {
      CCTK_VWarn (0, __LINE__, __FILE__, "Cactus",
                  "CCTKi_CreateGroup: Working dimension already set, "
                  "cannot create GF group '%s' with dimension %d",
                  warn_mixeddim_gfs, warn_mixeddim);
    }
 }

  CCTKi_RegisterFortranWrapper("SphericalSurface", CCTKi_BindingsFortranWrapperSphericalSurface);

  return 0;
}

