/*@@
   @file    WaveMoL.c
   @author  Automatically generated by GridFuncStuff.pl
   @desc
            Creates the CCTK variables for thorn WaveMoL
   @enddesc
 @@*/


#define THORN_IS_WaveMoL 1

#include <stddef.h>

#include "cctk.h"
#include "cctk_Arguments.h"
#include "cctk_Parameter.h"
#include "cctk_WarnLevel.h"
#include "cctki_Groups.h"
#include "cctki_FortranWrappers.h"

int CactusBindingsVariables_WaveMoL_Initialise(void);
static int CCTKi_BindingsFortranWrapperWaveMoL(void *_GH, void *fpointer);

static int CCTKi_BindingsFortranWrapperWaveMoL(void *_GH, void *fpointer)
{
  cGH *GH = _GH;
  const int _cctk_zero = 0;
#ifndef CCTK_DEBUG
  CCTK_COMPLEX _cctk_dummy_var[4];
#endif
  void (*function)(WAVEMOL_C2F_PROTO);
  DECLARE_WAVEMOL_C2F
  INITIALISE_WAVEMOL_C2F
  (void) (_cctk_zero + 0);
#ifndef CCTK_DEBUG
  (void) (_cctk_dummy_var + 0);
#endif

  function = (void (*) (WAVEMOL_C2F_PROTO)) fpointer;
  function (PASS_WAVEMOL_C2F (GH));

  return (0);
}

int CactusBindingsVariables_WaveMoL_Initialise(void)
{
  const char * warn_mixeddim_gfs = "";
  int warn_mixeddim = 0;
  const CCTK_INT *allow_mixeddim_gfs;


  allow_mixeddim_gfs = CCTK_ParameterGet ("allow_mixeddim_gfs", "Cactus", 0);

  if (CCTKi_CreateGroup ("SCALAREVOLVEMOL_SCALAR", "WAVEMOL", "WAVEMOL",
                         "GF", "REAL", "PUBLIC",
                         3, 3,
                         "NONE", "DEFAULT",
                         "", "",
                         "tensortypealias=\"Scalar\"",
                         NULL,
                         2,
                         "phi",
                         "phit") == 1)
  {
    warn_mixeddim_gfs = "scalarevolvemol_scalar";
    warn_mixeddim = 3;
  }
  if (CCTKi_CreateGroup ("SCALAREVOLVEMOL_VECTOR", "WAVEMOL", "WAVEMOL",
                         "GF", "REAL", "PUBLIC",
                         3, 3,
                         "NONE", "DEFAULT",
                         "", "",
                         "tensortypealias=\"U\"",
                         NULL,
                         3,
                         "phix",
                         "phiy",
                         "phiz") == 1)
  {
    warn_mixeddim_gfs = "scalarevolvemol_vector";
    warn_mixeddim = 3;
  }
  if (CCTKi_CreateGroup ("SCALARRHSMOL_SCALAR", "WAVEMOL", "WAVEMOL",
                         "GF", "REAL", "PUBLIC",
                         3, 1,
                         "NONE", "DEFAULT",
                         "", "",
                         "",
                         NULL,
                         2,
                         "phirhs",
                         "phitrhs") == 1)
  {
    warn_mixeddim_gfs = "scalarrhsmol_scalar";
    warn_mixeddim = 3;
  }
  if (CCTKi_CreateGroup ("SCALARRHSMOL_VECTOR", "WAVEMOL", "WAVEMOL",
                         "GF", "REAL", "PUBLIC",
                         3, 1,
                         "NONE", "DEFAULT",
                         "", "",
                         "",
                         NULL,
                         3,
                         "phixrhs",
                         "phiyrhs",
                         "phizrhs") == 1)
  {
    warn_mixeddim_gfs = "scalarrhsmol_vector";
    warn_mixeddim = 3;
  }
  if (CCTKi_CreateGroup ("ENERGY", "WAVEMOL", "WAVEMOL",
                         "GF", "REAL", "PUBLIC",
                         3, 1,
                         "NONE", "DEFAULT",
                         "", "",
                         "",
                         NULL,
                         1,
                         "energy") == 1)
  {
    warn_mixeddim_gfs = "energy";
    warn_mixeddim = 3;
  }

  if (*warn_mixeddim_gfs)
  {
    if (allow_mixeddim_gfs && *allow_mixeddim_gfs)
    {
      CCTK_VWarn (2, __LINE__, __FILE__, "Cactus",
                  "CCTKi_CreateGroup: Working dimension already set, "
                  "creating GF group '%s' with different dimension %d",
                  warn_mixeddim_gfs, warn_mixeddim);
    }
    else
    {
      CCTK_VWarn (0, __LINE__, __FILE__, "Cactus",
                  "CCTKi_CreateGroup: Working dimension already set, "
                  "cannot create GF group '%s' with dimension %d",
                  warn_mixeddim_gfs, warn_mixeddim);
    }
 }

  CCTKi_RegisterFortranWrapper("WaveMoL", CCTKi_BindingsFortranWrapperWaveMoL);

  return 0;
}

